### ISSUE TITLE
Ability to edit forms after creation

### ISSUE THREAD

**Issue by mikweb2017** [nextcloud/forms#1]
Thanks for this great app!
some things have disturbed me a bit or maybe not yet understood after saving a Survey is no longer possible to edit it again .

can users vote multiple times the same survey would make sense only once for IP address or session?

possibly the possibility to customize the survey with a template where html or something like that for example by adding a photo and so on

**Comment by jakobroehrl** [comment]
Thanks for this great app! 
It solves my problem from here: https://github.com/nextcloud/polls/issues/560
A edit function would be great!

**Comment by larnd** [comment]
Really useful app for the NextCloud. To be able to edit the already created polls would definitely increase the usability of the app!

**Comment by lapor** [comment]
It's a great alternative to goolge forms. But edit part would be also nice.

Thanks

**Comment by qbicdesign** [comment]
edit

> It's a great alternative to goolge forms. But edit part would be also nice.
> 
> Thanks

Not just nice, its essential

**Comment by pieter-groeneweg** [comment]
I cannot use this as long as there is no edit button. But it is a good start.
Also now entries do not show the type after they are added.

**Comment by luixxiul** [comment]
> 
> 
> it is a good start.

I assume the app might have been done, according to this post: https://help.nextcloud.com/t/were-making-a-forms-app/50271

> We’re a team of 8 UMD students. We’re taking a software engineering class and as part of the class we have a semester long project.

**Comment by pwepwe973** [comment]
Bravo for this application that I look for some time because I do not trust google: d.

I can not wait to see him evolve

**Comment by pwepwe973** [comment]
Hello, I wanted to know if there will be updates for this apps or if it will be released because the last modification is 2 months ago

**Comment by affan98** [comment]
We've transferred the repo to nextcloud.  I believe they have plans to improve the app.  When I eventually get some time I might make some contributions.  But that won't be happening soon so you have to wait for others to make updates.  Or feel free to make your contributions

**Comment by glunardi** [comment]
Expressing interest here on the edit capability. It would make the app a lot more useful for us. Thanks for the great start though!

**Comment by soerpoers** [comment]
yeah it would be great. maybe it's a limitation that you can't edit a form due a user is fill it with data. but maybe we can edit it since we share it?
But with this nextcloud get better and better… thank you 👍

**Comment by MarkPartlett** [comment]
based on the routes file (https://github.com/nextcloud/forms/blob/master/appinfo/routes.php) : ['name' => 'page#edit_form', 'url' => '/edit/{hash}', 'verb' => 'GET'],

The 'edit' page is /edit/{hash}

**Comment by tavinus** [comment]
Isn't the Edit function the same as CREATE FORM but instead of default/empty, you load the ID / info of an existing form at that same page and the rewrite it?

**Comment by loisspitz** [comment]
When the 'edit' page is viewed as @MarkPartlett mentioned, there can just the title and the description edited. But when you look at the html-Code you get delivered to the browser, there you find:
`<h2>Make a Form</h2> <div id="quiz-form-selector-text" style="display: none ;"><label for="ans-type">Answer Type: </label>`

`<li type="text"><div>tuitzutg</div> <div><input placeholder="Add Answer" style="height: 30px; display: none;"> <ul id="form-list" class="form-table"></ul></div> `

When you edit the text in the inspector of the browser and remove the word "**none**", then you can edit your existing form.
Unfortunately my knowledge is quite limited, so i have no idea, where is this possible to change this in the code.

**Comment by skjnldsv** [comment]
Fixed with upcomming 2.0

**Comment by bigemmxxx** [comment]
Also from me: THANKS a lot for this great App! 
Is it planned to add additional explanations to single questions? 
For each question there is actually only a single line to describe the question and include explanations. It would be great if there was a second line or text field for additional explanations how to understand a question, what to fill in etc.

**Comment by skjnldsv** [comment]
> Is it planned to add additional explanations to single questions?

No idea! Search for existing issues and if there isn't any, create one! :)
Tanks for the kind words!! :hugs:
