### ISSUE TITLE
Release for Nextcloud 17?

### ISSUE THREAD

**Issue by e-alfred** [nextcloud/forms#100]
Hello,

can you publish a new release to the App Store for Nextcloud 17?

**Comment by affan98** [comment]
That's a good idea

**Comment by Sebaristoteles** [comment]
Is someone working on this issue or is it in any release pipeline?

**Comment by affan98** [comment]
I’ll do it this week

**Comment by affan98** [comment]
Ran into some issues. Will update again once it's up

**Comment by stefanoco** [comment]
Any forecats on this? Don't want to make pressure just need to know for our planning of using it soon.

**Comment by fdrgit** [comment]
Any chance we get a release within few days ? Thanks in advance.

**Comment by dennorske** [comment]
What's the status here? What's taking months, can we be of any assistance?

**Comment by davidtrattnig** [comment]
I'm also eager to use it with Nextcloud 17.

And still dreaming of having an Upload Functionality within the Forms App (see #42). 
Please let me know if I can support in any way.

Any chance to release it before end of January?

**Comment by luixxiul** [comment]
The version was bumped on https://github.com/nextcloud/forms/commit/ee65a88442cd7673d39339475fd2ca543ac5a157#diff-224bb875c5d3cfcd7621135069013242R35

**Comment by jancborchardt** [comment]
There’s releases out on the app store for Nextcloud 17 as well as for upcoming 18. :slightly_smiling_face: 

If you like the Forms app, consider leaving a review on the store page :balloon: https://apps.nextcloud.com/apps/forms
