### ISSUE TITLE
Minor language change proposal

### ISSUE THREAD

**Issue by zell-mbc** [nextcloud/forms#1005]
After having spent a bit of time with a user who struggled to create a public form, may I suggest a slight language change?

![image](https://user-images.githubusercontent.com/29018767/124477774-b2425a00-dda4-11eb-9b44-26b74ac9fe57.png)

I didn't have access to the UI at first, so I kept on asking to make sure to select "create public link" or something of that nature. 

After a few wrong attempts I finally got to checking the UI, and I had to agree that the correct "Share via link" setting doesn't really say if this link is going to be public or not. Especially for non IT individuals like my users.
How about changing this string to "Share via public link", and if possible a tool tip saying "Acessible by everyone, no account and login required"
And maybe for "Show to all users of this instance" a tool tip similar to "Requires login and an active account on this server"

**Comment by jotoeri** [comment]
Hey @zell-mbc,

thank you for thinking about and for this proposal! However as one of the urgently planned next steps is to rework the sharings to show them as in other apps like files. So for now i won't invest too much time here, but try to get started with the sidebar-rewrite. ;)

Greets,
Jonas
