### ISSUE TITLE
Upon Enable get: Column "oc_forms_v2_forms"."is_anonymous" is type Bool and also NotNull, so it can not store "false".

### ISSUE THREAD

**Issue by nothing2obvi** [nextcloud/forms#1010]
Hello,

When I try to enable Forms on Nextcloud I get this message:

Column "oc_forms_v2_forms"."is_anonymous" is type Bool and also NotNull, so it can not store "false".

![error message](https://user-images.githubusercontent.com/85228035/125847045-4d16e75f-a993-4549-a0f3-457f415374c2.png)

I can't seem to find any information about how to address this. Any ideas would be greatly appreciated :)

**Comment by alfredkusuma** [comment]
yes.. so do I. Please help...

**Comment by stevecopeza** [comment]
I have the same error message

**Comment by qianqiulin** [comment]
me too.

**Comment by jotoeri** [comment]
Will be solved with the next release. I have it in mind, as we also need to support NC22, but might still take some time, as i'm quite busy currently.
In case you have database-access (and know what you're doing!) and need a urgent solution, you can change the notnull-values of the three database-columns: https://github.com/nextcloud/forms/pull/881/files

**Comment by jotoeri** [comment]
Now there is a release available for NC22. 🙂
