### ISSUE TITLE
Share with Circle

### ISSUE THREAD

**Issue by dominik34** [nextcloud/forms#1012]
Sharing with circles is not possible.
Unlike in the sharing section of Documents, eg. there are no circles found to share with.

**Comment by JOpsDev** [comment]
Would sharing with circles enable editing the form by multiples persons make possible? We don't need to edit the form at the same time but adjusting some things would be really helpful.

**Comment by Chartman123** [comment]
No, it's primarily just for sharing the form with regard to submitting...

**Comment by punkyard** [comment]
hi
our teams never share with groups, they share with circles, which they can create and modify as needed.
so far we can't use forms for this reason.

I'm pushing the request!!
thanks for your concern :)

**Comment by punkyard** [comment]
hi @Chartman123 
could you please enlighten me with the future of this issue?
'merged' does it mean it's going to be taken into consideration for a future update?

**Comment by Chartman123** [comment]
Hi @punkyard

yes, merged means that the changes in the code are in the main branch now and that they will be part of the next release.
