### ISSUE TITLE
Feature Request: Editable default text in long & short text answer

### ISSUE THREAD

**Issue by RalfAlbers** [nextcloud/forms#1029]
**Nextcloud (please complete the following information):**

    Nextcloud-Version: 21.0.3
    Forms-Version: 2.3.0

**Is your feature request related to a problem? Please describe.**
the default-text in long and short text-answers should be editable, so this cloud be a hint, what a user could fill in der answer form.

**Describe the solution you'd like**
It would be great if it is configurable.

**Comment by jotoeri** [comment]
Just realised, this is the same as #1041, which i already scheduled. So closing this one here. 😉
