### ISSUE TITLE
Allow sharing via Link and to all the users

### ISSUE THREAD

**Issue by tobyps** [nextcloud/forms#1043]
**Nextcloud (please complete the following information):**
- Nextcloud-Version: 21.0.4
- Forms-Version: 2.3

**Is your feature request related to a problem? Please describe.**
As it is only possible to select either share by link or share to users of the instance, users cant see the form in their nextcloud if you want to include nonusers because it is only accessible via the link

**Describe the solution you'd like**
If the form is shared by link make it possible to also share it to all users (or even better share by groups) of nextcloud

Thx

**Comment by jotoeri** [comment]
It is on the plan with #425 and on my list as one of the first todos when i find some time. Thus closing this one. 😉
