### ISSUE TITLE
Share results

### ISSUE THREAD

**Issue by nicovd737** [nextcloud/forms#1050]
**Nextcloud (please complete the following information):**
- Nextcloud-Version: [e.g. 19.0.0]
- Forms-Version: [e.g. 2.0.0-beta4]

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Would it be possible to share only summary / results of form for users without sharing the form itself ? 
For example, if i'd like to share the results with a link and submit it to my boss.

**Describe alternatives you've considered**
At the moment, we export the summary but it's not really flexible for us. Maybe there is another way to share but we don't know.

**Additional context**

**Comment by jotoeri** [comment]
Not yet there, but planned with #455. So closing this as duplicate. ;)
