### ISSUE TITLE
An API to mine data from the form results 

### ISSUE THREAD

**Issue by haja-k** [nextcloud/forms#1085]
**Nextcloud (please complete the following information):**
- Nextcloud-Version: [e.g. 19.0.0]
- Forms-Version: [e.g. 2.0.0-beta4]

**Is your feature request related to a problem? Please describe.**
It is not really a problem. More like a question on is there a way to extract results from the forms automatically using an API provided by the creators? At the moment the form results can only be exported to csv so I was wondering is there an API that we can use to mine the data to be used by another system. 

**Describe the solution you'd like**
an API to extract form results to be consumed by another system. Like a data retrieval API.

**Describe alternatives you've considered**
Not that I know of.

**Additional context**
None.

**Comment by jotoeri** [comment]
Please see [API Docs #Submission Endpoints](https://github.com/nextcloud/forms/blob/master/docs/API.md#submission-endpoints) 😉 

Greets!
Jonas

**Comment by haja-k** [comment]
thank you :)
