### ISSUE TITLE
Unreleased update to 2.4.0 offered in Nextcloud

### ISSUE THREAD

**Issue by materpillar** [nextcloud/forms#1097]
Nextcloud offers me an update to 2.4.0, but no such version is released here and I couldn't find a 2.4.0 tag. Nextcloud does not offer me a changelog for this update. There is still a 2.4.0 milestone in this repository which has 0% progress. Is this an official release?
If this is just a compatibility update for newer Nextcloud versions, I believe that the version number 2.3.1 would have been more fitting?

Please document and tag your releases as usual and could you please update the issues and milestones so it is possible to track a bit the ongoing development of this plugin?
Thank you!

**Comment by jotoeri** [comment]
@skjnldsv You implemented some way of automatic release?! How does it work? Shouldn't it also create the GH-Release as well as the tag?

**Comment by skjnldsv** [comment]
https://github.com/nextcloud-releases/forms/releases

**Comment by jotoeri** [comment]
👀 Can wie make that workflow/bot also create the tag & release here, so it is visible on the code-repository?
