### ISSUE TITLE
Format of results, especially in CSV

### ISSUE THREAD

**Issue by dueringa** [nextcloud/forms#11]
A feature request:

**Which Forms version are you running?** (see apps page)
1.0.3

**Nextcloud or ownCloud?:**
Nextcloud

**Nextcloud/ownCloud version:** (see Nextcloud admin page)
16.0.1

### Steps to reproduce
1. Create Form
2. Provide some answers
3. View results

### Actual behaviour

Results are shown with one line per answer:

~~~
Name    Question #   Question             Response
anon1   1            Pineapple on pizza?  Yes
anon1   2            Favorite editor?     Emacs
anon2   1            Pineapple on pizza?  No
anon2   2            Favorite editor?     vim
~~~

### Expected behaviour

I'd actually like the output to be one line per user, so I have all answers in one line, like

~~~
Name    Question #   q1                   r1      q2                 r2
anon1   1            Pineapple on pizza?  Yes     Favorite editor?   Emacs
anon2   1            Pineapple on pizza?  No      Favorite editor?   vim
~~~

or even like

~~~
Name    Question #   Pineapple on pizza?    Favorite editor?
anon1   1            Yes                    Emacs
anon2   1            No                     vim
~~~

That would make the data easier to work with for my use with (using the exported CSV file as a data file for jekyll).

(I'm interested if other users found this useful, too. Currently, I could work around this by doing a custom SQL query as I only have one form).

**Comment by lachmanfrantisek** [comment]
I agree. It would be useful in CSV as well as in the results' page.

- One line per user is used also in google forms.
- The current view was a little bit misleading for me on the first try when I got some results from anonymous users whose name was shortened.

I'm not sure about precise behaviour when we have many questions and many users. We need to scroll both horizontally and vertically.  What about some switching between questions? (One question per page.)

Nevertheless, thank you for this app!

**Comment by derBobby** [comment]
I just happily found the plugin but was sadly disappointed that results cannot be exported in one line per user. This would be AWESOME!

**Comment by stefan123t** [comment]
In general one line per user or submit should be possible.
The only problem can occur if the form has multiple choices as answer per question. In those cases the result should be a concatenation of all checked answers with some (configurable?) delimiter (eg , comma or | pipe) to separate individual selected options.

User Favorite_OS?
Anon3 Linux,FreeBSD,OpenBSD,NetBSD,you-name-it(tm)
Anon4 Linux,you-name-it(tm)

**Comment by ntnsndr** [comment]
I agree this would be extremely useful. I've found the form data very hard to work with because there's no way to organize it when each entry is scattered across multiple rows. Thank you so much for considering this change.

**Comment by Spartachetto** [comment]
I think that the data as is now is easier to use with a lot of statistical software...

In addition I think it would be useful to interact with @Rello to understand how the Data Analytics app could better use this data ..

**Comment by Rello** [comment]
Hello,
Nice idea actually. I will have a look. 
Do the results have a json endpoint or so already?

If not, i am planning a nc-internal-table type datasource for DA

I will get back...

**Comment by jancborchardt** [comment]
We should definitely use the same format as used by Google Forms, so software which can import responses will understand ours just the same. @jotoeri to keep in mind for the responses reworks. :)

**Comment by Rello** [comment]
Hello,

I think this request more relates to
Different Result-views #314

This gives the various statistics the user might need right in the form.
I had a look as the forms datamodel. To connect it to a proper (generic) reporting, quite some transpositioning and rearranging needs to be done.
I think the use-case here is a little limited and the forms-internal statistics should be sufficient
