### ISSUE TITLE
Deactivate Form manually

### ISSUE THREAD

**Issue by dacoex** [nextcloud/forms#1101]
_It would be great to be able to deactivate a form (resp. submission to it) manually._

<details>
<summary>Original Request</summary>
Currently, one has to delete a form in order to ensure no one enters further submissions into an existing form.

It would be great to be able to deactivate a form at certain conditions:

1. Submission deadline reached (similar to expiry of a sharing link max. validity)
2. Number of answers reached a certain threshold (e.g. registrations for a weekend excursion)
3. Manual deactivation 

Deactivation would have the the advantage that forms can be used for recurring occasions such as annual member meeting.
</details>

**Comment by jotoeri** [comment]
1.  You can currently set an expiration date on a form. Then nobody (except you as owner) can submit anymore after that date.
2. #596 
3. Ok, that seems to be a new request. ;)

**Comment by dacoex** [comment]
thanks for the triage.

so manual deactivation is similar to setting expiration date to the next hour (as a work around).

**Comment by hamza221** [comment]
What would be a better approach to implement this? 

1. set expiration to now or the previous date when the form gets deactivated
2. add a property to form "isOpen" and sync it with "expires" (when form expires or gets desactivated)

**Comment by jotoeri** [comment]
I'd go for a separate property `isDisabled`, but NOT syncing it. Disabling is then just evaluated first and thus overrides expiration. Can probably also have a separate EmptyContent.
