### ISSUE TITLE
Switch to main-branch

### ISSUE THREAD

**Issue by jotoeri** [nextcloud/forms#1115]
Meanwhile even parts of the core-ecosystem changed to `main`. I think there shouldn't be too much pain anymore to finally go this step.
Ref also https://github.com/nextcloud/groupware/issues/3

**Comment by jotoeri** [comment]
@Chartman123 Anything against doing this step now? 😉

**Comment by Chartman123** [comment]
I don't think so :)

**Comment by jotoeri** [comment]
Updating local setup possible by:
```
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```

Alternatively - just delete and freshly clone. 😉
