### ISSUE TITLE
forms is almost perfect for online voting, but need for full anonymitee

### ISSUE THREAD

**Issue by courtiol** [nextcloud/forms#1123]
- Nextcloud-Version: latest

Hi all,

We want to organize an online election within our company and we identified **forms** as almost the perfect tool for that.

We don't need something as secure as what would be needed for national presidential elections or anything like that, so the current version of **forms** seems to already meet almost all our needs:
- [x] people have to log in to connect to NextCloud, so outsiders cannot barge in
- [x] **forms** can constrain answers so as to voter being able to vote only for one candidate
- [x] **forms** can be set so that a given voter does not see for whom other voters have already voted for

There is just one caveat I can think about: the anonymous option does not prevent the person that created the form to check who voted for whom when exploring the Results.

The feature request would therefore to add a global additional anonymous option for the form, which would not reveal the identity of those that have filled the form. Only the summary results would thus be shown:

![image](https://user-images.githubusercontent.com/7499666/154276501-742d02ea-9511-4827-a04d-6f792d270670.png)

but not the detailed one:

![image](https://user-images.githubusercontent.com/7499666/154276737-d6a095e4-520d-46d2-8cd1-77ef690f0361.png)

Same for the download.

**Comment by jotoeri** [comment]
Hey Alexandre,

thank you for the praise! 😉
However: are you sure, you submitted that response, when the form was set to be anonymous?
Normally that should work just as you expect it: If the option is set, the storing of responses is directly anonymized on submit, so the information who gave which response is not even stored on the database (while everything beeing on database is shown then, as e.g. previously submitted non-anon responses).
That however introduces another drawback: As it is not stored who voted, we can not control who already voted. - So for the election case: People might be able to vote twice, once the responses are anonymized.
Just one workaround, that i could imagine, depending a bit on your election setup & security constraints: If you can assure, that everybody votes and you know the number of allowed voters, then you could just declare the whole election as invalid if the numbers don't match. However as i said - you just need to be clear with everybody that everybody really submits a response... 😕 

Some kind of access-control might be implemented with #617 (somewhen).
Hope, that helps...?!
Greets,
Jonas

**Comment by courtiol** [comment]
Thanks a lot for these info @jotoeri.

Yes I am sure I did set things as anonymous beforehand, but perhaps the issue is related to the fact that I am choosing the setting "Choose users to share with":
![image](https://user-images.githubusercontent.com/7499666/154427280-ea806389-c428-4d52-a45e-b1a69900a66a.png)
How is the anonymous setting supposed to handle such cases?

I am using the setting "Choose users to share with" because for the real use case, I would like only people from a specific group to have access to the voting.

**Comment by jotoeri** [comment]
Hey Alexandre,

normally the behaviour i described should be independent of which sharing option you chose...
Can you give me the exact Version oft your Nextcloud & Forms-App? Then i can test it once again on my side...

Greets,
Jonas

PS: Just to be sure: In the picture above, the anonymous Option seems to be unchecked. But i assume, you know that and it happened meanwhile during testing, no? 😉 

https://github.com/nextcloud/forms/blob/3602d4c46cd076cca009b88dd624274735613088/lib/Controller/ApiController.php#L987

**Comment by courtiol** [comment]
Shame on me... I mixed up and indeed the anonymous is indeed working...

OK, so I guess you are right, the drawback is that "Anonymous" and "Multiple responses per person" are tied together.

Perhaps one (simple?) way that would not require #617 would then be for the ID to be stored in the database so as to prevent multiple responses and yet that this ID would remain internal so that the admin would not see them in the CSV or detailed results.

I understand that this is less safe, but in most cases the point is to organize fair questionnaires and not to prevent gifted hacker to intercept data flow and decipher them.

My 2 cents on a possible design would someone be keen to implement that: perhaps clicking on "Anonymous responses" would by default tick the "Allow multiple responses per person" as it does now, but upon subsequent unticking of "Allow multiple responses per person" the new behavior would be triggered and an information message would be shown explaining the potential vulnerability.

**Comment by 089** [comment]
> Huhh, i'm sorry, but i don't see this happen.... I see it more probable, that we have somewhen a kind of one-time links & shares, as proposed in https://github.com/nextcloud/forms/issues/617. That will however still take quite a while to happen... 😕

Too bad! 

Surveys that are anonymous, although participants must be logged in to prevent multiple participation, I think is a killer feature in the corporate context and association context. 

This would make it possible to conduct anonymous, data-minimizing, privacy-compliant surveys without being able to assign individual answers to people, but also without people being able to falsify the survey result by filling out the form more than once. 

Is not there anything you can do?
