### ISSUE TITLE
Transfer Ownership

### ISSUE THREAD

**Issue by ThibautPlg** [nextcloud/forms#1131]
**Nextcloud (please complete the following information):**
- Nextcloud-Version: 22.2.5
- Forms-Version: 2.4.0

**Is your feature request related to a problem? Please describe.**
Nextcloud is used by many companies, that implies staff turnover and leaving employees. If the account is disabled or deleted, we lost access to the forms and related data. 

**Describe the solution you'd like**
We would like to be able to transfer forms ownership from an user to another, using occ commands and/or a web gui option.

**Describe alternatives you've considered**
I thought about changing manually the db, but it seems touchy and I cannot give control to it through my userbase. 

**Additional context**
If this isn't a regular use case, I think it may tend to become one as Nextcloud seems to be more and more used by privacy-concerned companies. Nextcloud Files and Calendar are already proposing such a feature, it's a shame that this is not "standardized".

Thanks for your reading and thanks for the amount of work you're placing on Nextcloud as a whole.

**Comment by CorinthCom** [comment]
This would be useful; User A develops the form, transfer Form to Users B,C,D... or Group. Then recipient users can share link to external people to answer/fill-in and collect their own answers.

**Comment by ajoana** [comment]
I support this request! I set up a form for an organizer of a small community festival and wish to assign editing rights to the organizing circle. See also https://github.com/nextcloud/forms/issues/322

**Comment by TheMetMan** [comment]
Same here! 
I have developed forms, but need my editor to be able to edit them also

**Comment by susnux** [comment]
Additionally:

It would be nice if you could configure to transfer all forms to another user / the admin, when a user is deleted (instead of removing the forms). This would be useful e.g. if a user leaves your company.

**Comment by ReimarBauer** [comment]
Hi.
thx for forms in nextcloud.
I got also to this. I would prefer to share the edit feature to someone else, e.g. a circle.
