### ISSUE TITLE
Intregration Onlyoffice with Nextcloud

### ISSUE THREAD

**Issue by SushantRathore-Admin** [nextcloud/forms#1132]
HI Team, 

I m trying to integrate Onlyoffice with nextcloud.   BUt i m facing Error when trying to connect (Error occurred in the document service: Error while downloading the document file to be converted.) (version 7.0.0.132) error while connecting onlyoffice from nextcloud.

Nextcloud and office installed on oracle7 Linux. 

I used this one 
1. ‘allow_local_remote_servers’ => true, ‘onlyoffice’=> array ( ‘verify_peer_off’ => true, ),
2. changed value of "rejectUnauthorized": from true to false in /etc/onlyoffice/documentserver/default.json

But its nothing still not working any solutions for me.

**Comment by jotoeri** [comment]
Please head over to the forum for such requests: ![help.nextcloud.com](help.nextcloud.com)
