### ISSUE TITLE
Email notification about every completed form answering

### ISSUE THREAD

**Issue by bvn13** [nextcloud/forms#1143]
**Nextcloud (please complete the following information):**
- Nextcloud-Version: 23.0.3.1
- Forms-Version: 2.4.0

**Is your feature request related to a problem? Please describe.**
I want to place my form on my site to collect answers. And I want to be informed about new answers.

**Describe the solution you'd like**
It will be good to have a possibility to receive e-mail notification about new answers.

**Comment by jotoeri** [comment]
Hey Vyacheslav,

this is already possible if you have the activity app enabled. New form responses create an activity, so on your settings you can disable/enable the email-notifications for these activities.
This is indeed currently only possible for all forms at once, setting it differently for single forms is tracked in #790.

Greets!
Jonas
