### ISSUE TITLE
New DB-Limit on String Length

### ISSUE THREAD

**Issue by jotoeri** [nextcloud/forms#1152]
Ref. https://github.com/nextcloud/server/pull/31679
Unfortunately we intentionally set the String-Column to 8192, as we had the use-case of 4900 chars on the form-description (https://github.com/nextcloud/forms/issues/529#issuecomment-665718823). I wouldn't like to strip that now again... 😢 

@nickvergessen Can you give me a hint on how to properly walk around this limit now on forms? Is maybe `MAX_STRING_SIZE initialization parameter is set to EXTENDED` given, so we could move to a `VARCHAR2` Type?

> <html><body>

VARCHAR2 | Maximum size: 4000 bytes, or 32767 bytes if the MAX_STRING_SIZE initialization parameter is set to EXTENDED
-- | --

</body>
</html>

Ref. [Oracle Docs](https://docs.oracle.com/en/database/oracle/oracle-database/19/refrn/datatype-limits.html#GUID-963C79C9-9303-49FE-8F2D-8AAF04D3095)

**Comment by nickvergessen** [comment]
Instead of string use Text and that can be up to 65k chars:
https://github.com/nextcloud/server/blob/master/core/Migrations/Version13000Date20170718121200.php#L835-L837
