### ISSUE TITLE
Small Code Cleanup

### ISSUE THREAD

**Issue by jotoeri** [nextcloud/forms#1160]
- To have it all in one place: Move `Question::Types` to a new `Constants::ANSWER_TYPES`

https://github.com/nextcloud/forms/blob/bd28203c5c2a51ed0f7cacffb94393bec090cd86/lib/Controller/ApiController.php#L457
https://github.com/nextcloud/forms/blob/bd28203c5c2a51ed0f7cacffb94393bec090cd86/lib/Db/Question.php#L53-L61
https://github.com/nextcloud/forms/blob/bd28203c5c2a51ed0f7cacffb94393bec090cd86/lib/Constants.php#L31-L41

**Comment by Chartman123** [comment]
If we unify question/answer types, we need to have a separation between allowed types for new questions and all available types   when we use the array in our code (e.g. datetime).

**Comment by jotoeri** [comment]
Actually there is no difference between answerTypes and QuestionTypes. It's just a matter of outdated naming. It was earlier the Question until John renamed it on the frontend to AnswerTypes for v2. So this here is just a rest of the old naming.

In the code, there is only this single mentioned usage of the QuestionType afaik. And to block the new creation of 'datetime' you implemented a separate check, no? So this is planned to just be an array `ANSWER_TYPES` listing in fact the 'all available types' and beeing used just as the old one is used. 😉

**Comment by Chartman123** [comment]
Yes, true. But I thought that in some future version we could remove it altogether from allowed types and remove my separate check again.

**Comment by jotoeri** [comment]
That's right, that's exactly the plan for v4. But then we will remove datetime completely (maybe convert old questions, thus v4 as it is a breaking change), so we also don't need it anymore in this array. 😉
