### ISSUE TITLE
Users can not enter a form when they do not have access to the app

### ISSUE THREAD

**Issue by xbluemonkx** [nextcloud/forms#1165]
**Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!**

**Describe the bug**

**To Reproduce**
Only a few users should be allowed to create forms. therefore the access to forms is limited to a specific usergroup.
If those people create a form they can share the link and people that do not have a nextcloud account fill out the form.
People that DO have a nextcloud account can not fill out the form because they do not have access to the app and are therefore forwarded to the dashboard.

**Expected behavior**
People with nextcloud account should be able to fill out forms, if anonymous users are allowed to fill it out. Even if they do not have access to the app itsel.

**Nextcloud (please complete the following information):**
- Nextcloud-Version: 23.0.3
- Forms-Version: 2.5

**Comment by jotoeri** [comment]
More or less duplicate to #647 😉
