### ISSUE TITLE
Export userID

### ISSUE THREAD

**Issue by demlak** [nextcloud/forms#1179]
**Is your feature request related to a problem? Please describe.**
We use LDAP for accounts in our NC. We can have people with same name.. but not same login.. so we would like to have Login-Name instead of Choosen-Name in CSV export.

**Describe the solution you'd like**
Ability to choose which credentials are going to be exported

**Describe alternatives you've considered**
Alternately i would like to know where in the code i have to change from Choosen-Name to Login-Name

**Comment by jotoeri** [comment]
Hey @demlak,

The export is done here: https://github.com/nextcloud/forms/blob/cd4bf61ab60130fe1ad62573e398208051883b50/lib/Service/SubmissionService.php#L149

Including the userID could indeed be a reasonable way on export 👍
