### ISSUE TITLE
Export results in 404

### ISSUE THREAD

**Issue by demlak** [nextcloud/forms#1180]
**Describe the bug**
Export to CSV results in 404
(view summary in backend works)

**Screenshots**
![Screenshot_20220419_063349](https://user-images.githubusercontent.com/11285006/163920950-68ad02e7-e05d-45f5-9863-cf13baa56b39.jpg)

**Nextcloud (please complete the following information):**
- Nextcloud-Version: 22.2.1 (i can't upgrade right now)
- Forms-Version: Latest Dev Setup (git clone 19.04.2022 - 06.30am)

**Additional context**
Latest Version (2.5.0) from Appstore works

**Comment by jotoeri** [comment]
Hey @demlak,

i'm sorry, seems like we didn't update the readme for a while...
You need to install the php-dependencies by running `composer install`. Ideally run this command twice, then you have the full setup and everything should work. Also the errrors out of #1181 should disappear then.

Greets! ☺️ 
Jonas
