### ISSUE TITLE
Confusing mixture of element types and question types

### ISSUE THREAD

**Issue by tflidd** [nextcloud/forms#1190]
From my point of view, you mostly describe what kind of element is used to answer the question, a dropbox or a checkbox. Why isn't there the option `radio button`?

![image](https://user-images.githubusercontent.com/8111200/165475584-8132edff-7f8a-47b1-8c91-197c4c6b473e.png)

I found an old issue that already referred to translation problems (https://github.com/nextcloud/forms/issues/597), it would be great to find a solution that makes it easy and understandable for everyone to use.

> The term 'multiple choice' is the right term for choosing only one option in english.

For me that would apply for the dropbox as well where you can just choose one option. The dropbox and the radio buttons are just two different visual implementations of the same type of question.

**Comment by tflidd** [comment]
For the translation:
The definition is not that clear in other languages (e.g. French) that it has to be a unique choice. So if we translated the term `single-answer question` instead, it would be clearer. But in this sense, we should then translate the Checkboxes as `multiple-answer question`. It's not impossible but a bit confusing especially with Transifex, you don't get the whole context easily. And it isn't logic with the dropdown....

transifex discussion: https://www.transifex.com/nextcloud/nextcloud/translate/#fr/forms/292389149

**Comment by Chartman123** [comment]
The current names for the question types are based on e.g. the names in Google Forms. What should make it clear are the symbols in front of the entries:
![image](https://user-images.githubusercontent.com/16020496/165490596-0b8df929-c069-4e14-9d16-aa82cbcbbb7c.png)

**Comment by tflidd** [comment]
I don't have any symbols.



> The current names for the question types are based on e.g. the names in Google Forms.

Still I think it's strange to have this mixture. And their translation is just the word-by-word translation that doesn't solve the confusion. Can we do it better than google?

**Comment by Chartman123** [comment]
> Can we do it better than google?
Sure, why not... Just wanted to point to the possible origin of the wording 🙂

**Comment by jotoeri** [comment]
> you mostly describe what kind of element is used to answer the question
> The dropbox and the radio buttons are just two different visual implementations of the same type of question.

That is at least a true argument... 😉 👍 
The argument once was the too technical wording of 'Radio buttons'.

@jancborchardt @nimishavijay @skjnldsv  I'd be fine with `Radio buttons` i think. - Seems like we have the confusion anyways. I could imagine to do the change as one-way step for v3 and hopefully getting rid of that annoying discussion. How do you think?

**Comment by nimishavijay** [comment]
The icons seem to be useful for me but if this is repeatedly causing confusion then we should definitely change it.
"Radio buttons" sounds good to me, also because it sounds consistent with the rest of the options :) would there be any translation issues with "Radio buttons"?

**Comment by jotoeri** [comment]
> would there be any translation issues with "Radio buttons"?

Probably at least less than now i think... 🤔

**Comment by jotoeri** [comment]
@skjnldsv Any opinion? Otherwise i'd say let's go for the `Radio buttons`?
