### ISSUE TITLE
Date/Datetime Icons broken in dark mode

### ISSUE THREAD

**Issue by jotoeri** [nextcloud/forms#1196]
See add-question menu here:
> https://youtu.be/j0APTeBFfSU?t=173

**Comment by Chartman123** [comment]
Can't confirm... Probably a cache problem in his browser.
![grafik](https://user-images.githubusercontent.com/16020496/167314226-a7301240-0418-408d-a2e3-a2f0f64aa938.png)

**Comment by jotoeri** [comment]
🎉 👍
