### ISSUE TITLE
Notification/Activity for new form responses

### ISSUE THREAD

**Issue by bpcurse** [nextcloud/forms#12]
**Which Forms version are you running?** (see apps page)
1.0.3
**Nextcloud or ownCloud?:**
Nextcloud
**Nextcloud/ownCloud version:** (see Nextcloud admin page)
15.0.5

A customizable notification on form submission (either to the owner or to a defined email address) would be another great feature.

**Comment by GoodInfoSeeker** [comment]
Every webform would need option to being notified by email immediatelly!

**Comment by jancborchardt** [comment]
Moving @Pilzinsel64’s comment from https://github.com/nextcloud/forms/issues/318 here

> It would be really nice to see an integration to the Activity App, like Files, Talk and Deck has.
> 
> Just a few points for what it would be nice to get an info in your stream or per E-Mail:
> - Notification if an anonyme user has sent an answer to a form (if unregistred user or "anonym answer" is checked on a Form)
> - Notification if an registred user has sent an answer to a form
> - maybe more?
> 
> If I talk about notifications, it also would be nice to decide for every single board to enable notifications or not.
> 
> If you need any more infos/examples, just ask.

**Comment by ei8fdb** [comment]
Email notification would be useful, but for me a lower priority than a question, and answer rich form creator.

If I really want to know if someone's answered, I'll go look. :smile:

**Comment by bpcurse** [comment]
> Email notification would be useful, but for me a lower priority than a question and answer rich form creator.
> 
> If I really want to know if someone's answered, I'll go look. smile

It depends on the use case.
If you want to use it as a system to register for some kind of service, you will need an email notification to the provider. If the questions are simple, notification will probably have a higher priority. Most people won't be willing to check manually every hour if there is new input.

**Comment by rocky-III** [comment]
we really are waiting for this feature "Notification/Activity for new form responses"
we are glad you aded it to milestone 2.2
THANKS

**Comment by Oni-Shadow** [comment]
G'day
I have just started using the form app and enjoying it so far. Thanks for your work, it is a very usefull app !
I would love being notified whenever an answer is made and I am not the only one.
I was wondering if it is possible to make a list of people/user in the form who should be notified whenever there is a new answer. Of course this list could be updated/modified by going back to the form.

is it something that could be considered ? 

Cheers

**Comment by jospoortvliet** [comment]
I would say that 'just' creating an activity when a form is filled in would already be very helpful - users can then configure if they want to get an email or push notification. That would then of course notify on ALL forms, at once, so limiting it a bit more might be a next step but that's less urgent. Creating an activity on each form added would be relatively easy, I suppose.
