### ISSUE TITLE
Error during install migration

### ISSUE THREAD

**Issue by JanMalte** [nextcloud/forms#1201]
**Describe the bug**
Install an enable the app results in a database migration error.

```
php occ app:install forms
Error: Database error when running migration 010200Date20200323141300 for app forms
Column "oc_forms_v2_forms"."description" is type String, but exceeding the 4.000 length limit.
```

**Expected behavior**
Install and enable should not throw any database error

**Screenshots**

**Nextcloud (please complete the following information):**
- Nextcloud-Version: 24.0.0
- Forms-Version:  2.5.0

**Comment by jotoeri** [comment]
@nickvergessen Any idea, why we don't see this issue in the CI, but it happens here? We changed the column in a later migration to text, so indeed the first moment creates a too long string. But ci doesn't show that error on installation.

@JanMalte Could you please provide more information on your setup, esp on your DB server (Server & Version)?

**Comment by nickvergessen** [comment]
Let's see after we know the DB system + version

**Comment by JanMalte** [comment]
I'm running nextcloud with PostgreSQL 14.2

**Comment by jotoeri** [comment]
Hmm, normally this is what we had on ci, too:

> starting PostgreSQL 14.2

https://github.com/nextcloud/forms/runs/5988005027?check_suite_focus=true


@JanMalte Can you please give information on:
- php Version
- Updated Nextcloud & Forms app or fresh installation?
- (And just for completeness maybe http-Server version?)

**Comment by nickvergessen** [comment]
https://github.com/nextcloud/forms/blob/7417ce590c113dc948b9bdb901978c0a85b1918c/lib/Migration/Version010200Date20200323141300.php#L95-L98

you actually create columns with String > 4000 during the migration.
Installing works as it goes all the way before running the DB change.
But if any previous version existed we update migration by migration and so you step through this.

**Comment by nickvergessen** [comment]
Can reproduce with this:
1. Install master
2. Run these queries
```
DELETE FROM `oc_migrations` WHERE `oc_migrations`.`app` = 'forms';
DROP TABLE `oc_forms_v2_answers`, `oc_forms_v2_forms`, `oc_forms_v2_options`, `oc_forms_v2_questions`, `oc_forms_v2_submissions`;
UPDATE `oc_appconfig` SET `configvalue` = '2.1.0' WHERE `oc_appconfig`.`appid` = 'forms' AND `oc_appconfig`.`configkey` = 'installed_version'; 
```
3. Run `occ upgrade`
> Exception: Database error when running migration 010200Date20200323141300 for app forms
Column "oc_forms_v2_forms"."description" is type String, but exceeding the 4.000 length limit.
Update failed

**Comment by nickvergessen** [comment]
Pull request to fix it is at https://github.com/nextcloud/forms/pull/1212

**Comment by jotoeri** [comment]
> But if any previous version existed we update migration by migration and so you step through this.

But that would in practice (without manually producing this specific situation) mean to have a migration from forms <v2.0.2 (Maxversion NC19), so there is any migration run, that changes the column and triggers the check, no?
> // we will NOT detect invalid length if the column is not modified

Anyways - we'll change the migration, yes. I just didn't fully get the way this happened here. :thinking:

**Comment by JanMalte** [comment]
These are the two migrations I currently have in my DB. I'm not sure how I got into the current situation.
```
nextcloud=# SELECT * FROM oc_migrations WHERE oc_migrations.app = 'forms';
  app  |         version
-------+--------------------------
 forms | 0010Date20190000000007
 forms | 010102Date20200323120846
(2 rows)
```

**Comment by jotoeri** [comment]
So - should work now with v2.5.1 @JanMalte  🙂
