### ISSUE TITLE
Anonymous form invisible to logged in users

### ISSUE THREAD

**Issue by sixtyfive** [nextcloud/forms#1211]
When a form created as anonymous is shared as a link with a user who happens to also have an account and be logged in, the link which would otherwise display the form (as in, https://cloud.domain.tld/apps/forms/UUID) will now instead redirect to the Cloud's dashboard (as in, https://cloud.domain.tld/apps/dashboard/#/). A non-technical user will therefore assume the form/survey to be broken.

**Comment by jotoeri** [comment]
Works for me on NC24 & Forms 2.5. Please give more information on your setup, otherwise we can just guess. Please use the given template next time, then we already have much more information.
