### ISSUE TITLE
Reduce Vertical Dead Space

### ISSUE THREAD

**Issue by mathmaniac43** [nextcloud/forms#1234]
Hello,

I have recently started using this app, and so far think that the flexibility it affords is great! However, I have noticed that the forms take up a lot of vertical dead space, reducing the amount of information and interactive elements on the page at one time.

![image](https://user-images.githubusercontent.com/918497/176795792-d023f3c0-761d-4529-aef1-00fa6721c950.png)

Would it be possible to reduce the amount of vertical space between elements? I personally think that it would be beneficial to apply that for everyone, but a setting to allow it would be great too.

Thanks!

**Comment by jotoeri** [comment]
@jancborchardt @nimishavijay That one is your decision. 😉

**Comment by jancborchardt** [comment]
Yeah, in the sharing mode the whitespace could be reduced a bit – but not a lot, cause whitespace is important for separation. Maybe 8–16px or something.

Because also, for form creators, we would like little difference/movement between the edit and view modes.

**Comment by Chartman123** [comment]
Thank you :) Yes, we should make sure to have as little movement between the different modes.

**Comment by Chartman123** [comment]
Comparison of padding between questions (80px is current). As we're using the same CSS rules for edit/view mode there will be no movement between the two modes.

@jancborchardt I think we can go as low as 50 px before we lose the separating aspect of the white space.

|80px | 70px | 60px | 50px |
|---|---|---|---|
|![grafik](https://github.com/nextcloud/forms/assets/16020496/66d2b7be-a3d3-4476-a45d-8c69c4677689)|![grafik](https://github.com/nextcloud/forms/assets/16020496/55e40d16-21f4-4361-9030-476cf967b70f) |![grafik](https://github.com/nextcloud/forms/assets/16020496/86f43dda-57f3-44b3-b32b-b3ec42ae67ba) |![grafik](https://github.com/nextcloud/forms/assets/16020496/8e375e19-da5c-49c0-9586-0f1fa376dbfc) |
