### ISSUE TITLE
Forms Will Not Submit On Desktop

### ISSUE THREAD

**Issue by FinpyJ** [nextcloud/forms#1244]
Forms do not submit on desktop, when you click the button it loads for a second and then just returns back to the form and nothing is submitted. Works fine on mobile though.

**Comment by jotoeri** [comment]
Hey Finley,

i'm sorry to tell you, but submitting works perfectly fine on all of my test-instances. Thus:
- Please clear your browser-cache and try again. Maybe even try with another desktop-device to make sure it is not a problem on your side.

In case the problem then still consists, you can come back here. However, please provide Information on your setup! This means, give your Server-Version, Forms-Version, Information on your OS, Browser, etc... Then we can at least try to reproduce your problem. Currently i can just guess and tell you it works on all my guessed setups.

In general, please use the provided template for bug-reports! There it is e.g. also initiated to provide the information on your setup.

Greets,
Jonas
