### ISSUE TITLE
Separator line is barely visible due to low contrast

### ISSUE THREAD

**Issue by PVince81** [nextcloud/forms#1254]
Input fields are shown with a thin, grey line with too low contrast to the white background.

![image](https://user-images.githubusercontent.com/277525/179236046-dda5d3b7-3303-4724-b65d-a7cb2e4a5e17.png)

**Comment by jancborchardt** [comment]
@skjnldsv @jotoeri @Chartman123 how would it look like if we just use the normal textarea style? Might just be fine, no?

Otherwise, we can up the contrast by using `var(--color-text-maxcontrast)` for the line?

**Comment by Chartman123** [comment]
Is the color the same as for the placeholder text at the moment? At least in dark mode it seems to be the same...

![image](https://user-images.githubusercontent.com/16020496/179949791-b8a8d008-ca7c-48b1-8c6d-e83b094b39fc.png)

Do we need that line at all? For other question types there is also no separator...

**Comment by jancborchardt** [comment]
We definitely need a line denoting that it's an input field, otherwise it just looks like normal text. :)

**Comment by Chartman123** [comment]
> how would it look like if we just use the normal textarea style? Might just be fine, no?

@jancborchardt do you have an example where this textarea style is already used? I've also tried the 'maxcontrast' on my dev instance and think that this is also fine for now. I just can't seem to get it working while being in the edit mode of the form. It keeps the color no matter what is set in the corresponding css.
