### ISSUE TITLE
Swedish translation doesn't match the English one

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/forms#1264]
https://github.com/nextcloud/forms/blob/e6231fa38445d99d6e8e414873aa8ad618296b43/src/views/Submit.vue#L71-L73
https://github.com/nextcloud/forms/blob/3c5e843d8489af8d4abb11aad5de8ab609f3a2c1/l10n/sv.js#L100-L101

Since there is an aria-label which gives more details about the button, it would be expected that the wording matches.

**Comment by jotoeri** [comment]
@rakekniven seems like i can't create an issue on transifex, since i'm no translator for swedish. Do you know whom to ping or can you create the appropriate issue on transifex? :blush:

**Comment by jotoeri** [comment]
Thank you! ❤️
