### ISSUE TITLE
non anynymous poll for user without a Nextcloud account

### ISSUE THREAD

**Issue by MrManor** [nextcloud/forms#1291]
**Nextcloud (please complete the following information):**
- Nextcloud-Version: 24.0.3
- Forms-Version: 2.5.1

**Is your feature request related to a problem? Please describe.**
I cant find any way to poll people outside Nexcloud, except using anonymous polls. But anonymous polls comes with its own set of problems like people voting several times, organizer unable to see who has not voted and so on

**Describe the solution you'd like**
The posibility to send identifiable polls, with a unique link to each participants
Maybee with a possibility for the participant to add his own name on the answer form, like seen on doodle.

**Describe alternatives you've considered**
I use doodle - sorry 

**Additional context**
If the above is implemented a "pseudo anonymous poll" could be added by letting Nextcloud send invite links including a hashed identifier, not visible in the form builder. Of cource the form show to the user should then include some information that a the anonymity  could easily be defeated. 
But in many cases anonymity is not desired neither by the quiz master or the participant.

**Comment by jotoeri** [comment]
Apart from the polls app, dullicate of #617 😉

**Comment by MrManor** [comment]
> For Doodle-like polls you can use the Polls app. innocent

Dang! I did not think about searching for another app. Thanks! And @jotoeri  you are right to! #617 covers the rest of my dreams :-)
