### ISSUE TITLE
Some text is not localized for "ru" locale

### ISSUE THREAD

**Issue by akhilman** [nextcloud/forms#1296]
**Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!**

**Describe the bug**
[The Russian localization file](https://github.com/nextcloud/forms/blob/master/l10n/ru.json) has no entry for "Enter your answer", It should be "Введите ответ".

**To Reproduce**
1. Create a form with a "Short answer" question
2. Open this form as responder in browser with Russian locale
3. See non localized placeholder.

**Expected behavior**
All text should be localized.

**Screenshots**
![Screenshot from 2022-08-17 14-16-14](https://user-images.githubusercontent.com/180812/185058013-c0d504dd-ca8f-4026-a627-aaf4a528bfdd.png)

**Nextcloud:**
- Nextcloud-Version: 23.0.8
- Forms-Version: 2.5.1

**Desktop (please complete the following information):**
 - OS: Manjaro GNU Linux
 - Browser Firefox
 - Version 103

**Comment by jotoeri** [comment]
Hey @akhilman,

seems like you are able to translate it to russian? Because i am not. :stuck_out_tongue: 
If you want, we'd be happy if you can head over to transifex and insert the right translation there, which will then automatically be pushed to the linked localisation-file. As far as i see, there's ~20% not translated to russian currently. With the next release, the russian translation then would be more complete. :tada: 

https://www.transifex.com/nextcloud/nextcloud/forms/

Greets! :slightly_smiling_face: 
Jonas

**Comment by akhilman** [comment]
Thanks. I'll take a look.

**Comment by akhilman** [comment]
We found that these strings are not translated: 
- Enter your answer
- Pick a date
- Pick a date and time

All of them currently translated in transifex.

**Comment by jotoeri** [comment]
Just wait a day for transifex to push to the repo.

**Comment by Chartman123** [comment]
Must the strings be reviewed on Transifex before being pushed to Github?

**Comment by jotoeri** [comment]
Nope. Just the Bot only runs once a day.

**Comment by akhilman** [comment]
Translations for "Pick a date" and "Pick a date and time" already present in my `custom_apps/forms/l10n/ru.js` and `custom_apps/forms/l10n/ru.json` but the form page still shows English placeholders. 

```
root@servak:/srv/nextcloud/nextcloud# grep "Pick a date" custom_apps/forms/l10n/ru.*
custom_apps/forms/l10n/ru.js:    "Pick a date" : "Выберите дату",
custom_apps/forms/l10n/ru.js:    "Pick a date and time" : "Выберите время и дату",
custom_apps/forms/l10n/ru.json:    "Pick a date" : "Выберите дату",
custom_apps/forms/l10n/ru.json:    "Pick a date and time" : "Выберите время и дату",

```
![image](https://user-images.githubusercontent.com/180812/185140093-6946b691-c25c-4cac-9d2c-21ee055bc7b9.png)

**Comment by Chartman123** [comment]
Seems to be the same problem with German at least for the date fields. 

![image](https://user-images.githubusercontent.com/16020496/185144346-e33b3985-2702-4888-9062-d5e9ece825ef.png)

So do we have a problem with getting the translated strings there? At first glance, I couldn't see anything...

**Comment by Chartman123** [comment]
@jotoeri: Could it be because the NcDatetimePicker component already has a computed "placeholder" property?

https://github.com/nextcloud/nextcloud-vue/blob/2be31da78f84967b607f6e14d0dbdd2b0aa9ab70/src/components/NcDatetimePicker/NcDatetimePicker.vue#L305-L327

**Comment by jotoeri** [comment]
That seems to be it, yes! Seems like translations are not extracted there properly. Probably just needs to remove the `this.` there, then we can also remove it for us.

**Comment by jotoeri** [comment]
Or probably even better, fixing the extraction there and in addition creating a prop that can override the existing placeholders, so we can use our own ones. 😉 🙈

**Comment by Chartman123** [comment]
> Or probably even better, fixing the extraction there and in addition creating a prop that can override the existing placeholders, so we can use our own ones. 😉 🙈

You mean like for the format property?

**Comment by jotoeri** [comment]
Yep 👍

**Comment by Chartman123** [comment]
Ok, I'll create a PR for that :)
