### ISSUE TITLE
API Error

### ISSUE THREAD

**Issue by orkotr** [nextcloud/forms#1300]
Hello,

Whatever I try, I end up. with API error with forms app.
/ocs/v2.php/apps/forms/api/v2/forms

The error I receive: 
failure 404 Invalid query, please check the syntax. API specifications are here: http://www.freedesktop.org/wiki/Specifications/open-collaboration-services.

Whilst other apps working fine on my trials, I cannot make Forms api work.

Any suggestions?

**Comment by jotoeri** [comment]
- Please give more information on your setup! Otherwise we can just guess: Serverversion, Formsversion, how do you try to access?
- Just one guess: Is CORS involved in your way of requesting? See https://github.com/nextcloud/forms/pull/1139

**Comment by orkotr** [comment]
Hello,
I was trying with n8n http requests node. 
Now I installed an API Tester app to iPad screenshots as in the attachment.
Kindly awaiting for your helps.
![C56D6EFE-C570-48C0-B997-F8A989671A9D](https://user-images.githubusercontent.com/7313607/185744044-4f9f3b84-9ecc-4a87-9f30-bf9628de88d6.jpeg)
![482F392D-ACFA-4475-9A8E-F587BA8021A1](https://user-images.githubusercontent.com/7313607/185744049-128a2aae-87bb-471e-b0b5-6fd9aa7847f1.jpeg)

**Comment by jotoeri** [comment]
Still no information on your Cloud-Setup.
If your forms-app is not on current master, you need to use the api v1.1, as v2 is not released yet. https://github.com/nextcloud/forms/blob/v2.5.1/docs/API.md

Apart from that, for support-requests please use the forum: help.nextcloud.com

**Comment by orkotr** [comment]
Using v1.1 fixed the issue. Thanks 🙏
