### ISSUE TITLE
Make our changelog cloud-readable

### ISSUE THREAD

**Issue by jotoeri** [nextcloud/forms#1301]
Apps-Section in Server can show a changelog. However, our changelog is currently not formatted properly. Needs triage, i currently don't find the right documentation section for the right formatting. 🙈

**Comment by Chartman123** [comment]
The app store documentation for the Changelog can be found here:

https://nextcloudappstore.readthedocs.io/en/latest/developer.html#changelog

So we need to change the versioning in our Changelog to `^## (\d+.\d+.\d+)`
