### ISSUE TITLE
Abiity to remove embedded text

### ISSUE THREAD

**Issue by mtompkins** [nextcloud/forms#1307]
- Nextcloud-Version: all
- Forms-Version: 2.5.1

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Ability to remove the embedded text of:
*Responses are connected to your Nextcloud account. An asterisk (*) indicates mandatory questions.*

If a form is exposed externally for public use this creates confusion.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by jotoeri** [comment]
It is only shown if you're logged in. So public users won't see it. :wink: 
https://github.com/nextcloud/forms/blob/7097be76385827db46c94d1af26940be6748f8a3/src/views/Submit.vue#L169

**Comment by mtompkins** [comment]
Mea culpa. Thanks for the information.
