### ISSUE TITLE
Style problems in the footer

### ISSUE THREAD

**Issue by Pentaonia** [nextcloud/forms#1337]
**Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!**

**Describe the bug**

1. In the footer of the forms, we noticed some style problems as you can see in the screenshot. On the computer you can see that the slogan is slightly cut off. On the mobile phone half of the slogan in the footer is missing.
2. There is a link to the nextcloud sing up site in the footer that is called "Holen Sie sich Ihr eigenes kostenloses Konto", how to remove that?

**To Reproduce**
1. Go to [this](https://cloud.queer-bayreuth.de/index.php/apps/forms/QSqo5K3tSZzPnpyr) example form of our nextcloud
2. Scroll down
3. On the computer: see the slight cut off or shrink the browser to mobile phone size and see that the slogan disappears nearly completely.

**Expected behavior**
1. The footer should be displayed completely on phone and pc
2. The "sing up" link should be removable or at least customizable.

**Screenshots**

Style problem on the computer
![Here the footer from the computer browser](https://user-images.githubusercontent.com/93387223/189612076-8d61e794-b058-4e82-b3f8-b2ef97548b21.png)

Style problem on the mobile phone
![Here from the mobile phone browser](https://user-images.githubusercontent.com/93387223/189612258-207fb5b3-39b6-4812-869e-2404ce64e769.png)

**Nextcloud (please complete the following information):**
- Nextcloud-Version: 24.0.4
- Forms-Version: 2.5.1

**Desktop (please complete the following information):**
 - OS: Windows/Android/iOS
 - Browser: Chrome/Safari

**Smartphone (please complete the following information):**
 - Device: Iphone/Motorrola
 - Browser: Chrome, Safari

Thanks for your help!

Best
Loubert

**Comment by Chartman123** [comment]
@jotoeri will this already be fixed by your latest commits?

**Comment by jotoeri** [comment]
Not sure. I only worked on the min-height. We might need to double-check and also where this comes from in this specific case.

**Comment by Chartman123** [comment]
I can reproduce it on one of my productive clouds and also on master on my dev machine. The footer is overlapped by the content div:

![image](https://user-images.githubusercontent.com/16020496/189890564-df60a011-2bb0-4af1-a6c1-2b31d0c34415.png)

The problem only appears when disclaimer and privacy links are set.

**Comment by jotoeri** [comment]
Did you check the size of the footer and its content? Maybe its also a Server issue, having a too small footer.

**Comment by Chartman123** [comment]
Yes, this might be it... When I change the height of the footer style from 65 px to 85 px, everything is within this div. So we can't do really anything about it here and it has to be fixed in the server repo?

**Comment by fabolhak** [comment]
Turning off the "Holen Sie sich ihr eigenes kostenloses Konto" is pretty easy: 
https://help.nextcloud.com/t/remove-link-get-your-own-free-account/41131

However, there is still a style problem when having both the legal notice and privacy policy link.

**Comment by hobigo** [comment]
This problem still persists.
The submit button can not be touched on IOS devices with Safari.
Forms are not usable for me, as most of the IOS/Safari users do not know how to use Chrome instead.

![ssssss](https://user-images.githubusercontent.com/9110172/216836351-2baba800-8c79-4722-93f8-b21e3728b900.jpg)

**Comment by stefan-franz** [comment]
Do you really need this footer.....neither microsoft forms nor google forms have this. 
Whould improve Nextrcloud Forms really if we can use it without a footer.

**Comment by Chartman123** [comment]
@stefan-franz This is part of the public page view of Nextcloud and as far as I know can't be removed within an app. Please correct me if I'm wrong :)

**Comment by Art4** [comment]
I've received the same problem with the hidden send button behind the footer on Safari. We noticed that the button appears again after closing the Nextcloud app banner on the top. 

![grafik](https://github.com/nextcloud/forms/assets/2162994/59e0b208-9334-42a4-be24-2dfcf85e2ce1)

**Comment by Chartman123** [comment]
Has been fixed in Server now and will be part of the next releases of Nextcloud.
