### ISSUE TITLE
Add search feature in Dropdown menu

### ISSUE THREAD

**Issue by s8321414** [nextcloud/forms#1339]
**Nextcloud (please complete the following information):**
- Nextcloud-Version: 24.0.4
- Forms-Version: 2.5.1

**Is your feature request related to a problem? Please describe.**
Dropdown question in Forms may have many options, but we can only find a option by eyes for now.

**Describe the solution you'd like**
Add search box in Dropdown.

**Comment by Chartman123** [comment]
This will be available in the next release. #1283

**Comment by Chartman123** [comment]
I have to apologize... the old PR contained `searchable=false`... So this will be fixed with #1342
