### ISSUE TITLE
Mandatory/non mandatory questions

### ISSUE THREAD

**Issue by stefan123t** [nextcloud/forms#135]
**Which Forms version are you running?**
1.0.3

**Nextcloud or ownCloud?:**
Nextcloud

**Nextcloud/ownCloud version:** (see Nextcloud admin page)
17

### Steps to reproduce
1. create a form with non-mandatory fields
2. enter data into mandatory fields (*) leave non-mandatory fields empty

### Actual behaviour
3. cannot submit form without filling some non-mandatory fields with eg „n/a“ or some other non-null value

### Expected behaviour
Option to submit anyway or preset fields with some default text eg „n/a“

### Server configuration
**Where did you install Nextcloud from:**
Nextcloud App store 
**Operating system**:
Linux
**Web server:**
Apache2
**Database:**
MySql/MariaDB
**PHP version:**
7.2

**Comment by stefan123t** [comment]
Many thanks for creating the App, it truly eases an itch!
Maybe you can add the feature to add non-mandatory fields easily to the next revision ?

**Comment by ntnsndr** [comment]
Agreed on both @stefan123t's points above!

**Comment by skjnldsv** [comment]
Mandatory support is coming for version 2
