### ISSUE TITLE
Fix Results Bar

### ISSUE THREAD

**Issue by jotoeri** [nextcloud/forms#1350]
Look changed somehow with nc25. Was discussed on the chat somewhen, should ideally look like the old version.

![grafik](https://user-images.githubusercontent.com/47433654/191379620-1119d9e2-83c8-4d79-aa6d-7687c703fb3a.png)

**Comment by Chartman123** [comment]
So, I think the original color has been calculated by this scss file:
https://github.com/nextcloud/server/blob/48def620cb2132258be7eaf2495f67a5d88a1932/core/css/variables.scss#L58

The result for --color-primary-element-light was `#17ADFF`

But here it has been set to a much lighter color `E5F2F9`
https://github.com/nextcloud/server/blob/12e7f414f783acc9a30b7000a09b68a214077f04/apps/theming/css/default.css#L23

Which color definition should be used for this? The from the core variables.scss or from the default.css?

**Comment by jotoeri** [comment]
CC @jancborchardt @skjnldsv 
Can you tell how to use the 'New' colors? Or esp. which one to use now for the progress bar?

**Comment by jancborchardt** [comment]
@Chartman123 @jotoeri I can't comment on the algorithm, but yes, progress bars and forms results bars should look more like before, the new light color is definitely not intended.

**Comment by Chartman123** [comment]
@jancborchardt So would it make sense to create a new color variable for that purpose? In my opinion this should happen in server... The value from the above mentioned scss file in core/css would be just the way we need it, but it gets overwritten by the one from the theming app... So perhaps we should introduce a new variable, e.g. `--color-primary-element-gradient`?

**Comment by jancborchardt** [comment]
Sounds reasonable @Chartman123 – what do you think @juliushaertl @skjnldsv or do we have an existing variable for that already?

**Comment by jotoeri** [comment]
There are two gradient variables already. Just no gradient primary-ELEMENT.

https://github.com/nextcloud/server/blob/12e7f414f783acc9a30b7000a09b68a214077f04/apps/theming/css/default.css#L27

**Comment by Chartman123** [comment]
@jotoeri, @jancborchardt: So we could use this instead of our own gradient definition?

This would show a gradient from `#0082c9` to `#329bd3` instead of `#0082c9` to `#17ADFF` before.

**Comment by jotoeri** [comment]
Old one was probably better. So the new variable that you mentioned could of course be an option. But i also font know in which base variables are created and used in Server.
