### ISSUE TITLE
to submit the form, mouse can only click on border

### ISSUE THREAD

**Issue by maximelehericy** [nextcloud/forms#1372]
**Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!**

**Describe the bug**

**To Reproduce**
Fill in a form.

**Expected behavior**
Click anywhere on submit button to submit the form.

**Screenshots**
mouse on button
![22-10-07_000034](https://user-images.githubusercontent.com/87175513/194520229-bd2dad63-80fa-42f0-9bbf-39cec0644c79.png)

mouse on border
![22-10-07_000033](https://user-images.githubusercontent.com/87175513/194520239-18080217-7d61-4a8d-abed-a472a924adda.png)

Color change is not really noticeable, but I can assure you that clicking on the button does nothing.
Only clicking on the border actually submit the form.

**Nextcloud (please complete the following information):**
c.nc.c

**Desktop (please complete the following information):**
windows 11
firefox latest version

**Browser log**
```
Open your console, reload your page and/or do the action leading to this issue and copy/paste the log in this thread.
```

<details>
<summary>How to access your browser console (Click to expand)</summary>

# Chrome
- Press either CTRL + SHIFT + J to open the “console” tab of the Developer Tools.
- Alternative method:
    1. Press either CTRL + SHIFT + I or F12 to open the Developer Tools.
    2. Click the “console” tab.

# Safari
- Press CMD + ALT + I to open the Web Inspector.
- See Chrome’s step 2. (Chrome and Safari have pretty much identical dev tools.)

# IE9
1. Press F12 to open the developer tools.
2. Click the “console” tab.

# Firefox
- Press CTRL + SHIFT + K to open the Web console (COMMAND + SHIFT + K on Macs).
- or, if Firebug is installed (recommended):
    1. Press F12 to open Firebug.
    2. Click on the “console” tab.

# Opera
1. Press CTRL + SHIFT + I to open Dragonfly.
2. Click on the “console” tab.
</details>

**Additional context**

**Comment by Chartman123** [comment]
I'll have a look at it :)

**Comment by Chartman123** [comment]
@maximelehericy I can't reproduce it... neither on my dev setup on openSUSE Tumbleweed, latest Firefox, nor on Win 11 with latest Firefox/Chrome. The mouse cursor always switches to the "hand" mode as soon as it's over the button. What's the pixelated thing on your screenshots below the button?

**Comment by jotoeri** [comment]
Same here. Cant reproduce on Ubuntu20 latest firefox, as well as on Win10 latest Firefox. On both machines also the public template of the NC-Include form works. (https://cloud.nextcloud.com/apps/forms/7x6yQHNpZDbgC3EP)
@maximelehericy could you investigate it a bit on your browser to get an idea, how it could happen?

**Comment by maximelehericy** [comment]
hmm; cannot reproduce it either now... the greyed thing was an update popup that I couldn't minimize. Maybe that was linked.
I'll close the issue for now,
