### ISSUE TITLE
Display time in user-defined timezone (or add an option) in CSV-export

### ISSUE THREAD

**Issue by terion-name** [nextcloud/forms#1384]
On results view responses are properly displayed with timestamps in timezone defined by viewing user. But when exporting to CSV timestamps are in GMT-0, which is very hard to read for people that process them (if fill time is valuable). Export should respect timezone setting, or there may be an option to choose TZ (global or user's)

**Comment by Chartman123** [comment]
Please tell us which Forms version you're using... We did change quite a few things regarding the date/time question in the latest release and also made the decision to remove the timezone information for new submissions after some longer discussion.

**Comment by terion-name** [comment]
@Chartman123 2.5.1

**Comment by terion-name** [comment]
@Chartman123 I'll try 3.0 and write back

**Comment by Chartman123** [comment]
Ok so please be aware that with version 3 there will only be date and time questions for new forms but no more datetime questions.

For those two question types timezones don't really matter. 

So I'll close this issue as wontfix. :)

**Comment by terion-name** [comment]
@Chartman123 to clarify, the issue is not about date or datetime questions, it's just about forms entirely and form filling datetime in export csv

**Comment by Chartman123** [comment]
You mean the submission timestamp then?

**Comment by terion-name** [comment]
> You mean the submission timestamp then?

exactly

**Comment by Chartman123** [comment]
@jotoeri What do you think about this?

https://github.com/nextcloud/forms/blob/f33167c0daa53f7ef17800c872e72a5f9e7354a7/lib/Service/SubmissionService.php#L203

In the SubmissionService the user's timezone is already read. But I wonder where this should come from... I couldn't find any place where a user's timezone is stored. So is this line completely useless?

**Comment by Chartman123** [comment]
Once again I was too quick sending the comment... I found it in the preferences table (e.g. Europe/Berlin). And I found the solution, too. The parameters are passed in the wrong order.
