### ISSUE TITLE
Can't clone form

### ISSUE THREAD

**Issue by tzugen** [nextcloud/forms#1386]
Server error 500:
`
{"reqId":"q8reW59U8Jk4vyDsKnGW","level":3,"time":"2022-10-24T10:37:38+00:00","remoteAddr":"xxxxxxxxxxxxxx","user":"xxxxxxxxx","app":"no app in context","method":"POST","url":"/ocs/v2.php/apps/forms/api/v2/form/clone/4","message":"OCA\\Forms\\Db\\Question::setExtraSettings(): Argument #1 ($extraSettings) must be of type array, stdClass given, called in /var/www/html/lib/public/AppFramework/Db/Entity.php on line 55 in file '/var/www/html/custom_apps/forms/lib/Db/Question.php' line 72","userAgent":"xxxxxxxxxxxxxxxxxx","version":"25.0.0.18","exception":{"Exception":"Exception","Message":"OCA\\Forms\\Db\\Question::setExtraSettings(): Argument #1 ($extraSettings) must be of type array, stdClass given, called in /var/www/html/lib/public/AppFramework/Db/Entity.php on line 55 in file '/var/www/html/custom_apps/forms/lib/Db/Question.php' line 72","Code":0,"Trace":[{"file":"/var/www/html/lib/private/AppFramework/App.php","line":172,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Forms\\Controller\\ApiController"},"cloneForm"]},{"file":"/var/www/html/lib/private/Route/Router.php","line":298,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Forms\\Controller\\ApiController","cloneForm",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},["v2","4","ocs.forms.api.cloneForm"]]},{"file":"/var/www/html/ocs/v1.php","line":63,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/ocsapp/apps/forms/api/v2/form/clone/4"]},{"file":"/var/www/html/ocs/v2.php","line":23,"args":["/var/www/html/ocs/v1.php"],"function":"require_once"}],"File":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","Line":165,"Previous":{"Exception":"TypeError","Message":"OCA\\Forms\\Db\\Question::setExtraSettings(): Argument #1 ($extraSettings) must be of type array, stdClass given, called in /var/www/html/lib/public/AppFramework/Db/Entity.php on line 55","Code":0,"Trace":[{"file":"/var/www/html/lib/public/AppFramework/Db/Entity.php","line":55,"function":"setExtraSettings","class":"OCA\\Forms\\Db\\Question","type":"->","args":[{"__class__":"stdClass"}]},{"file":"/var/www/html/custom_apps/forms/lib/Controller/ApiController.php","line":323,"function":"fromParams","class":"OCP\\AppFramework\\Db\\Entity","type":"::","args":[[12,1,"multiple_unique",true,"I am answering this form as ..","And 2 more entries, set log level to debug to see all entries"]]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":225,"function":"cloneForm","class":"OCA\\Forms\\Controller\\ApiController","type":"->","args":[4]},{"file":"/var/www/html/lib/private/AppFramework/Http/Dispatcher.php","line":133,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Forms\\Controller\\ApiController"},"cloneForm"]},{"file":"/var/www/html/lib/private/AppFramework/App.php","line":172,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Forms\\Controller\\ApiController"},"cloneForm"]},{"file":"/var/www/html/lib/private/Route/Router.php","line":298,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Forms\\Controller\\ApiController","cloneForm",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},["v2","4","ocs.forms.api.cloneForm"]]},{"file":"/var/www/html/ocs/v1.php","line":63,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/ocsapp/apps/forms/api/v2/form/clone/4"]},{"file":"/var/www/html/ocs/v2.php","line":23,"args":["/var/www/html/ocs/v1.php"],"function":"require_once"}],"File":"/var/www/html/custom_apps/forms/lib/Db/Question.php","Line":72},"CustomMessage":"--"}}`

**Comment by tzugen** [comment]
No ideas what these ExtraSettings are. It's a basic, recently created form with just a couple of questions

**Comment by jotoeri** [comment]
@susnux or @Chartman123 could you have a look? Should probably be simply copying the extaSettings in the cloning API.

**Comment by susnux** [comment]
@jotoeri sure I will look into this shortly

**Comment by tzugen** [comment]
Thanks, that was prompt!
