### ISSUE TITLE
Favicon gets replaced

### ISSUE THREAD

**Issue by ssstain** [nextcloud/forms#1399]
**Nextcloud (please complete the following information):**
- Nextcloud-Version: 24.0.6
- Forms-Version: 2.5.1

**Is your feature request related to a problem? Please describe.**
When you substitute cloud's favicon with your app's favicon, it gets cached and cloud's global favicon never returns. 

**Describe the solution you'd like**
Don's substitute global favicon with the app's one.

**Comment by Chartman123** [comment]
@ssstain Please add a screenshot, I don't understand what you mean :)

**Comment by ssstain** [comment]
My self-hosted cloud has default Nextcloud favicon. Like this:
<img width="121" alt="Screenshot 2022-10-31 at 13 19 12" src="https://user-images.githubusercontent.com/15293404/198996537-13fe941e-7692-439d-9f6d-cc1b4801f9c4.png">

The favicon in the tab may get replaced by the forms icon. And this form's favicon persists no matter where you go within the cloud. Now I have cleared my Safari cache and cannot reproduce it anymore. Sorry. If this happens, I'll make a screenshot.

**Comment by Chartman123** [comment]
Ok, I think this might also be related to public sharing. At least I've seen the forms favicon there. But it never stayed that way for me... So probably only a caching problem. I'll close this issue for now. Please feel free to re-open it if this happens again. :)
