### ISSUE TITLE
"Date" question type with dropdown calendar

### ISSUE THREAD

**Issue by pricard32** [nextcloud/forms#14]
You should add a dropdown calendar.

**Comment by jancborchardt** [comment]
@pricard32 could you describe your use-case a bit more? This helps us design it properly. :)

**Comment by WNYmathGuy** [comment]
I made my first form today and it included a date field. I didn't know there wasn't an answer type of Date. I just made it a short answer, but a pop-out calendar date picker would be "clutch". 

What my first form was based on is my wife's disorganization of business expenses for real estate work. Date, Type (dropdown based on IRS classifications), Item, Amount. With the CSV output it's going to work fine, but you know how data people want clean inputs. The date and the amount are my concerns. 

#### Forms are about tightening the variance on inputs. 
A date widget call for a date field set to the current date is efficient _and_ accurate. 

A number type question would be ideal too and maybe on mobile dev's it calls the calculator type keypad for better input.

**Comment by skjnldsv** [comment]
So adding a input date picker?
That would be enough for you ?

**Comment by jancborchardt** [comment]
Yep, just like Google Forms, a "Date" question type would be good.

**Comment by skjnldsv** [comment]
I would say this goes with https://github.com/nextcloud/forms/issues/177
Just predefined input types :)

**Comment by jancborchardt** [comment]
That issue is about text validation of the single input line. This is about a specific `input type="date"`, just like Google Forms does. I’d say keep it separate cause it’s something else.

**Comment by skjnldsv** [comment]
Well, if the input is a type date/datetime/time we show the dropdown?

**Comment by jancborchardt** [comment]
Point is that the "Date" and "Time" elements are different elements from the "Short answer" field. It’s not about only validation, but about adding a specific element in the "Add question" part as well.

(Just making sure that we don’t have the situation where people have to first pick "Short question" and then there’s some validation stuff where you select "Date" cause that would be quite comples.

See Google Forms for guidance:
![](https://cdn.guidingtech.com/imager/assets/215605/Microsoft-Forms-vs-Google-Forms-Which-is-Better-for-Surveys-and-Polls-24_4d470f76dc99e18ad75087b1b8410ea9.png?1549268251)

**Comment by skjnldsv** [comment]
They are different entries, but google form is doing exactly what I said, this is just an input type date afterwards
`<input type="date" class="quantumWizTextinputPaperinputInput exportInput" jsname="YPqjbf" autocomplete="off" tabindex="0" value="" data-initial-value="">`

**Comment by skjnldsv** [comment]
I guess we are in an issue of coding vs UX :wink: 
Same component to use, so for me it's a duplicate, while you want dedicated entries in the new question menu, correct?

**Comment by skjnldsv** [comment]
The, seeing your comment in https://github.com/nextcloud/forms/issues/177#issuecomment-624342477
Closing ?

**Comment by ei8fdb** [comment]
I'd like to boost [the design Crowdsignal uses]( https://github.com/nextcloud/forms/issues/177#issuecomment-624607099) - they have a list of predefined form fields - email addresses, date, URL, etc.

**Comment by jancborchardt** [comment]
> I guess we are in an issue of coding vs UX wink
> Same component to use, so for me it's a duplicate, while you want dedicated entries in the new question menu, correct?

Enhancements should always be looked at from the user perspective, so I’d keep this open. :)

**Comment by jotoeri** [comment]
Done with #672 :)
