### ISSUE TITLE
Wish : share with Circles

### ISSUE THREAD

**Issue by livier** [nextcloud/forms#140]
Forms 1.0.3
Nextcloud, 16 and 17 (on 2 differents instances !)

### Steps to reproduce
1. create a form
2. trying to share with a circle

### Actual behaviour
Can't find circles in "Share with" form

### Expected behaviour
A form could be share in a circle

Same difficulty as "Polls" maybe it is a lib or api issu, not yours ... ?
Thaks for your work

**Comment by skjnldsv** [comment]
@daita how hard is it to implement circle sharing?

**Comment by jancborchardt** [comment]
Shouldn’t we simply use the proper sharing interface and mechanism of Nextcloud?

**Comment by skjnldsv** [comment]
@jancborchardt there is no such thing :p

**Comment by jancborchardt** [comment]
Well, what I mean is: It should work like in Files, the closest thing to what we can call "standardized". :)

**Comment by skjnldsv** [comment]
AH, yes, we have the autocompletion api if that is what you meant.
But according to my minimal knowledge, I think the sharing part needs to be implemented
