### ISSUE TITLE
Remove sign-up link in shared forms

### ISSUE THREAD

**Issue by ssstain** [nextcloud/forms#1400]
**Nextcloud (please complete the following information):**
- Nextcloud-Version: 24.0.6
- Forms-Version: 2.5.1

**Is your feature request related to a problem? Please describe.**
In publicly shared forms there is link at the bottom that confuses people as it misleads them to gain free account on Nextcloud on the global Nextcloud site, while self-hosted cloud is a closed one with no new registrations possible.

**Describe the solution you'd like**
Remove the call-to-action link.

**Comment by Chartman123** [comment]
This is not related to the Forms app, it's the public footer shown on all publicly shared links
