### ISSUE TITLE
Result Download fails "failure 997 CORS requires basic auth"

### ISSUE THREAD

**Issue by netdox** [nextcloud/forms#1430]
**Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!**

**Describe the bug**
Since the Update of forms to 3.0.2 Download of the result of a survey __
**To Reproduce**
1. create a form
2. get some response
3. change to Results
4. try download the result as CSV
5. got this Error message:

![issue](https://user-images.githubusercontent.com/52862324/209633295-70288600-2a7b-492d-891a-9a0c12285050.png)

**Expected behavior**
Download the CSV file

**temporary solution**
change back to forms 3.0.1 ( working without any problem )

**Nextcloud (please complete the following information):**
- Nextcloud-Version: 25.0.2
- Forms-Version: 3.0.2

**Desktop (please complete the following information):**
 - OS: [Linux Mint 21]
 - Browser [Chrome Version 108.0.5359.124 (Offizieller Build) (64-Bit)]

**Comment by Chartman123** [comment]
@netdox What do you use as user backend?

**Comment by Chartman123** [comment]
@jotoeri Is this related to these lines?

https://github.com/nextcloud/forms/blob/0eba3a0af439ba912263156beaca2ab9bbc2dc65/src/views/Results.vue#L78-L83

I think that the link from NcActionLink loses the context of the active user and therefore triggers the CORS problem. Am I right? However, I don't know how to fix this.

**Comment by netdox** [comment]
> @jotoeri Is this related to these lines?
> 
> https://github.com/nextcloud/forms/blob/0eba3a0af439ba912263156beaca2ab9bbc2dc65/src/views/Results.vue#L78-L83
> 
> I think that the link from NcActionLink directly addresses the API and loses the context of the active user and therefore triggers the CORS problem. Am I right? However, I don't know how to fix this.

Yes, I think you're right with this, because after the error you're also logged out and have to re login.
