### ISSUE TITLE
Navigation: Sort forms by recently edited / responses received

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/forms#1462]
**Nextcloud (please complete the following information):**
- Nextcloud-Version: 25.0.3
- Forms-Version: 3.0.3

**Is your feature request related to a problem? Please describe.**
Currently the forms in the navigation are sorted by creation date, which makes forms which have been created some time ago but are very active very difficult to navigate to.

**Describe the solution you'd like**
It would make most sense to sort the forms by most recent activity, be it editing or having received responses. Basically similar to Talk or Notes. Newly created forms should still show up at the very top then (fitting the logic).

**Additional context**
In this example, "Nextcloud Include applications" is by far the most active form, but it stays on the bottom because I created it first:
![image](https://user-images.githubusercontent.com/925062/214039631-9d2732d3-fb20-4882-b1c2-75abb230836a.png)

**Comment by Chartman123** [comment]
@jancborchardt Currently we don't store a last edit timestamp into the database... So I could think of the following solution: Adding a new timestamp column to the forms table that will be updated every time the form will be edited or gets a submission.

@jotoeri What do you think? Something worth implementing? Shouldn't be too hard...

**Comment by jotoeri** [comment]
Yeah, why not... UX-wise we should anyways somewhen show new submissions with the highlighted counter, no? So having the recentActivity storage in combination with a local storage last-seen could be a way to do that...
