### ISSUE TITLE
API: Can not get form in XML format

### ISSUE THREAD

**Issue by susnux** [nextcloud/forms#1469]
**Describe the bug**
Currently it is not possible to get a form, using the API, in the `xml` format, only JSON is possible.
The response a HTTP 200, with empty content and following error in the server log:
```json
{
  "reqId": "lDSN6tYXk1tWzlUNgifS",
  "level": 3,
  "time": "2023-01-29T14:59:32+00:00",
  "remoteAddr": "172.18.0.1",
  "user": "admin",
  "app": "PHP",
  "method": "GET",
  "url": "/ocs/v2.php/apps/forms/api/v2/form/1",
  "message": "TypeError: XMLWriter::writeElement(): Argument #2 ($content) must be of type ?string, stdClass given at /var/www/html/lib/private/AppFramework/OCS/BaseResponse.php#148",
  "userAgent": "curl/7.87.0",
  "version": "26.0.0.2",
  "data": {
    "app": "PHP"
  }
}
```

**To Reproduce**
1. `curl -v -u admin:admin -X GET 'http://localhost:8080/ocs/v2.php/apps/forms/api/v2/form/1' -H "OCS-APIRequest: true"`
2. See empty response

**Expected behavior**
OCS response with form in XML format.

**Nextcloud (please complete the following information):**
- Nextcloud-Version: 26 (current master)
- Forms-Version: current main

**Additional context**

**Comment by jotoeri** [comment]
Sounds more like a server bug, no? 🤔

**Comment by Chartman123** [comment]
Might be related to this server issue: https://github.com/nextcloud/server/issues/33330

**Comment by AlexM4H** [comment]
BTW: Same behaviour with 

curl -v -u admin:admin -X GET 'http://localhost:8080/ocs/v2.php/apps/forms/api/v2.1/submissions/{hash}' -H "OCS-APIRequest: true"

without the new feature https://github.com/nextcloud/server/pull/38745
