### ISSUE TITLE
datetime is submitted in the user agent's language

### ISSUE THREAD

**Issue by thymaro** [nextcloud/forms#1472]
I have read other open (and closed) issues about datetime and found none that mentions this issue.

**Describe the bug**
When sending a form to other people with a datetime field, the answer is submitted in the language of the people answering the questionaire instead of being translated to a common language (like the language of the creator, or English, I don't care much).

**To Reproduce**
1. Create a new form with a datetime question
2. Have answers coming in from user agents with different language settings.
3. Even though you didn't ask the people specifically, you'll know their browser's language setting.
4. Export to .csv
5. See error definitively when opening the .csv with the datetime texts in different languages.

**Expected behavior**
The submissions to the datetime question are all in a consistent format, in the same language (and, by the way, without the days of the week, if possible)

**Screenshots**
![grafik](https://user-images.githubusercontent.com/24420636/215587252-210d39d5-2b0e-4651-be03-86b4ac39e25b.png)

**Nextcloud (please complete the following information):**
- Nextcloud-Version: 24.0.4
- Forms-Version: 2.5.1

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser FF 
 - Version 109

**Comment by Chartman123** [comment]
Hi @thymaro

we decided to drop the datetime fields in newer versions of this app, so we won't put any more effort into fixing issues regarding this field type.

**Comment by thymaro** [comment]
That is a decision one can make. Does the automatic timestamp stay, though? I think we can close this issue regardless.

**Comment by Chartman123** [comment]
@thymaro If you're talking about the timestamp of the submission: yes :)

see #1001
