### ISSUE TITLE
NcRichContenteditable missing required property autoComplete

### ISSUE THREAD

**Issue by Chartman123** [nextcloud/forms#1474]
https://github.com/nextcloud/forms/blob/c7bbae2d3b3526deec11b0d861dde6775c333532/src/components/Questions/Question.vue#L78-L84

https://github.com/nextcloud/forms/blob/c7bbae2d3b3526deec11b0d861dde6775c333532/src/views/Create.vue#L59-L65

Apparently the Nextcloud-Vue component ~~changed in the latest release and now~~ requires a property autoComplete

https://nextcloud-vue-components.netlify.app/#/Components/NcRichContenteditable

**Comment by jotoeri** [comment]
Let's try giving it a default empty function on the lib? We wouldn't do anything else here on forms? 🤔

**Comment by Chartman123** [comment]
Yes, as we're using the component only for the descriptions we don't need the autocompletion. I wonder why we didn't see this warning while reviewing the PR, the respective code lines in the source component haven't been changed lately.

**Comment by jotoeri** [comment]
https://github.com/nextcloud/nextcloud-vue/pull/3757

**Comment by susnux** [comment]
PR was merged and `@nextcloud/vue` updated to `7.6.1`: https://github.com/nextcloud/forms/commit/f06a7bdee30e48b48fa68e3960b6436e27554e55
