### ISSUE TITLE
showExpiration is not a valid attribute

### ISSUE THREAD

**Issue by tranrn** [nextcloud/forms#1475]
**Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!**

**Describe the bug**
After updating Forms to 3.0.4 version app is not working

**To Reproduce**
1. Updated Forms to version  3.0.4. NC 25.0.3
2. Click on 'Forms' to open app
3. popup error An error occurred while loading the forms list

**Expected behavior**
Forms app should open and show me my Forms.

**Nextcloud (please complete the following information):**
- Nextcloud-Version: 25.0.3
- Forms-Version: 3.0.4.  

**Desktop (please complete the following information):**
 - OS: Fedora Linux
 - Browser Firefox
 - Version 108.0

**Browser log**
# Firefox
ERROR] forms: Error while loading owned forms list 
Object { app: "forms", uid: "username", level: 2, error: {…} }
​app: "forms"
​error: Object { message: "Request failed with status code 500", name: "AxiosError", code: "ERR_BAD_RESPONSE", … }
​​code: "ERR_BAD_RESPONSE"
​​config: Object { timeout: 0, xsrfCookieName: "XSRF-TOKEN", xsrfHeaderName: "X-XSRF-TOKEN", … }
​​message: "Request failed with status code 500"
​​name: "AxiosError"
​​request: XMLHttpRequest { readyState: 4, timeout: 0, withCredentials: false, … }
​​response: Object { data: "<?xml version=\"1.0\"?>\n<ocs>\n <meta>\n  <status>failure</status>\n  <statuscode>500</statuscode>\n  <message>Internal Server Error\n</message>\n </meta>\n <data/>\n</ocs>\n", status: 500, statusText: "Internal Server Error", … }
​​stack: ""
​​<prototype>: Object { constructor: a(e, t, n, r, a), toJSON: toJSON()
, stack: "", … }
​level: 2
​uid: "username"
​<prototype>: Object { … }
​​__defineGetter__: function __defineGetter__()
​​__defineSetter__: function __defineSetter__()
​​__lookupGetter__: function __lookupGetter__()
​​__lookupSetter__: function __lookupSetter__()
​​__proto__: 
​​constructor: function Object()
​​hasOwnProperty: function hasOwnProperty()
​​isPrototypeOf: function isPrototypeOf()
​​propertyIsEnumerable: function propertyIsEnumerable()
​​toLocaleString: function toLocaleString()
​​toString: function toString()
​​valueOf: function valueOf()
​​<get __proto__()>: function __proto__()
​​<set __proto__()>: function __proto__()

[ERROR] forms: Error while loading shared forms list 
Object { app: "forms", uid: "username", level: 2, error: {…} }

Nextcloud log:
LOG: "app":"no app in context","method":"GET","url":"/ocs/v2.php/apps/forms/api/v2/shared_forms","message":"showExpiration is not a valid attribute","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:108.0) Gecko/20100101 Firefox/108.0","version":"25.0.3.2","exception":{"Exception":"BadFunctionCallException","Message":"showExpiration is not a valid attribute","Code":0,"Trace":[{"file":"/var/www/html/nextcloud/lib/public/AppFramework/Db/Entity.php","line":165,"function":"setter","class":"OCP\\AppFramework\\Db\\Entity","type":"->"},{"file":"/var/www/html/nextcloud/lib/public/AppFramework/Db/Entity.php","line":73,"function":"__call","class":"OCP\\AppFramework\\Db\\Entity","type":"->"},{"file":"/var/www/html/nextcloud/lib/public/AppFramework/Db/QBMapper.php","line":322,"function":"fromRow","class":"OCP\\AppFramework\\Db\\Entity","type":"::"},{"file":"/var/www/html/nextcloud/lib/public/AppFramework/Db/QBMapper.php","line":340,"function":"mapRowToEntity","class":"OCP\\AppFramework\\Db\\QBMapper","type":"->"},{"file":"/var/www/html/nextcloud/apps/forms/lib/Db/FormMapper.php","line":105,"function":"findEntities","class":"OCP\\AppFramework\\Db\\QBMapper","type":"->"},{"file":"/var/www/html/nextcloud/apps/forms/lib/Controller/ApiController.php","line":173,"function":"findAll","class":"OCA\\Forms\\Db\\FormMapper","type":"->"},{"file":"/var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":225,"function":"getSharedForms","class":"OCA\\Forms\\Controller\\ApiController","type":"->"},{"file":"/var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":133,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/html/nextcloud/lib/private/AppFramework/App.php","line":172,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/html/nextcloud/lib/private/Route/Router.php","line":298,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/html/nextcloud/ocs/v1.php","line":63,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/html/nextcloud/ocs/v2.php","line":23,"args":["/var/www/html/nextcloud/ocs/v1.php"],"function":"require_once"}],"File":"/var/www/html/nextcloud/lib/public/AppFramework/Db/Entity.php","Line":136,"CustomMessage":"--"}}

**Comment by Chartman123** [comment]
Hi @tranrn 

it looks like your instance didn't run some a database migration script and that the corresponding column doesn't exist. Could you please tell us, which DB you're using?

**Comment by tranrn** [comment]
I have two instances of NC with different DB types:
  'dbtype' => 'mysql',
  'version' => '25.0.3.2',
and  
 'dbtype' => 'pgsql',
  'version' => '25.0.3.2',
Both has the same error.

**Comment by Chartman123** [comment]
Strange, I'm running mysql and pgsql on my production instances. Couldn't reproduce it there...

@jotoeri any clues why this might happen?

**Comment by Chartman123** [comment]
@tranrn could you please do the following to see more about the executed migrations on your system?

1. Set your NC instance to debug mode: `./occ config:system:set debug --value=true --type=boolean`
2. Run `./occ migrations:status forms`
3. Post the output here

You can then disable the debug mode again.

**Comment by tranrn** [comment]
occ migrations:status forms
    >> App:                                                forms
    >> Version Table Name:                                 oc_migrations
    >> Migrations Namespace:                               OCA\Forms\Migration
    >> Migrations Directory:                               /var/www/html/nextcloud/apps/forms/lib/Migration
    >> Previous Version:                                   030100Date20221231100426
    >> Current Version:                                    030100Date20230115214242
    >> Next Version:                                       Already at latest migration step
    >> Latest Version:                                     030100Date20230115214242
    >> Executed Migrations:                                19
    >> Executed Unavailable Migrations:                    19
    >> Available Migrations:                               19
    >> New Migrations:                                     19
    >> Pending Migrations:                                 None

**Comment by jotoeri** [comment]
Hm, i just tested it with a NC25.0.2 and with NC25.0.3 to update from v3.0.3, both worked. However, only with mariadb currently.
@tranrn Just to be sure - I assume you updated from v3.0.3, no?

The migration summary looks good so far. Any errors from the migrations themselves @tranrn ?

**Comment by jotoeri** [comment]
@lookup82 since you reacted with the thumb - i assume you ran into the same issue? Which setup do you have? Any different information than by tranrn here?

**Comment by tranrn** [comment]
> Just to be sure - I assume you updated from v3.0.3, no?

Yep, 3.0.3 -> 3.0.4

No other messages in Logging, just


Error | no app in context | BadFunctionCallException: showExpiration is not a valid attribute |  
-- | -- | -- | --


2023-02-01T12:45:02+0300

**Comment by tranrn** [comment]
Should I try to reinstall Forms app?

**Comment by lookup82** [comment]
Yes, I have the same situation as @tranrn.
My instance is Nextcloud 25.0.3 with mysql-mariadb 10.8.6.
I tried:
* disable and re-enable the app
* remove and reinstall the app
* look for something in the server log
At the moment I can't find any more information.

**Comment by jotoeri** [comment]
That's strange... 🤔 Which php version are you both running? Did you reboot your server to try clearing any php-cache or so?

**Comment by lookup82** [comment]
> Edit: Ok - I could at least reproduce the error now by removing some code:
> Does the file /forms/lib/Db/Form.php for you contain the 5 lines regarding `showExpiration`? You can compare to https://github.com/nextcloud/forms/blob/main/lib/Db/Form.php

My file is identical to this.

Then I fix restarting php!!!

In my case:
systemctl restart php8.1-fpm.service

Thank you!

**Comment by jotoeri** [comment]
- Maybe check your opcache setup on the server again. 😉 
https://docs.nextcloud.com/server/latest/admin_manual/installation/server_tuning.html#enable-php-opcache

**Comment by tranrn** [comment]
PHP 8.1.14
same, restarting php-fpm helped

**Comment by Niclas-sol** [comment]
Please add a note for restarting php-fpm in the app store / install page. Upgraded yesterday to the latest version of forms and had an internal server error for everyone who tried to open the link to the form. NC 25.0.2, PHP 8.0, MariaDB 10.6.11

**Comment by jotoeri** [comment]
@Niclas-sol Generally i'd say its more an issue of the server configuration, than of our side. The files are replaced correctly, but your server cache seems to use the old version. Do you have the opcache properly configured, as linked above?
@nickvergessen Do you have any idea, what else could cause such an issue, that is maybe to check on our side?

**Comment by Niclas-sol** [comment]
@jotoeri yes, opcache is exactly configured as shown in the manual.
