### ISSUE TITLE
Notfications (push or e-mail) don't work

### ISSUE THREAD

**Issue by stefan-franz** [nextcloud/forms#1483]
Hello, i checked on that i should get an e-mail if a new form is filled out. 
But neither an e-mail nor a push message is received. 
I use the current forms app and the nextcloud 25.0.2
What do i have to do?

**Comment by stefan-franz** [comment]
I found out that push works. My fault was, i was logged in as i filled out. After logging out the push alert comes. 
Unfortunately no e-mail comes. May a spam filter is a problem of my mail server. 
Has anyone a copy of the mail which is sending? So i can send a message to my mail server provider.

**Comment by stefan-franz** [comment]
Sorry. Now it works. Its only a bit time delay of some minutes. All works fine. 
The user has to be logged out for testing.

**Comment by Chartman123** [comment]
Closing as it is obsolete now...
