### ISSUE TITLE
Some wishes for your next versions.

### ISSUE THREAD

**Issue by stefan-franz** [nextcloud/forms#1487]
First, thanks for you App. For me a further way to come away from the Big Tech.....

Let me write some ideas / wishes of the current Forms version. 

Between the questions are in my opinion very large gaps. I would find it a little more compact beautiful. 
https://nco.stefan-franz.de/index.php/apps/forms/s/bdG295Aoyr9ePsWyKrdPSPWk

For longer forms (many questions) a text, heading or sections function would be useful for clarity. So that one could insert between the questions if necessary a heading (maybe with 2nd line explanation). 

The footer of the Nextcloud is always displayed. This disturbs just on the smartphone something. Like here e.g. 

For the organization of many forms, a sorting option in folders would be great. 

The export and import of forms has already been mentioned - I would also very much welcome because I have a complete distribution stream, where you could then make the forms available to each other.

**Comment by susnux** [comment]
Thank you for your feedback!


> Between the questions are in my opinion very large gaps.

This is already tracked by #1234 

> For longer forms (many questions) a text, heading or sections function would be useful for clarity.

This is also already on the list: #624 

> The footer of the Nextcloud is always displayed.

This has to be well-wrought, there are good reasons you might want to keep the footer: e.g. if you are within the European Union: GDPR and e.g. for your imprint (necessary in some countries).

> For the organization of many forms, a sorting option in folders would be great.

Already tracked by #853

**Comment by Chartman123** [comment]
As @susnux already pointed out, your points are either duplicates of existing issues or an issue not directly related to forms. So I'll close this issue here :)
