### ISSUE TITLE
Should not call it a survey, it's a form

### ISSUE THREAD

**Issue by pricard32** [nextcloud/forms#15]
V1.0.3
NextCloud 16

I don't want to see the result like a survey.
When someone submit their form, the result should be sent to the admin or group of this form.

I think you should see it more like a request form.

**Comment by jancborchardt** [comment]
@pricard32 both cases can be accomodated. There could be an option if you want to be notified after every submission, which makes it usable as a contact form too.

But the aggregated results are useful too for the use-cases that people use Google Forms, Surveymonkey and Typeform.

**Comment by jancborchardt** [comment]
And actually this issue exists already: **Notification on form submission #12** :) So we can close this as duplicate.

**Comment by luixxiul** [comment]
Closing based on https://github.com/nextcloud/forms/issues/15#issuecomment-500827097
