### ISSUE TITLE
Pasting Text Into Description Sometimes Deletes All Existing Text Without Any Way to Undo This

### ISSUE THREAD

**Issue by gohrner** [nextcloud/forms#1536]
**Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!**

**Describe the bug**
In Forms 3.1.0 you can easily lose text you entered into a description field.

Anytime you paste test into an existing text row, all other rows will be irrevocably deleted. Please see attached screencast.

![Peek 2023-02-28 10-31](https://user-images.githubusercontent.com/26199042/221811641-bec02b11-c207-41d6-aaf5-2ceecd0090fd.gif)

Obviously, this can lose data / information from the description and may be especially annoying if it's not noticed right away.

**To Reproduce**
1. See screencast.

**Expected behavior**
The pasted text is added to the row the cursor is in, but all other text rows stay unaffected.

**Screenshots**
See above.

**Nextcloud (please complete the following information):**
- Nextcloud-Version: 25.0.4
- Forms-Version: 3.1.0

**Desktop (please complete the following information):**
 - OS: KDE neon (Ubuntu 22.04)
 - Browser Chromium
 - Version 110.0.5481.100 (Offizieller Build) Built on Ubuntu , running on neon 22.04 (64-Bit)

**Comment by susnux** [comment]
Fixed as soon as we update `@nextcloud/vue` to version 7.7.2

**Comment by gohrner** [comment]
> Fixed as soon as we update `@nextcloud/vue` to version 7.7.2

Thanks - what does that mean / when will this probably happen? Is it coupled to a Nextcloud maintenance or major update, or can it be resolved with a Forms update?

**Comment by susnux** [comment]
This will be resolved with the next forms update (probably 3.1.1)
