### ISSUE TITLE
Paragraphs in Descriptions Fields Are Not Possible

### ISSUE THREAD

**Issue by gohrner** [nextcloud/forms#1537]
**Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!**

**Describe the bug**
It seems to be impossible to add paragraph breaks into description fields.

**To Reproduce**
1. Write some text in a description field with empty rows which should add paragraph breaks according to Markdown syntax.
2. Leave the edit field so it's rendered.
3. All text will be stuck together as a bit block of text without any paragraph breaks.

**Expected behavior**
I can insert paragraph breaks into descriptions to structure the description text a bit and improve readability.

**Screenshots**

_Markup:_
----
![image](https://user-images.githubusercontent.com/26199042/221814276-561938ef-accd-4614-b41b-b93a4909a387.png)
----

_Result:_
----
![image](https://user-images.githubusercontent.com/26199042/221814390-e436935f-0440-4236-9b27-d30ebb2e33c4.png)
----

**Nextcloud (please complete the following information):**
- Nextcloud-Version: 25.0.4
- Forms-Version: 3.1.0

**Desktop (please complete the following information):**
 - OS: KDE neon (Ubuntu 22.04)
 - Browser Chromium
 - Version 110.0.5481.100 (Offizieller Build) Built on Ubuntu , running on neon 22.04 (64-Bit)

**Comment by susnux** [comment]
Happens because of the `breaks` option of markdown-it. I will look into this soon.
