### ISSUE TITLE
Markdown: Pasting code "loses" pasted content

### ISSUE THREAD

**Issue by gohrner** [nextcloud/forms#1562]
**Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!**

**Describe the bug**
Pasting the following code block into a description field in Forms simply "loses" the Generic Type in angle brackets:

    ```java
    Test<Object> myMethod() {
        if (1 == 2) {
            // code
        }
    }
    ```

**To Reproduce**
1. Paste the code block above into an empty description field.
2. The method's return type will be the raw type `Test` instead of `Test<Object>`.

**Expected behavior**
The code block should be pasted as-is.

**Screenshots**
Screencast of the issue:

![Peek 2023-03-16 21-54](https://user-images.githubusercontent.com/26199042/225750499-b26a276a-47d1-4d33-bbf2-7fc6e279eb26.gif)

**Nextcloud (please complete the following information):**
- Nextcloud-Version: 25.0.4
- Forms-Version: 3.2.0

**Desktop (please complete the following information):**
 - OS: KDE neon (Ubuntu 22.04)
 - Browser: Chromium
 - Version 111.0.5563.64 (Offizieller Build) Built on Ubuntu , running on neon 22.04 (64-Bit)

**Comment by susnux** [comment]
Upstream issue: nextcloud/nextcloud-vue#3908
