### ISSUE TITLE
Markdown: First Line Of "Triple Backtick" Code Blocks is Sometimes "Absorbed" Into Triple-Backtick-Line

### ISSUE THREAD

**Issue by gohrner** [nextcloud/forms#1563]
**Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!**

**Describe the bug**
First Line Of "Triple Backtick" Code Blocks is Sometimes "Absorbed" Into Triple-Backtick-Line.

See screencast.

**To Reproduce**
1. Enter a (in this example one-line) Markdown code block into a description field
2. Leave edit mode.
3. The description field will be empty.
4. Re-entering edit mode will show why: the code block content was merged into the first "backtick line".

**Expected behavior**
The first line in the actual code block should NOT be merged into the backtick line.

**Screenshots**
![Peek 2023-03-16 22-12](https://user-images.githubusercontent.com/26199042/225753959-9ad9333a-9799-4e92-af07-2bdfd70d6846.gif)

**Nextcloud (please complete the following information):**
- Nextcloud-Version: 25.0.4
- Forms-Version: 3.2.0

**Desktop (please complete the following information):**
 - OS: KDE neon (Ubuntu 22.04)
 - Browser: Chromium
 - Version 111.0.5563.64 (Offizieller Build) Built on Ubuntu , running on neon 22.04 (64-Bit)

**Comment by susnux** [comment]
I can only reproduce this with Chrome. Using Firefox everything works as expected.

I think this is another issue with NcRichContenteditable.

**Comment by susnux** [comment]
BTW this an instance of nextcloud/nextcloud-vue#3836
