### ISSUE TITLE
Markdown: Special HTML Characters Are Converted Into Their HTML Entity Codes Within Codeblocks

### ISSUE THREAD

**Issue by gohrner** [nextcloud/forms#1564]
**Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!**

**Describe the bug**
Special HTML Characters Are Converted Into Their HTML Entity Codes Within Codeblocks.
This renders code like e.g. Java - or worse, XML or similar - unreadable.

See attached screencast.

**To Reproduce**
1. Enter a code block into a description field, and add e.g. angle brackets into it.
2. Leave the edited field.
3. HTML entity codes will be rendered instead of the angle brackets.

**Expected behavior**
Angle brackets should be entered, just as entered into the text field.

**Screenshots**
![Peek 2023-03-16 22-05](https://user-images.githubusercontent.com/26199042/225752554-29b61947-3678-4952-98c1-66cc4d28c289.gif)

**Nextcloud (please complete the following information):**
- Nextcloud-Version: 25.0.4
- Forms-Version: 3.2.0

**Desktop (please complete the following information):**
 - OS: KDE neon (Ubuntu 22.04)
 - Browser: Chromium
 - Version 111.0.5563.64 (Offizieller Build) Built on Ubuntu , running on neon 22.04 (64-Bit)

**Comment by susnux** [comment]
This is an upstream bug: https://github.com/nextcloud/nextcloud-vue/issues/3264

As this and #1562 both are caused by the NcRichContenteditable component, I vote for replacing it with a simple textarea input.
