### ISSUE TITLE
Usability: Selecting Text in Description Fields is Difficult - Leaving The Area With The Mouse Leaves Edit Mode And Destroys Selection

### ISSUE THREAD

**Issue by gohrner** [nextcloud/forms#1565]
**Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!**

**Describe the bug**
If you try to select a larger part of a description field's contents, you'll often slightly leave the area with the mouse during the selection drag.

I do not know any text editor or edit field where this is a problem, except Forms - see screencast.

Leaving the actual text are during the selection drag operation will terminate edit mode, completely losing the selection. This converts any larger selection attempt into a precision surgery...

**To Reproduce**
1. Switch a description field with a few lines of content into edit mode.
2. Try to select a larger part of the text including e.g. the beginning of the first line, without being "too" careful.
3. Edit mode will be left and the selection will be lost. See screencast.
   (Note that I did NOT actually click outside of the text area. I just released to mouse button to stop the drag operation. Maybe some mouse event listener responsible to quit edit mode is not properly filtered to check for actual "click" events instead of any mouse button event?)

**Expected behavior**
Edit mode should stay enabled, and the text should be selected, ready to be copied.

**Screenshots**
![Peek 2023-03-16 22-14](https://user-images.githubusercontent.com/26199042/225754869-e2067707-e2d5-402d-b4d6-6eb516fd1715.gif)

**Nextcloud (please complete the following information):**
- Nextcloud-Version: 25.0.4
- Forms-Version: 3.2.0

**Desktop (please complete the following information):**
 - OS: KDE neon (Ubuntu 22.04)
 - Browser: Chromium
 - Version 111.0.5563.64 (Offizieller Build) Built on Ubuntu , running on neon 22.04 (64-Bit)

**Comment by susnux** [comment]
Thank you for your report.
I can reproduce this with Chrome, with Firefox it works as expected.

**Comment by Chartman123** [comment]
Just as an addition: On Firefox this happens the other way round, so you can't select the text while the field is not in edit mode

**Comment by mschmidm** [comment]
I am not a Vue developer, but after having a look at the code I think I found a possible fix.

On the header-element which includes the description input, a [v-click-outside](https://vuetifyjs.com/en/api/v-click-outside/) directive of vuetifyjs is applied.

The directive passes a MouseEvent to the handler, which maybe could be used to check, whether it was a real click or just a mouseUp-Event. If I am correct, this should be an easy fix :)

**Comment by mschmidm** [comment]
I just tested checking the event passed by the v-click-outside directive but in both cases (real click & ending selecting outside of the area) the event.type is "click".
Vuetify has a similar issue ([vuetifyjs/vuetify#6969](https://github.com/vuetifyjs/vuetify/issues/6969)) that seems to have a workaround, but I am not sure if it could be applied here.
