### ISSUE TITLE
Is translation planned?

### ISSUE THREAD

**Issue by Himra** [nextcloud/forms#157]
Forms 1.0.3
Nextcloud 17

Is a translation into other languages planned ? 
My main interest is the frontend.

Thanks for your efforts.

**Comment by skjnldsv** [comment]
Hello :)
Any nextcloud app is translatable on transifex: https://www.transifex.com/nextcloud/nextcloud/translate/#forms

**Comment by luixxiul** [comment]
As a note it's been addressed here: https://github.com/nextcloud/forms/issues/2#issuecomment-507853946
