### ISSUE TITLE
Unable to mark as read Forms app notify

### ISSUE THREAD

**Issue by danjde** [nextcloud/forms#1580]
Hi Devs,
I’m using Linux Ubuntu 20.04, where I’ve installed NC client 3.1.1.
All is working fine, except for [Forms](https://apps.nextcloud.com/apps/forms) notify.

In fact, some weeks ago I built a simple form, where I asked information of various kinds to the users.
Now the form is closed, but I still receive the response notifications and seems impossible to mark them as read to stop notify alert.

Where I’m wrong?

Many thanks!

Davide

**Comment by Chartman123** [comment]
Hi @danjde 

Can you reproduce this with the current version of Forms?

**Comment by Chartman123** [comment]
Closing as stale after two weeks and no response. Feel free to re-open if the problem still exists in latest version.
