### ISSUE TITLE
No favicon when sharing link

### ISSUE THREAD

**Issue by notaprodev** [nextcloud/forms#1587]
**Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!**

**Describe the bug**
When sharing a link from Nextcloud forms no favicon is used when the link is pasted. 

**To Reproduce**
1. Go to 'Forms'
2. Click on 'click create a new form or an existing one'
3. Share this form
4. Paste it on any platform no favicon will be pulled only the pasted url. 

**Expected behavior**
Show a favicon of Nextcloud when the link has been pasted.
**Screenshots**

**Nextcloud (please complete the following information):**
- Nextcloud-Version: 25.0.1
- Forms-Version: 3.2.0

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser Firefox, chrome
 - Version 111

**Smartphone (please complete the following information):**

**Browser log**
```
Open your console, reload your page and/or do the action leading to this issue and copy/paste the log in this thread.
```

<details>
<summary>How to access your browser console (Click to expand)</summary>

# Chrome
- Press either CTRL + SHIFT + J to open the “console” tab of the Developer Tools.
- Alternative method:
    1. Press either CTRL + SHIFT + I or F12 to open the Developer Tools.
    2. Click the “console” tab.

# Safari
- Press CMD + ALT + I to open the Web Inspector.
- See Chrome’s step 2. (Chrome and Safari have pretty much identical dev tools.)

# IE9
1. Press F12 to open the developer tools.
2. Click the “console” tab.

# Firefox
- Press CTRL + SHIFT + K to open the Web console (COMMAND + SHIFT + K on Macs).
- or, if Firebug is installed (recommended):
    1. Press F12 to open Firebug.
    2. Click on the “console” tab.

# Opera
1. Press CTRL + SHIFT + I to open Dragonfly.
2. Click on the “console” tab.
</details>

**Additional context**

**Comment by Chartman123** [comment]
@notaprodev Could you please try again with the latest version? I just tried it and couldn't reproduce it.

Steps I tried:
- Copy public link
- Add it to bookmark bar in Firefox
- see Favicon

**Comment by Chartman123** [comment]
Closing as stale after two weeks and no response. Feel free to re-open if the problem still exists in latest version.
