### ISSUE TITLE
Option to increase default font sizes

### ISSUE THREAD

**Issue by andreasmjg** [nextcloud/forms#1598]
**Nextcloud (please complete the following information):**
- Nextcloud-Version: 25.0.1
- Forms-Version: 3.2.0

**Is your feature request related to a problem? Please describe.**
Form fonts and question descriptions are very small and I can't find a way to modify the font size. Is there a way to make these bigger by default? 

On my laptop screen the font is very small and hard to read even for me with great eye sight. 

**Describe the solution you'd like**
A drop-down list in the administrative config settings to set the default font size. 

**Describe alternatives you've considered**
I know users can click "CTRL +" to make it bigger, but it would be nice to give a better UX up front.

**Comment by Chartman123** [comment]
@andreasmjg Could you please add a screenshot where we can see what you mean exactly? However, I doubt that we will add a configuration here.

**Comment by Chartman123** [comment]
Closed due to missing feedback
