### ISSUE TITLE
Option to suppress Nextcloud banner

### ISSUE THREAD

**Issue by andreasmjg** [nextcloud/forms#1599]
**Nextcloud (please complete the following information):**
- Nextcloud-Version: 25.0.1
- Forms-Version: 3.2.0

**Is your feature request related to a problem? Please describe.**
The next cloud banner at the bottom takes up previous screen real estate, particularly on mobile. It would be nice to be able to disable it. 

**Describe the solution you'd like**
An option toggle in the administrative config settings to suppress the bottom banner. 

**Describe alternatives you've considered**
Make it smaller, e.g. one-line only and smaller font?

**Additional context**

The banner states: 

Nextcloud – a safe home for all your data
[Get your own free account](https://nextcloud.com/signup/)

**Comment by Chartman123** [comment]
@andreasmjg This is not Forms related. Please see for example this config parameter:

https://github.com/nextcloud/server/blob/2bd08c8198599a8999bb57d9aafc91b32d48e0f6/config/config.sample.php#LL2214C1-L2220C34
