### ISSUE TITLE
Add option to change default font colours

### ISSUE THREAD

**Issue by andreasmjg** [nextcloud/forms#1600]
**Nextcloud (please complete the following information):**
- Nextcloud-Version: 25.0.1
- Forms-Version: 3.2.0

**Is your feature request related to a problem? Please describe.**

Form text and background color is too similar on laptop, which may make the font hard to read for people.

**Describe the solution you'd like**

A drop-down list in the administrative config settings to change form font color and background color.

**Describe alternatives you've considered**

* Make all color choices more high-contrast by default.

* Create a single option called "high contrast" which would follow some sensible guide such as https://webaim.org/articles/contrast/

**Additional context**

On Android, the background is white and font black, making contrast much better.

**Comment by Chartman123** [comment]
@andreasmjg Could you please post a screenshot of where you show us the colors that are too similar in your oppinion?

**Comment by Chartman123** [comment]
Closed due to missing feedback
