### ISSUE TITLE
Form share with QR codes

### ISSUE THREAD

**Issue by nicovd737** [nextcloud/forms#1606]
Hello,

A recent update of polls introduced QR codes option to share the polls with QR code instead of long URLs.

Is it planned to do the same with form ?

Would be very appreciated by lot of our users.

Many thanks
Nico

**Comment by Chartman123** [comment]
Hi @nicovd737,

currently it's not planned. As a workaround you could of course just take the share URL and put it into any QR code generator.

**Comment by nicovd737** [comment]
Thanks.

But i have lot of Requests so it will be Welcome to have it 🙂

Le lun. 24 avr. 2023, 09:48, Chartman123 ***@***.***> a
écrit :
