### ISSUE TITLE
Share Forms with others persons

### ISSUE THREAD

**Issue by bundyboss** [nextcloud/forms#1607]
- Nextcloud-Version: 24.0.11
- Forms-Version: 2.5.2

Thanks for this app. I've created some forms and I want to share some of them to my collegue.
I hope they could modifiy the form, have an access to the results, etc..
It's possibe to do that ?

**Comment by bundyboss** [comment]
Seems to be the same of this request : https://github.com/nextcloud/forms/issues/322

**Comment by Chartman123** [comment]
Yes, you're right. I'll close this as a duplicate :)
