### ISSUE TITLE
Change order of forms in the sidebar

### ISSUE THREAD

**Issue by sascha08-15** [nextcloud/forms#1610]
**Nextcloud (please complete the following information):**
- Nextcloud-Version: Latest stable
- Forms-Version: Latest stable

**Describe the solution you'd like**
- I would like to change the order of the forms in the left sidebar.
- With time I will create more and more forms and I need to organize them. First thing that comes to my mind is ordering them.
- I want to be able to give a new order by dragging and dropping the forms on the left sidebar

**Describe alternatives you've considered**
- Next to ordering them in a customized way (per user?) is a folder-like hierarchical structure
- Another alternative would be to tag the forms and "auto-arrange" them by tags in a folder-like structure on the left sidebar

**Comment by Chartman123** [comment]
This is currently not planned. We just changed the behavior of the list to always show the form with the latest changes/submissions on top.
