### ISSUE TITLE
Forms not accessible via external link

### ISSUE THREAD

**Issue by sushifrick** [nextcloud/forms#1616]
**Describe the bug**
After setting the option "Permit access to all logged in accounts" to a form, the internal Link should work for other users than the creator I guess. When I try to open the internal link with a test user, I cannot access the form, instead the (empty) list of forms for this user will be shown. When I also set "Show to all accounts on sidebar", the internal link works as expected, but this is not always the desired state.

**To Reproduce**
1. Create a form
2. Activate "Permit access to all logged in accounts"
3. Open the internal link as nother logged in user
4. See the list of formst instead of the wanted form

**Expected behavior**
The form with the option "Permit access to all logged in accounts" should be accessible by other logged in users via the internal link.

**Screenshots**
https://github.com/nextcloud/forms/assets/1727991/e6c37689-79c7-4fdb-815e-3eebeceffd3e

**Nextcloud (please complete the following information):**
- Nextcloud-Version: 25.0.6 Enterprise
- Forms-Version: 3.2.0

**Desktop (please complete the following information):**
 - OS: Archlinux
 - Browser: Firefox
 - Version: 112.0.2 (64-Bit)

**Browser log**
```
Nothing interesting here...
```

**Additional context**
-

**Comment by Chartman123** [comment]
@sushifrick @maxemann96

Could you please try again with the latest version 3.3.0 of Forms? I just tried to reproduce this behaviour and could open the link just fine.

**Comment by Chartman123** [comment]
Closing as stale after two weeks and no response. Feel free to re-open if the problem still exists in latest version.

**Comment by sushifrick** [comment]
Works for me now as well, thank you!

**Comment by pReya** [comment]
Same problem here. Gonna open another issue since this has been closed.
