### ISSUE TITLE
Pre-release for Nextcloud 27

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/forms#1624]
**Nextcloud (please complete the following information):**
- Nextcloud-Version: 27
- Forms-Version: ?
- 
**Is your feature request related to a problem? Please describe.**

We would like to run the Forms app in pre-production with Nextcloud server RC1 on May 17th. This app currently has no compatible release on the app store.

**Describe the solution you'd like**

Tag a pre-release (beta, rc) for 27 and put in onto the app store. The final release is only due mid of June.

**Describe alternatives you've considered**

N/a

**Additional context**

https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule

---

cc @jotoeri

**Comment by AndyScherzinger** [comment]
cc @susnux

**Comment by jotoeri** [comment]
👍 We're on it.

**Comment by AndyScherzinger** [comment]
Thanks a lot @jotoeri - highly appreciate this 💙

**Comment by Chartman123** [comment]
Done with e0058cc
