### ISSUE TITLE
Forms does not use brand/theming name in text about Nextcloud account

### ISSUE THREAD

**Issue by april83c** [nextcloud/forms#1631]
**Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!**

**Describe the bug**
When filling out a form, the text "Responses are connected to your Nextcloud account." will always say Nextcloud and not the brand name in the settings.

**To Reproduce**
1. Set brand name in Nextcloud settings (specifically `/settings/admin/theming`) to something other than Nextcloud 
2. Create a form
3. Make sure that responses are **not** anonymous
4. Look at the preview, or go to fill out the form while signed in. The text is below the form description.

**Expected behavior**
"Nextcloud" in this text should be replaced with the brand name.

**Screenshots**
![image](https://github.com/nextcloud/forms/assets/124521665/f038248a-6b1f-42a2-b9df-3530eb886894)
![image](https://github.com/nextcloud/forms/assets/124521665/21ec1810-c0eb-43a9-b084-848a500766d5)

**Nextcloud (please complete the following information):**
- Nextcloud-Version: 26.0.1
- Forms-Version: 3.3.0

**Desktop (please complete the following information):**
 - OS: Nobara Linux 
 - Browser: Firefox 112

**Comment by Chartman123** [comment]
Hi @april83c 

this is by design and not a bug. So I switched the labels to enhancement. I'm not quite sure if we should apply the branding name here. Perhaps @jancborchardt or @nimishavijay could quickly join in and assess this from a design pov? I could also imagine to just drop the "Nextcloud" here and just say "not connected to your account".

**Comment by april83c** [comment]
> Hi @april83c
> 
> this is by design and not a bug. So I switched the labels to enhancement. I'm not quite sure if we should apply the branding name here. Perhaps @jancborchardt or @nimishavijay could quickly join in and assess this from a design pov? I could also imagine to just drop the "Nextcloud" here and just say "not connected to your account".

I don't see why it would be by design to specifically say the name of the software and not the name of the specific instance you're on... unless you can, like, log into a form from another server with a Nextcloud account from a *different* server? Although I didn't see an option like that anywhere...

In fact this is a place where I'd rather expect it to say the specific brand name, and *not* the software, since it's specifically accounts on that Nextcloud instance

**Comment by april83c** [comment]
> A bug would be that the software doesn't work the way it was meant by the devs... In this case it perfectly does what's in the code. So as I pointed out earlier, this is more an enhancement/feature request...

I didn't mean to imply I disagree with this being marked enhancement, I was just explaining why I think it should be changed/why I think the intended behavior *should be* to show the brand name

**Comment by susnux** [comment]
> I could also imagine to just drop the "Nextcloud" here and just say "connected to your account".

I like this idea.

**Comment by nimishavijay** [comment]
Just using "account" sounds good to me as well :)
