### ISSUE TITLE
Cant share forms link

### ISSUE THREAD

**Issue by Mqwx27** [nextcloud/forms#1651]
Hello,

I can't share forms with external links. Has anyone had this problem [before?]

![image](https://github.com/nextcloud/forms/assets/137516834/a52d02c0-6544-472f-9263-9c10d6087c3e)

Thanks in advance for your help.

**Comment by Chartman123** [comment]
Hi @Mqwx27 

unfortunately your post is missing the required support information and so we can only guess what's wrong. Please tell us more about your installation (NC version, Forms version and so on).

**Comment by susnux** [comment]
What browser do you use? Because this error should only pop up if you somehow access that button without the browsers clipboard permission. Which is automatically granted by any browser, with an exception for Firefox which has this rule:

> [Transient user activation](https://developer.mozilla.org/en-US/docs/Web/Security/User_activation) is required. The user has to interact with the page or a UI element in order for this feature to work.
> The "clipboard-write" permission of the [Permissions API](https://developer.mozilla.org/en-US/docs/Web/API/Permissions_API) is granted automatically to pages when they are in the active tab.

So for any normal usage that permission is granted and it should work.

**Comment by Mqwx27** [comment]
> Hi @Mqwx27
> 
> unfortunately your post is missing the required support information and so we can only guess what's wrong. Please tell us more about your installation (NC version, Forms version and so on). Also add relevant information from your browser console log.

Hi, im on NC version 27.0.0 and forms version 3.3.0. Im note sure what else you could need ? 
Thank you.

I have this in the console log, idk if this is relevant.

![image](https://github.com/nextcloud/forms/assets/137516834/c33440cf-d698-435f-a706-70bfc705b952)

**Comment by Chartman123** [comment]
@Mqwx27 I can reproduce the error on my local dev instance, but not on my productive instance. How do you access your installation? Is it HTTPS or only HTTP? My dev instance runs on HTTP which might explain the blocked access to the clipboard.

**Comment by Mqwx27** [comment]
> @Mqwx27 I can reproduce the error on my local dev instance, but not on my productive instance. How do you access your installation? Is it HTTPS or only HTTP? My dev instance runs on HTTP which might explain the blocked access to the clipboard.
> 
> https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Interact_with_the_clipboard#using_the_clipboard_api
> 
> > As the API is only available to [Secure Contexts](https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts), it cannot be used from a content script running on http:-pages, only https:-pages.

Indeed, I was just testing Nextcloud form and the site must be in HTTPS to use the links. Thanks a lot for your quick feedback. Have a nice day.

**Comment by Uatschitchun** [comment]
Hi. Stumbled over the exact same issue. My site is only http. So this means, I can't share a form externally?

**Comment by Chartman123** [comment]
In 2023 you should really think about using https for any site/web app. But we will soon release a new version containing the fix.

**Comment by Uatschitchun** [comment]
Yes, know that! Until now that site was only a personal test-platform, but need it now to share a form.
I guess "soon" is not within the next few days, is it?

**Comment by Chartman123** [comment]
Yes it is, probably this evening ;)
