### ISSUE TITLE
Answering options cannot be added in v1.1.0

### ISSUE THREAD

**Issue by DBJRdev** [nextcloud/forms#166]
**Which Forms version are you running?**
1.1.0, installed today from app store via Nextcloud web interface

**Nextcloud/ownCloud version:**
Nextcloud 17.0.2

### Steps to reproduce
1. Start to create form
2. Pick any clickable answer type (radio, checkboxes, dropdown)
3. Any given answer option will not be accepted by the Forms app
![Bildschirmfoto von 2020-01-15 15-29-42](https://user-images.githubusercontent.com/13522599/72442101-31586280-37ac-11ea-9793-f68a3a014a54.png)

Tested on Firefox 72.0.1 and Chromium 79, both on Ubuntu 19.10

### Actual behaviour
There seem to be no way to enter answering options. The visible input field does not do anything. If you enter the answer options there, you won't be able to finish creating – when clickin on "Fertig" (Finish?): there is a message that all questions need answers.

### Expected behaviour
Some possibility to enter answering options for checkboxes, radio buttons and dropdown questions.

**Comment by schniepp** [comment]
Same problem here. NC17, apache, chrome, server:ubuntu-18.04, client:ubuntu-18.04

**Comment by joseams86** [comment]
I have the same problem too. I tried installing from the store, downloading from the web and it does not work, I also tried to install the previous version of forms but it is not compatible with nextcloud 17.

I hope someone knows the solution or update the error soon.

**Comment by fdrgit** [comment]
Same problem. Nextcloud 17.0.2 server on Debian 9 (stretch), forms 1.1.0 installed from the store. Tested with Chrome Version 79.0.3945.117 running on win10. 
Was working fine with previous release of forms...

**Comment by born2webdesign** [comment]
Same here.
Is there anyone who _doesn’t_ see this with NC 17(.0.2) and forms 1.1.0?
I think the problem is with Forms and/or NC; but, FWIW: server is PHP 7.3, MySQL, Apache; client is Firefox 68.4.1 on Debian 10.

**Comment by pwepwe973** [comment]
Sam Problem for me.

**Comment by mikweb2017** [comment]
Sam Problem for me NC 18 and forms 1.1.0

**Comment by jotoeri** [comment]
Didn't try now, but a few weeks ago it was possible to add answers by typing and pressing Enter.
Indeed, it's just kind of a workaround for now, a button or so would be helpful.

**Comment by githubDante** [comment]
Same here. Nextcloud 17 and the latest version of the app installed through the admin panel. 

Console output:
`Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”).`
The console output indicates that `$csp->allowInlineScript(true);` needs to be set in PageController.php. Also the latest commit to Create.vue f95b22c335a9c537da8198411cced72070e3f23e looks directly related to the issue. Tried some modifications but I've failed miserably.
I hope that it will be fixed soon as the app is currently in an useless state for me.

**Comment by rhersel** [comment]
Same problem for me on NC 17.02. Forms 1.1.0

**Comment by githubDante** [comment]
Please issue an updated version with all commits included and everyone will be happy.

**Comment by joseams86** [comment]
I found a solution and it seems to work without problems (chrome browser)

Download the version 1.0.3 of forms.
https://apps.nextcloud.com/apps/forms

Copy the "js" folder and paste it in: /nextcloud/apps/forms

To the forms.js and survey.jquery.min.js files change the owner to httpdusr (if you don't do this step you will not be able to see the forms when you save them.

Refresh the browser with cnrt. + F5 or restart it (windows)

That is all. I hope it works for you, it works for me.

**Comment by DBJRdev** [comment]
@joseams86 Thanks for the suggestion, but I was not able to reproduce your temporary solution. You meant just overwrite the same-name files or to replace the entire "js" folder (==deleting the other files in "js")?

**Comment by githubDante** [comment]
> @joseams86 Thanks for the suggestion, but I was not able to reproduce your temporary solution. You meant just overwrite the same-name files or to replace the entire "js" folder (==deleting the other files in "js")?

forms.js and all files from the js/chunks/ dir. That's what is build by `make build-js-production`. It is better to clone this repo and to build from master. It takes several minutes and will work, unless you share forms publicly :-)

**Comment by forteller** [comment]
Same issue.

Does anyone have an ETA on a new version? Thanks a lot!

**Comment by agentlibre** [comment]
Same problem. Tested from multiple computers and different browsers.

**Comment by forteller** [comment]
I updated to the latest version, 1.1.6, yesterday, but that did not help.

**Comment by DBJRdev** [comment]
@forteller : Are you possibly mixing up "Forms" and "Polls", because there seems to be no new Forms version, but Polls actually has received an update yesterday or so.

**Comment by forteller** [comment]
Ah, yeah, that's correct. Sorry. No wonder I still have the same issue then :P

**Comment by agentlibre** [comment]
Could someone bring this issue to a higher priority? I am trying to prove the efficiency of NextCloud to an association on the national level and this feature was exactly an important point I wanted to make... Please help :/

**Comment by peetCreative** [comment]
The author @ordaolmayanadam  of PR #123 made more changes, which didn't came in the PR. 
Maybe one also has to keep line 128 in Create.vue  account?
`<input id="unique" v-model="form.event.unique" :disabled="form.event.access === 'public' || form.event.isAnonymous">`

I have no experiences with nextcloud apps. Just now try to manually build it.
Did not succeed by now. Maybe someone else is faster.

**Comment by nightbluepn** [comment]
@peetCreative you need to build it on your server/within the nextcloud file tree. i.e. clone this repository into apps/forms within your server directory, at least this is how i did it.

Adding answers is working with a current build, it still gives a db error on saving the form though.

**Comment by peetCreative** [comment]
Jup, I'm just stuck in an npm error, write access error, ... 
I'll come back later.

**Comment by JazMTaz** [comment]
Same for me here NC 17.0.3 with PHP Version: 7.3.14 and Forms app version 1.1.0

**Comment by MaxG-Git** [comment]
would love to see a fox to this of possible

**Comment by pwepwe973** [comment]
hello, still no solution for this bug?
an update is planned?

**Comment by agentlibre** [comment]
It seems that this app was a one-shot project: [https://help.nextcloud.com/t/were-making-a-forms-app/50271](https://help.nextcloud.com/t/were-making-a-forms-app/50271)

I'm trying to raise awareness on the main NextCloud forum: [https://help.nextcloud.com/t/awareness-on-a-sadly-dying-app-nextcloud-forms/70823](https://help.nextcloud.com/t/awareness-on-a-sadly-dying-app-nextcloud-forms/70823) 

Perhaps you guys could help by mainting my post alive (comment, like, etc.)!

**Comment by pwepwe973** [comment]
hello 
It's good i put the comment

**Comment by mokkin** [comment]
Unfortunately I'm facing the same issue even at the actual master https://github.com/nextcloud/forms/tree/07f9e4bdd5b83f36c5ec8b739585d12bc196b950

**Comment by pzehle** [comment]
Same problem here. It doesn't seem to be solved.

**Comment by jotoeri** [comment]
@pzehle @mokkin 
Can you provide some information on your setup?
How did you build from Master? (dev-setup, build-js-production?)

And just to be sure you know about: In current master you have to press Enter on Keyboard to add options.

Greets,
Jonas

**Comment by pwepwe973** [comment]
> Same problem here. It doesn't seem to be solved.

I have the same problem for 2 months and from what I understood it is not nearly solved

**Comment by pzehle** [comment]
@jotoeri hi, thanks for the reply.

Nextcloud version is 18.0.1
Forms version is 1.1.0

I installed Nextcloud as instructed from the website. Forms was downloaded directly from the nextcloud app store.

I don't think my setup could be any different from the many other users that have the same problem. Simply hitting enter to add an answer won't work.

**Comment by githubDante** [comment]
@pzehle 
Yes this is a known issue. The version published to the app store does not include all commits to the master branch of this repo. Clone the repository, follow the production build instructions, then copy forms.js and all files which will be generated in the js/chunks dir to your installation and you will be able to add answers.

**Comment by Fry-4TF1V** [comment]
Is it possible to push last commits to the app store ? As a user of an hosted and managed Nextcloud I cannot have access to files configuration.

**Comment by schniepp** [comment]
Awesome, it seems like v 1.1.1 fixes the issue! Thank you so much for moving this forward!

**Comment by pwepwe973** [comment]
yessssss for me too thanks you

**Comment by DBJRdev** [comment]
Cool, it works with v1.1.1, thanks for the progress! I think we can close the issue now.

**Comment by pzehle** [comment]
Hello. Sadly it destroyed the app for me. I updated to v1.1.1, and as an admin I am able to open the app, but not even click on "new form", because I get this error:

<img width="675" alt="Bildschirmfoto 2020-03-09 um 18 13 59" src="https://user-images.githubusercontent.com/27866874/76239455-e3069380-6231-11ea-9ca9-b2d44823e995.png">

As a regular user I am not even able to open the app, as it just redirects me to my root domain.

I tried uninstalling and reinstalling but still the same. Hope you can help me. Thanks.

**Comment by DBJRdev** [comment]
@pzehle : Hi, it seems that your problem is another issue. I would propose to open a separate issue for that, because developers might not find your problem here.

**Comment by born2webdesign** [comment]
Thank you for 1.1.1!

**Comment by br608** [comment]
Answering options cannot be added in v. 1.1.1. - in Safari I can add the answer, but not in Firefox, Edge or Chrome.
