### ISSUE TITLE
Apostrophes in "expiration date" shown as numeric char reference

### ISSUE THREAD

**Issue by dvdjaco** [nextcloud/forms#1662]
**Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!**

**Describe the bug**
When an expiration date is set on a form, and the UI language is set to Catalan, the apostrophe is shown as the numeric character reference, e.g. `&#39;` instead of `'`. This happens both on the left panel and under the form description (if the "Show expiration date on form" option is enabled). For example, the text under the form title in the left panel reads `d&#39;aquí una hora.` instead of `d'aquí una hora.`. Other characters such as accented letters are displayed correctly.

**To Reproduce**
1. Create a new form.
2. Set an expiration date.
3. Change the UI language to Catalan.

**Expected behavior**
Apostrophes should be correctly displayed.

**Screenshots**
![image](https://github.com/nextcloud/forms/assets/1502076/c1b74c60-56c8-4974-badb-72040bdfad52)

**Nextcloud (please complete the following information):**
- Nextcloud-Version: 26.0.2
- Forms-Version: 3.3.1
- 
**Desktop (please complete the following information):**
 - OS: Linux Mint
 - Browser: Firefox
 - Version: 115.0

**Comment by dvdjaco** [comment]
Thinking now that this might be a bug in the translation, I'll check that too

**Comment by Chartman123** [comment]
Yes, it's probably translation related :)

**Comment by Chartman123** [comment]
I just another look at it and probably the translation issue is already coming from one of our dependencies.

**Comment by Chartman123** [comment]
As the moment library is no longer in active development, I don't think that we will get a solution for this issue. However, there are some efforts going on to provide some of the things from moment.js directly in NC libs. So we'll perhaps see a fix in a future version.
