### ISSUE TITLE
Password as answer type

### ISSUE THREAD

**Issue by paramazo** [nextcloud/forms#1665]
**Nextcloud (please complete the following information):**
- Nextcloud-Version: 26.0.2
- Forms-Version: 3.3.0

**Is your feature request related to a problem? Please describe.**
We want to give our users the opportunity for requesting restricted data. For this purpose, the users should set a password. Actually this can be done with the existent answer type: short answer as plain text. 
Admins can see the passwords in plain text in the answers tab.

**Describe the solution you'd like**
Admins should not see the desired user password in plain text, it should be hidden, but possible to copy it to the clipboard for further processing tasks.

**Additional context**
A new anwser type field of type password would be great, where users can enter a password and retype it to confirm. Admins should be able to copy this password hidden to the clipboard.

**Comment by Chartman123** [comment]
@paramazo I don't think that this makes sense... An admin could easily copy the password to another text field/file and see the value in cleartext. Furthermore the password would be stored in the DB in clear text and could be extracted from there as well. API would also transfer the value in cleartext. So from a security perspective there is no difference to directly process the input in a normal text field. Please rethink your process.

**Comment by Chartman123** [comment]
I did understand it correctly. But I don't think we should implement something that just looks secure, but isn't in any way. That's why I closed the request.

**Comment by Chartman123** [comment]
Yes, it was. But I think we should end this discussion here...
