### ISSUE TITLE
Database error when running migration

### ISSUE THREAD

**Issue by kaffeeringe** [nextcloud/forms#1666]
**Describe the bug**
I think I had Forms installed earlier, but I uninstalled it, because I didn't need it. Now I wanted to try it out again an it failed to install.

**To Reproduce**
1. Go to Apps
2. Search for "Forms"
3. Klick Download and Activate
4. Error: Database error when running migration 020002Date20200729205932 for app forms Column "oc_forms_v2_answers"."text" is type String, but exceeding the 4.000 length limit.

**Expected behavior**
It should install an run

**Nextcloud (please complete the following information):**
- Nextcloud-Version: 27.0.0
- Forms-Version: 3.3.1
- MariaDB:10.5.19 (Edit)

**Comment by Chartman123** [comment]
Hi @kaffeeringe 

unfortunately you're missing some necessary pieces of information about your environment. As your problem seems database related we at least need to know which DB you're using.

If you don't need your data from your earlier installation, you could also try to just drop all forms related tables (starting with `oc_forms`) from your DB and then try to reinstall the app.

**Comment by kaffeeringe** [comment]
MariaDB:10.5.19

**Comment by kaffeeringe** [comment]
I dropped the tables: DROP TABLE `oc_forms_v2_answers`, `oc_forms_v2_forms`, `oc_forms_v2_options`, `oc_forms_v2_questions`, `oc_forms_v2_submissions`;

Now it complains, that the tables don't exist. I guess, it's still somewhere in the settings?

Database error when running migration 020202Date20210311150843 for app forms An exception occurred while executing a query: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'd01d3714.oc_forms_v2_forms' doesn't exist

**Comment by kaffeeringe** [comment]
BTW: It should be possible to delete apps AND delete all data. But that's a feature request for Nextcloud core ;-)

**Comment by kaffeeringe** [comment]
I deleted the three settings in oc_appconfig for forms. Now I get this error: 

There is no table with name 'db.oc_forms_v2_forms' in the schema.

**Comment by Chartman123** [comment]
You probably need to delete also all rows from oc_migrations for Forms:

`Delete from oc_migrations where app = 'forms'`

**Comment by Chartman123** [comment]
> BTW: It should be possible to delete apps AND delete all data. But that's a feature request for Nextcloud core ;-)

https://github.com/nextcloud/server/issues/5539

**Comment by kaffeeringe** [comment]
That worked! Thank you!

**Comment by kaffeeringe** [comment]
BTW: Thank you for your great work!

**Comment by Chartman123** [comment]
Glad to hear that I could help you! You're welcome and have fun using Forms!
