### ISSUE TITLE
Markdown H1 is not formatted correctly

### ISSUE THREAD

**Issue by mschmidm** [nextcloud/forms#1668]
**Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!**

**Describe the bug**
A H1-Markdown element does not get formatted. Other header elements work.

**To Reproduce**
1. Create a new form
2. Enter "# h1" into the description input
3. See output: The "# h1" is formatted like normal text

**Expected behavior**
The header should not be styled like normal text.

**Screenshots**
![image](https://github.com/nextcloud/forms/assets/66086922/71f16ca9-64c9-47a6-928b-5da3e7df5610)
![image](https://github.com/nextcloud/forms/assets/66086922/fd0c50cd-3b7d-4c3e-ada9-3dd548710bc5)

**Nextcloud**
- Nextcloud-Version: 26.0.2
- Forms-Version: 3.3.1

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: Chrome
 - Version:  114.0.5735.198
 
Thank you very much for your work on Forms, it's a really nice app! :)

**Comment by Chartman123** [comment]
The text is correctly put into `<h1>` tags in view mode. However, there is some "wrong" styling applied to it.

The computed font size for h1 is 15px, for h2 20px. Whereas the h2 form title has a font size of 28px.

@susnux Do you have an idea where this false styling is coming from?
