### ISSUE TITLE
Potential wording problem when using anonymous forms

### ISSUE THREAD

**Issue by bene64** [nextcloud/forms#1673]
**Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!**

**Describe the bug**
The text "answers are anonymous" is not correct, depending on the content of the form.

For example: 
- I make a survey for an upcoming event. To be able to filter out double answers and to know who is coming, I ask for the names.
- The link is shared among the potential persons for this event.
- I get more or less nice messages from persons about the form not being anonymous, despite saying so. 

**Expected behavior**
- Either the text should say "Answers are not linked to your Nextcloud account." instead of "Answers are anonymous.". But this could also lead to confusion, as not every person with a link knows what a Nextcloud account is. So probably not the best alternative.
- Or the text should be adaptable.

**Nextcloud (please complete the following information):**
- Nextcloud-Version: 26
- Forms-Version: 3.3.1

**Comment by Chartman123** [comment]
No problem :) yes, a little more documentation on how the different switched behave wouldn't hurt. If you want you can create PR for that :)

**Comment by bene64** [comment]
![Screenshot 2023-07-24 at 17 41 01](https://github.com/nextcloud/forms/assets/43176624/5ae8c660-6ebe-4e47-baa4-f046bfe7224e)
[1673.diff.txt](https://github.com/nextcloud/forms/files/12147627/1673.diff.txt)


@Chartman123 I did a quick prototype for the settings tab, the global form settings are still missing.
MR will follow. I'm open to suggestions, as I'm not really into frontend stuff.

**Comment by Chartman123** [comment]
@bene64 Thanks for your input 👍🏻 

@nextcloud/designers Any thougts on this? Should we keep the text directly visible or only as a tooltip?
