### ISSUE TITLE
Cannot install forms app due to db migration

### ISSUE THREAD

**Issue by marc-leinweber** [nextcloud/forms#1679]
**Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!**

**Describe the bug**
Trying to install the forms app in Nextcloud 27.0.1 yields the error 

```
Database error when running migration 030100Date20230123182700 for app forms
There is no table with name 'nextcloud.oc_forms_v2_shares' in the schema.
```

**To Reproduce**
Install forms app via `occ` or app store.

**Expected behavior**
Forms app installs without error.

**Nextcloud (please complete the following information):**
- Nextcloud-Version: 27.0.1
- Forms-Version: 3.3.1

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04

**Comment by Chartman123** [comment]
Was the app installed anytime before?

**Comment by marc-leinweber** [comment]
Good point. Yes, I think so for some testing purposes. So I guess there is some garbage in a migrations tracking table? Do I have to clear this by hand?

**Comment by Chartman123** [comment]
Please see #1666
