### ISSUE TITLE
SCSS scoped inside vue files vs. SCSS files inside css folder

### ISSUE THREAD

**Issue by luixxiul** [nextcloud/forms#168]
Basically there are two ways of styling components:

- SCSS scoped inside vue files
- SCSS files inside css folder

I'm sort of being unable to keeping myself up to the conventional coding style of Vue stuff, still I feel the styles are scattered over the codebase and not quite organized. IMO it's one of the hurdles for those who are willing to work on the UI. There should possibly a naming rule like BEM be adopted to maintain the codebase clean and organized, also to prevent UI regressions.

**Comment by jancborchardt** [comment]
@luixxiul good point! @skjnldsv what do you think? :)

**Comment by skjnldsv** [comment]
Hello :)
At nextcloud we suggest to not use scss file anymore.
Scss inside vue single-file-components is the easiest way to go.
Lots of apps now uses this pattern and lots of new contributors were quite happy by how easy they were able to manage it.

The only scss that is usually still needed or helpful at least, is an icons.scss file so apps can use the svg colour api, but that's very specific and should not bother newcomers :)

**Comment by luixxiul** [comment]
> Scss inside vue single-file-components is the easiest way to go.

From my experience at another project without the naming rules it's easiest and also a way of inconsistent styling. Adding comments might help, which isn't promised though.

**Comment by skjnldsv** [comment]
Closing :)
