### ISSUE TITLE
Open markdown link in new tab

### ISSUE THREAD

**Issue by Iwios** [nextcloud/forms#1680]
**Nextcloud (please complete the following information):**
- Nextcloud-Version: [27.0.0]
- Forms-Version: [ 3.3.1]

**Is your feature request related to a problem? Please describe.**
When I create a link formatted in markdown, link open in the current tab

**Describe the solution you'd like**
I would like open link in new tab

**Additional context**
It"'s seem Markdown dosn't allow open link in new tab. HTML allow this, or somme people dev some js library to do that
https://www.eddymens.com/blog/how-to-make-a-markdown-link-open-in-another-tab

**Comment by Chartman123** [comment]
@susnux is anything like this already implemented in Text? I think we shouldn't add anything new but perhaps have some common base across the other apps.

As a workaround, every user can of course just manually open the link in another tab (middle click, long tap, context menu)

**Comment by Iwios** [comment]
Hello,
In fact I can click middle but this function was not user friendly for non initiate :)

**Comment by Iwios** [comment]
and for an external link ?
