### ISSUE TITLE
Validation of singleline/short response, url, regex...

### ISSUE THREAD

**Issue by genofire** [nextcloud/forms#177]
On a single line answer type it would be nice to have validation:
- E-Mail
- IBAN
- own Regular Expression

---
Edit (@jotoeri):
- Numeric only #605

**Comment by jancborchardt** [comment]
Yes, that would be good.

"Date" should be a separate question type though just like it is in Google Forms: https://github.com/nextcloud/forms/issues/14

**Comment by ei8fdb** [comment]
Crowdsignal (a service I use and pay for) implements this as predefined form fields. See below:

![Screenshot from 2020-05-06 12-54-59](https://user-images.githubusercontent.com/1899506/81174041-01221300-8f99-11ea-92a3-9501e6f2c304.png)

The labels, and format are then customisable:

![Screenshot from 2020-05-06 12-56-55](https://user-images.githubusercontent.com/1899506/81174160-39295600-8f99-11ea-8da8-b58b02f0e7a5.png)

for me, this approach makes sense as it focuses on *what I want to gather* - email, telephone, date, etc.

**Comment by MrLoverLoverMMMM** [comment]
I would like to see this feature in future as well :)

**Comment by andrewj720** [comment]
Would be nice to have regex allowed for individual questions, for example, I'd like to limit character length for certain questions using `[\w]{1,140}`
