### ISSUE TITLE
Forms exports with line feeds (LF), that makes analysing the export complicated

### ISSUE THREAD

**Issue by chiguh** [nextcloud/forms#1775]
**Describe the bug**
If a user fills in a long text and he uses line feeds to structure his text, this line feeds are also exported with the .csv making it hard to analyse the export with other tools. First you need to remove this extra line feeds in every line a line feed was used with e.g. Notepad++ and then you can move on.

**To Reproduce**
1. Create a form with a long text
2. Fill in the long text and use line feeds in the text
3. Export the form as .csv
4. Open the .csv with e.g. Notepad++ to see the extra line feeds

**Expected behavior**
I would except that the extra line feeds in long texts do not appear in the export.

**Screenshots**
<img width="637" alt="2023-11-09 11_05_03-Downloads" src="https://github.com/nextcloud/forms/assets/8359470/63ea0b32-d75e-45c9-8b3f-af0dfcc10b7c">

**Nextcloud (please complete the following information):**
- Nextcloud-Version: [27.1.2]
- Forms-Version: [3.3.1]

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Chrome]
 - Version [118.0.5993.120]

**Comment by Chartman123** [comment]
@Koc could you please have a look, if your PR also fixes this problem?

**Comment by Chartman123** [comment]
@chiguh I had a look at the exports in our latest main: in CSV it depends on how your software handles the new lines, libre office imported it correclty. ODS and XLSX exports also work properly. So you now have two options that should work. If you don't mind, I'll close this issue. Please re-open it, if you think we should handle it another way. But I prefer to have the line breaks in the exports, too.
