### ISSUE TITLE
"Public access to all logged in accounts" not working – Form not accessible for all users

### ISSUE THREAD

**Issue by pReya** [nextcloud/forms#1779]
**Describe the bug**
When I create a new form and enable the option "Public access to all logged in accounts", the form is not actually accessible by ALL other users. For some of my users it works – for others, it doesn't. I'm not sure what the difference between these users is that has an influence on this functionality. The two users where it doesn't work are a member of the same (main) group as all other users. So it can't be due to group membership. I'm really lost to understand this.

**To Reproduce**
1. Create new Form
2. Enable "Public access to all logged in accounts"
3. Log in as (a specific) other user, open the link
4. You'll only see the "No forms created yet" / default screen of the App – not the wanted form

**Expected behavior**
ALL users should be able to see/submit the linked form.

**Screenshots**
There's a video/issue about the same behavior in this issue: https://github.com/nextcloud/forms/issues/1616. Though the other issue doesn't say that it works for some users and not for others. But visually the video shows the same behavior as my problematic user.

**Nextcloud (please complete the following information):**
- Nextcloud-Version: 27.1.3
- Forms-Version: 3.3.1

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Firefox
 - Version 120

**Browser log**
Nothing related to the Forms App in the JS console.

**Comment by pReya** [comment]
I've looked at the code and it seems that it fails in this line:
https://github.com/nextcloud/forms/blob/e1b980b70f023496fe60fbb424ad1d3af185211a/lib/Controller/PageController.php#L165

So somehow the session of the problematic users is not valid?! Which is weird, because they can use the rest of Nextcloud just fine.

Anyway, logging out and back in again seemed to fix the problem for these users. I'll close this issue, because it seems unrelated to the Forms app, and rather to be a bug in Nextcloud core.

**Comment by Chartman123** [comment]
@pReya did you enable the second switch "Show to all accounts on sidebar", too? Could you please also have a look if the link contains index.php or not? We had some other issues with links in mail notifications that only worked without index.php

I could reproduce the problem here, if the "show to all accounts on sidebar" isn't enabled, that at least one other user couldn't access the shared form.

**Comment by Chartman123** [comment]
I think that this might indeed be related to #1771 as both involved methods use the `urlgenerator`...
