### ISSUE TITLE
Search for users by email in the sharing section

### ISSUE THREAD

**Issue by iFortunateSon** [nextcloud/forms#1781]
Hello,

**Nextcloud (please complete the following information):**
- Nextcloud-Version: 26.0.4
- Forms-Version: 3.3.1

**Describe the solution you'd like**
When entering an email into the user search box, the found user is displayed, as it is done when sharing access to files in nextcloud

**Additional context**
Providing access for files in NC:
![image](https://github.com/nextcloud/forms/assets/54754344/2502607c-ceb2-4e48-b569-b8f03236977a) 
The user is found by email

Providing access for Forms:
![image](https://github.com/nextcloud/forms/assets/54754344/ac62ca95-7fe3-4175-aa7b-e4ca836d967e)
User is not found by email

**Comment by susnux** [comment]
Sounds good! I will have a look how this can be done :)
