### ISSUE TITLE
Use the IP address of the user if userId is empty

### ISSUE THREAD

**Issue by githubDante** [nextcloud/forms#179]
**Which Forms version are you running?** (see apps page)
git [master]
**Nextcloud or ownCloud?:**
Nextcloud
**Nextcloud/ownCloud version:** (see Nextcloud admin page)
17.0.2

#### Description
If the patch proposed in #178 is applied, the form is **not** configured as _Anonymous Form_ and Access is set to _Public access_ the _Name_ column in the results view will be left empty. The patch included below is using the IP address from where the request is received as userId and as a result the IP address will be shown in _Name_ column.

```
diff --git a/lib/Controller/PageController.php b/lib/Controller/PageController.php
index dcb60f0..5ba188b 100644
--- a/lib/Controller/PageController.php
+++ b/lib/Controller/PageController.php
@@ -278,7 +278,11 @@ class PageController extends Controller {
                $questions = $this->questionMapper->findByForm($form->getId());

                try {
-                       $notification = $this->notificationMapper->findByUserAndForm($form->getId(), $this->userId);
+                       if($this->userId === null) {
+                               $notification = $this->notificationMapper->findByUserAndForm($form->getId(), '');
+                       } else {
+                               $notification = $this->notificationMapper->findByUserAndForm($form->getId(), $this->userId);
+                       }
                } catch (DoesNotExistException $e) {
                        $notification = null;
                }
@@ -400,6 +404,9 @@ class PageController extends Controller {
                                if($form->getIsAnonymous()){
                                                $vote->setUserId($anonID);
                                }else{
+                                               if ($userId === '') {
+                                                       $userId = $this->request->getRemoteAddress();
+                                               }
                                                $vote->setUserId($userId);
                                }
                                $vote->setVoteOptionText(htmlspecialchars($questions[$i]['text']));
```

**Comment by oscaropenness** [comment]
I like your suggestion of using some identifier for unidentfied users.
I tried to apply your suggestion in my Nextcloud instance. My userId column is still empty.
There is no error in the log or anything. Am I missing something?

Another thought:
From a privacy point of view it would be more appropriate to store some hash of the RemoteIp since it contains already some information about the user (location, workplace, country...)

**Comment by githubDante** [comment]
I just tested again with the master branch and the IP address is displayed correctly in the Name column. I'm sending a pull request.

**Comment by jotoeri** [comment]
Things are mixed up here a bit.
The internal server Error itself is removed on master, just a release is pending.

The Proposal above is still open, but does not produce any Error if not implemented. Just an empty Name-Field in Results appears for unauthenticated users.

**Comment by jotoeri** [comment]
@skjnldsv @jancborchardt John & me talked about this for a moment and store these users just like anonymous users now, as John said he wouldn't see any advantage of using the ip.
So the initial problem of an empty user here is solved. Is this issue to develop or just to close? ;)

**Comment by jancborchardt** [comment]
@jotoeri @skjnldsv I’d say if we have a different system which we consider better, we can close this? But your call :)

**Comment by skjnldsv** [comment]
The only real advantage I could see here is using a browser's footprint to store and make the "only one submission" option available for public views too. But this is far more complicated and not 100% foolproof. So I would close this indeed as out of scope :)

**Comment by warrenwong87** [comment]
how to do this?
