### ISSUE TITLE
Repository organization

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/forms#18]
We would love to support you with development on the app and make it possible for more people to see it and contribute! :)

In the readme, you write:

> Note: This will be moved to https://github.com/nextcloud/forms.git once the app has been accepted to the NextCloud app store

Are you interested in doing that? The way this generally needs to be done is that you as app owners need to transfer it to an admin of the Nextcloud org (like @rullzer or me) and then we move it to there.

Let us know what you think! @Barkuto @affan98 @TimS3434 @slink58

**Comment by lachmanfrantisek** [comment]
[Comment by affan98](https://help.nextcloud.com/t/were-making-a-forms-app/50271/27) in the forum:

> It’s probably better to fork for further development. Many of us have just graduated and are starting/have started new jobs. Finding time to work on this project will be unlikely

**Comment by jancborchardt** [comment]
@lachmanfrantisek thanks a lot for the info! Reached out to @affan98 via the forum if they are interested in a transfer. :)

**Comment by jancborchardt** [comment]
Now moved to https://github.com/nextcloud/forms thanks to @affan98! :tada:

To do – cc @skjnldsv @nextcloud/forms cause I am on holiday
- [ ] The app store cert should be transferred, probably to @skjnldsv?
- [ ] Add the collaborators from this repo's settings to the Nextcloud org and the Forms team
- [ ] Adjust the readme to the format we use for other apps

Anything else? :)

**Comment by rullzer** [comment]
> The app store cert should be transferred, probably to @skjnldsv?

Lets create a new certificate and revoke the old one. That seems like a better approach :wink:

**Comment by affan98** [comment]
Sorry, about that. I told my friend to take care of it but I guess he
didn't. I'll send it to you in a bit

**Comment by jancborchardt** [comment]
Closing since the main part has been done with the move, we can track other things in separate issues. :)
