### ISSUE TITLE
Missing localizations in v1.1.0

### ISSUE THREAD

**Issue by DBJRdev** [nextcloud/forms#181]
**Which Forms version are you running?** 
1.1.0 on NC 17.0.2

### Actual behaviour
There are two very visible things that seem not to be localized yet: I tried in German, French, Spanish (and English): 
* The big 'Complete' button
* The warning "﻿ *NOTE: This form is anonymous"

### Expected behaviour
localization ;-)

**Comment by jotoeri** [comment]
Yes, it's gone with the submit-template. But maybe we could think about, if such a hint could be included again in Submit.vue?
