### ISSUE TITLE
Admin account was disabled on all devices by bruteforce protection

### ISSUE THREAD

**Issue by gxpcluster** [nextcloud/forms#1811]
**Describe the bug**
After upgrading to version 3.4.2, my admin account was disabled on all devices by bruteforce protection. The logs constantly show the same error:
`Exception: Undefined constant OCA\Forms\Activity\ActivityConstants::TYPE_NEWSHAREDSUBMISSION in file '/var/www/nextcloud/apps/forms/lib/Activity/Settings/NewSharedSubmission.php' line 35`
After disabling the app everything works fine.

**To Reproduce**
1. Install version 3.4.2
2. Bruteforce protection must be enabled
3. Wait for 1-2 hours

**Nextcloud (please complete the following information):**
- Nextcloud-Version: 27.1.4
- Forms-Version: 3.4.2

**Desktop (please complete the following information):**
 - OS: Debian 12
 - Browser Chromium
 - Version 119

**Smartphone (please complete the following information):**
 - Device: Sony XA2
 - OS: Android 9
 - Browser Bromite
 - Version 108

**Comment by Chartman123** [comment]
Hi @gxpcluster 

I don't believe that a missing constant in one of the PHP files could trigger the bruteforce protection. So you probably have another problem, too. I've also enabled bruteforce protection and the latest release in my prod instance of NC and have no problems at all.

As we had some PHP caching related problems in the past, you could try to reload your webserver and see if the problem persists. Other than that you could also try to overwrite all the files of your Forms installation manually with the files from the latest release. Perhaps there was some problem while installing this version.

**Comment by gxpcluster** [comment]
Hi @Chartman123
Thank you for quick reply.
A server reboot seems to have solved the problem, but that's very strange since app updates didn't require a reboot before.

**Comment by Chartman123** [comment]
Normally they shouldn't need a reboot, but this of course depends on the configuration and the used caching mechanisms as far as I know... However, I'm glad to hear that you could solve your problems 👍🏻
