### ISSUE TITLE
Forms 4.0 now blank after upgrading.

### ISSUE THREAD

**Issue by llambkin** [nextcloud/forms#1838]
I have upgraded from NextCloud 27 to 28, and now my forms page is completely blank. I can access files, photos etc. but the forms tab displays a blank page with just the app tabs and user account icons visible.

**Expected behavior**
Forms section to load correctly

**Screenshots**
![image](https://github.com/nextcloud/forms/assets/3177909/2dcc11ae-7ab8-4b9f-8d87-ec340446c596)

**Nextcloud (please complete the following information):**
- Nextcloud-Version: 28
- Forms-Version: 4.0

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome and Edge
 
**Browser log**
JQMIGRATE: Migrate is installed, version 3.4.1
forms-main.mjs:1 Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "application/octet-stream". Strict MIME type checking is enforced for module scripts per HTML spec.
session-heartbeat.js:103 session heartbeat polling started
bootstrap:19 Proxying an event bus of version 3.1.0 with 1.3.0
e @ index.es.js:2337
91099 @ index.es.js:3314
a @ bootstrap:19
76506 @ requesttoken.js:11
a @ bootstrap:19
3878 @ index.js:25
a @ bootstrap:19
50395 @ index.js:14
a @ bootstrap:19
22534 @ index.js:41
a @ bootstrap:19
61595 @ notificationsService.js:92
a @ bootstrap:19
Promise.then (async)
NotificationsApp @ main.js:42
f @ vue.runtime.esm.js:2796
si @ vue.runtime.esm.js:4478
(anonymous) @ vue.runtime.esm.js:2916
oe @ vue.runtime.esm.js:2866
t.$createElement @ vue.runtime.esm.js:2639
render @ main.js:44
t._render @ vue.runtime.esm.js:2684
i @ vue.runtime.esm.js:3875
t.get @ vue.runtime.esm.js:3446
t @ vue.runtime.esm.js:3436
t @ vue.runtime.esm.js:3892
Ti.$mount @ vue.runtime.esm.js:8779
t._init @ vue.runtime.esm.js:5705
Ti @ vue.runtime.esm.js:5766
(anonymous) @ main.js:37
(anonymous) @ main.js:44
(anonymous) @ main.js:44
Show 13 more frames
Show less

**Additional context**
I have deleted forms and reinstalled, and has the same result

**Comment by Chartman123** [comment]
Hi @llambkin there's probably not a problem with Forms but with your web server. Which server are you using? Please make sure that the mimetypes are configured correctly.

**Comment by llambkin** [comment]
> Hi @llambkin there's probably not a problem with Forms but with your web server. Which server are you using? Please make sure that the mimetypes are configured correctly.

okay. Would you kindly guide me on how to go about this? I wasn’t aware I had to be a coder to utilise this software.

I am using the Linuxserver docker container on Unraid.

I have no idea on what a mimetype even is nor where to start. All the rest of NextCloud seems to work fine.

**Comment by Chartman123** [comment]
> be a coder

You're not supposed to be a coder, but you should at least now a little about web servers and how the web works in general 🙂 

I'll be closing this issue. Please follow the Linuxserver bug tracker, as there's already an issue with the same problem:

https://github.com/linuxserver/docker-nextcloud/issues/388

**Comment by llambkin** [comment]
> > be a coder
> 
> You're not supposed to be a coder, but you should at least now a little about web servers and how the web works in general 🙂
> 
> I'll be closing this issue. Please follow the Linuxserver bug tracker, as there's already an issue with the same problem:
> 
> [linuxserver/docker-nextcloud#388](https://github.com/linuxserver/docker-nextcloud/issues/388)
> 
> It seems to be related to a file mime.types used by the nginx web server in those images. You'll have to add `mjs` to the list of javascript file extensions in that file. As nginx is not officially supported by Nextcloud that's all I can do for you right now. Good luck! I hope you can figure out how to fix it yourself.

Okay, got it!
I edited file /config/nginx/nginx.conf

Scrolled down to http { section, and made my section look like this:


http {
    # Includes mapping of file name extensions to MIME types of responses
    # and defines the default type.
    include /etc/nginx/mime.types;
    types {
        application/javascript js mjs;
    }
    default_type application/octet-stream;

Reloaded Nextcloud, and it now works :)

**Comment by nicovd737** [comment]
Hello,

> > > be a coder
> > 
> > 
> > You're not supposed to be a coder, but you should at least now a little about web servers and how the web works in general 🙂
> > I'll be closing this issue. Please follow the Linuxserver bug tracker, as there's already an issue with the same problem:
> > [linuxserver/docker-nextcloud#388](https://github.com/linuxserver/docker-nextcloud/issues/388)
> > It seems to be related to a file mime.types used by the nginx web server in those images. You'll have to add `mjs` to the list of javascript file extensions in that file. As nginx is not officially supported by Nextcloud that's all I can do for you right now. Good luck! I hope you can figure out how to fix it yourself.
> 
> Okay, got it! I edited file /config/nginx/nginx.conf
> 
> Scrolled down to http { section, and made my section look like this:
> 
> http { # Includes mapping of file name extensions to MIME types of responses # and defines the default type. include /etc/nginx/mime.types; types { application/javascript js mjs; } default_type application/octet-stream;
> 
> Reloaded Nextcloud, and it now works :)

Wonderfull !
Thanks for the tip, it solved our issue with Forms.

@Chartman123 Sorry for creating new ticket for that but for me github search is not very usefull for non github users :-) By the way it's another subjet.

Regards.
