### ISSUE TITLE
Export Resultat as CSV to Files not functional 

### ISSUE THREAD

**Issue by overcuriousity** [nextcloud/forms#1842]
**Describe the bug**
The survey results cannot be exported as CSV to the files app, at least in my instance.

**To Reproduce**
1. Go to 'results'
2. Click on 'three dot menu'
3. Choose "Export CSV to Files"
4. No file created 

**Expected behavior**
File should be created 

**Screenshots**

**Nextcloud (please complete the following information):**
- Nextcloud-Version: [ 28.0.0.1]
- Forms-Version: latest as of time of reporting 

**Desktop (please complete the following information):**
 - OS: [Debian 12]
 - Browser Brave
 - Version latest as of time of reporting

**Comment by Chartman123** [comment]
> * Go to 'results'
> * Click on 'three dot menu'
> * Choose "Export CSV to Files"
> * No file created

Hi @overcuriousity, your steps to reproduce can't be complete. If you only the app should present you the file picker where you have to choose the storage location of the csv file. Does the file picker appear?

Do you see anything in your browser console? You didn't fill out the whole bug template so I have to guess what's going wrong. Please provide us with more information

**Comment by Chartman123** [comment]
Ok, I just tried it myself, the file picker doesn't work and the following error is logged in the browser console:

```
Uncaught (in promise) TypeError: can't redefine non-configurable property "$router"
    Mn https://cloud.tsmd.de/custom_apps/forms/js/forms-main.mjs:2
    use https://cloud.tsmd.de/custom_apps/forms/js/_plugin-vue2_normalizer-b29d135b.mjs:2
    <anonymous> https://cloud.tsmd.de/custom_apps/forms/js/forms-main.mjs:2
forms-main.mjs:2:12207
```

**Comment by overcuriousity** [comment]
Hi,
I checked and can confirm that the file picker does not appear.
Console:
`forms-main.mjs:2 Uncaught (in promise) TypeError: Cannot redefine property: $router
    at Function.defineProperty (<anonymous>)
    at Function.Mn [as install] (forms-main.mjs:2:12207)
    at t.use (_plugin-vue2_normalizer-b29d135b.mjs:2:102354)
    at forms-main.mjs:2:174155`

**Comment by susnux** [comment]
I can not reproduce this using forms 4.0.0 and Nextcloud 28.0.1.
Could you check if it is fixed for you when upgrading to 28.0.1?

**Comment by Chartman123** [comment]
@susnux yes, I can confirm it on 28.0.1, too. But not on all instances, my local dev instance works just fine.

**Comment by susnux** [comment]
I have no idea why this is happening only sometimes, but at least I was able to reproduce and fix it for the instances where it did not work.
