### ISSUE TITLE
Submission date not in locale format

### ISSUE THREAD

**Issue by QQ7QQ7** [nextcloud/forms#1856]
**Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!**

**Describe the bug**
It seems that the submission date that is shown in "Results -> Responses" is not affected by the locale that the user has selected.

**To Reproduce**
1. Create a form
2. Submit to the form
3. Change your locale to "German (Germany)"
4. Open the Results of the form
5. Change the view to "Resonses"
6. The submission date is displayed in english

**Expected behavior**
The submission date should be displayed in the selected locale format.

**Screenshots**
Submission date in Responses:
![image](https://github.com/nextcloud/forms/assets/74598225/0d457435-7a71-4703-82cf-994761266cc0)

Selected locale:
![image](https://github.com/nextcloud/forms/assets/74598225/84235a45-5ff7-409d-a363-15e858ec54fd)

**Nextcloud (please complete the following information):**
- Nextcloud-Version: 28.0.1
- Forms-Version: 4.0.0

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Microsoft Edge
 - Version: 120.0.2210.91

**Comment by Chartman123** [comment]
@susnux Any idea why `nextcloud-moment` no longer provides the localized output?

**Comment by susnux** [comment]
This seems to be related to tree shaking because the locales are not imported for moment thus they are removed. Fixed this on the nextcloud-moment package. See https://github.com/nextcloud-libraries/nextcloud-moment/pull/781
