### ISSUE TITLE
Not possible to answer forms with guest accounts Nextcloud 28

### ISSUE THREAD

**Issue by DaphneMuller** [nextcloud/forms#1864]
**Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!**

**Describe the bug**
Forms cannot be filled in by guest users

**To Reproduce**
1. Create a new form
2. Create a public share link
3. Add access for logged in users:
<img width="363" alt="Scherm­afbeelding 2024-01-03 om 10 48 59" src="https://github.com/nextcloud/forms/assets/86835268/b41a0d05-bd7e-4f1b-85a0-25cf2ff16d84">
 
4. Try to access the share link while being logged in with a guest account
5. See error:
![afbeelding](https://github.com/nextcloud/forms/assets/86835268/fee7f886-2587-4118-afb4-6854cab33a69)

**Expected behavior**
The survey should be accessible.

Without the configuration switch on (step 3), the survey also does not work. Steps:
1. Create a new form
2. Create a public share link
3. Access the public share link while logged in as guest
4. Survey appears
5. Fill in the survey, submit the survey
6. Error appears:

Submit fails without visible reason - “There was an error submitting the form”

https://cloud.nextcloud.com/apps/forms/s/39CQsYBnH59c5fnZjsReRnXg

User sees 403 on https://cloud.nextcloud.com/ocs/v2.php/apps/forms/api/v2.2/submission/insert

**Screenshots**

**Nextcloud (please complete the following information):**
- Nextcloud-Version: 28 (company instance)
- Forms-Version: see company instance

**Comment by Chartman123** [comment]
> if sysadmin did not allow guest users access to the application. Asking now.

Hi @DaphneMuller, did you already get more information about that?

**Comment by nickvergessen** [comment]
Yeah, the guests on our instance are not allowed to use the forms app, so that's not a bug in forms.
