### ISSUE TITLE
Results visible for anyone

### ISSUE THREAD

**Issue by XNarno** [nextcloud/forms#1865]
**Nextcloud :**
- Nextcloud-Version: 26.0.1.1
- Forms-Version: 3.4.2

**Is your feature request related to a problem? Please describe.**
I use forms to create events with friends, and no one can see the results.

**Describe the solution you'd like**
I'd like people who click on the link in the form to be able to see the results, a bit like the form admin can do.

**Describe alternatives you've considered**
An alternative would be to create a second link just for the answers, but this would be less practical.

**Comment by Chartman123** [comment]
This is already possible, you can grant the permission to see the results by sharing a form with other users of your Nextcloud instance.

**Comment by XNarno** [comment]
Yes, but I want to share it for users outside my instance, like a public link.

**Comment by Chartman123** [comment]
@XNarno what do you mean by "create events with friends"? What are your typical forms looking like? If you just want to use forms as replacement for Doodle or something like that you should have a look at the Polls app which will suite you better than Forms :)

**Comment by XNarno** [comment]
Yes, but polls allow me to let them propose choices, and I'd like to have the form text input feature. In form I can let my friends write some text in a text area and I can see what they wrote.
My typical form is "What do you want to eat at the party ?" or "What can you bring to the party ?" and because of that, I like form for the text area and not a choice like in polls because it'll do a lot of choice with only 1 vote which is useless.
And my problem is that in form, I can publicly share a form to non-user friends, they can answer, but can't see the results.

**Comment by Chartman123** [comment]
Ok, I understand. As a workaround for your very special use case you will be able to link a file to a form where all submissions will automatically be stored. You can then share that file containing all answers via files :)

This will be available in 4.1

**Comment by XNarno** [comment]
Nice ! Thank you for this workaround, I'll look forward to it !
