### ISSUE TITLE
Text color of form descriptions has too little contrast and is difficult to read

### ISSUE THREAD

**Issue by mschmidm** [nextcloud/forms#1878]
**Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!**

**Describe the bug**

First of all, thank you for working on this nice app! :)

The users of my Nextcloud instance complain about the bad readability of the form descriptions, especially in dark mode. In our use case, we use longer form descriptions similar to a short invitation letter and I think many other "Forms" users are doing the same.

The reason for the bad readability is the use of the `var(--color-text-maxcontrast)` CSS variable which should be used for " secondary text like sublines, timestamps, and similar" ([source: nextcloud docs](https://docs.nextcloud.com/server/latest/developer_manual/design/foundations.html)). But in contrast to the form question descriptions, the form description is not a short secondary text like a subline. Therefore, instead the `var(--color-main-text)` CSS variable should be used, which has a higher contrast and should be used for "main text", according to the Nextcloud Docs.

**To Reproduce**
1. Create a form
2. Add a form description
3. The description is hard to read due to bad contrast, both in bright and dark mode, and both when editing and viewing the form

**Expected behavior**

The description should be easily readable. The Markdown support for descriptions highlights that users may want to use descriptions for longer text. Such longer text should not use secondary text color but main text color with good contrast. This is also required for better accessibility and to be in line with the Nextcloud theming guidelines.

**Screenshots**

Current status with bad readability. **Screenshots of my expected design are expandable below.**

![image](https://github.com/nextcloud/forms/assets/66086922/92584384-a1d2-422f-8a2d-1b433f6e6bf7)

![image](https://github.com/nextcloud/forms/assets/66086922/355b004f-c3fa-4e6e-b46e-6597a7855443)

<details>

<summary>Screenshots of much better readability with var(--color-main-text)</summary>

![image](https://github.com/nextcloud/forms/assets/66086922/f90deeec-092d-4aa9-941c-7c21a869fbd0)

![image](https://github.com/nextcloud/forms/assets/66086922/025b3be3-f32e-4e52-8e00-3cb0019babe5)

</details>

**Nextcloud (please complete the following information):**
- Nextcloud-Version: [28.0.0]
- Forms-Version: [4.0.0 (main branch from 2024/01/16)]

**Desktop (please complete the following information):**
 - OS: [Ubuntu]
 - Browser [Chrome]
 - Version [120.0.6099.216]

**Comment by Chartman123** [comment]
@nextcloud/designers What do you think about that? Is the mentioned variable the correct one to use here?

**Comment by szaimen** [comment]
I would personally also use `var(--color-main-text)` here because it makes the text easier to read

**Comment by jancborchardt** [comment]
@mschmidm sounds good! Would you like to submit a pull request to fix the variable? :)

**Comment by mschmidm** [comment]
@jancborchardt Yes, I will have a look at it! :)
