### ISSUE TITLE
forms is not displayed

### ISSUE THREAD

**Issue by Tealk** [nextcloud/forms#1879]
**Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!**

**Describe the bug**
since the update to 28, forms is no longer displayed to me and no errors or warnings are written to the log

**To Reproduce**

1. open nextcloud in the browser
2. select forms app

**Expected behavior**
I can see the forms or create new ones

**Screenshots**
![image](https://github.com/nextcloud/forms/assets/12276250/f0533de7-b5e0-429a-a659-421f56000fb8)

**Nextcloud (please complete the following information):**
- Nextcloud-Version: 28.0.1
- Forms-Version: 4.0.0

**Desktop (please complete the following information):**
 - OS: Arch
 - Browser Firefox
 - Version 121.0.1 (64-bit)

**Browser log**
```
Content-Security-Policy: Ignoring “blob:” within script-src-elem: ‘strict-dynamic’ specified [forms](https://rollenspiel.cloud/apps/forms/)
Initializing bitwardenContentMessageHandler [bootstrap-content-message-handler.js:229:13](moz-extension://9eafbaeb-d094-4539-81b3-0b2a1fb6f65d/content/bootstrap-content-message-handler.js)
Attaching message event listener. [bootstrap-content-message-handler.js:217:17](moz-extension://9eafbaeb-d094-4539-81b3-0b2a1fb6f65d/content/bootstrap-content-message-handler.js)
Loading failed for the module with source “https://rollenspiel.cloud/apps/forms/js/forms-main.mjs?v=3d8bba83-62”. [index-f091e784.css:37:18](webpack://./node_modules/@nextcloud/vue/dist/assets/index-f091e784.css)
JQMIGRATE: Migrate is installed, version 3.4.1 [jquery-migrate.min.js:2:980](webpack:///nextcloud/node_modules/jquery-migrate/dist/jquery-migrate.min.js)
Global search initialized! [GlobalSearch.vue:51](webpack:///nextcloud/core/src/views/GlobalSearch.vue)
session heartbeat polling started [session-heartbeat.js:103:9](webpack:///nextcloud/core/src/session-heartbeat.js)
Proxying an event bus of version 3.1.0 with 1.3.0 [index.es.js:2337:14](webpack:///notifications/node_modules/@nextcloud/notify_push/node_modules/@nextcloud/auth/node_modules/@nextcloud/event-bus/dist/index.es.js)
Registering notifications container as a menu [NotificationsApp.vue:219](webpack:///notifications/src/NotificationsApp.vue)
Notifications permissions granted [NotificationsApp.vue:453](webpack:///notifications/src/NotificationsApp.vue)
Polling interval updated to 30000 [NotificationsApp.vue:416](webpack:///notifications/src/NotificationsApp.vue)
Started background fetcher as session_keepalive is enabled [NotificationsApp.vue:275](webpack:///notifications/src/NotificationsApp.vue)
Search providers 
Array(21) [ {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, … ]
[GlobalSearchModal.vue:243](webpack:///nextcloud/core/src/views/GlobalSearchModal.vue)
Contacts 
Array(25) [ {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, … ]
[GlobalSearchModal.vue:247](webpack:///nextcloud/core/src/views/GlobalSearchModal.vue)
Got notification data, restoring default polling interval.
```

<details>
<summary>How to access your browser console (Click to expand)</summary>

# Chrome
- Press either CTRL + SHIFT + J to open the “console” tab of the Developer Tools.
- Alternative method:
    1. Press either CTRL + SHIFT + I or F12 to open the Developer Tools.
    2. Click the “console” tab.

# Safari
- Press CMD + ALT + I to open the Web Inspector.
- See Chrome’s step 2. (Chrome and Safari have pretty much identical dev tools.)

# IE9
1. Press F12 to open the developer tools.
2. Click the “console” tab.

# Firefox
- Press CTRL + SHIFT + K to open the Web console (COMMAND + SHIFT + K on Macs).
- or, if Firebug is installed (recommended):
    1. Press F12 to open Firebug.
    2. Click on the “console” tab.

# Opera
1. Press CTRL + SHIFT + I to open Dragonfly.
2. Click on the “console” tab.
</details>

**Additional context**

**Comment by Chartman123** [comment]
@Tealk this is really strange... Could you please try to install the files again into your app directory? Perhaps something went wrong with your installation. Or are you using some kind of script blocker?

**Comment by Tealk** [comment]
Manually or via the appstore?

**Comment by Chartman123** [comment]
Manually... you can download the package from here: https://github.com/nextcloud-releases/forms/releases/tag/v4.0.0

**Comment by Tealk** [comment]
I have now overwritten the files once and I have just uninstalled and deleted the app and reinstalled it via the appstore, the problem remains.

I have no script blockers or similar active for the domain; but even in a new browser profile I have the problem

**Comment by Chartman123** [comment]
Ok, then it's probably related to this issue here: #1838

**Comment by Tealk** [comment]
yes i have solved it

I have replaced the following in the file `/etc/nginx/mime.types`

```
    application/javascript                js;
```
with
```
    application/javascript		 js mjs;
```

**Comment by Chartman123** [comment]
Glad you could fix your problem :)

**Comment by Tealk** [comment]
Thank you verry much
