### ISSUE TITLE
"Form not found" page looks broken in 28

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/forms#1903]
open e.g. `/apps/forms/s`

![grafik](https://github.com/nextcloud/forms/assets/213943/630ab4f9-1723-4f41-b63c-5557f3b06fe9)

**Comment by Chartman123** [comment]
Ok, might be related to the nextcloud-vue changes regarding NcEmptyContent

**Comment by Chartman123** [comment]
It's a problem in the template of the FormsEmptyContent and also affects stable3
