### ISSUE TITLE
Forms app disappointing, buggy and unusable

### ISSUE THREAD

**Issue by waazdakka** [nextcloud/forms#192]
**Which Forms version are you running?** (see apps page)
1.1.0
**Nextcloud or ownCloud?:**
Nextcloud
**Nextcloud/ownCloud version:** (see Nextcloud admin page)
18
### Steps to reproduce
1. Use Nextcloud Forms
2. Look for a *Ggle forms* like behaviour
3. Use Framaforms or Google forms

Hello,
The Nextcloud forms app is really unusable since a lot of functionnalities are missing : 
- Can't edit forms (replacing "form" by "edit" in the URL display and empty form page)
- Radioboxes, checkboxes and dropdown are not working anymore in NC18 (No options are displayed)
- Results are not usable (list of mixed answers, and no way to display results by question, or some graphs...)
- No possibility to add another admin to the form
- Get internal server error when sharing the link in public...

Any chance this could be improved soon ? Users are leaving Nextcloud fast for another solution :(

Thanks

**Comment by marcelklehr** [comment]
I agree that the current state of the app is undesirable. The main underlying problem underneath all of these issues is the lack of a maintainer. There would need to be somebody who will take on maintenance of this app to consistently and permanently work on fixing these issues.

**Comment by agentlibre** [comment]
I concur. The app is useless as it stands.

**Comment by agentlibre** [comment]
It seems that this app was a one-shot project: [https://help.nextcloud.com/t/were-making-a-forms-app/50271](https://help.nextcloud.com/t/were-making-a-forms-app/50271)

I'm trying to raise awareness on the main NextCloud forum: [https://help.nextcloud.com/t/awareness-on-a-sadly-dying-app-nextcloud-forms/70823](https://help.nextcloud.com/t/awareness-on-a-sadly-dying-app-nextcloud-forms/70823) 

Any of you could help by keeping my post alive (comment, like, etc.)!

**Comment by poVoq** [comment]
IMHO, as already foretold in the original thread on the forums, reinventing the wheel usually leads to abandonment.

What Nextcloud really needs is an OpenRosa standard implementation to leverage the existing application ecosystem around it.

**Comment by CoreyBurger** [comment]
To comment - this is not an original implementation. If you read the original forum thread, this is based on SurveyJS. There was discussion of using OpenRosa/ODK but they chose not to.

**Comment by waazdakka** [comment]
Ok I understand the apsect of an one-shot-project, but I don't understance why Nextcloud still propose this package as it's not maintained anymore.
If the goal is to fill up the app store like an Android store full of crapware, you're doing it right...
But I really don't think it's the purpose of Nextcloud here...

**Comment by jancborchardt** [comment]
Closing this as it’s not the kind of tone we communicate with in the Nextcloud project. Please stay friendly and remember that in online communication, a smiley can’t hurt. :)

We did a design review and there will be some more general architectural changes. We are also looking for people to join in and collaborate, so please check out the design review issue at https://github.com/nextcloud/forms/issues/34 and other more productive issues. :)
