### ISSUE TITLE
API response: Failure 404

### ISSUE THREAD

**Issue by geephile** [nextcloud/forms#1929]
**Describe the bug**
API request only returns 

`<?xml version="1.0"?>
<ocs>
 <meta>
  <status>failure</status>
  <statuscode>404</statuscode>
  <message>Invalid query, please check the syntax. API specifications are here: http://www.freedesktop.org/wiki/Specifications/open-collaboration-services.
</message>
 </meta>
 <data/>
</ocs>`

**To Reproduce**
execute command `curl -s -u "<user:password>" -X GET https://<baseURL>/ocs/v2.php/apps/forms/api/v2.2/forms --header "OCS-APIRequest: true"`

where user/password/baseURL are replaced by the proper values

**Expected behavior**
A response of condensed objects of all Forms beeing owned by the authenticated user. (according to https://github.com/nextcloud/forms/blob/main/docs/API.md)

**Nextcloud (please complete the following information):**
- OS: Debian GNU/Linux trixie x86_64 
- httpd: nginx 1.24.0-2+b1
- Nextcloud-Version: 27.1.5 and 27.1.6
- Forms-Version: 3.4.4

**Client (please complete the following information):**
 - OS: Ubuntu 23.04 x86_64 
 - curl 7.88.1

**Additional context**

To verify the API mechanic ive tried a default one on user status and that seems to work
`curl -s -u "<user:password>" -X GET https://<baseURL>/ocs/v2.php/apps/user_status/api/v1/user_status --header "OCS-APIRequest: true"`

Does give me a correct response 

`<?xml version="1.0"?>
<ocs>
 <meta>
  <status>ok</status>
  <statuscode>200</statuscode>
  <message>OK</message>
 </meta>
 <data>
  <userId>hajo</userId>
  <message/>
  <messageId/>
  <messageIsPredefined></messageIsPredefined>
  <icon/>
  <clearAt/>
  <status>online</status>
  <statusIsUserDefined></statusIsUserDefined>
 </data>
</ocs>
`

**Comment by Chartman123** [comment]
Can't reproduce here... Please double check that you don't have any typo in your URL. If it wouldn't work, the app couldn't work either, as we completely rely on the API for the front end

**Comment by Chartman123** [comment]
@geephile closed due to missing feedback
