### ISSUE TITLE
Multiple responses to question

### ISSUE THREAD

**Issue by jamesstanw** [nextcloud/forms#1957]
**Nextcloud (please complete the following information):**
- Nextcloud-Version: 27.1.2]
- Forms-Version: 3.4.5]

**Is your feature request related to a problem? Please describe.**
Forms are great!  I've got a couple of issues I cannot find answers to:
1. When setting a multiple choice question (e.g., with radio buttons) can users submit multiple responses (e.g., A, B, and D)? This is in the context of a student quiz where there may be more than one correct answer.
2. Can a user (e.g., Class X) submit more than one answer?
Thanks.

**Comment by Chartman123** [comment]
1. Radio buttons only allow one of them to be selected, just use the checkboxes.

2. It depends on the settings of the form whether someone can submit several times.
