### ISSUE TITLE
Confusing arrow "button" near "technical name" input field

### ISSUE THREAD

**Issue by matthijskooijman** [nextcloud/forms#1973]
I previously posted this as feedback on a PR before it was applied (https://github.com/nextcloud/forms/pull/1758#issuecomment-1896763727), but since this issue really seems unrelated to the PR itself, I'm reposting it here separately.

**Describe the bug**
When clicking the dots menu for a question, there is a "Technical name" input field, with a "right arrow" button. However, it is unclear to me what that button is supposed to do. I thought maybe a "save" or "apply" button, but clicking it does not give any feedback, and even when not clicking it changes seems saved.

![image](https://github.com/nextcloud/forms/assets/194491/5aa94c11-5c60-4a07-88ac-ab3d8fa514c7)

**Expected behavior**
I would expect clicking the button gives some kind of feedback that the value was saved.

Or, if data is automatically saved without clicking the button, I would expect the button to not be there.

**Nextcloud:**
- Nextcloud-Version: 28.0.1
- Forms-Version: 4.0.0 with PR #1758 applied

**Desktop (please complete the following information):**
 - OS: Linux Ubuntu 23.04
 - Browser: Firefox
 - Version: 121.0.1

**Browser log**
No entries in the log in response to opening the dots menu or clicking the button.

**Comment by susnux** [comment]
@nextcloud/designers I think this is a general design / UX desicion also for other placed (e.g. core settings):

1. Should there be only an explicit save button
2. Or show save button + auto save but give feedback when value is saved
3. Or only auto save + show saved indicator?

**Comment by szaimen** [comment]
> 3\. Or only auto save + show saved indicator?

In this case here, I would choose this option.
