### ISSUE TITLE
unable to add answers 

### ISSUE THREAD

**Issue by phonon112358** [nextcloud/forms#200]
**Which Forms version are you running?** (see apps page) 1.1.0

**Nextcloud or ownCloud?:** NC

**Nextcloud/ownCloud version:** (see Nextcloud admin page) 18.0.1

### Steps to reproduce
1. Create a new form
2. Add a question with answer type "radio buttons" or "check boxes"
3. Try to add the answers which should be selectable 

### Actual behaviour
No answer can be added. And the form cannot be saved due to the error message that every question must have an answer. See also https://help.nextcloud.com/t/nextcloud-forms/54654/8?u=phonon

### Expected behaviour
Answers should be able to be added by pressing enter.

**In case of a bug, please answer the following questions**

### Server configuration

**Operating system**: Debian 10

**Web server:** nginx 

**Database:** mariadb 10.4

**PHP version:** 7.3

**Comment by laarisyko** [comment]
Hi, the same problem here. Can't use the app anymore. Great app anyways :)

**Comment by jotoeri** [comment]
#166 
Should be solved already. Just waiting for a release :)

**Comment by rogercreagh** [comment]
Still not working....(4 days later - app not workable)

**Comment by phonon112358** [comment]
thanks @jotoeri ! 
closed as duplicate of https://github.com/nextcloud/forms/issues/166
