### ISSUE TITLE
Organize forms in folders

### ISSUE THREAD

**Issue by jamesstanw** [nextcloud/forms#2012]
**Nextcloud (please complete the following information):**
- Nextcloud-Version: 27.1.2
- Forms-Version: 3.4.6
**Is your feature request related to a problem? Please describe.**
Two issues:

1. I am creating forms as quizzes for classes I teach.  It is hard to keep them organized as the list will grow long e.g., 4 classes x 5 quizzes x 5 quiz sessions = 100 quizzes spread across 4 classes in a long unweildly list!

~~2. The option to co-author a form.  I may write some questions but then an assistant could, ideally, add others - if we could easily co-author
I really appreciate forms as an alternative to Google and I know you are working hard on developments - so perhaps this could slip in somewhere?~~ Already tracked in #322 

**Describe the solution you'd like**
For:
1. Perhaps a system of folders, sub-folders or some other smarter technical solution
2. ~~Share button for co-authors~~

**Describe alternatives you've considered**
As above - sorry not really following

Thanks!

**Comment by Chartman123** [comment]
Hi @jamesstanw 

Your second request is already tracked in #322, so I edited your post a little.

The organization of Forms in folders sounds like a nice addition, but I don't think that this will be used by many users. So, I don't think we will see this in the near future.

@susnux @jancborchardt What do you think about that?

**Comment by jamesstanw** [comment]
> The organization of Forms in folders sounds like a nice addition, but I don't think that this will be used by many users. So, I don't think we will see this in the near future.

Thanks - great co-authoring is on the tracked for future development

Organization of forms - I'm struggling to believe other users will not want to organize forms.  A long list of "stuff"  is not helpful. Organizing forms by name so they are co-located for organization is also hard work.  I've ended up with folders in Google to keep track of forms. 
I'd be interested to see how other users react before killing the idea.

**Comment by estux** [comment]
Totally agree that some kind of organization is needed here (and also in other Nextcloud apps but we're here for Forms). 
A long list of things is usually always a mess.

Just saying it could be folders, tags, both of them or/and also an archived folder to put there past forms (e.g. if you need to keep track of old forms for some reasons like GDPR register)

**Comment by Chartman123** [comment]
@jamesstanw I just saw that your other request is also already tracked in #853 

Please use the search the next time :) So, I'll close this issue as duplicate
