### ISSUE TITLE
Duplicate/Clone Form

### ISSUE THREAD

**Issue by laarisyko** [nextcloud/forms#202]
It would be great, if one could duplicate a form, so it could be reused. We want to use the app for internal employee surveys every month. This little feature would simplify the process a lot. 

The advanced version, would be an option for time periodic forms :)

Thank you and all the best,
Lorenz

**Comment by learndyanimcs** [comment]
I was reading somewhere that this feature is already available in the Beta Version. I'm currently running Nextcloud 20.0.0 Beta 4 and installed Forms 2.0.4, but there is no option to duplicate a form. Is it possible to use the current beta?

**Comment by skjnldsv** [comment]
No it is not available.
See the labels and milestone on the right :) :v:
