### ISSUE TITLE
Allow visitors to fill out forms

### ISSUE THREAD

**Issue by w460101** [nextcloud/forms#2035]
**Nextcloud (please complete the following information):**
- Nextcloud-Version: [e.g. 19.0.0]
- Forms-Version: [e.g. 2.0.0-beta4]

**Is your feature request related to a problem? Please describe.**
The Form app does not support external visitors filling in information.

**Describe the solution you'd like**
Allow external visitors to fill out forms

**Describe alternatives you've considered**
Polls App allows external visitors to fill out questionnaires

**Additional context**
![Snipaste_2024-03-29_11-14-19](https://github.com/nextcloud/forms/assets/7324277/52adfb7b-d9a4-449f-92a3-e3460f49f788)

**Comment by Chartman123** [comment]
This is possible, just create a public link share for the form.
