### ISSUE TITLE
Refactor `lastUpdated` handling

### ISSUE THREAD

**Issue by Chartman123** [nextcloud/forms#2072]
Maybe we should just have updated the `FormMapper::update` method to set always the lastupdated value on update and then call the parent `update` :thinking:

_Originally posted by @susnux in https://github.com/nextcloud/forms/issues/2066#issuecomment-2056545922_

**Comment by kinimodmeyer** [comment]
I wonder if this needs to be part of 4.3?

Currently you can not have the forms app with NC 30. 
My feeling is, it would be good to have as soon as possible a form app for NC30 in the app-store.

**Comment by Chartman123** [comment]
This is not the one we're waiting for for 4.3. In the meantime you could use the currently released alpha on NC30. It just work as fine as 4.2 and already brings some new features.
