### ISSUE TITLE
View-Switch is transparent when view is not selected

### ISSUE THREAD

**Issue by Chartman123** [nextcloud/forms#2089]
I just realised that the view switch is transparent when you're not hovering the element or it is not selected:

![grafik](https://github.com/nextcloud/forms/assets/16020496/e9317ce0-9a9d-474d-a5f0-1bde82e00fe5)

**Comment by susnux** [comment]
Are you sure this is not an upstream issue?

**Comment by Chartman123** [comment]
Might be, yes. Had no time to investigate further...

**Comment by susnux** [comment]
Upstream fix: https://github.com/nextcloud-libraries/nextcloud-vue/pull/5509
