### ISSUE TITLE
Form input fields not working at screen width less than 512 px

### ISSUE THREAD

**Issue by bobbadshy** [nextcloud/forms#2139]
**Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!**

**Describe the bug**
Form input fields stop working at screen width less than 512 px. Text entry fields cannot be selected anymore, dropdown lists will not appear. This renders forms unusable on small screens, namely on smartphones.

**To Reproduce**
1. Create a test form with some text entry and dropdown answer lists.
2. Open the form in view mode on a smartphone (or, enable device mode in browser dev tools and lower horizontal screen size to below 512 px, tested in Chrome dev tools)   
3. Entry fields become unresponsive.

**Expected behavior**
Form entry fields should stay responsive and usable at small horizontal reolutions.

**Screenshots**
Working at 512xp:
![image](https://github.com/nextcloud/forms/assets/19748174/ddccdb49-f299-44d5-a734-a3141c08e1ed)

Not working at 511px:
![image](https://github.com/nextcloud/forms/assets/19748174/bd56c6d1-765b-47c7-ac37-b77a67f1317c)

**Systeminfo:**

[2024-05-04.md](https://github.com/nextcloud/forms/files/15209841/2024-05-04.md)

**Nextcloud (please complete the following information):**
- Nextcloud-Version: 29.0.0.19
- Forms-Version: 4.2.3

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Chrome
 - Version 123.0.6312.105

**Smartphone (please complete the following information):**
 - Device: Motorola g(7)
 - Browser Chrome

**Browser log**
```
Dev tools show no log output when clicking entry fields.
```

<details>
<summary>How to access your browser console (Click to expand)</summary>

# Chrome
- Press either CTRL + SHIFT + J to open the “console” tab of the Developer Tools.
- Alternative method:
    1. Press either CTRL + SHIFT + I or F12 to open the Developer Tools.
    2. Click the “console” tab.

# Safari
- Press CMD + ALT + I to open the Web Inspector.
- See Chrome’s step 2. (Chrome and Safari have pretty much identical dev tools.)

# IE9
1. Press F12 to open the developer tools.
2. Click the “console” tab.

# Firefox
- Press CTRL + SHIFT + K to open the Web console (COMMAND + SHIFT + K on Macs).
- or, if Firebug is installed (recommended):
    1. Press F12 to open Firebug.
    2. Click on the “console” tab.

# Opera
1. Press CTRL + SHIFT + I to open Dragonfly.
2. Click on the “console” tab.
</details>

**Additional context**

**Comment by bobbadshy** [comment]
While I am not primarily a JS or Vue developer, if you can point me to the source where this bug originates, I might even be able to propose a PR for it :).

**Comment by Chartman123** [comment]
@susnux Is this a bug in the vue lib?

**Comment by susnux** [comment]
I do not think so as it works on the styleguide

**Comment by tmlmt** [comment]
I posted a similar but different issue in #2145: I can't edit forms on my mobile device. There seems to be generally speaking quite some incompatibility with mobile devices? (editing, responsiveness, etc.)

**Comment by Chartman123** [comment]
@tmlmt So why do you think that your bug is different than this one here? It seems like this bug here is connected to the screen width (which in landscape mode is of course much bigger than in portrait mode).

**Comment by sven-verkstedt** [comment]
Awesome guys! Thx for the quick fix  :+1:  :)

**Comment by Chartman123** [comment]
@sven-verkstedt It will still take some time until the fix will be available... :)

**Comment by susnux** [comment]
Release is scheduled for today of the library so we might be able to release an app update next week :)
