### ISSUE TITLE
Form isn't shown on iOS <= 16.2

### ISSUE THREAD

**Issue by wilddom** [nextcloud/forms#2163]
**Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!**

**Describe the bug**
Form isn't shown on iOS<=16.2 but works fine on iOS starting with 16.4. Maybe related to #2032

**To Reproduce**
Open external form link.

**Screenshots**
![2024-05-12 22-06-18 High Res Screenshot](https://github.com/nextcloud/forms/assets/53584/ef7ffe33-5a26-4ca2-aaa5-24f9781cb7a8)

**Nextcloud (please complete the following information):**
- Nextcloud-Version: 29.0.0
- Forms-Version: 4.2.3

**Smartphone (please complete the following information):**
 - Device: iPhone (model doesn't matter)
 - OS: iOs<=16.2 (works on iOs 16.4)
 - Browser: safari

**Browser log**
Not available. After user reports tested in simulator of appetize.io

**Comment by Chartman123** [comment]
On lambdatest.com I could reproduce the issue with iOS 16.2, 16.4 seems to be working fine.

**Comment by Chartman123** [comment]
![grafik](https://github.com/nextcloud/forms/assets/16020496/53d866bf-4f5a-4d9c-bcb5-5f9e6a49205d)

**Comment by Chartman123** [comment]
@susnux I think it might be related to a user picker or something like that. Might this be coming from one of our dependencies? I can't find the regex at that position of *.mjs file: `\\B(?<![^a-z0-9_\\-@.'\\s])`

**Comment by susnux** [comment]
Upstream issue: https://github.com/nextcloud-libraries/nextcloud-vue/issues/5589

**Comment by arthurlockman** [comment]
May want to keep this open until my fix is released by the Vue library. It's targeted for 8.17.0.
