### ISSUE TITLE
Allow synchronous form answering and spreadsheet editing

### ISSUE THREAD

**Issue by artonge** [nextcloud/forms#2165]
**Nextcloud (please complete the following information):**
- Nextcloud-Version: [e.g. 19.0.0]
- Forms-Version: [e.g. 2.0.0-beta4]

**Is your feature request related to a problem? Please describe.**

When you open the spreadsheet of a form, the file gets locked, and it prevents people from answering the form.

**Describe the solution you'd like**

- Store the submitted data in the database
- Try to add the data in the spreadsheet later in a background job

@susnux

**Comment by Chartman123** [comment]
@artonge could you verify which error message you get, when the file is locked? There's another open issue, where we still don't know exactly where the error comes from (#2067)

**Comment by alexanderdd** [comment]
maybe related: https://github.com/nextcloud/forms/issues/1970

**Comment by alexanderdd** [comment]
I just had this problem in 29.0.6

Ideally, the data is not added after manual editing is finished, but live, during editing. Then you have live monitoring of answers coming in =)

**Comment by Chartman123** [comment]
> Ideally, the data is not added after manual editing is finished, but live, during editing. Then you have live monitoring of answers coming in =)

@alexanderdd I think that this can't be done easily as we don't know if someone uses an online office like Collabora/Nextcloud office or OnlyOffice. And even if they have the app installed the file could still be locked by someone working on it through a client locally.

**Comment by susnux** [comment]
> @alexanderdd I think that this can't be done easily as we don't know if someone uses an online office like Collabora/Nextcloud office or OnlyOffice. And even if they have the app installed the file could still be locked by someone working on it through a client locally.

If we do it async (background job) we can check for locking as those apps should lock the file for modifications.
So nothing we need to special handle, but just catch locked exceptions and postpone writing the results.
