### ISSUE TITLE
confirmation system

### ISSUE THREAD

**Issue by tatrapikao** [nextcloud/forms#2167]
**Is your feature request related to a problem? Please describe.**
The possibility to have my form get confirmed by one or multiple Accounts. For e.g.  getting my hollidays application approved by my senior before it goes to HR wich then also could confirm.

**Describe the solution you'd like**
- The possibility to define multiple Accounts that will be able to aknowledge a form.
- the possibility to define wich Accounts have to confirm to consider a form "complete" or "approved". 
- The possibility to assign the filled form to one of this accounts for confirmation whilst answering p.e. a popup when submitting
- A Notification and or Statuspage for my transmitted form where i can see the current state

**Comment by Chartman123** [comment]
I don't see this feature anytime soon if at all... This is not a use case for a form but for a workflow management system. Perhaps this can be achieved when #805 will be developed. But until I will close this as won't fix. Feel free to add your thoughts to the linked issue.
