### ISSUE TITLE
An error occurred while sending the questionnaire

### ISSUE THREAD

**Issue by lapor-kris** [nextcloud/forms#2186]
**Describe the bug**
If I try to send the questionnaire, I get the error: "An error occured while sending the questionnaire"

**To Reproduce**
1. Open a questionnaire
2. Fill it
3. Send it

**Expected behavior**
It should send the questionnaire and inform you, that the questionnaire is accepted.

**Screenshots**
![Zaslonska slika 2024-05-14 09-56-07](https://github.com/nextcloud/forms/assets/68855741/5d60d5e1-47e1-466f-8354-a27e7d05964c)

**Nextcloud (please complete the following information):**
- Nextcloud-Version: 28.0. 5
- Forms-Version: 4.2.4
**Desktop (please complete the following information):**
 - OS: Fedora 40
 - Browser: Firefox, Chromium
 - Version 126, 125

**Additional context**
The issue happened after one of the upgrades of the app. I was not aware of, because we didn't use it for couple of months. Last week we started to use it and we could not any more.

Any idea where to search for the problem? Thanks

**Comment by Chartman123** [comment]
Hi @lapor-kris 

without any logs we can't help you any further, as this might happen due to different things. So the first step should be to have a look at the browser console and see the exact error message related to the message.

Some guesses:
- You have a "required" field with radio buttons/checkboxes that aren't filled
- You have linked the form results to a file in a folder that is shared with the user who created the form
- ...

**Comment by lapor-kris** [comment]
Hi @Chartman123 

thanks for your fast reply and suggestions.

- I filled all of the fields;
- there is something with the sharing part. I unshared my questionnaire and it started to work. But my co-workers questionnaire just doesn't work. 
I'll have to dig a bit deeper here. I'll check it out and let you know what was wrong.

**Comment by Chartman123** [comment]
@lapor-kris thanks for the feedback. As I pointed out before, the best place to start would be the browser console in the developer tools of the browser.

**Comment by lapor-kris** [comment]
Sorry, I managed to get sick and could not operate the computer. I did get the information from our IT guy, that there is nothing related to Forms in Nextcloud log files.
New questionnaires work as expected. I have no idea what caused the issues. I will close the issue. Thanks

**Comment by lachmanfrantisek** [comment]
Hello,

I am hitting a similar issue and it looks like it's only when there are checkboxes or radio buttons..

It's only effective if the question is answered. (See the screenshots below.)

Here are the browser logs:
```
[ERROR] forms: Error while submitting the form 
Object { app: "forms", level: 0, error: {…} }
[NcSettingsSection-V9DkkSuI-DIvibN42.chunk.mjs:941:434](???/apps2/forms/js/NcSettingsSection-V9DkkSuI-DIvibN42.chunk.mjs)
log https://???/apps2/forms/js/NcSettingsSection-V9DkkSuI-DIvibN42.chunk.mjs:941
error https://???/apps2/forms/js/NcSettingsSection-V9DkkSuI-DIvibN42.chunk.mjs:941
onConfirmedSubmit https://???/apps2/forms/js/Submit-VdG59qwp.chunk.mjs:4836
onSubmit https://???/apps2/forms/js/Submit-VdG59qwp.chunk.mjs:4836
submit https://???/apps2/forms/js/Submit-VdG59qwp.chunk.mjs:4836
me https://???/apps2/forms/js/vendor-IHXb49lc.chunk.mjs:2
n https://???/apps2/forms/js/vendor-IHXb49lc.chunk.mjs:2
_wrapper https://???/apps2/forms/js/vendor-IHXb49lc.chunk.mjs:2
(Async: EventListener.handleEvent)
Qc https://???/apps2/forms/js/vendor-IHXb49lc.chunk.mjs:2
Zo https://???/apps2/forms/js/vendor-IHXb49lc.chunk.mjs:2
mn https://???/apps2/forms/js/vendor-IHXb49lc.chunk.mjs:2
y https://???/apps2/forms/js/vendor-IHXb49lc.chunk.mjs:2
u https://???/apps2/forms/js/vendor-IHXb49lc.chunk.mjs:2
_ https://???/apps2/forms/js/vendor-IHXb49lc.chunk.mjs:2
u https://???/apps2/forms/js/vendor-IHXb49lc.chunk.mjs:2
Uc https://???/apps2/forms/js/vendor-IHXb49lc.chunk.mjs:2
_update https://???/apps2/forms/js/vendor-IHXb49lc.chunk.mjs:2
r https://???/apps2/forms/js/vendor-IHXb49lc.chunk.mjs:2
get https://???/apps2/forms/js/vendor-IHXb49lc.chunk.mjs:2
e https://???/apps2/forms/js/vendor-IHXb49lc.chunk.mjs:2
ys https://???/apps2/forms/js/vendor-IHXb49lc.chunk.mjs:2
$mount https://???/apps2/forms/js/vendor-IHXb49lc.chunk.mjs:2
init https://???/apps2/forms/js/vendor-IHXb49lc.chunk.mjs:2
p https://???/apps2/forms/js/vendor-IHXb49lc.chunk.mjs:2
u https://???/apps2/forms/js/vendor-IHXb49lc.chunk.mjs:2
Uc https://???/apps2/forms/js/vendor-IHXb49lc.chunk.mjs:2
_update https://???/apps2/forms/js/vendor-IHXb49lc.chunk.mjs:2
r https://???/apps2/forms/js/vendor-IHXb49lc.chunk.mjs:2
get https://???/apps2/forms/js/vendor-IHXb49lc.chunk.mjs:2
e https://???/apps2/forms/js/vendor-IHXb49lc.chunk.mjs:2
ys https://???/apps2/forms/js/vendor-IHXb49lc.chunk.mjs:2
$mount https://???/apps2/forms/js/vendor-IHXb49lc.chunk.mjs:2
init https://???/apps2/forms/js/vendor-IHXb49lc.chunk.mjs:2
p https://???/apps2/forms/js/vendor-IHXb49lc.chunk.mjs:2
```


Here are the screenshots:
![Image](https://github.com/user-attachments/assets/d3871be2-75d7-4a98-9a78-dc24efe21a00)
![Image](https://github.com/user-attachments/assets/ffad1ef0-c2db-4d91-8849-a3170c9630c1)
![Image](https://github.com/user-attachments/assets/8fa07296-00f7-40ea-af4b-738c4b1d1672)
![Image](https://github.com/user-attachments/assets/dfb7641b-a249-4961-8be2-3c84eb2db8c7)

I can't see anything related in the server logs...

**Comment by Chartman123** [comment]
@lachmanfrantisek please create a new issue and fill the bug template. Thank you very much.
