### ISSUE TITLE
Cannot create forms with drop-down, checkbox, etc.

### ISSUE THREAD

**Issue by shgysk8zer0** [nextcloud/forms#219]
### Steps to reproduce
1. Create a new form
2. Add a question of types drop-down, etc.
3. Fill in an answer to list
4. Press enter

### Expected behaviour
Answer should be added as an option and new field for another answer should be created

### Actual behaviour
Nothing. Pressing enter does not do anything.

## Server configuration detail

**Operating system:** Linux 4.15.0-88-generic #88-Ubuntu SMP Tue Feb 11 20:11:34 UTC 2020 x86_64

**Webserver:** Apache/2.4.41 (Ubuntu) (fpm-fcgi)

**Database:** mysql 10.4.12

**PHP version:** 

7.2.24-0ubuntu0.18.04.3
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, sodium, session, standard, cgi-fcgi, mysqlnd, PDO, xml, apcu, apc, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, gmp, iconv, igbinary, imagick, intl, json, exif, msgpack, mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, memcached, Zend OPcache

**Nextcloud version:** 18.0.1 - 18.0.1.3

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from previous

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.4.0
 - activity: 2.11.0
 - admin_audit: 1.8.0
 - analytics: 2.0.0
 - announcementcenter: 3.7.0
 - appointments: 1.0.9
 - apporder: 0.9.0
 - audioplayer: 2.9.0
 - audioplayer_editor: 0.2.0
 - bookmarks: 2.3.4
 - bruteforcesettings: 1.5.0
 - calendar: 2.0.2
 - checksum: 0.4.4
 - circles: 0.18.3
 - cloud_federation_api: 1.1.0
 - cms_pico: 1.0.5
 - comments: 1.8.0
 - contacts: 3.2.0
 - cookbook: 0.5.7
 - cospend: 0.3.3
 - data_request: 1.5.0
 - dav: 1.14.0
 - deck: 0.8.0
 - dicomviewer: 1.2.1
 - documentserver_community: 0.1.5
 - event_update_notification: 1.0.1
 - external: 3.5.0
 - federatedfilesharing: 1.8.0
 - federation: 1.8.0
 - files: 1.13.1
 - files_accesscontrol: 1.8.1
 - files_automatedtagging: 1.8.0
 - files_external: 1.9.0
 - files_frommail: 0.3.0
 - files_markdown: 2.2.0
 - files_mindmap: 0.0.17
 - files_pdfviewer: 1.7.0
 - files_photospheres: 1.0.7
 - files_retention: 1.7.0
 - files_rightclick: 0.15.2
 - files_sharing: 1.10.1
 - files_trashbin: 1.8.0
 - files_versions: 1.11.0
 - files_videoplayer: 1.7.0
 - firstrunwizard: 2.7.0
 - forms: 1.1.0
 - gpxpod: 4.1.1
 - group_everyone: 0.1.4
 - groupfolders: 6.0.1
 - guests: 1.4.1
 - issuetemplate: 0.6.0
 - logreader: 2.3.0
 - lookup_server_connector: 1.6.0
 - mail: 1.1.3
 - maps: 0.1.5
 - metadata: 0.11.1
 - news: 14.1.3
 - nextcloud_announcements: 1.7.0
 - notes: 3.1.5
 - notifications: 2.6.0
 - oauth2: 1.6.0
 - onlyoffice: 4.1.4
 - password_policy: 1.8.0
 - passwords: 2020.3.1
 - phonetrack: 0.6.2
 - photos: 1.0.0
 - polls: 1.3.0
 - privacy: 1.2.0
 - provisioning_api: 1.8.0
 - quota_warning: 1.7.0
 - ransomware_protection: 1.6.0
 - recommendations: 0.6.0
 - registration: 0.4.7
 - serverinfo: 1.8.0
 - settings: 1.0.0
 - sharebymail: 1.8.0
 - sharingpath: 0.1.1
 - social: 0.2.101
 - sociallogin: 2.4.4
 - socialsharing_diaspora: 2.0.0
 - socialsharing_email: 2.0.0
 - socialsharing_facebook: 2.0.0
 - socialsharing_twitter: 2.0.0
 - spreed: 8.0.5
 - support: 1.1.0
 - survey_client: 1.6.0
 - systemtags: 1.8.0
 - talk_simple_poll: 1.1.0
 - tasks: 0.11.3
 - telephoneprovider: 1.0.3
 - terms_of_service: 1.4.0
 - text: 2.0.0
 - theming: 1.9.0
 - twofactor_admin: 2.0.0
 - twofactor_backupcodes: 1.7.0
 - twofactor_nextcloud_notification: 2.2.0
 - twofactor_totp: 4.1.2
 - twofactor_u2f: 5.0.2
 - twofactor_webauthn: 0.1.2
 - updatenotification: 1.8.0
 - viewer: 1.2.0
 - workflow_script: 1.3.1
 - workflowengine: 2.0.0
Disabled:
 - camerarawpreviews
 - encryption
 - files_readmemd
 - mood
 - qownnotesapi
 - user_ldap
 - workflow_pdf_converter

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "cloud.kernvalley.us"
    ],
    "htaccess.RewriteBase": "\/",
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "http:\/\/cloud.kernvalley.us",
    "dbtype": "mysql",
    "version": "18.0.1.3",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "mail_smtpmode": "smtp",
    "mail_smtpauthtype": "LOGIN",
    "memcache.local": "\\OC\\Memcache\\APCu",
    "logtimezone": "America\/Los_Angeles",
    "log_rotate_size": 2097152,
    "mail_smtpsecure": "tls",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauth": 1,
    "mail_smtpport": "587",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "maintenance": false,
    "theme": "",
    "loglevel": 2,
    "mail_sendmailmode": "smtp",
    "twofactor_enforced": "true",
    "twofactor_enforced_groups": [
        "admin"
    ],
    "twofactor_enforced_excluded_groups": [],
    "mysql.utf8mb4": true,
    "app_install_overwrite": [
        "forms",
        "dashboard",
        "dicomviewer",
        "social",
        "files_frommail"
    ],
    "has_rebuilt_cache": true,
    "updater.release.channel": "stable"
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

## Client configuration

**Browser:** Mozilla/5.0 (X11; Linux x86_64; rv:74.0) Gecko/20100101 Firefox/74.0

**Operating system:** Fedora 29

## Logs

<details><summary>Web server error log</summary>

```
NA
```
</details>

<details><summary>Nextcloud log</summary>

```
NA
```
</details>

<details><summary>Browser log</summary>

Content Security Policy: Directive ‘child-src’ has been deprecated. Please use directive ‘worker-src’ to control workers, or directive ‘frame-src’ to control frames respectively.
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). 2 utils.js:35:9
JQMIGRATE: Migrate is installed, version 1.4.1 jquery-migrate.min.js:2:551
This page uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”. addStylesClient.js:220:17
Handlebars is deprecated: please ship your own, this will be removed in Nextcloud 20 globals.js:66:15
Proxying an event bus of version 1.1.2 with 0.2.1 ProxyBus.js:65:14
Handlebars is deprecated: please ship your own, this will be removed in Nextcloud 20 globals.js:66:15
Source map error: Error: NetworkError when attempting to fetch resource.
Resource URL: https://cloud.kernvalley.us/apps/terms_of_service/js/terms_of_service_user.js?v=1d25814b-69
Source Map URL: terms_of_service_user.js.map

</details>

**Comment by jotoeri** [comment]
Seems like a duplicate of #166 ?

**Comment by shgysk8zer0** [comment]
It appears so. Somehow missed this when looking through open issues.

**Comment by jotoeri** [comment]
Should be solved now?

**Comment by shgysk8zer0** [comment]
Can't tell. After update, just redirects to `/`.

**Comment by jotoeri** [comment]
Hm. I could reproduce such a behaviour with Console giving me a 

> simplexml_load_file([...]/nextcloud/apps/forms/appinfo/info.xml):  failed to open stream: No such file or directory at  /var/www/html/nextcloud2/lib/private/App/InfoParser.php#65

This seems to be a underlying problem. `apt install --reinstall php-xml` helped for me.

**Comment by shgysk8zer0** [comment]
I'll give it a shot. Will open a separate issue with log if necessary. Know from networking tab that there are a lot of CSP errors but no details because they don't show in console for some reason.

**Comment by shgysk8zer0** [comment]
@jotoeri Cannot tell. Opened #228 

I think I'll close this issue as it's a duplicate.
