### ISSUE TITLE
Allow to add pictures in questionnaire form questions

### ISSUE THREAD

**Issue by zywz666** [nextcloud/forms#2196]
**Nextcloud (please complete the following information):**
- Nextcloud-Version: stable
- Forms-Version: stable

**Is your feature request related to a problem? Please describe.**
Wish the Nextcloud Form allows to include pictures in questions.

**Describe the solution you'd like**
Capability to upload a picture and embedded into the question.

**Describe alternatives you've considered**

**Additional context**

**Comment by Chartman123** [comment]
Duplicate of #1006
