### ISSUE TITLE
Layout issue with Upload type question.

### ISSUE THREAD

**Issue by TUCAOEVER** [nextcloud/forms#2253]
**Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!**

**Describe the bug**
Layout issue with upload type question.

**To Reproduce**
Add upload type question and check the layout

**Expected behavior**
There should be no blank space between the upload button and question

**Screenshots**
![image](https://github.com/nextcloud/forms/assets/43756134/d60cab54-cb02-463b-ad67-915054c2830a)

In editor view, there is spacing between the option and answer.

![image](https://github.com/nextcloud/forms/assets/43756134/02ac0a90-8954-48cd-a6f9-757777fde579)

In preview page, there is spacing under the upload file button, which may related to the layout issue.

**Nextcloud (please complete the following information):**

-   Nextcloud-Version: 29.0.3
-   Forms-Version: [[e.g. 2.0.0-beta4]](https://github.com/nextcloud/forms/issues/2220#issuecomment-2210256685)

**Desktop (please complete the following information):**

-   OS: Ubuntu
-   Browser: Edge
-   Version: 127.0.2651.61

**Comment by Koc** [comment]
@TUCAOEVER I've opened PR with fix for it, please check/suggest changes
