### ISSUE TITLE
Allow to disable "permit access to all logged in accounts"

### ISSUE THREAD

**Issue by mejo-** [nextcloud/forms#2266]
**Nextcloud (please complete the following information):**

-   Nextcloud-Version: 29.0.4
-   Forms-Version: 4.2.4

**Is your feature request related to a problem? Please describe.**
On shared instances with many users, the sharing setting "permit access to all logged in accounts" can be confusing and is missused. Some users don't understand that this effectively means to share the form with all users on this instance.

![grafik](https://github.com/user-attachments/assets/55035421-2466-4f6d-9bdf-b53dc405a0f1)

**Describe the solution you'd like**
I'd imagine a config option to disable this option either globally, or to all non-admin users.

**Describe alternatives you've considered**
Manually monitor globally shared forms and unshare them in the database.

**Comment by susnux** [comment]
This is already implemented as an admin setting:

![image](https://github.com/user-attachments/assets/6d6de40e-7a70-4739-a56d-61537d5490d3)

**Comment by mejo-** [comment]
Ouch, thanks @susnux. I should have looked closer.
