### ISSUE TITLE
New release v4.3.0 request

### ISSUE THREAD

**Issue by vermeeren** [nextcloud/forms#2281]
Hi hi,

Since the last release v4.2.4 many great features have been added that I would like to try out. As it has been a lot longer than usual for a new release to be made I figured I'd ask. I do notice in file https://github.com/nextcloud/forms/blob/main/CHANGELOG.en.md a planed new release for 2024-09-13, but considering it was added a few days ago in c69bff208f4d6e2894dcda91ed1d11f2d02431ca it might be a mistake intended for today 2024-08-13?

Would it be possible to have a new release soon-ish? Probably @Chartman123 considering recent releases made.

Many thanks!

**Comment by Chartman123** [comment]
No the date is intended, we're currently planning the new release before or with NC30. So just wait until it's ready ;)
