### ISSUE TITLE
Answers not shown in Forms-App but in Database 

### ISSUE THREAD

**Issue by NeverLoseHope777** [nextcloud/forms#2302]
**Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!**

**Describe the bug**
Hello everyone, I have the problem that my forms answers are no longer displayed. However, they are available in the “oc_forms_v2_answers” database. When I fill out the form again, the new answer is also written to the database, but it does not appear under “Answers”. It only says “100 % no answer”

Do you have any idea?

(same Problem with 4.3.0-alpha-6)

**To Reproduce**

1. create a form
2. answer a form
3. go to the answers

**Expected behavior**
All given answers are shown

**Screenshots**
![Bildschirmfoto vom 2024-08-25 14-02-20](https://github.com/user-attachments/assets/1adc52e0-43d1-42b7-b87b-280735250859)
![Bildschirmfoto vom 2024-08-25 14-02-45](https://github.com/user-attachments/assets/e87e8f3f-337e-4646-8b82-34c9a498d693)
![Bildschirmfoto vom 2024-08-25 14-03-00](https://github.com/user-attachments/assets/72f29aa8-5c3a-462b-aac7-1a1d0aed89be)

**Nextcloud (please complete the following information):**

-   Nextcloud-Version: 29.0.5
-   Forms-Version: 4.2.4

**Desktop (please complete the following information):**

-   OS: Linux Mint
-   Browser Libre Wolf / Firefox / Brave
-   Version 129.0.1-1

**Comment by Chartman123** [comment]
Hi @NeverLoseHope777

Could you please check if there are any problems shown in your browser console?

**Comment by NeverLoseHope777** [comment]
> Hi @NeverLoseHope777
> 
> Could you please check if there are any problems shown in your browser console?

Yes, thank you :)

![Bildschirmfoto vom 2024-08-25 16-00-36](https://github.com/user-attachments/assets/76feca1d-4dda-4aa0-be51-d2337c9f2d4e)

**Comment by Chartman123** [comment]
Ok, this error is unrelated to your problem...

Can you please tell us more about your environment? (DB, Web server, PHP version) Do you use any script blockers / add-ons that might interfere with the application?

**Comment by NeverLoseHope777** [comment]
A few days ago, everything was still running normally. I'm not sure if it's related to the update from Nextcloud 29.0.4 to 29.0.5. We use web hosting with SSH access. I do not use any blockers or addons. I tried it in different clean browsers.

OS: Linux 4.18.0-553.8.1.lve.el8.x86_64 x86_64
Processor: AMD EPYC 7282 16-Core Processor (32 threads)
Webserver: LiteSpeed V8.1 Cloudlinux 1.3 
MySQL: 10.6.18
PHP: 8.2.22
   Memory limit: 1 GB
   Maximum execution time: 3600
   Maximum upload size: 64 MB
   OPcache revalidation frequency: 2
   Extensions: Core, date, libxml, openssl, pcre, sqlite3, zlib, bz2, calendar, ctype, curl, hash, filter, ftp, gettext, json, iconv, SPL, pcntl, random, readline, Reflection, session, standard, mbstring, shmop, SimpleXML, tokenizer, xml, litespeed, apcu, bcmath, dba, dom, enchant, fileinfo, gd, gmp, igbinary, imagick, imap, intl, ldap, exif, memcache, PDO, mysqlnd, mysqli, odbc, pdo_mysql, PDO_ODBC, pdo_pgsql, pdo_sqlite, pgsql, Phar, posix, pspell, snmp, soap, sockets, sodium, sysvmsg, sysvsem, sysvshm, tidy, xmlreader, xmlrpc, xmlwriter, xsl, zip, Zend OPcache

**Comment by NeverLoseHope777** [comment]
I don't know if this is helpful, but today I have these errors in protocol.

![Bildschirmfoto vom 2024-08-27 07-50-28](https://github.com/user-attachments/assets/e085acd1-496f-4e22-ad36-d43ee149c595)

**Comment by susnux** [comment]
The first 3 could be related, how did you update forms? Do you see any file integrity issues in the "security warnings" section of the admin settings?

**Comment by TannerNelson16** [comment]
Having the same issue

**Comment by Chartman123** [comment]
@TannerNelson16 could you please also have a look at your browser console if there are any warnings/errors?

**Comment by TannerNelson16** [comment]
Is this what you're referring to?

![Screenshot from 2024-09-09 08-12-24](https://github.com/user-attachments/assets/f4879879-049b-4b91-895d-7f2058e50cf0)

**Comment by Chartman123** [comment]
I'm still clueless what could be the reason for this specific problem. 

@TannerNelson16 @NeverLoseHope777:
- Do you use any additional plugins in your browsers? Can you reproduce the issue in a private tab without any plugins active?
- Do you see the correct answers if you have a look at the submissions view (Antworten) and not the summary view (Zusammenfassung)?
- Does this issue affect all users with result permissions on your servers?
- Does this affect all of your forms?

**Comment by TannerNelson16** [comment]
No plugins. I do have Adguard on the network. Not sure if that would have an affect, but I've disabled filtering and the same thing happens. Also tried in a different browser with the same result.

I can't see the answers either way, and it gives errors when I try to generate a csv. The only way I can see them is throught the sql database

It affects all users and forms.

**Comment by Chartman123** [comment]
Ok, then it has probably got something to do with either your installation of the Forms app, your NC Server or the web server.

Could you please create a backup and then try to uninstall the Forms app, remove all remnants of Forms in the apps directory of your Nextcloud inside the web server and then re-install the app?

**Comment by Chartman123** [comment]
@TannerNelson16 @NeverLoseHope777 Any news? Did you test a new and clean install of Forms?

**Comment by NeverLoseHope777** [comment]
Hello @Chartman123, uninstalling, removing and new-installation didn't solve my problem. But with new Nextcloud-Version (now 29.0.8) everything works fine again :)
