### ISSUE TITLE
"Other" option doesn't work with radio buttons

### ISSUE THREAD

**Issue by ischiros** [nextcloud/forms#2307]
**Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!**

**Describe the bug**

If I add a radio button question to my form and check the option "Allow "other"", the "other" option is hardly usable.
If a user checks the "other" option, it is not selected. The only possibility to select it is to click in the text field and start typing text. Until one starts typing, the option is not selected. It is very much counter-intuitive.

**To Reproduce**

1. Create a form.
2. Add a "Radio button" question.
3. Activate the "Allow "other"" option in the question.
4. Fill the form, try to select the "other" option -> impossible

**Expected behavior**

On step 4, a click on the "other" option should select it.

**Nextcloud :**

-   Nextcloud-Version: 29.0.3
-   Forms-Version: 4.2.4

**Desktop :**

-   OS: MacOS 12.7.6
-   Browser Firefox 129.0.2

Other people had the same problem with Linux & Windows

**Browser log**

```
TypeError: e.startsWith is not a function
```

**Comment by Chartman123** [comment]
I can confirm it... Strange that nobody noticed it until now...

**Comment by Chartman123** [comment]
@susnux it seems to come from here https://github.com/nextcloud/forms/blob/75192da27e4b0b39b8f19851d6e17a6a9cd8f319/src/components/Questions/QuestionMultiple.vue#L316 and is still present in current main
