### ISSUE TITLE
Forms app keeps trying to load infinitely when user doesn't have access to internal link

### ISSUE THREAD

**Issue by akhil1508** [nextcloud/forms#2308]
**Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!**

**Describe the bug**
- Infinite loading glitch with internal share link when correct permissions are not configured

**To Reproduce**
- Create a new form
- Go to sharing options
- Make sure "Permit all users" is turned off
- Copy internal link
- Login with another user
- Paste copied link

- Loads forever with many requests to backend

**Expected behavior**
- Go back to the forms app main page with a single "Form not found" message after trying once

**Screenshots**
 
![image](https://github.com/user-attachments/assets/ae7e387e-5a5a-4a4e-81a3-98b08d6e3d11)
![image](https://github.com/user-attachments/assets/854fa86b-ee2d-4e99-96a5-f91f7ac43c9d)

**Nextcloud (please complete the following information):**

-   Nextcloud-Version: 28.0.9
-   Forms-Version: 4.2.4

**Desktop (please complete the following information):**

-   OS: [e.g. iOS]
-   Browser [e.g. chrome, safari]:  Firefox
-   Version [e.g. 22]: 128

**Comment by Chartman123** [comment]
Already fixed in #2268
