### ISSUE TITLE
Hardcoded strings

### ISSUE THREAD

**Issue by osworx** [nextcloud/forms#233]
https://github.com/nextcloud/forms/blob/120ac948476c30a6f9f318a53c678b163c63b0ec/src/views/Create.vue#L58
https://github.com/nextcloud/forms/blob/120ac948476c30a6f9f318a53c678b163c63b0ec/src/views/Create.vue#L61
https://github.com/nextcloud/forms/blob/120ac948476c30a6f9f318a53c678b163c63b0ec/src/views/Create.vue#L286
Maybe could be changed to translateable variable?

**Comment by skjnldsv** [comment]
Fixed with upcomming 2.0
