### ISSUE TITLE
Nextcloud 30 support

### ISSUE THREAD

**Issue by micah** [nextcloud/forms#2334]
**Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!**

**Describe the bug**

According to the NC app store:
```
    This app cannot be installed because the following dependencies are not fulfilled:
    Server version 29 or lower is required. 
```

Is there a roadmap for getting 30 support?

**To Reproduce**

1. Click on Apps
3. Click on Disabled Apps
4. Click on Forms
5. See error

**Nextcloud (please complete the following information):**

-   Nextcloud-Version: 30
-   Forms-Version: 4.2.4

**Comment by Chartman123** [comment]
This is not a "bug", it is clearly communicated before the upgrade to NC30 that Forms currently doesn't support it yet. So if you rely on this app you shouldn't have upgraded in the first place.

On the other hand, we already have released an alpha release that you can install in NC30 and that should just work as fine as 4.2.4 and already brings some new features.

The final 4.3 release is already on its way, but as always no ETA.

**Comment by micah** [comment]
Is there a milestone, or similar that one can follow to understand how far along the 4.3 release is?

**Comment by Chartman123** [comment]
Yes, just the regular Github milestones: https://github.com/nextcloud/forms/milestone/22 :)
