### ISSUE TITLE
Cannot save new Form, bcause: All questions need answers!

### ISSUE THREAD

**Issue by osworx** [nextcloud/forms#234]
https://github.com/nextcloud/forms/blob/120ac948476c30a6f9f318a53c678b163c63b0ec/src/views/Create.vue#L480

Something goes wrong with the validation.
Using latest NC 18.0.2. and Forms (installed via backend), I am not able to save a new created form.
Get always - no matter which type of question and answer, the same message: **All questions need answers!**

**Comment by Tazzios** [comment]
It would also be nice if we can choose if the answer needs be answered or that is is an optional question.

**Comment by stefan123t** [comment]
Tazzios your feature is described in #135. Dunno if that is related to this Bug in 18.0.2 or can be implemented together.

**Comment by Tazzios** [comment]
@stefan123t ok great!
 i did a search for 'optional' instead of 'mandatory' that`s why i didn`t find the already existing issue.

**Comment by jotoeri** [comment]
Ok, so to solve the initial question:

@osworx:
- Did you press enter to add answers on questions?
- If it still doesn't work: Can you provide some more information on your setup, on the NC-Log, maybe even a browser log? Cause in general case, the app works, even if a bit special to handle.
- Please use the [Issue-Template](https://github.com/nextcloud/forms/blob/master/ISSUE_TEMPLATE.md) to open issues & provide Information.

**Comment by Tazzios** [comment]
I thought i had the same problem but i indeed forgot to hit ENTER.

**Comment by osworx** [comment]
> 
> 
> Ok, so to solve the initial question:
> 
> @osworx:
> 
>     * Did you press enter to add answers on questions?
> 
>     * If it still doesn't work: Can you provide some more information on your setup, on the NC-Log, maybe even a browser log? Cause in general case, the app works, even if a bit special to handle.
> 
>     * Please use the [Issue-Template](https://github.com/nextcloud/forms/blob/master/ISSUE_TEMPLATE.md) to open issues & provide Information.

Sorry, cannot. Reason: do not use NC curently anymore (maybe later once again).
The project had to start very quickly (because of the current Covid-19 situation) and was for a Primary School project.
But those children (and teacher) cannot wait such a long time to use that system.

And yes, I did hit the ENTER button (or in this case clicked via mouse).

**Comment by jotoeri** [comment]
Ok, so without information, we will not get further here. On many systems this works flawless.
