### ISSUE TITLE
Primary index name "id" for table "oc_forms_v2_uploaded_files" collides with the constraint on table "oc_e2e_encryption_lock".

### ISSUE THREAD

**Issue by RainerEmrich** [nextcloud/forms#2346]
**Describe the bug**
Updating tthe Forms app to Version 4.3.0 gives the error:
{"reqId":"6xRpvk0LJJZu7sdEXy2W","level":2,"time":"2024-10-05T04:50:55+00:00","remoteAddr":"","user":"--","app":"forms","method":"","url":"--","message":"Primary index name \"id\" for table \"oc_forms_v2_uploaded_files\" collides with the constraint on table \"oc_e2e_encryption_lock\".","userAgent":"--","version":"29.0.7.1","data":{"app":"forms"}}

**To Reproduce**

Updating Forms to version 4.3.0

**Expected behavior**
There should be no database index collision.

**Nextcloud (please complete the following information):**

-   Nextcloud-Version: 29.0.7.1
-   Forms-Version: 4.3.0

**Comment by Chartman123** [comment]
@RainerEmrich do you have the e2e app installed? I saw that there are several changes in the DB table schema for their app related to the indexes. Also there's this open issue I linked. So I'm unsure, if we can do anything here. The new table is created just like all our other tables.

**Comment by RainerEmrich** [comment]
> [@RainerEmrich](https://github.com/RainerEmrich) do you have the e2e app installed and updated to the latest version? I saw that there are several changes in the DB table schema for their app related to the indexes. Also there's this open issue I linked. So I'm unsure, if we can do anything here. The new table is created just like all our other tables.

No, I don't have any end to end encryption app installed.

**Comment by Chartman123** [comment]
Ok, then this is the problem... you had it installed in the past and there are some leftovers in your database that haven't been upgraded to the latest schema version. Please try to remove all tables starting with `oc_e2e` (probably only `oc_e2e_encryption_lock`) and then try to do the Forms update again :)

**Comment by RainerEmrich** [comment]
> Ok, then this is the problem... you had it installed in the past and there are some leftovers in your database that haven't been upgraded to the latest schema version. Please try to remove all tables starting with `oc_e2e` (probably only `oc_e2e_encryption_lock`) and then try to do the Forms update again :)

I only have oc_e2e_encryption_lock table in the database. So i will remove it and try again.

**Comment by RainerEmrich** [comment]
Short summary. I don't know why, but I had the oc_e2e_encryption_lock table in some of my nextcloud instances, but not in all.
I don't remember that I installed an e2e encryption app at any time.
I removed the table oc_e2e_encryption_lock from the database and reinstalled the forms app. For now every thing looks fine.

**Comment by Chartman123** [comment]
@RainerEmrich thanks for the feedback and glad you could fix your issue 👍🏻
