### ISSUE TITLE
Missing translations

### ISSUE THREAD

**Issue by jgrocha** [nextcloud/forms#2379]
### Missing translations in forms

The app supports translation but fails in two small cases.

**To Reproduce**

1) Create a form, in a language different from English (I used Portuguese in the test)
2) The "Other" option is called "Outra" when developing the form, which is ok (the string is translated)
3) The "Other" option is not translated into the generated form when presented to the users.
4) The "Enter your answer" string is not translated when presented to the users.

**Expected behavior**

The strings `Other` and `Enter your answer` should be translated.

**Screenshots**

![Image](https://github.com/user-attachments/assets/c7b16630-9317-4338-92c3-b9ac522d1969)

**Nextcloud (please complete the following information):**

-   Nextcloud-Version: 30.0.1
-   Forms-Version: 4.3.2

**Comment by Chartman123** [comment]
@rakekniven could you please check if there are some translations missing here? I had a quick look at our code and we use the t() function for the strings.

**Comment by Chartman123** [comment]
I checked the translation files... the translated strings are only included in pt_BR but not in pt_PT. So no bug, but just missing translations. @jgrocha you can help fixing this by joining the translators on Transifex :)

**Comment by jgrocha** [comment]
> [@jgrocha](https://github.com/jgrocha) As starting point please see https://help.nextcloud.com/t/translation-knowledge-valid-for-the-entire-nextcloud-project-wiki/51550 We welcome everybody.

The translation is done in Transifex. Thank you, @rakekniven and @Chartman123, for reviewing this issue and suggesting a solution.
