### ISSUE TITLE
Missing common image mimetypes from file upload restricted for image type

### ISSUE THREAD

**Issue by gyuris** [nextcloud/forms#2399]
**Describe the bug**
Currently (Forms 4.3.2) for file upload=image only allows these mimetypes:
application/coreldraw
application/illustrator
application/postscript
application/x-dcraw
application/x-gimp
application/x-photoshop

**To Reproduce**

1. Go to Forms
2. Create a new form
3. Add a field type file
4. Restrict allowed types to image
5. See it in action: you can not add a simple `jpg` file

**Expected behavior**
I expect for example to be allowed these types:
image/apng
image/gif
image/jpeg
image/png
image/svg+xml

**Nextcloud (please complete the following information):**

-   Nextcloud-Version: Nextcloud Hub 8 (29.0.8)
-   Forms-Version: Forms 4.3.2

**Desktop (please complete the following information):**

-   OS: Windows
-   Browser: Chrome and Firefox
-   Version: Ch-130, F-132

**Comment by Chartman123** [comment]
@Koc could you please have a look at this issue?

**Comment by Koc** [comment]
Indeed, not everything clear here. I've opened draft PR to fix that, see #2401
