### ISSUE TITLE
label "Responses are anonymous" is wrong

### ISSUE THREAD

**Issue by tolot27** [nextcloud/forms#2407]
Below the title and description of a form a small gray text is shown: "Responses are anonymous."

This is sometimes incorrect if the form asks for personal data. How can this text adjusted or disabled at all?

**Comment by Chartman123** [comment]
This text is not about the questions asked in your form, but about the fact that we do not store the username of a logged in user. That's also why this text can not be changed.

**Comment by tolot27** [comment]
> This text is not about the questions asked in your form, but about the fact that we do not store the username of a logged in user. That's also why this text can not be changed.

Yes, I know what the rationale is behind. From the technical point of view, the message is absolutely okay. But from the perspective of the person who fills the form it is quite irritating reading this message and entering personal data below (if it is asked). And in those cases, the message is simply incorrect and should not be shown.

Currently, there is no way to adapt this message. Instead of "Responses are anonymous" I would write "No other data will be saved other than what is entered."

IMHO, the message is not necessary at all because if the form is set to anonymous with a public link, it is quite obvious that no Nextcloud user data is availabe (except for those users which are logged in at this instance).

**Comment by Chartman123** [comment]
We had this discussion already a few times: see #804, #1623, #1673 and probably some more. We're currently not planning to change this text.
