### ISSUE TITLE
Submission notification email needs a plural form as multiple users can be present in {user}

### ISSUE THREAD

**Issue by Mer0me** [nextcloud/forms#2434]
**Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!**

**Describe the bug**
When multiples users have answered to a form since the last notification email, we receive a mail notification saying "user1 and user2 answered your form". In french translation of this sentence, there is a grammar error. This cannot be fixed in transifex because no plural form is available for this sentence.

**To Reproduce**

1. User1 fills a form
2. User2 fills the same form
3. Form owner receives a notification mail with grammar error.

**Expected behavior**
Notification mails should be correct grammatically (in french !).

**Screenshots**
![Image](https://github.com/user-attachments/assets/95e20ca0-8365-4245-8fe7-3e04adec6f52)
 "a répondu" should be "ont répondu"

**Nextcloud (please complete the following information):**

-   Nextcloud-Version:  30.0.2
-   Forms-Version: 4.3.4

Source ref : https://github.com/nextcloud/forms/blob/f5a51fe8901e7736575aee0cc596587447c5eee5/lib/Activity/Provider.php#L105

cc @rakekniven

**Comment by Chartman123** [comment]
How about switching this string to passive? 'Your form {formTitle} was answered by {user}'
