### ISSUE TITLE
Sharing the form by email does not work

### ISSUE THREAD

**Issue by Azgar1998** [nextcloud/forms#2446]
**Describe the bug**
When I enter an email address, I don't get the option to send it by email, like sharing a file or folder.

**To Reproduce**

1. Open the "Forms" application
2. Create a form
3. Click on "share" at the top right
4. Enter an email address

**Expected behavior**
the ability to share a form by email

**Screenshots**
![Image](https://github.com/user-attachments/assets/615e0d67-7aa8-4542-9230-34f457e4483a)

Example for share file or folder:

![Image](https://github.com/user-attachments/assets/c4444ea0-9fd9-40a3-8af7-e227118fc38e)

**Nextcloud (please complete the following information):**

- Nextcloud-Version: 29.0.6 (and tested on 30.0.2)
- Forms-Version: 4.3.4

**Desktop (please complete the following information):**

- OS: Windows 11
- Browser Edge and firefox
- Version lastest

**Comment by Chartman123** [comment]
@Azgar1998 this is not a bug, as this feature currently simpy doesn't exist. You can only share with users, groups and teams. For external users you have to create a public link share and distribute it yourself.

The corresponding feature request is tracked in #559
