### ISSUE TITLE
Voting layout 2

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/forms#250]
## Goals

The concept is to have a single component for editing and voting.
That way we have a direct preview of the final form. 
Currently the voting part is standalone jQuery. Let's move to a proper standalone app (different entry point, same shared component for edit/vote)

<details>
<summary>Google form examples</summary>

|<img width="1280" alt="téléchargement" src="https://user-images.githubusercontent.com/14975046/77677566-2bdb7d80-6f90-11ea-8613-a9342d49019f.png">|<img width="1280" alt="téléchargement" src="https://user-images.githubusercontent.com/14975046/77677568-2c741400-6f90-11ea-82c5-03017fc6e134.png">|
|:---------:|:------:|
|<img width="1280" alt="téléchargement" src="https://user-images.githubusercontent.com/14975046/77677571-2d0caa80-6f90-11ea-9b5a-c45861d5c644.png">|<img width="925" alt="téléchargement (3)" src="https://user-images.githubusercontent.com/14975046/77677574-2da54100-6f90-11ea-9344-01660fc90ed8.png">|

</details>

<details>
<summary>Typeform form examples</summary>

|<img width="1280" alt="téléchargement" src="https://user-images.githubusercontent.com/14975046/77678159-0ac75c80-6f91-11ea-8fbc-bc68cd42eed2.png">|<img width="1280" alt="téléchargement" src="https://user-images.githubusercontent.com/14975046/77678313-4104dc00-6f91-11ea-976c-ba65079e15f8.png">|
|:---------:|:------:|
|<img width="1280" alt="téléchargement" src="https://user-images.githubusercontent.com/14975046/77678379-5bd75080-6f91-11ea-9a42-6451b0999509.png">|<img width="925" alt="téléchargement (3)" src="https://user-images.githubusercontent.com/14975046/77678497-888b6800-6f91-11ea-8d59-c730377fc741.gif">|

</details>

### Layout / UX
- [x] Interface doesn’t reflect how the form will look for people afterwards
- [x] Too many different font-sizes
- [x] Misalignment of answers
- [x] No way to reorder answers or put things inbetween
- [x] Replies are not autosaved
- [x] No way to submit/confirm answer with mouse (needs to press enter)
- [x] No way to set questions as mandatory or not

### Answer types
- [x]  Icons for answer types
- [ ]  No way to change the answer type
- [x]  "Radio button" → Multiple choice
- [x]  "Checkboxes" → Checkboxes
- [x]  "Short response" → Short answer
- [x]  "Long response" → Long text
- [x]  "Drop Down" is the same as Single choice?

**Comment by jancborchardt** [comment]
Just from a brief look at the Google Forms screenshots vs Typeform:
Typeform is suuuper confusing, Google Forms looks straightforward and simple

I would definitely go along with Google Forms only for now, that’s also what @rullzer said when we had the last meeting if I remember correctly. Then when we have the initial steps done, we can still check what we do from that base.

**Comment by skjnldsv** [comment]
> * [ ]  No way to set questions as mandatory or not

@jotoeri this would be an important point to add I think :)

**Comment by jotoeri** [comment]
Yes, that's true, i started on this already yesterday, when first looking for the reorder-thing. ^^ With the API done it's a quite small change. See PR... ;)

**Comment by jotoeri** [comment]
@skjnldsv How about taking the last point 'No way to change the answer type'  as separate issue for V2.1. so closing this one?

**Comment by skjnldsv** [comment]
Yes :+1:

**Comment by ei8fdb** [comment]
Agreed with @jancborchardt. A way to "preview" would be very helpful.

That is the least I would need when creating a form - being able to answer the question: how does it look for the user.

**Comment by skjnldsv** [comment]
> Agreed with @jancborchardt. A way to "preview" would be very helpful.
> 
> That is the least I would need when creating a form - being able to answer the question: how does it look for the user.

You can already do that with v2.
Btw @ei8fdb thanks for your recent comments! Remember to use the github reactions if you just approve the issue discussed though, otherwise it creates a lot of notifications if you just want to say that you agree with what is being said :wink: 
Thanks for the support! :hugs:

**Comment by jotoeri** [comment]
> > @skjnldsv How about taking the last point 'No way to change the answer type' as separate issue for V2.1. so closing this one?
> 
> Yes 👍

Closing this in favor of #352
