### ISSUE TITLE
No translation

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/forms#255]
**Which Forms version are you running?** (see apps page)
1.1.1

**Nextcloud/ownCloud version:** (see Nextcloud admin page)
18.0.3

### Steps to reproduce
1. Create a new form

### Actual behaviour
No description translation:

- Help
- Answer Type
- Select
- Radio Buttons
- Checkboxes
- Short Response
- Long Response
- Drop Down

They also do not appear in Transefix.

![obraz](https://user-images.githubusercontent.com/47037905/77769769-90581480-7044-11ea-9dba-26d90ff56b2e.png)

### Expected behaviour
Translated descriptions.

**Comment by skjnldsv** [comment]
Fixed with upcomming 2.0
