### ISSUE TITLE
Convert Share-Storage

### ISSUE THREAD

**Issue by jotoeri** [nextcloud/forms#272]
Convert the Shared-Storage from strange string to JSON-Column on Db.

**Comment by jotoeri** [comment]
@skjnldsv What do you think would be a good object here? Something like this?
```
$access = [
    'type' => |public|registered|selected|;
    'users' => [userId, userId, userId]
    'groups' => [groupId, groupId, groupId]
];
```

**Comment by skjnldsv** [comment]
Sure! Looks simple enough to me :)

**Comment by jotoeri** [comment]
When rewriting the sidebar, would this include to rewrite the shareDiv, too? Is it worth to make the shareDiv usable at the moment or would you change it anyways?

**Comment by skjnldsv** [comment]
Ideally shareDiv would be replaced with the same design of the recent Sharing sidebar revamp on server :)

**Comment by jotoeri** [comment]
Ok. So i'll leave that out here.
