### ISSUE TITLE
New Result-View (incl. show timestamp)

### ISSUE THREAD

**Issue by 4y55** [nextcloud/forms#273]
The option to display the date / time the user submitted the form is extremely useful. Currently I only have the answer, I don't know when it was filled out.
Necessary option for a frequent filling form.

It is a form of control of reports / forms, along with the idea of generating PDF or write form responses directly to documents within the cloud.

Great job with the app, congratulations and I hope it always gets better.

**Comment by jotoeri** [comment]
@skjnldsv New Result-View, somehow sorted by submission also for V2?

**Comment by skjnldsv** [comment]
Sure! We already store the date ?

**Comment by jotoeri** [comment]
On current master, yes.
