### ISSUE TITLE
Server Internal Err0r when open the public link

### ISSUE THREAD

**Issue by megaherox** [nextcloud/forms#276]
Hi
I tried forms on 3 diferent Nextclouds. Wenn i add a form with answer type short.
And im trying to open the form form no nextcloud account with the puplic link following errro comes.
On the Website internal server error.
On the log : 

[index] Error: Exception: Argument 2 passed to OCA\Forms\Db\NotificationMapper::findByUserAndForm() must be of the type string, null given, called in /var/www/html/forum/nextcloud/apps/forms/lib/Controller/PageController.php on line 277 at <<closure>>

0. /var/www/html/forum/nextcloud/lib/private/AppFramework/App.php line 125
   OC\AppFramework\Http\Dispatcher->dispatch(OCA\Forms\Controller\PageController {}, "gotoForm")
1. /var/www/html/forum/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
   OC\AppFramework\App::main("OCA\\Forms\\Controller\\PageController", "gotoForm", OC\AppFramework\ ... {}, {hash: "rWSRQlky ... "})
2. <<closure>>
   OC\AppFramework\Routing\RouteActionHandler->__invoke({hash: "rWSRQlky ... "})
3. /var/www/html/forum/nextcloud/lib/private/Route/Router.php line 299
   call_user_func(OC\AppFramework\ ... {}, {hash: "rWSRQlky ... "})
4. /var/www/html/forum/nextcloud/lib/base.php line 1008
   OC\Route\Router->match("/apps/forms/form/rWSRQlkyjGzS57Tb")
5. /var/www/html/forum/nextcloud/index.php line 38
   OC::handleRequest()

GET /index.php/apps/forms/form/rWSRQlkyjGzS57Tb
from 192.168.0.2 at 2020-04-09T20:03:55+00:00

**Comment by jotoeri** [comment]
Hey @megaherox,

thank you for reporting this. The bug itself is solved and is just waiting for a release. Just as we are on a bigger rework it can still take a bit of time...

Greets,
Jonas
