### ISSUE TITLE
Public link  not working

### ISSUE THREAD

**Issue by dawidol** [nextcloud/forms#291]
**Which Forms version are you running?** (see apps page)
1.1.1
**Nextcloud or ownCloud?:**
Nextcloud
**Nextcloud/ownCloud version:** (see Nextcloud admin page)
18.0.2
### Steps to reproduce
1. Create a form, set as public
2. Complete the form
3. open the link in a  browser where your are not login on NC instance. 

### Actual behaviour
Error interno del servidor
El servidor no pudo completar tu solicitud.
Si esto vuelve a suceder, por favor envia los detalles tecnicos siguientes al adminsitrador del sistema.
Puedes consultar más detalles en la bitácora del servidor.

Detalles técnicos
Dirección Remota: XX.XX.XX.XX
ID de solicitud: MhKx99S74lWaJjuMoPAN

### Expected behaviour
Be able to see and fill the public form
![Captura de pantalla de 2020-04-17 11-46-45](https://user-images.githubusercontent.com/10899212/79598484-455c7a80-80a1-11ea-8de9-61506ede4e61.png)

**Comment by dwaxweiler** [comment]
Could this be a duplicate of #178?

**Comment by dawidol** [comment]
Looks like is probably the same, but i dont find the file PageController.php that is mentioned on the fix.

**Comment by dwaxweiler** [comment]
What does your log say?

**Comment by dawidol** [comment]
On the NC admin Panel.
Error | index | Exception: Argument  2 passed to OCA\Forms\Db\NotificationMapper::findByUserAndForm() must  be of the type string, null given, called in  /var/www/nextcloud/apps/forms/lib/Controller/PageController.php on line  277
-- | -- | --

**Comment by dawidol** [comment]
So with the log in the admin panel i found the location to apply de patch on [#178](https://github.com/nextcloud/forms/issues/178) 
after that i did:
cd  /var/www/nextcloud/apps/forms/lib/Controller/
cp PageController.php PageController.backup.php
wget https://github.com/nextcloud/forms/files/4091661/PageController_notifMapper_patch.txt
patch <  PageController_notifMapper_patch.txt

That fix the problem, thank you @dwaxweiler

**Comment by dwaxweiler** [comment]
I am happy to hear that! I hope a new release with this bugfix will follow soon too. :)
