### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by ThomasKujawa** [nextcloud/forms#294]
### Steps to reproduce
https://familienfreun.de/index.php/apps/forms/form/M61SCtSeoxu7p5QD

### Expected behaviour
public - fillable form

### Actual behaviour
Der Server konnte die Anfrage nicht fertig stellen.

Sollte dies erneut auftreten, senden Sie bitte die nachfolgenden technischen Einzelheiten an Ihren Server-Administrator.

Weitere Details können im Server-Protokoll gefunden werden.

Technische Details
Entfernte Adresse: 95.91.27.135
Anfragekennung: Xp7S@8RTgBlLxhJR3XZwFwAAAAE

## Server configuration detail

**Operating system:** Linux 4.15.0-96-generic #97~16.04.1-Ubuntu SMP Wed Apr 1 03:03:31 UTC 2020 x86_64

**Webserver:** Apache (fpm-fcgi)

**Database:** mysql 5.7.28

**PHP version:** 

7.4.2
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, sodium, cgi-fcgi, propro, raphf, iconv, mysqlnd, PDO, xml, bcmath, bz2, calendar, ctype, curl, dba, dom, mbstring, fileinfo, ftp, gd, gender, gettext, gmp, htscanner, http, imagick, imap, intl, json, ldap, mailparse, exif, mongodb, mysqli, OAuth, odbc, pdo_dblib, PDO_Firebird, pdo_mysql, PDO_ODBC, pdo_pgsql, pdo_sqlite, pgsql, Phar, posix, pspell, shmop, SimpleXML, soap, SourceGuardian, sqlite3, sysvsem, sysvshm, tidy, tokenizer, xmlreader, xmlwriter, xsl, zip, Zend OPcache

**Nextcloud version:** 18.0.2 - 18.0.2.2

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Array
(
    [news] => Array
        (
            [INVALID_HASH] => Array
                (
                    [lib/Explore/feeds/feeds.de.json] => Array
                        (
                            [expected] => 2b993761a01f6754be5ea6ca560aa63d76ca6d091f4585135dae4940f0acdfefdbe5042d26e0ffb52389406bf79c257c0026f6e7e173d30aa0094d7d8eb316c7
                            [current] => 5024a342cde22c5b49db688af49e1a5547351fbf2383f25d9d908ca6a3350afa6086a9404fc57063c04324ef582777426aaa11b1305b7135f46a1396160f85c5
                        )

                )

        )

)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.4.0
 - activity: 2.11.0
 - admin_audit: 1.8.0
 - announcementcenter: 3.7.0
 - bookmarks: 2.3.4
 - calendar: 2.0.3
 - cloud_federation_api: 1.1.0
 - comments: 1.8.0
 - contacts: 3.3.0
 - dav: 1.14.0
 - documentserver_community: 0.1.5
 - drawio: 0.9.5
 - encryption: 2.6.0
 - federatedfilesharing: 1.8.0
 - federation: 1.8.0
 - files: 1.13.1
 - files_accesscontrol: 1.8.1
 - files_automatedtagging: 1.8.2
 - files_pdfviewer: 1.7.0
 - files_rightclick: 0.15.2
 - files_sharing: 1.10.1
 - files_trashbin: 1.8.0
 - files_versions: 1.11.0
 - files_videoplayer: 1.7.0
 - firstrunwizard: 2.7.0
 - forms: 1.1.1
 - issuetemplate: 0.6.0
 - logreader: 2.3.0
 - lookup_server_connector: 1.6.0
 - news: 14.1.3
 - nextcloud_announcements: 1.7.0
 - notes: 3.2.0
 - notifications: 2.6.0
 - oauth2: 1.6.0
 - ocsms: 2.1.7
 - onlyoffice: 4.1.4
 - password_policy: 1.8.0
 - passwords: 2020.4.1
 - photos: 1.0.0
 - polls: 1.3.0
 - privacy: 1.2.0
 - provisioning_api: 1.8.0
 - registration: 0.4.7
 - serverinfo: 1.8.0
 - settings: 1.0.0
 - sharebymail: 1.8.0
 - support: 1.1.0
 - survey_client: 1.6.0
 - systemtags: 1.8.0
 - tasks: 0.12.1
 - text: 2.0.0
 - theming: 1.9.0
 - twofactor_backupcodes: 1.7.0
 - updatenotification: 1.8.0
 - viewer: 1.2.0
 - workflowengine: 2.0.0
Disabled:
 - files_external
 - recommendations
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "familienfreun.de",
        "www.familienfreun.de",
        "familienfreun.de.w0174798.kasserver.com"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "https:\/\/familienfreun.de",
    "dbtype": "mysql",
    "version": "18.0.2.2",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "smtp",
    "mail_smtpauthtype": "LOGIN",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpsecure": "ssl",
    "mail_smtpauth": 1,
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "465",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "maintenance": false,
    "default_language": "de",
    "tempdirectory": "\/www\/htdocs\/w0174798\/cloud\/tmp",
    "theme": "",
    "loglevel": 2,
    "updater.release.channel": "stable",
    "ldapIgnoreNamingRules": false,
    "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
    "app_install_overwrite": [
        "calendar"
    ]
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** 1

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

## Client configuration

**Browser:** Chrome Version 81.0.4044.113 (Offizieller Build) (64-Bit)

**Operating system:** Windows 10

## Logs

<details><summary>Web server error log</summary>

```

```
</details>

<details><summary>Nextcloud log</summary>

```
[index] Error: Exception: Argument 2 passed to OCA\Forms\Db\NotificationMapper::findByUserAndForm() must be of the type string, null given, called in /www/htdocs/w0174798/cloud/apps/forms/lib/Controller/PageController.php on line 277 at <<closure>>

0. /www/htdocs/w0174798/cloud/lib/private/AppFramework/App.php line 125
   OC\AppFramework\Http\Dispatcher->dispatch(OCA\Forms\Controller\PageController {}, "gotoForm")
1. /www/htdocs/w0174798/cloud/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
   OC\AppFramework\App::main("OCA\\Forms\\Controller\\PageController", "gotoForm", OC\AppFramework\ ... {}, {hash: "M61SCtSe ... "})
2. <<closure>>
   OC\AppFramework\Routing\RouteActionHandler->__invoke({hash: "M61SCtSe ... "})
3. /www/htdocs/w0174798/cloud/lib/private/Route/Router.php line 299
   call_user_func(OC\AppFramework\ ... {}, {hash: "M61SCtSe ... "})
4. /www/htdocs/w0174798/cloud/lib/base.php line 1008
   OC\Route\Router->match("/apps/forms/form/M61SCtSeoxu7p5QD")
5. /www/htdocs/w0174798/cloud/index.php line 38
   OC::handleRequest()

GET /index.php/apps/forms/form/M61SCtSeoxu7p5QD
from 95.91.27.135 at 2020-04-21T10:22:06+00:00

```
</details>

<details><summary>Browser log</summary>

</details>

**Comment by jotoeri** [comment]
Hey Thomas,

thank you for reporting this. The bug itself has been tackled already, so with the next release it will be solved.
In case you need an immediate solution, @dawidol posted his solution in simple steps in issue #291.

Greets,
Jonas

**Comment by ThomasKujawa** [comment]
Thank you.
