### ISSUE TITLE
Public access not work

### ISSUE THREAD

**Issue by AyelGoth** [nextcloud/forms#300]
Form Version 1.1.1
NextCloud 18.0.1

I created a form and put it up for public sharing via a link. But when the user clicks on the link an error appears when accessing the form.

Internal server error

The server was unable to complete your request.

If this happens again, please send the technical details below to the server administrator.

More details can be found in the server log.
Technical details

    Remote Address: 186.13.116.39
    Application ID: XqRva9YrXlRtb-osqZE@0wAA1x4

Translated with www.DeepL.com/Translator (free version)

**Comment by jotoeri** [comment]
Hey Darío,
Did you have a look into your nextcloud-log? (To be found under Settings->Logging)

In case there is something written like
> Argument 2 passed to OCA\Forms\Db\NotificationMapper::findByUserAndForm() must be of the type string

then please have a look into issue #291. The problem itself has been tackled and will disappear with the next release of forms. Within the issue you will find a quick-fix, if necessary.

In case you see a different issue inside your log, please provide this information from the log here, so we can try to help you.

Greets,
Jonas

**Comment by skjnldsv** [comment]
Fixed with upcomming 2.0
