### ISSUE TITLE
Small improvements for future versions

### ISSUE THREAD

**Issue by Pilzinsel64** [nextcloud/forms#316]
**Which Forms version are you running?** (see apps page)
v2.0.0 Beta 1

**Nextcloud or ownCloud?:**
Nextcloud

**Nextcloud/ownCloud version:** (see Nextcloud admin page)
18.0.4

I tested v2.0 Beta 1 and I am surprised how well it workes now (except already reported bugs)! It seems that Forms is going to be a really good App.

But I have a few small features/improvements that would be really nice to see in a feature version. This features are present in Google/Microsoft Forms and I miss a bit.
1. Mark question as option (so, It can be empty or unchecked)
1. Description for each question (Optional, helpful for some details to describe the question)
1. Allow line breaks in Form description (currently line breaks are only a white space)
1. Integration with Activity-App (Send to Stream/E-Mail if new submission made on a Form)
1. Ability to share to a user or group, so he/she can view the results or even edit the Form
1. Ability to delete single answers or all at once
1. Move questions in a Form up/down (maybe with an arrow button)

**Comment by skjnldsv** [comment]
Thank you so much for testing and for the kind words! :hugs: 

1. #135 
2. Might be interesting, not sure if realy necessary :thinking: 
3. Ah, that is a bug! Added in #296 
4. Can you open a dedicated issue for other people to see this too? :)
5. @jancborchardt do we want this?
6. You mean in multiple questions, have a button to clear everything?
7. Currently you can drag & drop, but we plan to also have a way to do it via keyboard! I opened an issue so we can track it specifically! #317

**Comment by Pilzinsel64** [comment]
2. Just check this [form here](https://forms.office.com/Pages/ResponsePage.aspx?id=DQSIkWdsW0yxEjajBLZtrQAAAAAAAAAAAAN__taH74pUOFIzWjFDT0JaQVFDTDVYUTFaMlRPQ1dWWS4u). There you see why it can be really helpful.
5. Just an example why I asked for: I have a group of users that checks user request (feature requests & bug reports), talk with the sender and create a card on a board in the Deck App.
6. Sorry, I didn't explained it. I mean in the "Results" view. Delete one result or all results. I know you want to improve it, but I don't know if this is a point actually.
7. Oh sorry, I don't know how I did miss the icon on the left side... 🙄I didn't see them all the time, but now they are there. I can move the questions.

**Comment by skjnldsv** [comment]
> to 2.
> Just check this [form here](https://forms.office.com/Pages/ResponsePage.aspx?id=DQSIkWdsW0yxEjajBLZtrQAAAAAAAAAAAAN__taH74pUOFIzWjFDT0JaQVFDTDVYUTFaMlRPQ1dWWS4u). There you see why it can be really helpful.

Great ressource! Thanks!

**Comment by jancborchardt** [comment]
> Description for each question (Optional, helpful for some details to describe the question)

Totally agree, this was also needed for the surveys we are doing for Nextcloud, cc @jospoortvliet. Can you open a separate issue for this @Pilzinsel64?

> Ability to share to a user or group, so he/she can view the results or even edit the Form

Yep, we absolutely should have collaborative editing of Forms, so that e.g. the whole marketing team has access to the forms and responses. Could you open a separate issue for that as well @Pilzinsel64? :)

> Ability to delete single answers or all at once

Yup, it should be possible to delete responses. :) Can you also open a separate issue for that?

Thank you so much for the feedback!

**Comment by skjnldsv** [comment]
> Yup, it should be possible to delete responses. :) Can you also open a separate issue for that?

This was also requested by the marketing team :+1: 
@Pilzinsel64 please close this one once each issue have its own ticket :wink:

**Comment by Pilzinsel64** [comment]
Alright, I created an separate bug ticket for each issue/feature. I hope I didn't miss one.
Many thanks for your friendly answers, by the way. 😉
