### ISSUE TITLE
Reorder question via arrows

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/forms#317]
Instead of drag and drop, support arrox reordering when focusing the drag handle.
Might also be interesting to show two arrows buttons when hovering/focusing the handle that can also be clicked?

cc @jancborchardt

**Comment by jancborchardt** [comment]
Yep, both suggestions are good enhancements. For the "support arrow reordering when focusing the drag handle" did you check if that is a somewhat standard in a way that it’s used by other apps too?

**Comment by skjnldsv** [comment]
We talked abou this already xD
Not done specifically, but A11y have a lot of specifications where using arrows key to change items are used and recommended.

**Comment by ei8fdb** [comment]
:100: agree. Reordering arrows would would much better here. I had the same issue. See timestamp 06:05 to 07:32 in [this testing video](https://www.flickr.com/photos/runningwithbulls/49862099823/in/datetaken/).

**Comment by skjnldsv** [comment]
> See timestamp 06:05 to 07:32 in [this testing video](https://www.flickr.com/photos/runningwithbulls/49862099823/in/datetaken/).

I'm guessing you mean this video https://www.flickr.com/photos/runningwithbulls/49862099753/
Can you open an issue? Drag&drop should scroll the window indeed :+1:
