### ISSUE TITLE
Alert when leaving the page with an unfinished filled form

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/forms#319]
To avoid data loss

**Comment by ei8fdb** [comment]
What do you mean prevent user from leaving the page with an unfinished form?

Setting I think setting mandatory questions would be helpful here, no?

**Comment by skjnldsv** [comment]
If form is filled but not submitted, leaving the page should trigger a warning to avoid data loss.

**Comment by Chartman123** [comment]
Just as a reminder: example of how it can be done from cookbook:

[RecipeEdit.vue](https://github.com/nextcloud/cookbook/blob/c099a02872e037ac3cdf84c644b97aa40fd39b33/src/components/RecipeEdit.vue)

**Comment by Chartman123** [comment]
According to https://alistapart.com/article/neveruseawarning/ this should only be the first part here. The better solution to this issue would be to implenent #456
