### ISSUE TITLE
Description for each question

### ISSUE THREAD

**Issue by Pilzinsel64** [nextcloud/forms#321]
Hello!

Sometimes it is really helpful (also for the user) to have a quick description or introduction about a question, so he/she know exactly what you want and type in the current answer.

As example, see this Form here I made using Microsoft Forms:
[SM64 ROM Manager - Bug Report](https://forms.office.com/Pages/ResponsePage.aspx?id=DQSIkWdsW0yxEjajBLZtrQAAAAAAAAAAAAN__taH74pUOFIzWjFDT0JaQVFDTDVYUTFaMlRPQ1dWWS4u)

This feature already has been discussed also here: #316

**Comment by ei8fdb** [comment]
This is a helpful feature. :100: agree. For me (doing user research) this would be a priority.

**Comment by Hanskes** [comment]
# 624 doesn't seem like a duplicate to me. This is about a description above a single question. # 624 is about the ability to put multiple questions in a section. Multiple sections, each with its own title and description, would be very useful.

**Comment by Hanskes** [comment]
#624 doesn't seem like a duplicate to me. This is about a description above a single question. #624 is about the ability to put multiple questions in a section. Multiple sections, each with its own title and description, would be very useful.

**Comment by loelkes** [comment]
> #624 doesn't seem like a duplicate to me. This is about a description above a single question. #624 is about the ability to put multiple questions in a section. Multiple sections, each with its own title and description, would be very useful.

What I meant for #624 was to have text blocks without questions. To have the questions _inside_ of sections would be nice, but for me it would be enough for it to _look like_ they're in sections with text blocks between them.

Another solution is to hide the question by creating a hidden field but with the description/title still visible. It sounds like a dirty hack but I would consider my issue "solved".

**Comment by skjnldsv** [comment]
> What I meant for #624 was to have text blocks without questions. To have the questions _inside_ of sections would be nice, but for me it would be enough for it to _look like_ they're in sections with text blocks between them.

Yes, thus why I re-opened :wink:
