### ISSUE TITLE
Input Drop-Down list via csv file

### ISSUE THREAD

**Issue by Stadtschreck** [nextcloud/forms#337]
I like to write my worktime with Form.
I need a list of around 50 vehicles in one Drop-Down-list and a second Drop-Down list with around 100 attachments for the vehicles.
Is there an other way of importing these list into the form?

Forms Vers.: 1.1.1
nextcloud: 17.0.2 via NextCloudPi
Odroid XU4 is in the moment the test-bench

**Comment by skjnldsv** [comment]
That is an interesting issue! I think we can improve indeed :)

@jancborchardt, what do you think about an option to do "bulk input" for multiple questions, would take new lines as separators :)
Seems like a nice easy optio that could easily help people!

**Comment by jancborchardt** [comment]
@skjnldsv just FYI this is very similar to **Uploading a CSV file to quicly create a form #102**

So I wouldn’t go any complicated "CSV import" route, but simply a power-user trick that if you paste a list of answer options with line breaks into an answer field, the fields following it will each be filled by one of the lines.

Do you know what I mean? So if the content of your clipboard looks like this:
```
Toshiba
Apple
Samsung
Lenovo
```

And you paste it into an answer type field of the multiple choice or checkboxes, it will fill multiple replies like so:

> - Toshiba
> - Apple
> - Samsung
> - Lenovo

**Comment by skjnldsv** [comment]
Yes, that is what I have in mind, but this isn't very discoverable, could we maybe make sure the users knows they can do that?

**Comment by jotoeri** [comment]
Hm, btw - imagine this form having a list of 50 & 100 options. Maybe a dropdown-list instead of just radiobuttons would be an interesting question-type somewhen again? ;)

**Comment by jancborchardt** [comment]
> Yes, that is what I had in mind, but this isn't very discoverable, could we maybe make sure the users knows they can do that?

Yes, but let’s first start with small steps. Remember it’s a feature only for creation, and we don’t even know if it will be used by a lot of people. So first MVP as we also need to focus on other things, and then we can still see what we need to make it more obvious.

> Hm, btw - imagine this form having a list of 50 & 100 options. Maybe a dropdown-list instead of just radiobuttons would be an interesting question-type somewhen again? ;)

Yup – want to open a new issue for that question type? :)

**Comment by Stadtschreck** [comment]
@jancborchardt I'm tried this with an enter/line-break separated list, it don't work.

**Comment by skjnldsv** [comment]
@Stadtschreck look on the right, this issue is marked as `to develop`, this is not implemented

**Comment by gerazo** [comment]
A simple copy-paste with newlines from a Spreadsheet would be adequate, but currently, it is not working. Everything goes into one inputbox when creating a drop-down list.
