### ISSUE TITLE
Forms app review

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/forms#34]
@skjnldsv @rullzer & @jancborchardt at Contributor Week June 2019

We also looked at [Google Forms](https://www.google.com/forms/about/) and [Typeform](https://www.typeform.com/) for comparison. We think it’s best to mainly model it after Google Forms as it’s quite widely used.

Below are detail review points of the current state so we can make small steps in the right direction based on the current app. :)

cc @nextcloud/forms 

## Initial list view
* [x] Forms should be listed in the left navigation instead of the main content. The main content is to edit the form.
* [x] Help button too present
* [x] Home icon is confusing and not necessary?
* [x] List header shows even though no forms
* [x] Emptycontent message missing?

## Form creation
* [x] No way to submit/confirm answer with mouse
* [x] Misalignment of answers
* [x] Too many delete buttons visible at the same time
* [x] Too many different font-sizes
* [x] Interface doesn’t reflect how the form will look for people afterwards
* [x] No way to reorder answers or put things inbetween
* [x] Replies are not autosaved

Answer types:
* [x] Icons for answer types
* [ ] No way to change the answer type
* [x] "Radio button" → Multiple choice
* [x] "Checkboxes" → Checkboxes
* [x] "Short response" → Short answer
* [x] "Long response" → Long text
* [x] "Drop Down" is the same as Single choice?

## Sidebar
* [x] Only 1 tab, which is not necessary → use sidebar component
* [ ] Spacing on owner is strange
* [ ] Settings are in 2 columns – unusual
* [ ] Settings like "Anonymous form" need explanation
* [ ] Use main Nextcloud sharing – default is public access which means everyone on the instance can see it

## List after creation
* [ ] Icon not clear (with green dot)
* [x] Clicking form should open editing configuration
* [x] Delete too present
* [x] "Created" date unnecessary

## Share view
* [x] Header should not show apps or contacts menu <- this is the logged-in view
* [ ] Header should not show "Nextcloud" placed a bit to the top <- this is unauthenticated view
* [ ] Header should have the survey title
* [ ] Input fields and textareas don’t look like inputs cause the other answer types have a container like that around it too
* [ ] Asterisk `*` before questions is confusing? Mandatory? Not possible to set or unset. Should instead say "mandatory" in a subline
* [x] "Thank you for completing he survey!" page is very bland

## Results view
* [x] Should simply be another tab in the sidebar? Or a switch of views in the app-content, kind of like we have the grid/list view? (Google Forms does this well, collapsing a block when not editing that specific one.)

## Potential
* [ ] Randomize order of choices in multiple choice and checkboxes (like in Google Forms, to reduce bias)
* [ ] Print submissions

**Comment by waazdakka** [comment]
I couldn't have said that better 😄 The list is very complete ! 
Maybe add the possibility to edit the form after validate it ?

**Comment by WNYmathGuy** [comment]
> Answer types:
> - [ ] Icons for answer types
> - [ ] No way to change the answer type
> - [ ] "Radio button" → Multiple choice
> - [ ] "Checkboxes" → Checkboxes
> - [ ] "Short response" → Short answer
> - [ ] "Long response" → Long text
> - [ ] "Drop Down" is the same as Single choice?

- [ ] "Date" → Date
- [ ] "Datetime" → Date & Time
- [ ] "Time" → Time
- [ ] "Integer / Float" → Value
- [ ] "Digits" → Numeric (_phone number, zip-code, street number field_)

##### Answer type enhancements:
- [ ] Mandatory fields option on any answer type
- [ ] Default entries for answers on a form (except on mandatory fields)
- [ ] Extended description (_for questions accessed via icon like a question mark in a circle_)

### Flow Control:
- [ ] Named Pages in the question set or the ability to link separate sub forms to one overall flow
- [ ] If option A is selected go to page X, else if opion B...
- [ ] On click Continue go to page Y

For a use case example, I built this gem...
[http://outsourcedmath.com/ContactInfo.html](http://outsourcedmath.com/ContactInfo.html)
It was designed to minimize the time a person spent filling it out. I only ask them what they prefer to tell me.

### Access:
- [x] Registered users only
- [ ] Registered users & Guest accounts (_if app is installed_)
- [ ] Anonomized Registered users & Guest accounts (_if app is installed_) `good for company suggestion boxes or legitemate anonymous voting`

### Form configurations:
- [x] Anonymous
- [x] Expires
- [ ] One entry per applicant (Unchecked is many)

### Post form landing page:
- [ ] Go to a specified URL
- [ ] Display a link for editing their entry
- [ ] Display a link to see results of the survey/vote/whatever
- [ ] Button(s) to share form to others via standard share via options

### Potential 
- [ ] Randomize queston order
- [ ] Password format field display while not in focus/editing mode
- [ ] Arbitrary user defined labling of the results page
- [ ] Pie Chart or Bar Chart display of results

**Comment by agentlibre** [comment]
Such a cool mission statement! <3

I can't directly contribute but I'm trying to bring this app back to life by other means.

Do not hesitate to comment, like, etc. my post on this forum to keep the attention on the topic: https://help.nextcloud.com/t/awareness-on-a-sadly-dying-app-nextcloud-forms/70823

Thanks!

**Comment by marcelklehr** [comment]
I just did a quick mockup, of how I think the form creation view could be improved:

![Untitled Diagram](https://user-images.githubusercontent.com/986878/76686633-38211b80-661d-11ea-980c-3a84c59ffcc6.png)

**Comment by jancborchardt** [comment]
@marcelklehr very nice! We are mainly looking at Google Forms which actually looks very similarly nice and simple. See https://github.com/nextcloud/forms/issues/250 if you want to get involved specifically on the form creation side. :)

**Comment by forteller** [comment]
Can I give my vote to reordering questions? I'm really sorry I can't help out with any coding, but I really appreciate your work and hope it's useful to get some feedback on priorities. Thanks!

And if the results could automatically be added to a editable document as the come in, instead of having to first export it, that would be really great. That's one of the huge advantages of Google Forms.

**Comment by jotoeri** [comment]
This would mean to store some question-order within Db... Maybe defining an Order-index of zero, that marks a deleted question? This would also solve the problem to still know the deleted questions, when editing a form after the first submissions are made. And when deleting a form, then all questions will be fully deleted.

**Comment by skjnldsv** [comment]
> This would mean to store some question-order within Db... Maybe defining an Order-index of zero, that marks a deleted question? This would also solve the problem to still know the deleted questions, when editing a form after the first submissions are made. And when deleting a form, then all questions will be fully deleted.

Yes :)
This can come in a different migration than #249 to keep your pr simple :wink: 
But we should really try to have this for v2

**Comment by jotoeri** [comment]
I think so too... 
Maybe i would still change the Migration-Script for V2 as long as not published, but within a different PR.
I'll open a separate issue, to have it in mind..

**Comment by jancborchardt** [comment]
> Can I give my vote to reordering questions? I'm really sorry I can't help out with any coding, but I really appreciate your work and hope it's useful to get some feedback on priorities. Thanks!
> 
> And if the results could automatically be added to a editable document as the come in, instead of having to first export it, that would be really great. That's one of the huge advantages of Google Forms.

@forteller could you ideally open 2 separate issues about the ability to reorder, as well as the automatic adding to a document? Thanks! :)

**Comment by inquisitiv3** [comment]
I would like to specify a user group as an owner of a form. What I want to give only this specific user group access to the form data.

Should I create a separate issue for this?

**Comment by skjnldsv** [comment]
> I would like to specify a user group as an owner of a form. What I want to give only this specific user group access to the form data.

Hey!
This is currently not supported and we do not want this feature for the moment. Please create a dedicated issue then so we can discuss this :)
Have a great Sunday!

**Comment by jancborchardt** [comment]
Closing this issue as most of the things are implemented in current master. We are tracking anything else in individual issues. :)

**Comment by wunschadresse** [comment]
Not sure, if the initial post is being updated, but it would be great, if the not yet implemented features would link to the main thread where it is being discussed.
