### ISSUE TITLE
Implement dropdown question-type

### ISSUE THREAD

**Issue by jotoeri** [nextcloud/forms#340]
Include dropdown as question-type.

(From #337, where a large list of options would produce a very long form. Dropdown would be more clearly arranged)

**Comment by jotoeri** [comment]
:D really @skjnldsv ?
@jancborchardt what do you think?

**Comment by jancborchardt** [comment]
Haha :D 

No but really, for a _lot_ of options on a question, we need the dropdown question type as well. Google Forms has it, we need to have it. ;)

**Comment by skjnldsv** [comment]
With search too! Before it was just a <select>, Which then is not ideal.
A proper Multiselect implementation would fit better :)

**Comment by ei8fdb** [comment]
A drop-down question is definitely necessary. :+1: 

Importing would be useful but personally that's less important (than having question formats that allow me to capture data in the right way).

**Comment by jancborchardt** [comment]
Fixed and merged via https://github.com/nextcloud/forms/pull/461! :) Will be in 2.0
