### ISSUE TITLE
Public link doesn't work

### ISSUE THREAD

**Issue by thebarless** [nextcloud/forms#344]
Using v1.1.1 with NC 18.04, I created a form. Opening the link in a new tab works. However, opening the link from a separate browser that is not logged in gives an internal server error:

> Exception: Argument 2 passed to OCA\Forms\Db\NotificationMapper::findByUserAndForm() must be of the type string, null given, called in /var/www/nextcloud/apps/forms/lib/Controller/PageController.php on line 277

**Comment by amsaravi** [comment]
i have a same problem with NC 18 Running on docker

**Comment by jotoeri** [comment]
Hey you both,

thank you for reporting this. This issue has been solved already and will be gone with the upcoming release.
For future, please search in old issues if the problem has been reported already to avoid duplicates.

Greets,
Jonas

Closed as duplicate of #291
