### ISSUE TITLE
Feature request/ideas for Forms 

### ISSUE THREAD

**Issue by greavette** [nextcloud/forms#348]
Nextcloud 18.0.3
Forms App - 1.1.1

I'm new to using Forms and very impressed with this app.  I see a lot of potential with Forms.  I have some suggestions (feature requests) and I'd like to know if these have been considered yet?

1. Ability to edit existing form.  I will create the form as the Nextcloud Admin but I'd like to provide the form to the business owner for review where they can make changes if necessary.  Currently there is no edit ability and it's onerous to recreate the entire form for any small changes.
2. Change direction of radio button questions.  For a question where you want to use 10 radio buttons (0 - Not Likely to 10 - Highly Likely) having this in a vertical does not look right.  This type of question is usually horizontal.  
3. Instead of Line Wrap allow for Centering of Title.  If a Title is longer than one line it doesn't look nice when it line wraps.  Would be better to allow for centering of Title's.
4. The text once submitted - "Thank you for completing the survey!".  This text is not centered and for some reason the words - the servey! wraps to the next line.  This text should be centered on the page (centered height and width) and it should fit on one line as it's not very long.

Thank you for considering these suggestions.

**Comment by skjnldsv** [comment]
Hey!
Have you tried the 2.0.0 beta version? Please check the following thread #226 
Lots of those issues are fixed in the upcoming version

**Comment by skjnldsv** [comment]
Please have a look at it and open new issues for each one you face :)
That would help a lot to keep track instead of one listing all the issues/features you encountered/wish :wink:
