### ISSUE TITLE
How do I upgrade forms to Beta 2?

### ISSUE THREAD

**Issue by greavette** [nextcloud/forms#349]
Hello Team,

Very much appreciate the reply to try out the Beta v2 that is out!  I've reviewed the issue - https://github.com/nextcloud/forms/issues/226#issuecomment-621328816 but I can't see how I can upgrade forms 1.1.1 to version 2?  

Could someone provide for me more granular steps on how I would do this?  If it's a zip file to download and copy to my Nextcloud Forms folder where do I get the required files and are there steps to manually update forms to Beta 2?

I also see an option to change my Nextcloud from stable to daily?  But where do I make this change and how do I change my Nextcloud back to stable?  I only want to update Forms and nothing else.

Thank you.

**Comment by skjnldsv** [comment]
It's a few messages down https://github.com/nextcloud/forms/issues/226#issuecomment-622548623 :wink:

**Comment by greavette** [comment]
I apologize for re-opening this question but I don't know where to find the code - updater.release.channel to change? I've grepped my nextcloud folder but I found this text in various files.  What file and where is this location of this file do I need to change updater.release.channel from stable to daily?

Thank you.

**Comment by skjnldsv** [comment]
You can do it via occ :)
There is a link to the occ web app that allow you to run occ commands directly there if you don't know how to manage :wink:

**Comment by skjnldsv** [comment]
https://docs.nextcloud.com/server/stable/admin_manual/configuration_server/occ_command.html

**Comment by greavette** [comment]
Thank you @skjnldsv for your patience in answering my questions.  Very much appreciate your help!

I've installed my Nextcloud through a sever called Nethserver.  Not looking for your support with Nethserver but I mention this because how I issue the occ command will look different to you.  

so in order for me to issue the occ command I use the following:

sudo -u apache /opt/rh/rh-php72/root/usr/bin/php /usr/share/nextcloud/occ app:list

I've tested this and occ works.  So my question to you now is...in order to change the update.release.chanel to to daily do I issue the following occ command:

sudo -u apache /opt/rh/rh-php72/root/usr/bin/php /usr/share/nextcloud/occ config:system:set updater.release.channel --value 'daily'`

And in order to have my Nethserver back to only allowing stable apps I would issue the following:

sudo -u apache /opt/rh/rh-php72/root/usr/bin/php /usr/share/nextcloud/occ config:system:set updater.release.channel --value 'stable'`

Thank you.

**Comment by greavette** [comment]
Ok @skjnldsv , I took a backup of my server (it's virtual) and pushed ahead and ran the command:

sudo -u apache scl enable rh-php72 -- php -dmemory_limit=512M /usr/share/nextcloud/occ config:system:set updater.release.channel --value 'daily'

It finished successfully.  I then grepped for file changes and found that my /nextcloud/config/config.php has been updated with the updater.release.channel --value 'daily' now.  That line wasn't in my config.php file previously so it appears my occ command has worked to add it.

So now what do I do to get forms beta 2 on my Nextcloud?  I've refreshed my Apps page and even rebooted my Nextcloud server.  I'm not seeing a new (beta) version of Forms app waiting to be installed.  How do I install the beta version  of Forms after adding this occ command? 

Thank you.

**Comment by skjnldsv** [comment]
Awesome :)
Sorry, I went to bed in the meantime :sleeping: 

This is the v2 beta1, we'll release the v2 beta2 today, no specific date for production, but should be in a matter of a few weeks :wink: 


> That line wasn't in my config.php file previously so it appears my occ command has worked to add it.

Yes, well done :)
Don't forget to remove the line now (via config file edit or occ)
Also, your occ commands looks very complex, you might benefit from the occweb app, that gives you an interface to run occ commands from your Nextcloud.

Anyway, let's continue the future discussions about forms v2 releases in the other thread #226 
Don't forget to report bugs for the v2 (after a search and if they aren't already reported of course ;)

Cheers!

**Comment by laurentiu2** [comment]
@skjnldsv 
I tried to update on a Ubuntu 18.0.4 server to beta with 
`sudo -u www-data php /var/www/nextcloud/occ config:system:set updater.release.channel --value 'daily'`, I do see the confirmation message, I see in Settings/Overwiew that the current channel is 'daily' but no update is available for the app.
The same did function on a Debian server.. Any advice? :)

**Comment by laurentiu2** [comment]
It did work after a few hours.
