### ISSUE TITLE
Where do I find the file to change the updater.release.channel parm?

### ISSUE THREAD

**Issue by greavette** [nextcloud/forms#350]
I apologize for re-opening this question (I would have added this comment to my other question but it was closed and I don't know how to re-open it).  but I don't know where to find the code - `updater.release.channel `
to change? I've grepped my nextcloud folder but I found this text in various files.  What file and where is this location of this file do I need to change updater.release.channel from stable to daily?

Thank you.

**Comment by skjnldsv** [comment]
Let's continue the discussion on the other one! Closed doesn't mean you cannot comment :sweat_smile:
