### ISSUE TITLE
Allow additional long-text 'explain why' in multiple choice or checkbox questions

### ISSUE THREAD

**Issue by ei8fdb** [nextcloud/forms#355]
Which Forms version are you running?
v2.0.0 beta 1 (build 20200505)

Nextcloud or ownCloud?:
Nextcloud

## Feature request
Allow for one "user comment" input field in multiple choice or checkbox questions

## Rational
In UX research, multiple choice or checkbox question are often used for closed/structured answers from participants. 

But in order to make sure you are understanding the user reasoning, it is common to also provide a short 2/3 line free text input field as part of these types of questions. In this case users can then write 1/2 lines of free text.

## UI
This would be a form admin configurable option when creating the form. For the participant filling out the form, it would look something like this:
![Screenshot from 2020-05-06 16-49-22](https://user-images.githubusercontent.com/1899506/81198708-b5339600-8fb9-11ea-913d-2cbbe8aa029c.png)

The label for this comment field would be customisable - i.e. above "Explain how you know this".

Reuse of the "long-text" answer UI element would be a good place to start.

## Priority
High

As a UX researcher who creates questionnaires having the capability of gathering a short free-text input to clarify a user's selection of an option s very helpful.

Thoughts?

**Comment by skjnldsv** [comment]
Shouldn't this be a separate long answer then?
I feel like it would make more sense as this would complicate things and gain will be minimal :thinking:

**Comment by ei8fdb** [comment]
> Shouldn't this be a separate long answer then?

No as the clarification (i.e. the input in the freetext field) is connected to that question. I'll try and get some examples for you. 

> I feel like it would make more sense as this would complicate things and gain will be minimal thinking

It would be more work trying to explain that this *new* question is connected to the *previous* question. Asking these kinds of questions is an inexact science. :wink:

**Comment by jancborchardt** [comment]
Yeah, I understand @skjnldsv’s point about that it could also just be a following long answer field.

@ei8fdb is this common in a lot of different questionnaire types, or domain specific to user research?

Also, does Google Forms support this or would enabling something like this mean that we would divert from the export format they use?

**Comment by elioqoshi** [comment]
Currently Google Forms does not have the feature Bernard mentioned, only offering an "Other" custom text input for multiple/checkboxes questions.

If you plan to stay compatible with the data format of Google Forms that makes sense, though I might miss something here about the importance of this feature request.

@renatagegaj has done quite a lot of Forms so she might have some thoughts on this?

**Comment by elioqoshi** [comment]
I just checked and currently there is no way to add a custom "Other" text answer in Nextcloud Forms (something which Google Forms supports), so that would definitely make sense to have in various scenarios apart user research.

**Comment by jancborchardt** [comment]
> Currently Google Forms does not have the feature Bernard mentioned, only offering an "Other" custom text input for multiple/checkboxes questions.

Cool, thanks for the info – if we get to implementing this (or if someone wants to pick it up) we should make sure it’s on par with Google Forms’ functionality. :)

**Comment by elioqoshi** [comment]
Do you have any bounty program we can contribute to for someone to develop this feature?

**Comment by jotoeri** [comment]
Ok, seems like things get mixed up here a bit. For the 'other'-option, there is already a separate issue. #93 
This one originally was about the ability to allow an additional long-text-field 'explain why' to multiple-questions, which as i understood is currently not planned, but goes to maybe-someday.

**Comment by spaetz** [comment]
Just FYI, while I do see the potential value of this feature: as a social scientist I have not often encountered these types of questions with associated explanation fields nor does eg Limesurvey offer it.

**Comment by ei8fdb** [comment]
> Just FYI, while I do see the potential value of this feature: as a social scientist I have not often encountered these types of questions with associated explanation fields nor does eg Limesurvey offer it.

Ok that's interesting to know. Can I ask how you'd handle getting further explanation for a participants answer to a closed question?

**Comment by spaetz** [comment]
Either you ask closed questions of you are after the statistics, open answers don't help in this case. Or you are after qualitative answers, trying to understand the why: often you don't use multtiple choice then.

Or you ask the long free form text simply in a separate question, which allows you to dynamically adapt the question based on your answer.

**Comment by Chartman123** [comment]
I wanted to add some thoughts here, too: We now have the "other" option for multiple choice questions and I've never seen this in other tools by now. I think that we shouldn't implement this but wait for the support of sections/conditions within a form. That way you can express that the following longtext belongs to the multiple choice question and you could also make it mandatory when the multiple choice question is answered.

So I close this issue for now.
