### ISSUE TITLE
Second character in answer sentence disappears when space bar pressed

### ISSUE THREAD

**Issue by ei8fdb** [nextcloud/forms#359]
**Describe the bug**
Second character in answer sentence disappears when space bar pressed. 

The second (sometimes 3rd/4th) character typed in any multiple choice or checkbox question disappears automatically when the spacebar is pressed.

It looks like an autocorrect type behaviour, but it's not autocorrecting to any English word!

**To Reproduce**
. Steps to reproduce the behavior:
1. Choose multiple choice or checkbox question
2. Write question text
3. Click 1st answer line
4. Type any 2 letter, then press space bar

**Expected behavior**
The character does not disappear!🙂

**Screenshots**
See [this short testing video](https://flickr.com/photos/runningwithbulls/49862099753/) I've recorded, look at video timestamps:
00:10
00:28
00:40
02:38
02:49
03:08

**Desktop (please complete the following information):**
 - OS: POP_OS 20.04 (Ubuntu based OS)
 - Browser: Firefox 
 - Version: 75.0 (64-bit)

**Browser log**
```
JQMIGRATE: Migrate is installed, version 1.4.1 main.js:566:531
Proxying an event bus of version 1.1.2 with 0.2.1 notifications.js:21:13435
Handlebars is deprecated: please ship your own, this will be removed in Nextcloud 20 main.js:1082:57
This page uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”. main.js:230:11228
moment is deprecated: please ship your own, this will be removed in Nextcloud 20 3 main.js:1082:57
moment is deprecated: please ship your own, this will be removed in Nextcloud 20 22 main.js:1082:57
Loading form 6 forms.js:771:2074
Locale used en-gb forms.js:771:26822
recommendations 
Array [ {…}, {…} ]
forms.js:771:21956
Source map error: Error: NetworkError when attempting to fetch resource.
Resource URL: https://nuboso.ei8fdb.org/apps/notifications/js/notifications.js?v=f26295c8
Source Map URL: notifications.js.map
Source map error: Error: NetworkError when attempting to fetch resource.
Resource URL: https://nuboso.ei8fdb.org/core/js/dist/main.js?v=f26295c8
Source Map URL: main.js.map
Created answer 
Object { id: "bbnfx", question_id: 22, text: "i", local: true }
forms.js:113:9011
Updated answer 
Object { id: Getter & Setter, question_id: Getter & Setter, text: Getter & Setter, … }
forms.js:113:9744
Updated answer 
Object { id: Getter & Setter, question_id: Getter & Setter, text: Getter & Setter, … }
forms.js:113:9744
```

**Additional context**

**Comment by jotoeri** [comment]
Hey Bernard,

which forms version are you running here? Have you already tried beta2, that has been released yesterday? I think your problem should be solved there.

Greets,
Jonas

**Comment by ei8fdb** [comment]
@jotoeri I managed to miss the link for beta2 yesterday. I did some quick testing just now and it *seems* this is fixed now. I'm going to test some more during the day and I'll come back and close it if all looks good. Thanks :+1:

**Comment by jancborchardt** [comment]
Cool, great that it was fixed then → closing :)
