### ISSUE TITLE
Show forms that are shared with me on the navigation

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/forms#364]
If I use one of the yellow fields the choosen user/all users should see the form but the don't.

![grafik](https://user-images.githubusercontent.com/24530680/81281335-fed3bd80-9059-11ea-88e3-f150c0d5022f.png)

**To Reproduce**
1. create a new form
2. share it to all users or to a special user
3. log in as this user
4. navigate to forms

**Expected behavior**
The shared form should be visible

**Comment by skjnldsv** [comment]
> The shared form should be visible

You mean on the left navigation ?
You can access it via the link, correct?

**Comment by jakobroehrl** [comment]
OK, sorry. It's working. I got it wrong. 
I thought the user/users would see the form/form results in there instance.

**Comment by skjnldsv** [comment]
> I thought the user/users would see the form/form results in there instance.

Funny, we were discussing this 20min ago :stuck_out_tongue: 
I'll leave this ticket opened to keep track of it! Because yep, we definitely need to have shared-with-me forms in the navigation for logged in users! :+1:

**Comment by jakobroehrl** [comment]
That's because I find https://github.com/nextcloud/forms/issues/5 important. 
With this I can share the results of an form

**Comment by jmcclelland** [comment]
Hi all - thanks for the great work on this app. I wanted to clarify this issue to see if it's the same issue i have.

As I understand it, right now "sharing" a form means indicating who should be able to _fill it out._ This ticket is asking for a new feature that would allow you to share admin control over the form with other users. So, two or more logged in users could add/edit/delete questions and also have full access to the results.

Is that what this ticket is about? Or should I open a new one?

**Comment by jotoeri** [comment]
Hey @jmcclelland ,

this issue is about forms, that i don't own admin-rights to, but i am only allowed to fill. These forms should be shown on the sidebar as well, to be able to access it from there, instead of only via link.

However, i think the features you want to be implemented are tracked in #455 (for accessing only results) and #322 (for collaborative editing). Feel free to use GitHubs reactions there, if you agree.
Hope that clarifies this? :)

Greets,
Jonas

**Comment by jmcclelland** [comment]
Thank you - those are definitely the issues for me to track.

**Comment by 2epal** [comment]
please forgive me to insist.... but i can't figure out how to share the form with other users...

i want to build a form and then (without send a link) the form to show at the other users. is it possible? or not?

**Comment by jotoeri** [comment]
Hey @2epal,
this is currently not possible, you still need to share the link, but you can restrict access onto the link with the sharing-options.
As you can see above, we discussed your request on this issue already and it's planned to be implemented within one of the next releases.
Greets,
Jonas

**Comment by 2epal** [comment]
many thanks for your response

**Comment by 2epal** [comment]
i found an "indirect" solution....
i use External sites app and make  icon-link on the menu bar for the form share-link and that shows automatically to the specified users!
