### ISSUE TITLE
Order of answer incoherent with order of questions

### ISSUE THREAD

**Issue by theosche** [nextcloud/forms#381]
**Describe the bug**
[Not sure if bug or feature request]
After questions are created, their order can be manually adjusted by using drag and drop, which is very useful. However, in the answer page, the order is not adapted accordingly.

**To Reproduce**
Create a new form, with two questions.
Move the second question above the first one.
Fill in your form and go to the answers page.

**Expected behavior**
The order of answers should be the same as the order of questions.

**Screenshots**
Form creation:
<img width="899" alt="Capture d’écran 2020-05-11 à 21 57 04" src="https://user-images.githubusercontent.com/34695683/81606615-b0b11800-93d3-11ea-93a8-688b6602ce88.png">

Answers:
<img width="883" alt="Capture d’écran 2020-05-11 à 21 57 20" src="https://user-images.githubusercontent.com/34695683/81606648-beff3400-93d3-11ea-8a8f-0f947e566442.png">

**Nextcloud (please complete the following information):**
- Nextcloud-Version: 18.0.4
- Forms-Version: 2.0.0-beta2

**Desktop (please complete the following information):**
 - OS: MacOs Mojave 10.14.6
 - Browser Firefox 
 - Version 76
(But same situation on other devices with different configurations)

**Comment by jotoeri** [comment]
Hey theosche,
thank you for reporting this! That is definately not a planned feature, so it must be a bug. ;)

@jancborchardt I would say, ideally show in the order, the user saw on submit, no? So not currently set order on form-edit?

**Comment by jancborchardt** [comment]
> @jancborchardt I would say, ideally show in the order, the user saw on submit, no? So not currently set order on form-edit?

I’d agree with @theosche that the expectation is seeing the responses in the same way that the questions are ordered. Even when the questions are reordered after there are already some responses – otherwise you also have inconsistencies in the display of the different answers based on when they filled it out.

**Comment by jotoeri** [comment]
Hm, ok. Might break the user-answers-context imo, but ok.

Showing given answers to deleted questions on top, on bottom or not? ;)

**Comment by theosche** [comment]
Thank you,
In my opinion, showing given answers to deleted questions is not necessary.

**Comment by jancborchardt** [comment]
Yep, would agree that showing answers to deleted questions is not necessary.

(If we every do it, we can show those below the other questions and have the font color be `var(--color-text-maxcontrast);`. But again, for now we should not show them.)
