### ISSUE TITLE
Allow for custom message and/or redirect after submission

### ISSUE THREAD

**Issue by adamduncan** [nextcloud/forms#385]
When creating a form, there's currently no flexibililty to configure the content/action that occurs after successful form submission.

Would it be beneficial to include a "Submission message" (text/richtext?) and/or "Redirect URL"  as part of Form configurations? These options would help with i18n for multilingual audiences, and offer improved UX for form creators.

As far as I can tell, there's no mechanism made available in the package to faciliate any customization [here](https://github.com/nextcloud/forms/blob/95cd4c0fb2fb46ce4b42f0020636249aa79c8300/src/views/Submit.vue#L67) or [here](https://github.com/nextcloud/forms/blob/95cd4c0fb2fb46ce4b42f0020636249aa79c8300/src/views/Submit.vue#L160-L175)?

**Comment by thenamelessthing** [comment]
I agree, the lack of possibility to edit forms fter they are submit is really pain in the ass..

**Comment by jotoeri** [comment]
That's right, currently there is no possibility for such custom feedback. Definitely a way to go imo. 👍

**Comment by jotoeri** [comment]
As also of #548:
- Allow custom 'Thank you'-message
- Allow button, that will redirect to custom link.

**Comment by TtuxX** [comment]
Hi there ! :)

Sorry for bumping this thread but are there any updates regarding this great feature ? 

For public users/visitors I think this functionality is one of the main things that are missing compared to Microsoft Forms. They indeed cannot be warned of the future expected interactions/steps following their vote/completion of the form.
