### ISSUE TITLE
Dialogs not sticky

### ISSUE THREAD

**Issue by jotoeri** [nextcloud/forms#398]
**Configuration**
Dialogs v1.3.0,
Forms-App on master
NC 18.0.4

**Behaviour**
Dialogs are not sticky, but appear at top of the page. So if i am not at top of the page (scrolled down on a long form), i don't see the dialog at all.

I assume, this is not intended, but they should appear sticky at the top of the current screen?

![grafik](https://user-images.githubusercontent.com/47433654/82068092-dab75280-96d1-11ea-93a4-b588bbb491c8.png)

**Comment by jancborchardt** [comment]
> Hm that is odd, I can reproduce this by calling `OCP.Toast.error` in forms but not in any other app. There is maybe something odd with the body as a scroll container there, but I cannot see anything obvious.

How can I invoke the toast so it stays and does not disappear automatically after some time? Then I could debug.

**Comment by jotoeri** [comment]
In theory `timeout: 0` should work. But with `OCP.Toast.error('test', {timeout: 0})` it even doesn't work for me...

**Comment by jotoeri** [comment]
@jancborchardt On branch `test/dialog` i just pushed my current testing environment. There it works for the toast to remain open.

**Comment by jancborchardt** [comment]
Simply disabling the `position: absolute` (which is relative to the apparently moving `body` element) fixes it – cause then the `position: fixed` from server.css takes over. The inline one is from nextcloud-vue, correct? That one should be fixed as well, no @juliushaertl?
inline | server.css
-|-
![toastify inline](https://user-images.githubusercontent.com/925062/82719684-0f687280-9cad-11ea-90ae-b053f376f55f.png)|![toastify server](https://user-images.githubusercontent.com/925062/82719682-0e374580-9cad-11ea-976a-e57374ad68cc.png)

**Comment by jotoeri** [comment]
Nice @jancborchardt 💪

The inline-one comes from nextcloud-dialogs/styles/toast.scss

Interesting thing is, that the style from server contains in fact the same styles just with the changed position. Maybe one of them should be removed, so toast-styles are only defined in one place??
(And resp. fixed position in case it remains in dialogs.)

**Comment by juliushaertl** [comment]
Yes, I think the server styles were fixed independently after we copied the styles over to https://github.com/nextcloud/nextcloud-dialogs/blob/master/styles/toast.scss#L10

@jotoeri Are you up for preparing a pull request to fix this in the dialogs library?

**Comment by jotoeri** [comment]
👍 , see link. :)
