### ISSUE TITLE
Don't show Nextcloud Toolbar with all apps

### ISSUE THREAD

**Issue by dueringa** [nextcloud/forms#4]
**Which Forms version are you running?** (see apps page)
1.0.3

**Nextcloud or ownCloud?:**
Nextcloud

**Nextcloud/ownCloud version:** (see Nextcloud admin page)
16.0.1

### Steps to reproduce
1. Create a form, make it public
2. Copy the link
3. Open the link in another browser or in icognito mode, so you're not logged into the Nexcloud instance

### Actual behaviour
On the top, the Nextcloud Toolbar is shown, including all apps that are installed.

### Expected behaviour
The toolbar shouldn't show the installed apps, because it leaks information about the installation.
Instead, a "blank" blue toolbar could be shown, like e.g. the Polls app does for public polls.

**Comment by jancborchardt** [comment]
Yep, it should instead show the title of the form, and possibly also who the form was shared by, just like we do in files:
![Files shared view](https://user-images.githubusercontent.com/925062/59276901-74bf8100-8c5f-11e9-8450-af16e4d31d76.png)

**Comment by skjnldsv** [comment]
Partially done, we should still show the title!
