### ISSUE TITLE
Find a way to merge the two layouts base for both views

### ISSUE THREAD

**Issue by jotoeri** [nextcloud/forms#400]
Submit & Create view use the same styling for header and form/section.

-> Last point of #261

**Comment by skjnldsv** [comment]
Can you elaborate?

> -> Last point of #261

I only see "All the settings in the sidebar are bold, taking away focus and making everything look the same" ? It's not what you're referring to, right?

**Comment by jotoeri** [comment]
... it was the last remaining, non-solved point of the bug-issue. Not the last one in list.
Exact text was the following one, and it must have been you, who added it there. So maybe you have to clarify here on your own, what you meant... ;)
> Find a way to merge the two layouts base for both views (they use the same styling for header and form/section)

**Comment by skjnldsv** [comment]
Ah, it was about sharing the same views for both submit & create, but I did this already, they share the logic and components :)
