### ISSUE TITLE
[2.0.0-beta2] Error in the Logging

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/forms#403]
Under Setting -> Logging I can see the following message a lot:

[PHP] Error: Undefined index: access at /var/www/nextcloud/apps/forms/lib/Controller/ApiController.php#217
POST /apps/forms/api/v1/form/update

UnfortunatelyI can't say what the user action was that generated this error, maybe it helps...

**Comment by jotoeri** [comment]
Hey Jakob, thank you for reporting.
I think this should be the same, as the one i solved in #392, even that i got a different line-number.
Your review (even from coding side) is welcome on the PR! :)

**Comment by jancborchardt** [comment]
Merged #392, this should be fixed now. :)
