### ISSUE TITLE
Server error when accessing form via public link

### ISSUE THREAD

**Issue by fri-sch** [nextcloud/forms#405]
I created a public form and tried to access it via the link. When I'm logged in this works fine. When I'm not logged in, I get an "Internal Server Error" and the following log:

```
[index] Error: Exception: Argument 2 passed to OCA\Forms\Db\NotificationMapper::findByUserAndForm() must be of the type string, null given, called in /var/www/html/custom_apps/forms/lib/Controller/PageController.php on line 277 at <<closure>>

0. /var/www/html/lib/private/AppFramework/App.php line 125
   OC\AppFramework\Http\Dispatcher->dispatch(OCA\Forms\Controller\PageController {}, "gotoForm")
1. /var/www/html/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
   OC\AppFramework\App::main("OCA\\Forms\\Controller\\PageController", "gotoForm", OC\AppFramework\ ... {}, {hash: "vGhE5VjG ... "})
2. <<closure>>
   OC\AppFramework\Routing\RouteActionHandler->__invoke({hash: "vGhE5VjG ... "})
3. /var/www/html/lib/private/Route/Router.php line 299
   call_user_func(OC\AppFramework\ ... {}, {hash: "vGhE5VjG ... "})
4. /var/www/html/lib/base.php line 1008
   OC\Route\Router->match("/apps/forms/form/vGhE5VjGvkC6xTDE")
5. /var/www/html/index.php line 38
   OC::handleRequest()

GET /apps/forms/form/vGhE5VjGvkC6xTDE
from XX.XX.XX.XX at 2020-05-22T18:37:30+00:00
```

**Comment by jotoeri** [comment]
Hey Frieder,

thank you for reporting this. The bug itself has been tackled already, so with the next release it will be solved.
In case you need an immediate solution, @dawidol posted his solution in simple steps in issue #291.
If you want, you can alternatively install current beta of Forms v2.0. Detailed steps for this are given in #349. However, keep in mind it's not released yet, so can contain other bugs.

And just for the next time - Please search in the old issues, if your problem has been reported yet, and otherwise use the Bug-Report-Template. This makes life much easier for us to support you. ;)

Greets,
Jonas

**Comment by fri-sch** [comment]
Thanks Jonas for the fast response and for linking to the issue. I admit that I forgot to look in the closed issues for duplicates. Good to know that this has already been tackled and sorry for the noise!

**Comment by szaimen** [comment]
@jotoeri Maybe it would be good to have one of those issue reportings opened, pinn it to the top of the repository and add a label: fixed?

I think that would be the best way to prevent such reportings until forms v2 is released...

**Comment by jotoeri** [comment]
Hm, yes, i tried already. With the effect, that the user closed it by himself.^^
But let's try again! 👍  Please don't close this issue... ;)

**Comment by szaimen** [comment]
@jotoeri sry, I didn't meant to edit your changes to the labels. I tried to restore the ones that you wanted to add.

**Comment by jotoeri** [comment]
All good. 👍 We just wanted to do the same thing at the same time...^^

**Comment by szaimen** [comment]
Yes 😅

**Comment by jancborchardt** [comment]
Will be fixed in the next release, closing this so we can close the milestone. :)
