### ISSUE TITLE
Add navigation second line status

### ISSUE THREAD

**Issue by jotoeri** [nextcloud/forms#423]
@jancborchardt Can you give details on this? Which information did you have in mind?

**Comment by jancborchardt** [comment]
What would be great here is to show:
- Sharing info
- Expiration date, if one is set.

So it could say:

> **Forms survey**
> Shared to instance · expires in 7 days
> 
> **Fall camping trip!**
> Shared by link

**Comment by Chartman123** [comment]
> So it could say:
> 
> > **Forms survey**
> > Shared to instance · expires in 7 days
> > 
> > **Fall camping trip!**
> > Shared by link

@jancborchardt do you talk about the navigation on the left side where all your forms and shared forms are listed? Is it possible at all to add a second line there? I had a look at the corresponding vue element and there is only a title...

**Comment by Chartman123** [comment]
I had a look at Talk/Spreed and how they do it to display a second/sub-title line in the conversations list: 

https://github.com/nextcloud/spreed/blob/33888d4290de0500f6c50928ee957d165e51f2b3/src/components/LeftSidebar/ConversationsList/AppContentListItem/AppContentListItem.vue

They seem to use a custom AppContentListItem. So this would need some bigger changes in the Forms vue code.

**Comment by skjnldsv** [comment]
@Chartman123 incoming v4 release of the components include the component you're looking for :)
https://nextcloud-vue-components.netlify.app/#/Components/List%20items?id=listitem

**Comment by Chartman123** [comment]
@skjnldsv Thanks! But this also means that we have to rebuild the navigation, doesn't it?

**Comment by jotoeri** [comment]
But v4 is planned to contain the router-update which contains the browserlist-update, no? So we'll have to wait until we drop support for NC21... 🤔

**Comment by skjnldsv** [comment]
If we include the vue components into our babel config, we're good to go as babel will transpile it again here

**Comment by Chartman123** [comment]
> What would be great here is to show:
> 
>     * Sharing info
> 
>     * Expiration date, if one is set.
> 
> 
> So it could say:
> 
> > **Forms survey**
> > Shared to instance · expires in 7 days
> > **Fall camping trip!**
> > Shared by link

@jancborchardt what is more important here? To keep the navigation "clean" or to show all proposed information? I think that might blow the available space...

![grafik](https://user-images.githubusercontent.com/16020496/163622558-424e7b0b-134c-4a48-aaca-2b5cad4660ba.png)

**Comment by jotoeri** [comment]
@Chartman123 please keep in mind, that the sharing information will funcamentally change, once the sharing-PR is merged! So it won't be that easy anymore to categorize the sharing like this. 🤷‍♂️

**Comment by Chartman123** [comment]
Ok, so perhaps the expiration information would be enough indeed 🙂
