### ISSUE TITLE
Not possible to change radio button selection after first choice (keyboard usage)

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/forms#437]
# Steps to reproduce
1. Get the share link of a form and go through it only using the keyboard
2. Go through checkboxes, short text and long text – all works fine with Tab key and space to select.
3. Go through radio buttons now and select one answer

### Actual behaviour 
You can now not go back and change your answer for that radio choice, it seems "locked in". With mouse it’s easy to change.

### Expected behaviour
You should be able to change it by simply Shift-Tabbing back up and choosing a different answer of the radio choices.

(This is with latest master.)

**Comment by skjnldsv** [comment]
Tried using arrows?
This is the default official browser behavior with radio sets
https://www.w3.org/TR/2016/WD-wai-aria-practices-1.1-20160317/examples/radio/radio.html

**Comment by jancborchardt** [comment]
Oh, you’re absolutely right, this is also how Google Forms does it. Nothing to see here then, great job. :)
