### ISSUE TITLE
Generate Calc-Table

### ISSUE THREAD

**Issue by kaffeeringe** [nextcloud/forms#438]
It would be cool if Forms generated a Calc-table.

I would like to publish a form. People enter their data there. The data should be collected in a table. I would like to share that table with another group of people.

**Comment by jancborchardt** [comment]
Hi @kaffeeringe, could it be that you mean what is also requested at issue #5: "Write responses to Nextcloud (e.g. into spreadsheet, like Google Forms)"? :)

**Comment by kaffeeringe** [comment]
Oh, yes. I searched for calc and tables, but missed to look for spreadsheed… Sorry ;-)
