### ISSUE TITLE
File img/app.svg fails in integrity check (2.0.0-beta3)

### ISSUE THREAD

**Issue by Chartman123** [nextcloud/forms#439]
**Describe the bug**
After updating to 2.0.0-beta3 the integrity check fails because of an additional file: img/app.svg

**To Reproduce**
1. Install Forms 2.0.0-beta3
2. Go to Settings - General
3. See the error message of the file integrity check

**Expected behavior**
No error message

**Screenshots**
![image](https://user-images.githubusercontent.com/16020496/83769753-896f0300-a680-11ea-8e22-e34ac156fb2e.png)

**Nextcloud (please complete the following information):**
- Nextcloud-Version: 18.0.4
- Forms-Version: 2.0.0-beta3

**Additional context**
Docker installation

**Comment by jancborchardt** [comment]
Any idea about this @skjnldsv @jotoeri @rullzer? I did remove the app.svg via https://github.com/nextcloud/forms/pull/412/, so not sure why it’s showing up as there?

**Comment by skjnldsv** [comment]
A leftover after update? No idea :thinking:

**Comment by skjnldsv** [comment]
Also can't reproduce

**Comment by Chartman123** [comment]
Ok, perhaps because I updated the app by downloading and extracting the tar file in my apps directory?

**Comment by skjnldsv** [comment]
Yep, that is why ;)
You didn't remove the previous folder

**Comment by jancborchardt** [comment]
In that case still thanks a lot for testing @Chartman123! :) Don't hesitate to open issues if you run across anything else in the beta.
