### ISSUE TITLE
Scroll properly to required field on submit

### ISSUE THREAD

**Issue by jotoeri** [nextcloud/forms#449]
Having a required question, that is not filled, on submitting the form, the body scrolls up to show the required field. This scrolling does not take into account NC-Header, as well as question-header, so the required input as well as corresponding question are not visible.

**Comment by jotoeri** [comment]
Connected to this:
- Scroll properly to focused question on edit. NC-Header as well as question-toolbar are not taken into account there.

**Comment by skjnldsv** [comment]
Is there a potential browser standard for this?
We could use the https://caniuse.com/#feat=autofocus maybe?

**Comment by jancborchardt** [comment]
A probably very hacky fix for that could be to give the element margin-top and a negative padding-top of the same amount. This basically results in more space being above the anchor.

Would this fix the issue @jotoeri or do you think there’s a better way of doing this?
