### ISSUE TITLE
Form submission doesn't work when expiration date is set

### ISSUE THREAD

**Issue by lars-becker** [nextcloud/forms#463]
Forms can't be submitted when an expiration date is set. When sending the form the message "There was an error submitting the form✖" ist displayed and form data won't get saved. When disabling expiration everything works fine.

**To Reproduce**

1. create a simple form with title und one question
2. set as "share with link"
3. set an expiration date one week in the future
4. copy the link and open a private window, paste the link and fill out the form
5. try to submit the form. the error will be displayed
6. uncheck the expiration date option, try to submit the form. the form will be submitted.

**Nextcloud:**
- Nextcloud-Version: 19.0.0
- Forms-Version: 2.0.0-beta4

**Comment by lars-becker** [comment]
Just saw that it might be related to #462. Only searched for bugs with expiration date, so I didn't find it before reporting this bug.

**Comment by jotoeri** [comment]
Hey Lars,

thank you for reporting this! This is definitely a bug and also definitely independent of the other issue. We'll have a look onto! :)

Greets,
Jonas
