### ISSUE TITLE
Install "Forms" in nextcloud as app

### ISSUE THREAD

**Issue by Kuphi** [nextcloud/forms#465]
Is it possible to install forms like a normal app or is it necessary to follow this procedure:
1. Clone this app into the apps folder of your Nextcloud: git clone https://github.com/nextcloud/forms.git
2. In the folder of the app, run the command npm ci && npm run dev to install dependencies and build the Javascript.
3. Enable the app through the app management of your Nextcloud

I have not installed npm on my nextcloud server. Is this a requirement?
I have not found more detailed installation instructions for this app.

If it is necessary to run the command npm [...], do I have to git clone [...] or can i simply download the app in the nextcloud administrator interface, deactivate it, run the command npm [...] and activate it again?

Thank you!

**Comment by Chartman123** [comment]
Of course, you can install Forms via the App Store: https://apps.nextcloud.com/apps/forms

**Comment by Kuphi** [comment]
> Of course, you can install Forms via the App Store: https://apps.nextcloud.com/apps/forms
> 
> But please keep in mind, that this is the issue tracker for bug reports and feature requests. For support please use https://help.nextcloud.com

Thank you for the fast answer. So the result of both installation methods should be the same?

**Comment by Chartman123** [comment]
No, if you do it with npm you will get the latest development state of the app... It might of course be unstable or not run at all.

**Comment by Kuphi** [comment]
> No, if you do it with npm you will get the latest development state of the app... It might of course be unstable or not run at all.

Oh, of course. Now I got it ^^ Thank you!
