### ISSUE TITLE
Can not install forms with npm

### ISSUE THREAD

**Issue by Kuphi** [nextcloud/forms#466]
I can not install forms with npm. Nextcloud version 18.0.6 on Ubuntu 20.04 with MariaDB and Apache.

I went to /var/www/nextcloud/apps
then
`git clone https://github.com/nextcloud/forms.git`
then
```
cd forms
sudo su
npm ci
```

Error result:

```
> fsevents@1.2.11 install /var/www/nextcloud/apps/forms/node_modules/fsevents
> node-gyp rebuild

gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/var/www/nextcloud/apps/forms/node_modules/fsevents/build'
gyp ERR! System Linux 5.4.0-33-generic
gyp ERR! command "/usr/bin/node" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /var/www/nextcloud/apps/forms/node_modules/fsevents
gyp ERR! node -v v10.19.0
gyp ERR! node-gyp -v v6.1.0
gyp ERR! not ok 
```

Complete log attached:
[forms.log](https://github.com/nextcloud/forms/files/4787067/forms.log)

**Comment by jotoeri** [comment]
That's nothing forms-specific. Your npm installation needs the rights to write onto the cloned forms folder.
I think this has been 'resolved' with #465? Otherwise please have a look or ask on help.nextcloud.com.
