### ISSUE TITLE
Results and export csv impractical format

### ISSUE THREAD

**Issue by Kuphi** [nextcloud/forms#467]
The results and export csv have an impractical format.

Currently:
id | userId | voteOptionId | voteOptionText | voteAnswer | voteOptionType
-- | -- | -- | -- | -- | --
1 | robert | 1 | radio | radio1 | radiogroup
2 | robert | 2 | checkboxes | box1 | checkbox
3 | robert | 3 | short answer | short | text
4 | robert | 4 | long answer | long | comment
5 | robert | 5 | dropdown | drop1 | dropdown
6 | philipp | 1 | radio | radio2 | radiogroup
7 | philipp | 2 | checkboxes | box2 | checkbox
8 | philipp | 3 | short answer | short | text
9 | philipp | 4 | long answer | long | comment
10 | philipp | 5 | dropdown | drop2 | dropdown

Possible:
  |   | 1 | 2 | 3 | 4 | 5
-- | -- | -- | -- | -- | -- | --
id | userId | radio | checkboxes | short answer | long answer | dropdown
1 | robert | radio1 | box1 | short | long | drop1
2 | philipp | radio2 | box2 | short | long | drop2
  | voteOptionType | radiogroup | checkbox | text | comment | dropdown

The numbers in the first row and voteOptionType might be obmitted to simplify it for easier use (e.g. import to other programs and tools)

**Comment by jotoeri** [comment]
Hey Kupi,

thank you for your proposal. This has been tackled already, and will be done with the upcoming release. If you want, you can already install current beta from the appstore by setting your Nextclouds release-channel to 'beta'. Might take about half an hour then, but then you can update.
However, keep in mind, it is a beta-version and might still contain other bugs.

Greets,
Jonas
