### ISSUE TITLE
Can not edit or duplicate forms

### ISSUE THREAD

**Issue by Kuphi** [nextcloud/forms#468]
Expected behavior:
Can edit and duplicate forms

Current behavior:
Can neither edit nor duplicate forms.

Forms version: 1.1.1
Nextcloud version: 18.0.6

**Comment by jotoeri** [comment]
Hey Kupi,

thank you for your report. This has been tackled already, and will be done with the upcoming release. If you want, you can already install current beta from the appstore by setting your Nextclouds release-channel to 'beta'. Might take about half an hour then, but then you can update.
However, keep in mind, it is a beta-version and might still contain other bugs.

Greets,
Jonas

**Comment by ostasevych** [comment]
> Hey Kupi,
> 
> thank you for your report. This has been tackled already, and will be done with the upcoming release. If you want, you can already install current beta from the appstore by setting your Nextclouds release-channel to 'beta'. Might take about half an hour then, but then you can update.
> However, keep in mind, it is a beta-version and might still contain other bugs.
> 
> Greets,
> Jonas

Hi Jonas! In the 2.0.0-beta4 version I also do not see editing options. Has this functionality been already implemented?
![image](https://user-images.githubusercontent.com/5199030/85198872-5f5e4780-b2f4-11ea-99fe-475ad8907eab.png)
