### ISSUE TITLE
Viewing responses by fields

### ISSUE THREAD

**Issue by ostasevych** [nextcloud/forms#476]
**Is your feature request related to a problem? Please describe.**
By now it is possible to see the responses only record by record, which is difficult in case of a long list of responses. Viewing the responses in csv file is not enough and demands special skills and additional software to parse it. 

**Describe the solution you'd like**
Please, add additional view to see the all responses by fields. This mean, that the fields will be shown one by one, and the responses will be provided under each field.

**Describe alternatives you've considered**
Use csv file.

**Additional context**
Please, have a look how it is implemented in Google Forms.

**Comment by jotoeri** [comment]
Hey Oleksa,

seems like you are running V1.1.1 of forms, no?
There's heavy changes ongoing already and we are preparing for V2.0.0 of forms, which should include your request already. If you want, you can test current beta of these changes already, by (temporarily) setting your Nextclouds Release-channel to 'beta'. Might need to wait for half an hour, but afterwards you can install Forms V2-beta versions. However, keep in mind it is not officially released yet and may contain several bugs.

Greets,
Jonas

PS - I close this issue now, as i think its content is done on our development already. If it is not solved on beta and not solved by #460 , you're of course allowed to come back here. ;)

**Comment by ostasevych** [comment]
Hi! I use 2.0.00-beta4. I see only one view, where the responses are ordered by a respondent, but not only by fields.
![image](https://user-images.githubusercontent.com/5199030/85434046-17f2e800-b58e-11ea-9435-20a54d349a67.png)

**Comment by jotoeri** [comment]
Hey Oleksa,
yes, please see #460, this is still a work in progress and not included in beta4 yet. After this PR is merged, the next release (beta) will contain this view.
Greets,
Jonas

**Comment by ostasevych** [comment]
> Hey Oleksa,
> yes, please see #460, this is still a work in progress and not included in beta4 yet. After this PR is merged, the next release (beta) will contain this view.
> Greets,
> Jonas

Thanks! Sorry, when the official 2.0 release is expected?

**Comment by jotoeri** [comment]
We're currently trying to get the PRs and fixes done and then release. So i think within the next two or three weeks this should be the case.
