### ISSUE TITLE
Pie or Bar Chart of results

### ISSUE THREAD

**Issue by ostasevych** [nextcloud/forms#477]
**Is your feature request related to a problem? Please describe.**
Some of the results are figures necessary to be nicely presented. By now that is not possible.

**Describe the solution you'd like**
Please, add the library to parse figures and present them in the form of different charts (types may be selected by a user in a select menu: line, bar and pie.

**Describe alternatives you've considered**
Let export data for building charts in a special app, eg OnlyOffice/Collabora Online

**Additional context**
We may reuse this app somehow https://apps.nextcloud.com/apps/dashboardcharts

**Comment by jotoeri** [comment]
Same here - the bar-chart will be done with #460. Also exported data will be better usable on forms V2.
Some direct integration into other statistical apps, like Analytics we thought about already, for now you might need to use export and reimport on different tools.

Greets,
Jonas

**Comment by Rello** [comment]
https://github.com/nextcloud/forms/pull/2195

I am working to add Forms as a direct data source to Analytics.
stay tuned...
