### ISSUE TITLE
How to deal with empty responses

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/forms#482]
Sometimes during the surveys we had responses which were completely empty, that is none of the questions had any answer.

We should probably catch this, even when none of the fields are mandatory. It’s just likely an error with pressing the submit button and doesn’t really make sense to list.

I thought about cutting it out of the data at display, but what would make more sense is to already catch it on submit. What do you think @jotoeri?

**Comment by skjnldsv** [comment]
We could add a status message, like `12 questions answered out of 14`  ?

**Comment by jancborchardt** [comment]
Haven’t seen that anywhere else and it’s not really needed. The only thing we need to fix that currently it’s possible to submit a completely empty form.

**Comment by skjnldsv** [comment]
So how do you differentiate an empty question left on purpose from a mistake?

**Comment by jancborchardt** [comment]
It's about a completely empty form, not just 1 question ;)

> Sometimes during the surveys we had responses which were completely empty, that is **none of the questions had any answer**.

**Comment by jotoeri** [comment]
Hm, i think an empty form we could check on submit and just don't store then or return an error.
But i'm also not sure, if we need to avoid that, or if the possibility to submit an empty form could be used on purpose...

**Comment by jancborchardt** [comment]
> Hm, i think an empty form we could check on submit and just don't store then or return an error.

Great, that is what I meant.

> But i'm also not sure, if we need to avoid that, or if the possibility to submit an empty form could be used on purpose...

At least from our surveys, it was only annoying to have empty responses. It makes no sense to only have a username and date on it. It would even skew data if someone accidentally submitted it. Or in the case where only 1 response per person is allowed, it would prevent that person to submit their actual answer until they messaged the admin to remove that empty useless response.

Hence, let’s catch this case.

**Comment by ei8fdb** [comment]
How would this catch be displayed to the user? On the attempt to submit a completely empty form, display a message "you're trying to submit a form with no answers"? Or completely invisibly?

I'm not sure of there is a right answer here. I've used submissions that look "strange" (like this would) to get a sense of how people are responding to the form. 

I'm going to ask other researchers what they'd expect here. I'll also see how other form applications handle this.

**Comment by jotoeri** [comment]
So, as  @Chartman123 brought that topic back:
In my opinion empty responses are valid: If there are no required questions, it is valid to submit without answering and i think that could even be used on purpose (some kind of abstention, esp. if the form was shared with specified users whose response is awaited).
I could imagine for the results-view to have some specific text like 'no question answered' to make it look a bit better, and somewhen a specific form-setting, that can block such responses if set.

@ei8fdb Did you get some information on this?

**Comment by Chartman123** [comment]
How about adding a setting to the form whether empty responses should be allowed? So the creator of the form can than decide if he wants to allow completely empty responses or not.

**Comment by ei8fdb** [comment]
> So, as @Chartman123 brought that topic back:
> In my opinion empty responses are valid: If there are no required questions, it is valid to submit without answering and i think that could even be used on purpose (some kind of abstention, esp. if the form was shared with specified users whose response is awaited).
> I could imagine for the results-view to have some specific text like 'no question answered' to make it look a bit better, and somewhen a specific form-setting, that can block such responses if set.
> 
> @ei8fdb Did you get some information on this?

I've asked 4 people so far, and they've all said the empy responses should be recorded, for a number of reasons. 

When it comes to data analysis, the empty responses can (if user wishes) be discarded.

I've created...[a Nextcloud Form ( :) ) and asked on the Internet for responses](https://saneux.ei8fdb.org/apps/forms/4f7qL43DcgFsFApd).

**Comment by jancborchardt** [comment]
So @jotoeri @nimisha-vijay talked about this again briefly (thanks for the input @ei8fdb :) and we were thinking a simple modal/question asking if they want to submit an empty form would be good. Cause this catches if it was actually a mistake – e.g. if people are used to multi-step forms and think this is the "Start form" button, or for any other reasons.

This way it’s not hard blocked but more like the "Send without attachment?" notice in an email app.

**Comment by ei8fdb** [comment]
> So @jotoeri @nimisha-vijay talked about this again briefly (thanks for the input @ei8fdb :) and we were thinking a simple modal/question asking if they want to submit an empty form would be good. Cause this catches if it was actually a mistake – e.g. if people are used to multi-step forms and think this is the "Start form" button, or for any other reasons.

Yup I guess that'd work (a question, do you want to submit an empty form).

I'm still unclear as to what problem this is trying to solve.

In the simple survey below, it is very clear the number of empty responses I have received:

![Screenshot_20210421-145448.jpg](https://user-images.githubusercontent.com/1899506/115557179-c3092680-a2b1-11eb-9a22-cb6a8d1db398.jpg)
![Screenshot_20210421-145443.jpg](https://user-images.githubusercontent.com/1899506/115557295-dc11d780-a2b1-11eb-87b8-a8982aca9f20.jpg)

As the survey creator, I can use this data (i.e. a high number of empty responses) to understand how my survey is performing. 

Have I asked the right questions? Do participants understand what I am asking? Have I missed an option?

**Comment by Chartman123** [comment]
> a simple modal/question asking if they want to submit an empty form would be good

I agree that a question for the user would be a good solution. And form creators that don't want to allow completely empty submissions just need to add at least one required question. This would then also apply to submissions that are sent via tha API.
