### ISSUE TITLE
unable to save form

### ISSUE THREAD

**Issue by tasstra** [nextcloud/forms#486]
Whatever i try, when i want to save a form i get an alert with "all questions need answers" although i provided answers.
Nextcloud 18.0.6

**Comment by jotoeri** [comment]
Hey tasstra,

please use the provided template to report an issue and provide enough information for us to exactly(!) understand what you are doing. As this is not the case here, i will close this issue.
However, i assume you are using V1.1.1 of forms, where you need to press enter to store the answers you provided.

Greets,
Jonas
