### ISSUE TITLE
Not possible to enter question answer (checkbox/radio button)?

### ISSUE THREAD

**Issue by kubajznik** [nextcloud/forms#490]
I am not able to enter an answer for the checkbox. Am I missing something?
![image](https://user-images.githubusercontent.com/35335130/86350913-b3a5e780-bc63-11ea-9cd4-8cf3215d1da3.png)
If I click the input field, I can't type.

- Nextcloud-Version: 19.0.0
- Forms-Version: e.g. 2.0.0-beta4

 - Windows 10
 - Chrome

**Comment by skjnldsv** [comment]
Yes, there is a bug :)
https://github.com/nextcloud/forms/pull/484

**Comment by jotoeri** [comment]
@kubajznik are you running beta4 or on master? As on beta4, the tabbable-thing should not be in, yet...

**Comment by kubajznik** [comment]
@skjnldsv Oh right sorry. I read that I think but I understood #484 the other way around - I figured there the bug is that tabbing doesn't work, just mouse. For me mouse doesn't word. Anyways, thanks!

**Comment by jancborchardt** [comment]
Fixed by #484 :)
