### ISSUE TITLE
Error 404 on screenshots on https://apps.nextcloud.com/apps/forms

### ISSUE THREAD

**Issue by tgurr** [nextcloud/forms#497]
e.g. https://raw.githubusercontent.com/affan98/forms/master/screenshots/Vote.PNG

The homepage link also points to https://github.com/affan98/forms instead of https://github.com/nextcloud/forms.

**Comment by skjnldsv** [comment]
@rullzer you have admin rights to the appstore?
cc @jancborchardt

**Comment by jancborchardt** [comment]
This will be fixed with the upcoming release end of this month, so nothing we need to worry about now I’d say?

**Comment by jancborchardt** [comment]
Will be fixed in the upcoming release, closing this so we can close the milestone. :)
