### ISSUE TITLE
Use the multiselect component in dropdown component

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/forms#498]
> Because the call on whether to use the multiselect component or its own component has changed around so much, I’d prefer if you can create that follow-up issue with the relevant info. :)

That would make the create preview also be the same as what the real final form would look like :rocket:

cc @jancborchardt
_Originally posted by @skjnldsv in https://github.com/nextcloud/forms/pull/461#pullrequestreview-443725230_

**Comment by Chartman123** [comment]
> That would make the create preview also be the same as what the real final form would look like rocket

@skjnldsv Do you mean that the component should be used to add new options, too, or only for the "real" preview as long as you're not in the edit mode for the options? Because I couldn't find a way to add new options directly within the Multiselect component other than for tags.
