### ISSUE TITLE
Write responses into spreadsheet (like Google Forms)

### ISSUE THREAD

**Issue by mapson01** [nextcloud/forms#5]
if the CSV file is storage on the nextcloud instance it can be process with another app called  "workflow external script" make a automatic form processing. 
the idea to set a file path/name in the form configuration 
thanks this app is the "piece missing in the puzzle" !!!

cheers
maps

**Comment by jancborchardt** [comment]
Also from https://github.com/nextcloud/forms/issues/263

> [As mentioned by @forteller](https://github.com/nextcloud/forms/issues/34#issuecomment-606182611)
> 
> > And if the results could automatically be added to a editable document as the come in, instead of having to first export it, that would be really great. That's one of the huge advantages of Google Forms.

**Comment by thibault649** [comment]
> if the CSV file is storage on the nextcloud instance it can be process with another app called "workflow external script" make a automatic form processing.
> the idea to set a file path/name in the form configuration
> thanks this app is the "piece missing in the puzzle" !!!
> 
> cheers
> maps

Any clue for doing an automatic form processing please ?

**Comment by Lionel-cl** [comment]
That would be great for my current project. I need to configure a registration form in a web page.
It would be nice to have 2 buttons near each response to accept / decline the request and start a flow. ex: create a user with specific rights in NC, add an user to a group, ...
Can I have an approximate date of availability of such a feature? 
Thanks for your app,
LC

**Comment by skjnldsv** [comment]
> Can I have an approximate date of availability of such a feature?

No ETA. This pr is also not about you're requesting. Sorry, this is off-topic :)

**Comment by pascoual** [comment]
Any news ?
Tx.

**Comment by jotoeri** [comment]
#780 for manual export to csv into cloud, automatic export and directly to spreadsheet might still take a while (see Milestone 3.0!).

**Comment by yehudaclinton** [comment]
It should be able to write data into an existing spreadsheet with custom functions

**Comment by SemaphoreOxalis** [comment]
Hi, Any news about this because it's still a big dealbreaker for our clients to move out to Google.

**Comment by jdaviescoates** [comment]
This is the killer feature of Google Forms.  I really hope it comes to Nextcloud Forms one day soon!
