### ISSUE TITLE
Using form with public link doesn't work.

### ISSUE THREAD

**Issue by piiskop** [nextcloud/forms#506]
**Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!**

**Describe the bug**
Using form with public link doesn't work.

**To Reproduce**
1. Create a form and set the access to public!
2. In the list of forms, copy the link of the form created in the step _1_!
3. Open a private browser window and go to the address you copied in the step _2_!
4. See error:
"Internal Server Error

The server was unable to complete your request.

If this happens again, please send the technical details below to the server administrator.

More details can be found in the server log.
Technical details

    Remote Address: 192.168.1.65
    Request ID: fzeC7hqEk6qScRFtTBD9"
"/projektid/nextcloud/data$ tail nextcloud.log":
"{"reqId":"fzeC7hqEk6qScRFtTBD9","level":3,"time":"2020-07-12T01:16:44+00:00","remoteAddr":"192.168.1.65","user":"--","app":"index","method":"GET","url":"/index.php/apps/forms/form/hxUBuSfzLDotZlXw","message":{"Exception":"Exception","Message":"Argument 2 passed to OCA\\Forms\\Db\\NotificationMapper::findByUserAndForm() must be of the type string, null given, called in /projektid/nextcloud/apps/forms/lib/Controller/PageController.php on line 277","Code":0,"Trace":[{"file":"/projektid/nextcloud/lib/private/AppFramework/App.php","line":125,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Forms\\Controller\\PageController"},"gotoForm"]},{"file":"/projektid/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Forms\\Controller\\PageController","gotoForm",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"hash":"hxUBuSfzLDotZlXw","_route":"forms.page.goto_form"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"hash":"hxUBuSfzLDotZlXw","_route":"forms.page.goto_form"}]},{"file":"/projektid/nextcloud/lib/private/Route/Router.php","line":299,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"hash":"hxUBuSfzLDotZlXw","_route":"forms.page.goto_form"}]},{"file":"/projektid/nextcloud/lib/base.php","line":1008,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/forms/form/hxUBuSfzLDotZlXw"]},{"file":"/projektid/nextcloud/index.php","line":38,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/projektid/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","Line":109,"Previous":{"Exception":"TypeError","Message":"Argument 2 passed to OCA\\Forms\\Db\\NotificationMapper::findByUserAndForm() must be of the type string, null given, called in /projektid/nextcloud/apps/forms/lib/Controller/PageController.php on line 277","Code":0,"Trace":[{"file":"/projektid/nextcloud/apps/forms/lib/Controller/PageController.php","line":277,"function":"findByUserAndForm","class":"OCA\\Forms\\Db\\NotificationMapper","type":"->","args":[1,null]},{"file":"/projektid/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":170,"function":"gotoForm","class":"OCA\\Forms\\Controller\\PageController","type":"->","args":["hxUBuSfzLDotZlXw"]},{"file":"/projektid/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":99,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Forms\\Controller\\PageController"},"gotoForm"]},{"file":"/projektid/nextcloud/lib/private/AppFramework/App.php","line":125,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Forms\\Controller\\PageController"},"gotoForm"]},{"file":"/projektid/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Forms\\Controller\\PageController","gotoForm",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"hash":"hxUBuSfzLDotZlXw","_route":"forms.page.goto_form"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"hash":"hxUBuSfzLDotZlXw","_route":"forms.page.goto_form"}]},{"file":"/projektid/nextcloud/lib/private/Route/Router.php","line":299,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"hash":"hxUBuSfzLDotZlXw","_route":"forms.page.goto_form"}]},{"file":"/projektid/nextcloud/lib/base.php","line":1008,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/forms/form/hxUBuSfzLDotZlXw"]},{"file":"/projektid/nextcloud/index.php","line":38,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/projektid/nextcloud/apps/forms/lib/Db/NotificationMapper.php","Line":65},"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0","version":"18.0.6.0"}"

**Expected behavior**
The form will be displayed.

**Nextcloud (please complete the following information):**
- Nextcloud-Version: 18.0.6
- Forms-Version: 1.1.1

**Desktop (please complete the following information):**
 - OS: Ubuntu Server 18.04
 - Browser Firefox or Chrome, actually any

**Browser log**
```

JQMIGRATE: Migrate is installed, version 1.4.1 jquery-migrate.min.js:2:551
This page uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”. addStylesClient.js:220:17
Handlebars is deprecated: please ship your own, this will be removed in Nextcloud 20 globals.js:66:15
Uncaught TypeError: r is undefined
    f routing.js:143
    <anonymous> viewer.js:23
    Webpack 3
routing.js:143:42
Successfully compiled asm.js code (total compilation time 80ms) libsignal-protocol.js
pre-main prep time: 3 ms libsignal-protocol.js:136:15
Handlebars is deprecated: please ship your own, this will be removed in Nextcloud 20 globals.js:66:15

​


```

**Comment by skjnldsv** [comment]
Fixed with upcoming version, please try the new beta #226
