### ISSUE TITLE
Form can't be edited.

### ISSUE THREAD

**Issue by piiskop** [nextcloud/forms#507]
**Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!**

**Describe the bug**
Forms can't be edited.

**To Reproduce**
1. Create a form!
2. In the list of forms, there's no option for editing!
**Expected behavior**
There's an option to edit created forms.

**Nextcloud (please complete the following information):**
- Nextcloud-Version: 18.0.6
- Forms-Version: 1.1.1

**Desktop (please complete the following information):**
 - OS: Ubuntu Server 18.04
 - Browser Firefox or Chrome, actually any

**Comment by skjnldsv** [comment]
Fixed in incoming release
