### ISSUE TITLE
Error 401 "Unauthorized " accessing /apps/forms/api/v1/form/{id}

### ISSUE THREAD

**Issue by Pilzinsel64** [nextcloud/forms#509]
Hello.

My plan is to include one of my public forms "Bug Report" into my program. I don't want to embed it as IFrame or in a WebBrowser control. I want to get the form data with questions and built the userinterface in my program. 

I hoped to be able to get a form (and it's questions) using the API and also sumbit a response. But it seems that I have to login for that. But that would confuse me, since the form is public.

I used the first two files of this comment to start: https://github.com/nextcloud/forms/issues/451#issuecomment-655433791 (using the first two refered files)

This is my current test code (C#):
![grafik](https://user-images.githubusercontent.com/23138465/87451119-b8718080-c5ff-11ea-9f36-6f74f287720f.png)

What I am doing wrong? Or should I make use somehow of this few API calls? https://github.com/nextcloud/forms/blob/769e8639a54cd8e06a6f9f3f06d612d2f2ba2bda/appinfo/routes.php#L31-L37

> Maybe first do a request to getForm($id) to get an impression of the Object-Structure (same to getSubmissions($hash)?). You need to be authenticated as the owner of the form for that.

Or would that explain my problem? And if yes, how could I go around, without login?

**Comment by skjnldsv** [comment]
You need a CSFR token. This is not a public API

**Comment by Pilzinsel64** [comment]
I use v2.0 Beta 4.

On accessing the URL you can see in the textbox in the screenshot I get an error message without the ability to access the response. If I access the same URL with the browser, you [get this](https://pilzinsel64.com/pilzcloud/apps/forms/api/v1/form/ofHSSw92E5sMBPqH): Access Denied, CSRF check failed.
![image](https://user-images.githubusercontent.com/23138465/87525880-61fd5400-c68a-11ea-9119-51b3ae63d2cd.png)

I used this function:
https://github.com/nextcloud/forms/blob/769e8639a54cd8e06a6f9f3f06d612d2f2ba2bda/appinfo/routes.php#L42

**Comment by skjnldsv** [comment]
You need to be authenticated, even as a guest.

**Comment by Pilzinsel64** [comment]
Hm... the only way to do this then would be to create an account for my application.
But I don't really like this way and embedding the public page into an WebBrowser control I also don't like since Internet Explorer is bad.

So, my feature request: Make it possible to access public forms and submit a result with the API without authentication.
But I guess it isn't possible for security reasons.

However, thank you very much for your help anyway. At least now I know that I can stop trying it anymore. 😉
