### ISSUE TITLE
CSV results are horizontal

### ISSUE THREAD

**Issue by azmiplg78** [nextcloud/forms#514]
I did not find any editing facilities after completing for, after I tried to fill in the form, the CSV results should be horizontal, not vertical. As in the Google form

**Comment by jancborchardt** [comment]
@skjnldsv @jotoeri aren’t we using the same CSV format as Google Forms? cc @jospoortvliet 

@azmiplg78 can you open a separate issue about the "Ability to edit after filling a form" issue?

**Comment by jancborchardt** [comment]
cc @simmstein as well ^

**Comment by skjnldsv** [comment]
No idea @jancborchardt :shrug:

**Comment by jotoeri** [comment]
@jancborchardt Sounds to me like V1.1.1., mixing up two different things that are both solved already.

@azmiplg78 Can you please tell us, which version of forms you are running? Please, next time use the provided issue template and properly describe your problem, so we don't have to guess your problem & setup.

**Comment by jancborchardt** [comment]
Closing as in 2.0 we are using the Google Forms format.

**Comment by azmiplg78** [comment]
> @jancborchardt Sounds to me like V1.1.1., mixing up two different things that are both solved already.
> 
> @azmiplg78 Can you please tell us, which version of forms you are running? Please, next time use the provided issue template and properly describe your problem, so we don't have to guess your problem & setup.

Version 1.1.1, I install from the nextcloud application

**Comment by azmiplg78** [comment]
> can you open a separate issue about the "Ability to edit after filling a form" issue?

oke, i will create separate from

**Comment by jotoeri** [comment]
> how I can update via nextcloud ?

Changing your NCs release channel to 'beta' enables you to update to current Release-candidate. Might need half an hour after changing the channel. Or just wait until next week for the release. ;)

**Comment by azmiplg78** [comment]
> > how I can update via nextcloud ?
> 
> Changing your NCs release channel to 'beta' enables you to update to current Release-candidate. Might need half an hour after changing the channel. Or just wait until next week for the release. ;)

thanks for the update info, I'm waiting for the next release

**Comment by azmiplg78** [comment]
> Changing your NCs release channel to 'beta' enables

- How i can Changing your NCs release channel to 'beta' enables, because iam newbie in nextcloud, 
- I have downloaded Forms 2.0.0-rc.1.gz, how to install in nextcloud, is it possible to repalace the app

**Comment by jotoeri** [comment]
>     * How i can Changing your NCs release channel to 'beta' enables, because iam newbie in nextcloud,

In Admin-Settings search for the Section about your NCs version, There you should see a dropdown list, which enables you to choose 'beta'.

**Comment by azmiplg78** [comment]
> In Admin-Settings search for the Section about your NCs version, There you should see a dropdown list, which enables you to choose 'beta'

Thanks for your's advise
