### ISSUE TITLE
Ability to edit after filling a form

### ISSUE THREAD

**Issue by azmiplg78** [nextcloud/forms#515]
I did not find any editing facilities after completing for on form version 1.1.1 ?

**Comment by jotoeri** [comment]
Ok, sorry, @azmiplg78. Please use the provided feature-template and describe properly, what you do and which behaviour you would expect.

**Comment by azmiplg78** [comment]
> Ok, sorry, @azmiplg78. Please use the provided feature-template and describe properly, what you do and which behaviour you would expect.

I used the template in version 1.1.1,
- Make Form
- Answer Type: Radio Buttons, Checkboxes, Short Response, Long Respone, Drop-Down

After everything was complete, and complete, I suddenly wanted to edit, but I couldn't because there was no edit button I could find.

Input from me:
- Answer Type that is still maintained: Radio Button, Checkbox, DropDown
- Answer Type that needs to be added: add files (documents, photos, videos), add links

**Comment by jotoeri** [comment]
Ok, i mean the feature-template here on github. Clicking on 'New Issue' and choosing 'Feature request' you get an prefilled text-area, which is the template, i ask you to use. If you fill these questions it is just much easier for us to understand what you want and what your setup is. If we need to guess, we could just do everything, but not what you want to ask for.

However, from the steps in your last comment i can at least guess, that you created a form on V1.1.1. and want to edit e.g. the question afterwards or add one more question? This will be possible in V2 with the upcoming release. So i would just say let's wait for next week and come back then, if necessary?

**Comment by azmiplg78** [comment]
> Ok, what i mean is the feature-template here on Github. Clicking on 'New Issue' and choosing 'Feature request' you get an prefilled text-area, which is the template, i ask you to use. If you fill these questions it is just much easier for us to understand what you want and what your setup is. If we need to guess, we could just do everything, but not what you want to ask for.
> 
> However, from the steps in your last comment i can at least guess, that you created a form on V1.1.1. and want to edit e.g. the question afterwards or add one more question? This will be possible in V2 with the upcoming release. So i would just say let's wait for next week and come back then, if necessary?

Thank you for the positive response, I will try to review later in the next version
