### ISSUE TITLE
Use php constant to list available questions

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/forms#524]
@jotoeri would be nice to have those coming from something like a const somewhere instead of being hardcoded there? :)
What do you think?

https://github.com/nextcloud/forms/blob/25bd1bd84c608ed55dde8f983a2953eb92cf983d/lib/Controller/ApiController.php#L730-L732

_Originally posted by @skjnldsv in https://github.com/nextcloud/forms/pull/520#discussion_r461344331_

**Comment by jotoeri** [comment]
Further provide this list to 
https://github.com/nextcloud/forms/blob/25bd1bd84c608ed55dde8f983a2953eb92cf983d/src/components/Results/Summary.vue#L31
