### ISSUE TITLE
Request Feature's

### ISSUE THREAD

**Issue by azmiplg78** [nextcloud/forms#526]
Dear Team Form
I just tried form version 2.0, it can be edited, it's more flexible and looks better than the previous version.
I have a request, hopefully this request creates a form for nextcloud, better than Google's form:
- add question "Date/Time"
- Can change the background color or can wallpaper
- Can change the color or header wallpaper
- Can add files (Document, Photo, movie, etc.), Folder integrated with nextcloud folder
- Can export to Excel, PDF format
- Can be integrated into onlyoffice spreadsheets
Thank you very much for updating to a better version

**Comment by skjnldsv** [comment]
Hey! Thanks for this! :hugs: 
A lot of your suggestions have dedicated issues already :)

* add question "Date/Time": #499
* Can add files (Document, Photo, movie, etc.), Folder integrated with nextcloud folder #42
* Can export to Excel, PDF format #103 #5 

Please create dedicated issues ber suggestion for the one that I haven't mentioned above :wink: 
Please also make sure to do a quick search to check if there isn't already one! Thanks a lot for your help, this will help track things properly!

**Comment by skjnldsv** [comment]
I'll leave this one opened while you create the other issues, please close it when you're done :)

**Comment by azmiplg78** [comment]
> Please create dedicated issues ber suggestion for the one that I haven't mentioned above 😉
> Please also make sure to do a quick search to check if there isn't already one! Thanks a lot for your help, this will help track things properly!

Sorry before, it turns out that there has been an issue in the nextcloud form forum, roughly when it can be realized, we lovers of open source are waiting for it. Thank you for the hard work of the form team

**Comment by skjnldsv** [comment]
Hey @azmiplg78, I don't understand your message :)
