### ISSUE TITLE
2.0.0 update loose forms history

### ISSUE THREAD

**Issue by tarradmac** [nextcloud/forms#527]
**Describe the bug**
I have update the forms app and I loose all the existing forms.
I just found a log warning message “Answer-text is too long for new Database:”
I saw that the new forms add new database tables and do a migration from the old one and I can find my old datas. The data seems to be in the new table. I can create a new form but olders are not visible.

I try to delete the new version and manually install the v1.1.1, my forms came back on my instance, but there is and error on accessing due to oc_forms_notif table not found.

**Nextcloud:**
- Nextcloud-Version: 18.0.7 stable branch
- Forms-Version: 2.0.0

**Comment by skjnldsv** [comment]
@jotoeri, what shall we do? cut?
cc @nickvergessen for assistance :)

**Comment by jotoeri** [comment]
Hey @tarradmac can you provide us some more information? Is there some more forms-related stuff written on your logs?
That warning should normally not kill the whole migration...

@skjnldsv Should normally be done already... https://github.com/nextcloud/forms/blob/44b73cfa1fcd6c7d694c5d7b5c93794727285306/lib/Migration/Version010200Date20200323141300.php#L355

**Comment by nickvergessen** [comment]
substr is not sufficient as it is not utf8 aware, see https://github.com/nextcloud/server/pull/19634

**Comment by jotoeri** [comment]
Uh, ok... 👍  Thanks @nickvergessen. I will do a pr...

**Comment by jotoeri** [comment]
@tarradmac - Still, to avoid more shit now - do you have access to your db and can look up there, which data is inside already?

**Comment by tarradmac** [comment]
@jotoeri  - I checked the log and the only message related to the update was the warning answer-text is too long for new database.

I desactivate and delete  the forms app, drop all oc_forms_v2** table and do the v2.0.1 installation, no message during the installation, but when I click on the app, I get a error "an error occur while getting forms". I check that the apps didn't create the v2 tables. 
How can I force the migration?

**Comment by skjnldsv** [comment]
> How can I force the migration?

Delete the migration 'Version010200Date20200323141300' in the migration table of your database.
Then start again

**Comment by tarradmac** [comment]
@skjnldsv Thanks for the trick, I did the install again and I get the same result, only one message in nextcloud.log "warning Answer-text is too long for new Database".
And when I go to the forms app the windows is blank, no history.
I check also that all new tables are filled.

**Comment by skjnldsv** [comment]
@tarradmac please test this release 
[forms.tar.gz](https://github.com/nextcloud/forms/files/5000977/forms.tar.gz)

**Comment by tarradmac** [comment]
@skjnldsv I install the v2.0.2 and no more warning in the nextcloud.log, but my forms are not shown in the forms app...
All the table are filled with data.
I have activated the debug log and no message for forms...
I create a new form to test and all is working, the data is correctly filled in the database, but my old forms are not shown.

**Comment by jotoeri** [comment]
Ah - @tarradmac who is the owner of your forms? Same NC-Account as the one you are logged in with?
While on V1.1.1 you always saw all existing forms, on V2 for security/privacy reasons you do only see the forms, that you created with your account!

**Comment by tarradmac** [comment]
@jotoeri 
Oo
I am a bit ashamed, I not the owner of the forms. I can't check now for other users, they are on holidays. 
By the way I really like this new version, great job.

**Comment by jotoeri** [comment]
Ahh, ok. Perfect. 👍 
So i think as you can create forms everything should be working.
Don't be ashame - it's an interesting feedback, maybe we should just have communicated that somewhere... ;)
