### ISSUE TITLE
Increase the size of the form description field (allow longer text)

### ISSUE THREAD

**Issue by samtuke** [nextcloud/forms#529]
**Nextcloud (please complete the following information):**
- Nextcloud-Version: 19.0.0
- Forms-Version: 2.0.0

Please increase the field size of the form description. My use case is putting a legal agreement text into a form (a contributor license agreement, like the [Software Freedom Conservancy](https://docs.google.com/forms/d/e/1FAIpQLSd2FsN12NzjCs450ZmJzkJNulmRC8r8l8NYwVW5KWNX7XDiUw/viewform?hl=en_US&formkey=dFFjXzBzM1VwekFlOWFWMjFFRjJMRFE6MQ#gid=0) uses). 

Therefore I want to put the main contract text somewhere in the form, and the description seems like a good place, except that the content length is too great, and the text is currently truncated due to the arbitrary limit.

**Comment by jotoeri** [comment]
Hey @samtuke,
Thank you for your feedback! - May i ask how long your description is? So which length would you expect to be able to fill in? Currently forms should allow 2048 chars on description, while the linked text is just ~1/4 of that?

Greets, :)
Jonas

**Comment by samtuke** [comment]
Tahnks for asking. Yes - in our case the length is 4,903. 

FWIW this is the same CLA text used by [ownCloud](https://owncloud.org/wp-content/uploads/2018/01/ownCloud-copyright-assignment-common-1.pdf), [phpList](https://phplist.com/cla), and I guess some others.

**Comment by skjnldsv** [comment]
@jotoeri doable?

**Comment by jotoeri** [comment]
Sure - it's small migration and a changed number in code.
Feels to me somehow a bit overkilled to set 8192 chars as maxlength, but seems indeed reasonable for such (specific) usecase... 👍

**Comment by skjnldsv** [comment]
Awesome! Thanks!
