### ISSUE TITLE
iOS layout and submission bug

### ISSUE THREAD

**Issue by auviolon** [nextcloud/forms#532]
**Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!**

**Describe the bug**
After completing the first box, some text overflows to the right side, scrolling is not possible. The submit-button disappears from the displayed part of the page.

**To Reproduce**
1. Click on a public link, sent by e-mail.
2. See the form displayed normally.
3. Enter something in the first textbox.
4. See the problem like described above

**Expected behavior**
The page content should not overflow to the right.

**Screenshots**
| before | after |
| ---------------------- | ----------------------------------- |
| ![image2](https://user-images.githubusercontent.com/51053759/88855385-118e0680-d1f3-11ea-8eee-e8b91e05ca2c.png) | ![image3](https://user-images.githubusercontent.com/51053759/88855443-28345d80-d1f3-11ea-9814-b7a3ad512853.png) |

**Nextcloud:**
- Nextcloud-Version: 19.0.1
- Forms-Version: 2.0.0

**Smartphone**
 - Device: iPhone 11
 - OS: iOS 13.5.1
 - Browser Safari

**Comment by auviolon** [comment]
Realised that there is already an issue about this #523 but I have to add that on my colleague's I-Phone this made it unable for him to submit the form because scrolling to the right is impossible.

**Comment by idecable** [comment]
See my post in https://github.com/nextcloud/forms/issues/523 tested and works for me.
