### ISSUE TITLE
Optional name on anonymous answeres by link

### ISSUE THREAD

**Issue by leaderred** [nextcloud/forms#534]
**Nextcloud (please complete the following information):**
- Nextcloud-Version: 18.0.7
- Forms-Version:  2.0.1

**Is your feature request related to a problem? Please describe.**
If you have share a form by link, it is always anonymous. You can't get an account for every member or friend. So when you have a form, you can't see, which people have answered and who has not answered. This form could way more flexible, when you can require or made optional name input of the person.

**Describe the solution you'd like**
Add an form field to enter a name und take the current option "anonymous" to make it required or not. So you can separate answeres. Of course there is alwas the possibility, that people fill in fake names, but normaly people will insert a name, that you can work with.

**Comment by skjnldsv** [comment]
Hello!

Why not add this as a field in the form itself?

**Comment by leaderred** [comment]
> Hello!
> 
> Why not add this as a field in the form itself?

Sorry, my vault. I haven't thought of this option. Thank you

**Comment by skjnldsv** [comment]
You're welcome!
No faults here! :hugs:
