### ISSUE TITLE
"Mehrfachauswahl" (Multi select) allows only a single selection

### ISSUE THREAD

**Issue by uli-heller** [nextcloud/forms#540]
**Describe the bug**
Adding a question of type "Mehrfachauswahl"  (multi selection) create a form where you can select just a single item:

![image](https://user-images.githubusercontent.com/1677414/89258837-4225d400-d629-11ea-9535-eb29b1df36d6.png)

![image](https://user-images.githubusercontent.com/1677414/89258813-363a1200-d629-11ea-818f-87576fe14d30.png)

I think the labels are quite misleading. The topmost item labeled "Kontrollkästchen" (control boxes) provides a multi selection.
"Mehrfachauswahl" (multi selection) actually provides a "single selection"

**Comment by stefan-niedermann** [comment]
Thank you for the hint 🙂 We already noticed it and changed the translation upstream in Transifex. I guess this will be fixed with the next released version.

**Comment by jotoeri** [comment]
https://github.com/nextcloud/forms/commit/5384dee315bc6b4f007faf86f5274e84b10e8c04 :)
