### ISSUE TITLE
Send email invitation for user share

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/forms#541]
For the user share, we should send an invitation, like calendar, mails, sharing... etc

**Comment by susnux** [comment]
Email notifications for user shares are already configurable using the notifications apps, so not sure if we really need a separate implementation for this, especially as users then would have to configure they do not want emails twice (in `/settings/user/notifications` and in `/settings/user/forms`). This would also require a per-user settings page.

**Comment by Chartman123** [comment]
@susnux I just found your comment here... yes, for me it's totally fine to close this one as not planned as it's already available through the notifications app.
