### ISSUE TITLE
Only one answer is rendered in bold when you have a tie on first place,

### ISSUE THREAD

**Issue by c-cesar** [nextcloud/forms#542]
**Describe the bug**
If the first place in a choice question is a tie, only one is rendered in *bold* letters

**To Reproduce**
* Create a chioces question
* Answer creating a tie of votes on the first place
* Go to answers page
**Expected behavior**
All firsrt place options should be bold

**Screenshots**
![image](https://user-images.githubusercontent.com/350914/89297555-735ad000-d63a-11ea-803a-edefcb47f5b1.png)

**Nextcloud (please complete the following information):**
- Nextcloud-Version: 18.0.7
- Forms-Version: 2.0.2

**Comment by ei8fdb** [comment]
I can understand the useful visual enhancement of having the first place answer being in bold. To me there seems to be 2 options here:

1. When there is a tie, for all options that share 1st place make them bold, like @c-cesar says.
2. Don't make anything bold, and rely the user to realise there is a tie (based on in your case 3 (33%))
3. Visually call out the fact there is a tie, maybe have this on a line above/below the results. 

Although I think it's important to mention that the "first place" answer isn't always the most important part of the results.
