### ISSUE TITLE
"help" button goes to bad URL - can you restore that URL?

### ISSUE THREAD

**Issue by markgalassi** [nextcloud/forms#544]
**Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!**

**Describe the bug**
hitting the "Help" button goes to a dead URL:

https://github.com/nextcloud/forms/blob/master/Forms_Support.md

**To Reproduce**
1. Go to 'the forms in a nextcloud instance'
2. Click on 'Help'

**Expected behavior**
It should go to a web page with the manual (in my case I was going to look for how to edit a form you've already made).

**Screenshots**

**Nextcloud (please complete the following information):**
- Nextcloud-Version: I cannot tell: it's kind of buried
- Forms-Version: The Forms page does not show the version inside my nextcloud instance

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Comment by jotoeri** [comment]
Hey markgalassi,

i would recommend to update your forms-version to current V2 (or ask your NC-Admin to do so)! As current version does not have this help-button, this file is also not existent anymore. Further effect: While editing is not possible on your installed version, on Forms-V2 it will be easily possible to edit a form. 👍 

Greets,
Jonas


@skjnldsv I'd close this, as it is for V1.1.1?

**Comment by skjnldsv** [comment]
> @skjnldsv I'd close this, as it is for V1.1.1?

Right, sorry ^^'
Missed this :)

Thanks!
