### ISSUE TITLE
translation german has a little error

### ISSUE THREAD

**Issue by fds2610** [nextcloud/forms#550]
**Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!**

**Describe the bug**
in german the Words "Mehrfachauswahl" und "Kontrollkästchen" sind nicht eindeutig.

**Expected behavior**
ich würde "Kontrollkästchen" in "Mehrfachauwahl" ändern und "Mehrfachauswahl" in "Einfachauswahl".

**Nextcloud (please complete the following information):**
- Nextcloud-Version: [ 19.0.1]
- Forms-Version: [ 2.0.2]

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Firefox
 - Version 79

**Comment by skjnldsv** [comment]
see #540
