### ISSUE TITLE
Repeatable Section

### ISSUE THREAD

**Issue by kevin147147** [nextcloud/forms#551]
**Nextcloud (please complete the following information):**
- Nextcloud-Version: [e.g. 19.0.0]
- Forms-Version: [e.g. 2.0.0-beta4]

**Describe the solution you'd like**
I'd love to have a section of questions to be repeatable.

**Comment by skjnldsv** [comment]
What do you mean by repetable? Like duplicate questions?
What is the sue case, I fail to see how this would be useful :)

**Comment by kevin147147** [comment]
Like a form about injuries. I could make a repeatable section of multiple questions. At the end of the section an "add injury" button would appear.

**Comment by skjnldsv** [comment]
Ah, this is out of scope to be honest. This is far beyond a simple form app should support imho.
This calls for a dedicated app :)
