### ISSUE TITLE
Document API

### ISSUE THREAD

**Issue by pieter-groeneweg** [nextcloud/forms#553]
Nextcloud-Version: 19.0.1
Forms-Version: 2.0.2
I like to see this app evolving. My future intent is to use the app to create entry forms for sports events.

When someone submits an entry, the owner of the form can see the results in the nextcloud instance.
It would be a very nice feature to have either one or both:
- share a link to the results with the possibility to turn on/off the visibility of the fields (GDPR may require)
- have an restfull link to the results with the possibility to turn on/off the visibility of the fields (GDPR may require) returning a json or xml that can be reused in any other app. Maybe something like the calendar app. This app has a dynamic export link.
There is a .csv export already. Maybe this can be reused?

**Comment by skjnldsv** [comment]
I would expose the api for this, to be honest, so you can retrieve whatever data you want with proper authentication. But that would be as far as we should go. If you want to build a dedicated app that uses this data to display results live on a screen or whatever use you'd have for your sport event, that would be up to your implementation :)

What do you think?

**Comment by pieter-groeneweg** [comment]
May be. But then it would publish all fields right? I need to see first how it behaves then.
Do you have an example of a CURL request for the forms app?

on https://domain.com/index.php/apps/forms/api/v1/form/whateveritis
and authorisation Username and Password set I get : "message": "CSRF check failed"
(using Postman)
But I may need to have more set? request headers?

**Comment by skjnldsv** [comment]
Yep, I'm migrating this to a proper ocs api standard #556 
You'll be able to use the data. Other than this, we won't customize output. This would be your job as an external app developer :)

**Comment by pieter-groeneweg** [comment]
Meaning there is no API access ,yet, for forms till milestone 2.1? 
Ok thanks, I'll need to be patient. Meanwhile I will try and see to improve my knowledge on the nextcloud app code and see where any of my simple input can be of any help. 

Thanks and keep up the good work. I really like where this is going to.

**Comment by skjnldsv** [comment]
Well, 2.1 is around the corner :)

Please help testing the linked pull request so we move things faster :rocket:

**Comment by skjnldsv** [comment]
The forms is now using the OCS API endpoint.
We're lacking documentation, but it's there! If anyone wants to dive on it! :)

**Comment by skjnldsv** [comment]
Actually let's close in favour of #451 :wink:
