### ISSUE TITLE
a three-answer-option would be nice

### ISSUE THREAD

**Issue by fds2610** [nextcloud/forms#555]
I would like to give users the chance to priorize their selections by adding a three-answer-option.
It would be nice to add three possible answers as radio-buttons to each question like:

e.g.:
Do you want to meet on September, 9th?
O - no   O - maybe   O - yes

Do you want to meet on September, 16th ?
O - no   O - maybe   O - yes

and so on...

**Comment by skjnldsv** [comment]
Hey!
What would be the difference between this and adding those answers on a multi choice question?

**Comment by fds2610** [comment]
Usually I provide my guests a number of fife to ten dates to select their most convenient ones.
It is far more effort to add fife to ten separate questions than to add one question with fife to ten three-option-answers.

**Comment by skjnldsv** [comment]
@jancborchardt

**Comment by jancborchardt** [comment]
It seems the Polls app (Doodle replacement) is more what you are looking for @fds2610? https://apps.nextcloud.com/apps/polls

**Comment by jdittrich** [comment]
…the equivalent to this that I know in other form apps would be the answer grid: 

![image](https://user-images.githubusercontent.com/3416487/89991015-80ec0780-dc83-11ea-827c-13dc54411b08.png)

But this would be another issue.

**Comment by fds2610** [comment]
i would go with @jdittrich 's suggestion - or use the poll app. you can close this if you do not want to use it as an issue for @jdittrich 's solution...

**Comment by pwepwe973** [comment]
> It seems the Polls app (Doodle replacement) is more what you are looking for @fds2610? https://apps.nextcloud.com/apps/polls

I don't think it's the polls option he needs, in google forms there is the same option it would be the top!

![Capture du 2020-10-18 00-57-14](https://user-images.githubusercontent.com/37281042/96355633-00fb7700-10e4-11eb-8b60-daef82a46434.jpg)

**Comment by jotoeri** [comment]
So - either polls app or #356 😉
