### ISSUE TITLE
Allow multiple users to edit a single form (admin sharing)

### ISSUE THREAD

**Issue by samtuke** [nextcloud/forms#557]
**Nextcloud (please complete the following information):**
- Nextcloud-Version: 19.0.0 RC3
- Forms-Version: 2.0.2

**Is your feature request related to a problem? Please describe.**
We need multiple admins to be able to view form responses

**Describe the solution you'd like**
I'd like other users, to whom the form has been shared, to be able to view form responses and edit the form contents.

**Comment by skjnldsv** [comment]
duplicate of #322

**Comment by skjnldsv** [comment]
Hey!
Thanks for your interest, an existing issue already exists, you can subscribe here to it if you wish to receive upcoming feedback :)
