### ISSUE TITLE
Language Translations

### ISSUE THREAD

**Issue by jaschrock** [nextcloud/forms#558]
Nextcloud 18.0.7 
Forms: 2.0.2

We are needing to get some translations in for the "Thank you note" and the "required questions" text. They are not automatically translating into Portuguese. We will have other languages as well that I am sure this will be the case. How can I do this either locally or somewhere in the system to provide a file with some options? They will be using a link, so the instructions within webshare are not as important and the questions will already be in the language of the country.

**Comment by skjnldsv** [comment]
You can join the translations on transifex :)
Thanks for the help! :hugs:

**Comment by jaschrock** [comment]
> 
> 
> You can join the translations on transifex :)
> Thanks for the help! 🤗

Is there a specific project within transifex or is it just the standard nextcloud project? I don't see a forms or nextcloud-forms option. Also, haven't used it before, so I could just be missing it. 

Thanks

**Comment by jaschrock** [comment]
Found it...

https://www.transifex.com/nextcloud/nextcloud/forms/
