### ISSUE TITLE
sharing link with non-nextcloud users?

### ISSUE THREAD

**Issue by frank-github** [nextcloud/forms#561]
is there any way to share this forms with non nextcloud users?
in my tests links seems to need a login for nextcloud
but I want to share this forms with users, who are not users of my nextcloud. How to solve this?

**Comment by skjnldsv** [comment]
Hey!
You can have a public share yes, and share the link to the persons you want :)

**Comment by skjnldsv** [comment]
![image](https://user-images.githubusercontent.com/14975046/90308419-a6754d00-dedf-11ea-963e-81080fea49a8.png)

**Comment by frank-github** [comment]
Hi,
yes, I found this panel, but because of some security restrictions in my browser "copy to clipboard" is disabled.
I copied it from browser-URL, but include the "edit", so you have to logon
without "edit" it can be used as public URL  :-)

maybe in a next release the sharing url can be shown below button "copy url" as in other apps, like share files 
etc. 
in this case copy can be done with CTRL-C :-)

thanks for this useful app   (one more google free app)

**Comment by skjnldsv** [comment]
> but because of some security restrictions in my browser "copy to clipboard" is disabled

Can you elaborate please? :)
Is this something you enabled or is it my default? Because it works for me on all browsers :thinking:

**Comment by frank-github** [comment]
it's enabled by me in my firefox with a very restricted user.js

**Comment by skjnldsv** [comment]
AH, then it make sense ! Thanks :)
