### ISSUE TITLE
Can add the ability to add an image to a question ?

### ISSUE THREAD

**Issue by Ramdane34** [nextcloud/forms#575]
To offer more possibilities, can add the possibility of adding an image to a question?

**Nextcloud (please complete the following information):**
- Nextcloud-Version: [e.g. 19.0.0]
- Forms-Version: [e.g. 2.0.0-beta4]

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by skjnldsv** [comment]
Hey!
As a description or as an answer choice?

**Comment by Ramdane34** [comment]
Hey! Thank ! First: in the description (text + image), and, which would be great: in the choice of answer !!

**Comment by skjnldsv** [comment]
I would put this as a duplicate of #321 then :)
If we support markdown, it would most likely includes images :wink:

**Comment by Ramdane34** [comment]
Thank you very much and good luck ...

**Comment by skjnldsv** [comment]
Thanks a lot :)
Have a great day!! :sun_with_face:
