### ISSUE TITLE
More visibility for the "Copy share link" button

### ISSUE THREAD

**Issue by 42l-neil-tmp** [nextcloud/forms#581]
**Nextcloud:**
- Nextcloud-Version: 19.0.1
- Forms-Version: 2.0.3

Related to: Frontend, UX

Hello!

Thanks for working on this app! I've been testing Nextcloud Forms with non tech-savvy people to get UX feedback.

The overall app UX is excellent and very promising, but I got multiple remarks about the "Copy share link" button, which seems hard to find for some people.

It isn't a bother to me, and I believe it's OK for most people (since the link is both in the dropdown menu in the form list in the left sidebar **and** in the form settings menu in the right sidebar), but it seems to be a concern for some people.

This form settings menu isn't open by default (and I believe it's a good thing) but near than half of the people who were testing the application made their form **without checking the settings**, so they had trouble to find the "copy link" button.

Unlike the settings that doesn't need special attention in all use cases, copying the form link is definitely a mandatory step for anyone who uses the application, exactly like checking the form answers though the "responses" button. So what about moving it into the main view?

Something like this:
![image](https://user-images.githubusercontent.com/70517536/91716049-2ad9f800-eb8f-11ea-9ed0-ea60f7d2700a.png)

Thanks for reading :slightly_smiling_face:

**Comment by skjnldsv** [comment]
cc @jancborchardt

**Comment by jancborchardt** [comment]
Yep, good point @42l-neil-tmp. Definitely makes sense to add it there in the main view. I would just move it to the right of the "Responses" toggle, since the share link is more related to the sidebar button. Also the text could be shortened to "Share link" and the tooltip could say "Link copied". :)
