### ISSUE TITLE
Export and import forms

### ISSUE THREAD

**Issue by Supergamerx3000** [nextcloud/forms#582]
Hello, is there a way to export a form and then import it again on another nextcloud server?

**Comment by skjnldsv** [comment]
Hi!
Currently no, I'll keep this one opened for future reference :)

**Comment by Xeudoron** [comment]
Hello,
I'm looking around for any information about copying/exporting forms to/with other users. Nowadays there is a way to copy form, which can be used to manage templates as mentioned in #833. I understand, that Forms are being developed and it takes time to accomplish some big steps like #322 but if there was a possibility to copy/share/export a form (empty form serving as a template) to another user in Nextcloud instance, it would really help in terms of collaboration. So my question is if nowadays there is any way to get form from one user to another not just by transcribing it in the app, and when can we expect any kind of an easier solution to this problem.

**Comment by skjnldsv** [comment]
@Xeudoron the labels on the right says `to develop`. There are currently no way to copy forms from one user to another

**Comment by RenataGegaj** [comment]
This feature was also requested by a few participants during our user testing round. 
(I'm assuming this was mainly a "solution" to the collaboration feature that is currently missing, not sure though, I didn't follow up with additional questions on this)

**Comment by ajoe** [comment]
Here this is an export import tool:
https://github.com/nextcloud/forms/issues/1425#issuecomment-4063645593
