### ISSUE TITLE
Update to nextcloud-axios 0.2.0

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/forms#6]
See https://github.com/ChristophWurst/nextcloud-axios/pull/20

**Comment by luixxiul** [comment]
This was addressed with https://github.com/nextcloud/forms/pull/55

**Comment by ChristophWurst** [comment]
In the meantime please use `@nextcloud/axios`. The `nextcloud-*` packages were PoCs: https://github.com/nextcloud/server/issues/15932
