### ISSUE TITLE
delete answer menu incorrectly positioned

### ISSUE THREAD

**Issue by 2epal** [nextcloud/forms#609]
**Describe the bug**
made a simple form. publish. get answers. 
i want to delete one and click the icon with the 3 dots and then the popup menu with the option to delete answer is incorrectly positioned
the above happens for the 3rd answer in the list and after.
1st and 2nd answer delete menu shows in place

**To Reproduce**
1. made a simple form A. publish. get answers. 
2. log as admin, go to forms and to form A.
3. go to answers list
4. try to delete one (3rd and after)

**Expected behavior**
click the icon with the 3 dots and then the popup menu with the option to delete answer is correctly positioned

**Nextcloud (please complete the following information):**
- Nextcloud-Version: 18.0.9
- Forms-Version: 2.0.4

**Desktop (please complete the following information):**
 - OS: win7 32bit el
 - Browser firefox 
 - Version 80.0.1 32bit

**Comment by skjnldsv** [comment]
Can you provide a screenshot please? :)

**Comment by jotoeri** [comment]
Looks to me like some bug in vue-lib?!

![grafik](https://user-images.githubusercontent.com/47433654/99002562-e5e22280-253c-11eb-9aa1-e58f6b0a35b4.png)
![grafik](https://user-images.githubusercontent.com/47433654/99002651-1033e000-253d-11eb-9874-41750a832a5a.png)

**Comment by skjnldsv** [comment]
Yeah, that is weird.
I can't reproduce the issue

**Comment by jotoeri** [comment]
Probably need to scroll around a bit... It is not everywhere the case and one can scroll it away...

**Comment by daCaPo** [comment]
I can confirm this issue. I've just create quite a long questionary, and also the "choose question type" pop-up gets positioned near the top of the page, letting me scroll back to the top of the page every time I want to add a question at the end. (Firefox 83 on macOS 11.0.1)

**Comment by jotoeri** [comment]
https://github.com/nextcloud/nextcloud-vue/issues/1384
- Seems to be a larger thing in server

**Comment by skjnldsv** [comment]
Yep, this is coming from the components :)
https://github.com/nextcloud/nextcloud-vue/issues/1384#issuecomment-690892427

**Comment by jotoeri** [comment]
> Yep, this is coming from the components :)
> [nextcloud/nextcloud-vue#1384 (comment)](https://github.com/nextcloud/nextcloud-vue/issues/1384#issuecomment-690892427)

So you think we should solve it on our own for now, as you rely on this specific comment? Might take longer for the Integration in Server?
