### ISSUE TITLE
Suggestion: Rating on a scale e.g. 1-5 or 1-7

### ISSUE THREAD

**Issue by StefanLiebich** [nextcloud/forms#618]
Hi, 
this is a great project!
One thing which would make it even better, would be a way to directly have a rating scale, e.g., between 1 and 5 or with the following options:
very good
good
neutral
bad
very bad

Thanks for considering this suggestions!

**Nextcloud (please complete the following information):**
- Nextcloud-Version: [e.g. 19.0.0]
- Forms-Version: [e.g. 2.0.0-beta4]

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jotoeri** [comment]
Hey Stefan,
sorry for the late reply. I'd close this issue in favor of #356. Feel free to tell us, if you meant different thing. ;)
Greets,
Jonas
