### ISSUE TITLE
Share by email (unique) or share to Circles, share to members (show shared forms) [PAYMENT]

### ISSUE THREAD

**Issue by mculibrk** [nextcloud/forms#646]
- Nextcloud-Version: 18.0, 19.0
- Forms-Version: 2.0.4

I do not know if this is really allowed here, so excuse me if I'm doing this the wrong way...

I urgently need some (minor?) fixes to Forms to be fully usable and I'm willing to pay someone for the required modifications.
The planned usage would be a simple questionnaire (like an exam)  for the contacts the link was sent to.
If this is allowed here, please leave a message and I'll get back to you.

The changes/fixes/functionality needed ASAP are:
- share forms by email (to people NOT having the account on the NextCloud instance which hosting form(s))
- possibility to import the email list for sending the form link or using Circles to share to
- see the shared form when a form is shared to users of the same NextCloud instance (now only possible to access the form by using the sent share and begin logged-in before)

**Comment by skjnldsv** [comment]
Hey! That is not how we work here.
Please search for existing issues and do not open issues with multiple requests.


> * share forms by email (to people NOT having the account on the NextCloud instance which hosting form(s))

This is already done. Just share publicly and send the mails.
Automatic email sending is in #541 and https://github.com/nextcloud/forms/issues/559

> * possibility to import the email list for sending the form link or using Circles to share to

This would be "Sharing with circles", and for the part to bulk-import email lists, this is a request for the https://github.com/nextcloud/circles repository

> * see the shared form when a form is shared to users of the same NextCloud instance

This is https://github.com/nextcloud/forms/issues/322 or https://github.com/nextcloud/forms/issues/364

For the payment requests, I suggest you ask on twitter/reddit or our forum?

**Comment by mculibrk** [comment]
Hi!

Uhh... I'm really sorry. I did not want to upset or insult or whatever 
anyone, really.

Regarding existing issues you listed, I saw those but... those are 
"missing something"....

I'll try to post the "question" on the forums, thanks!

Best regards,
-- 
Mauricio Čulibrk
Sistemski inženir

*t:* +386 1 581 8000
*m:* +386 41 368 158
*e:* mauricio@infohit.si
*w:* www.infohit.si
