### ISSUE TITLE
Only form creation for admins

### ISSUE THREAD

**Issue by aloisejulian** [nextcloud/forms#647]
**Nextcloud (please complete the following information):**
- Nextcloud-Version: 19.0.4
- Forms-Version: 2.0.4

**Is your feature request related to a problem? Please describe.**
I want to know if is possible to make the form creation only for admins, and this forms that admin create accesible for specific users o groups

Thanks!

**Comment by jotoeri** [comment]
Not possible yet, but i definitely have this in mind as followup to #372 
Not necessarily specifically for Admins, but to have some setting, which groups/users are allowed/denied to create forms.

**Comment by aloisejulian** [comment]
Great! I will be waiting for this! Thanks!

**Comment by greavette** [comment]
Hello @jotoeri ,

A follow-up question to this planned enhancement.  In addtion to only allowing certain groups to be able to create forms...would you also be adding in the ability for gropus to see and edit forms?  My usecase is we have two owners in our company and they both want to use forms and see each other's work.  They are Admins on our Nextcloud.  We don't want our employees to be able to create or edit forms...but we do want all Admins to be able to create and edit forms (regardless of which owner created the form).

Thank you.

**Comment by jotoeri** [comment]
Hey @greavette,

from your last sentence, i read as if you mean the collaborative access & editing of forms, no? That's different topic, but already tracked & scheduled in #322. Might however still take a while and be then on a base of sharing that access on single forms instead of all instance-forms automatically.

Greets :)
Jonas

**Comment by canalboy4** [comment]
I think this is related: I'd like members of a Group to be able to collaboratively edit forms (as we used to do with Drive). At present they can only see them, not edit.

**Comment by audunmb** [comment]
Can't you do this on an per-app-basis? In the app admin, you can check "limit to group" and then assign it to the admin group.
