### ISSUE TITLE
DE Translation

### ISSUE THREAD

**Issue by rocky-III** [nextcloud/forms#648]
in the files:

forms/l10n/de.js
forms/l10n/de.json 
forms/l10n/de_DE.js
forms/l10n/de_DE.json

the string
`"Thank you for completing the form!" :`
would be better translated like this: 
`"Thank you for completing the form!" : "Vielen Dank fÃ¼r das Ausfüllen des Formulars!",`

OK ?

I never did a pull request... let see how to do this :-)

**Comment by jotoeri** [comment]
Hey Rocky!

Translations on Nextcloud are managed via Transifex, so i hope you did not put too much effort into creating a pull-request yet: Just head over to the transifex-project and submit a sugestion or open an issue there (depending on severity?!) to discuss the translation: https://www.transifex.com/nextcloud/nextcloud/forms/

Greets!
Jonas

cc @rakekniven

**Comment by rakekniven** [comment]
Hello @rocky-III ,

just adapted the translation and used your suggestion.

Cheers

**Comment by rocky-III** [comment]
THANKS
