### ISSUE TITLE
Send E-mail Alert to new Answer

### ISSUE THREAD

**Issue by Gustavo-FS** [nextcloud/forms#649]
**Nextcloud (please complete the following information):**
- Nextcloud-Version: [e.g. 19.0.0] : 20.0.0
- Forms-Version: [e.g. 2.0.0-beta4] Last Version

**Is your feature request related to a problem? Please describe.**
It´s possible send a automatic e-mail when a new Answers its Submited

**Comment by skjnldsv** [comment]
Duplicate of https://github.com/nextcloud/forms/issues/12
