### ISSUE TITLE
Feature request: Copy Survey

### ISSUE THREAD

**Issue by Bapf** [nextcloud/forms#662]
**Nextcloud (please complete the following information):**
- Nextcloud-Version: 18.0.10
- Forms-Version: 2.0.4

**Describe the solution you'd like**
We are considering doing lecture evaluations with NextCloud Form.
Therefore we need a lot of forms containing mostly the same content, except for the header (which is different for every lecture).
So it would be gread if I could create the survey only once in whole, then copy it multiple times so that I only have the change the headers afterwards instead of creating every survey anew.

**Describe alternatives you've considered**
Creating all forms by hand ...

**Comment by jotoeri** [comment]
Hey Bapf,

this is already scheduled in #202. In case you didn't, please search for existing issues next time. (Indeed, searching for 'copy' might have gone wrong here...) :wink:

Greets,
Jonas
