### ISSUE TITLE
Integration of form.io wizard and renderer

### ISSUE THREAD

**Issue by thoka** [nextcloud/forms#670]
**Nextcloud (please complete the following information):**
- Nextcloud-Version: 20
- Forms-Version: 2.0.4

**Is your feature request related to a problem? Please describe.**
I want to use rhich forms with validation for emails, option lists etc.

**Describe the solution you'd like**
Could this framework be used to integrate the [open source form wizard](https://github.com/formio/formio) and [renderer](https://github.com/formio/formio.js) from form.io ?
This would allow use of very sophisticated forms without too much implementation efforts.

**Describe alternatives you've considered**
I searched for an already existing integration of formio into nextcloud but didnt find one.

**Comment by skjnldsv** [comment]
Hi,

Sorry, we decided to step away fro any existing framework because they were far too complicated and would make our maintenance of this far more complicated.
Nc forms is standalone and will stay this way :)
