### ISSUE TITLE
FR: allow non-logged-in users to enter a username

### ISSUE THREAD

**Issue by trougnouf** [nextcloud/forms#685]
I think it would be useful to let "anonymous" users who have received a form link enter their name.

Knowing who answered what can be important for scheduling. It also lets participants know that their input was taken into account. Then it would have the potential to replace the Doodle platform.

Ideally I would like users to be able to edit their answer if allowed by the poll admin (or any answer if they are feeling evil).

**Comment by jotoeri** [comment]
> I think it would be useful to let "anonymous" users who have received a form link enter their name.

Hm - As very simple solution: just use a short text question and give it a title 'Your Name'? - To implement this as extra feature, it is too specific and too easy to solve with the short-question, i'd say. 😉 

> Knowing who answered what can be important for scheduling. It also lets participants know that their input was taken into account. Then it would have the potential to replace the Doodle platform.

Do you know the polls-app? This one is specifically done for the Doodle-Functionality.
https://apps.nextcloud.com/apps/polls

> Ideally I would like users to be able to edit their answer if allowed by the poll admin (or any answer if they are feeling evil).

Hm, kind of a special request - probably for very long term, i'd say... If still worth a Feature-Request (now, that knowing Polls ;)), then please open a separate issue.

Greets, 😊 
Jonas

**Comment by trougnouf** [comment]
Polls is exactly the right app for that, thank you!
