### ISSUE TITLE
Also anonymous users should be able to enter a name

### ISSUE THREAD

**Issue by profhase** [nextcloud/forms#694]
**Nextcloud (please complete the following information):**
- Nextcloud-Version: e.g. 19.0.0
- Forms-Version: e.g. 2.0.4

**Is your feature request related to a problem? Please describe.**
Assume I create a form which is accessible by a link (public).
For Anonymous users I would still like to get a name (instead of "Anonymous")

**Describe the solution you'd like**
There should be a Question (option) available: "Enter your name"
or there should be a possiblity to ask the user for His name (i.e. in a modal)

**Describe alternatives you've considered**
I can make A short text question : "What is your name". Still in the form overview I would see
it answered by "anonymous"; The name is just another field

**Additional context**

**Comment by skjnldsv** [comment]
Hi, please search before opening issues :) 
see https://github.com/nextcloud/forms/issues/685

**Comment by profhase** [comment]
Thank you (sorry, did not find that one)

**Comment by skjnldsv** [comment]
No worries :)
