### ISSUE TITLE
Multiple user access + share link

### ISSUE THREAD

**Issue by MaPeras** [nextcloud/forms#697]
Hey folks,

thank you for this amazing app - it's really helpful!

We have experienced, that the public link for participation stops working, when we share the form with another NC-member. It seems to be an either/or option or is this a bug? 

Use case: I liked to show my companion the results of team applications we got so far, while the call was still open and the NC-form open for submission through the link.

Cheers,
Max

**Comment by jotoeri** [comment]
Hey Max,

i think you're mixing up stuff here a bit, while indeed wording might be a bit misleading.
The sharing-option only affects, who is allowed to fill(!) the form, while independent of the sharing-options only the form owner can edit the form and view results. So yes, when changing the sharing option, only the selected person can use the sharing link if beeing logged in. ;)
However, sharing results is already scheduled as a separate issue: #455 
Hope that clarifies your Problem?

Greets :) 
Jonas

**Comment by MaPeras** [comment]
Yes! That clarifies a lot. Thank you for pointing me to #455
