### ISSUE TITLE
Link to Сonsent on personal data processing

### ISSUE THREAD

**Issue by dsveshnikov** [nextcloud/forms#715]
How can I add a link to consent on personal data processing (or to any page) to my Nextcloud page? 
Nextcloud page: https://avocad.i234.me/nextcloud/index.php/apps/forms/qXn8ktqgkso3wBft
Page with consent on personal data processing: http://avocad.tilda.ws/privacy

**Comment by jotoeri** [comment]
Currently it is not possible to add links. I close this issue in favor of #489, which includes links. 😉
