### ISSUE TITLE
Add a form to a Project

### ISSUE THREAD

**Issue by JosselinTD** [nextcloud/forms#716]
**Nextcloud (please complete the following information):**
- Nextcloud-Version: 19.0.6
- Forms-Version: 2.0.4

**Is your feature request related to a problem? Please describe.**
I need to link some forms to a Project

**Describe the solution you'd like**
In the "Share form" panel, add a section to link the form to a project

**Comment by Chartman123** [comment]
@jotoeri @jancborchardt As "projects" were replaced by "related resources, can this issue be closed?

**Comment by Chartman123** [comment]
Projects no longer exist in the form when this issue was raised. So I'm closing this now.
