### ISSUE TITLE
Awesome, I Love it! Some other features would be cool!

### ISSUE THREAD

**Issue by rougerouter** [nextcloud/forms#724]
**Nextcloud (please complete the following information):**
- Nextcloud-Version: [e.g. 20.0.3]
- Forms-Version: [e.g. **2.0.4]**

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

_**Not a problem a request:**_
Date picker (I am doing  a form for auto maintenance and the service may not be the day I enter the data)
Attachments (to link a file to field in the table I am guessing this creates)
Great work so far! _**Thanks!**_

**Describe alternatives you've considered**

**Additional context**

**Comment by skjnldsv** [comment]
> Date picker (I am doing a form for auto maintenance and the service may not be the day I enter the data)

Incoming on next version :)

> Attachments (to link a file to field in the table I am guessing this creates)

See https://github.com/nextcloud/forms/issues/42

Thanks for the nice feedback! Glad you like it!! :rocket: :hugs:
