### ISSUE TITLE
Result show sid of ldap user

### ISSUE THREAD

**Issue by baopham25880** [nextcloud/forms#73]
When i view result of form it just show sid of ldap user, instead of name of ldap user
![1](https://user-images.githubusercontent.com/54933138/64323109-05eb8d00-cfee-11e9-8ed4-ae3e2492d4e8.PNG)

**Comment by skjnldsv** [comment]
@jotoeri for you if you want, most likely an issue between getDisplayName and getUID on the $user ?

**Comment by jotoeri** [comment]
Yes, have this already in mind for the Results. 👍
