### ISSUE TITLE
Encoding error on export csv

### ISSUE THREAD

**Issue by ironmaid3n** [nextcloud/forms#734]
Hello team of Nextcloud Forms,
i have try your nice app with greek characters, but when i try to export the answers with .csv and open the file with excel, the encoding is wrong and strange characters appears like these: userDisplayName,"timestamp","Ξ‘Ο€Ξ±ΞΉΟ„ΞµΞ―Ο„Ξ±ΞΉ","ΞΞΏΞ½Ο„ΞΏ Ξ΄ΞµΞ½ Ξ±Ο€Ξ±ΞΉΟ„ΞµΞΉΟ„Ξ±ΞΉ","ΞΞµΞ³Ξ¬Ξ»ΞΏ ΞΊΞµΞΉΞΌΞ½ΞµΞΏ"

I have try also change the encoding of my database with this sting: ALTER TABLE oc_forms_v2_forms CHARACTER SET utf8 COLLATE utf8_general_ci , (for all the tables of form app), but the result is the same.
Please help me to fix it.

**Comment by jotoeri** [comment]
Hm, i'm not completely sure, this is greek, i just copied it from somewhere on the internet:
![grafik](https://user-images.githubusercontent.com/47433654/104125886-cf4c2200-5359-11eb-949b-3349d9974c7b.png)

If it is greek, the export seems to work for me.
Did you use import on excel? For me it seems to work if i use excels data->import->from csv and set `Unicode (UTF-8)` as source and `Comma` as separator.
![grafik](https://user-images.githubusercontent.com/47433654/104126028-9791aa00-535a-11eb-8d76-b7c93132067b.png)

**Comment by ironmaid3n** [comment]
> Hm, i'm not completely sure, this is greek, i just copied it from somewhere on the internet:
> ![grafik](https://user-images.githubusercontent.com/47433654/104125886-cf4c2200-5359-11eb-949b-3349d9974c7b.png)
> 
> If it is greek, the export seems to work for me.
> Did you use import on excel? For me it seems to work if i use excels data->import->from csv and set `Unicode (UTF-8)` as source and `Comma` as separator.
> ![grafik](https://user-images.githubusercontent.com/47433654/104126028-9791aa00-535a-11eb-8d76-b7c93132067b.png)

Thanks very much jotoeri, your solution works fine!!! :)
