### ISSUE TITLE
Date format not consistent

### ISSUE THREAD

**Issue by KvoiceOxford** [nextcloud/forms#736]
The form's date format recorded in responses is dependent on the submitting browser, not the form-app. Hence different browsers produce different date-format outcomes. For example: '19 March 2021' using my Edge or my Firefox; whereas 'March 19, 2021' using my Chrome. This data-formatting outcome does not provide a consistent data format held within the NC database, hence potentially can lead to unpredictable results when analysing form responses.

**Comment by Chartman123** [comment]
@jotoeri I started looking into this and I'm already storing the date/datetime values as Unix timestamps into the db and can also get it back and display it in moment 'LL' and 'LLL' formats. However, older values from the db won't be displayed correctly. Should we do a db migration to convert date/datetime answers to Unix timestamps or should we do some more checks in the front-end?
