### ISSUE TITLE
Minversion 21 - Move to NC internal db column Types

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/forms#737]
Hi there,

I found that your app uses some classes of Nextcloud's third party libraries. Since an upgrade of those for php8 compatibility, your app will have to be adjusted as well. See https://docs.nextcloud.com/server/latest/developer_manual/app_publishing_maintenance/upgrade-guide.html#doctrine-dbal for details. Your app uses `Doctrine\DBAL\Types\Type` which lost the old constants: https://github.com/doctrine/dbal/blob/3.0.x/UPGRADE.md#deprecated-type-constants.

Cheers

**Comment by ChristophWurst** [comment]
Please note that we just merged a PR with our own constants for the types, so the app can be fully independent of any 3rdparty libraries: https://github.com/nextcloud/server/pull/25089.

**Comment by jotoeri** [comment]
Will these types get backported @ChristophWurst ? So are they available on NC19, if we move our migrations now to the new types? I didn't find any reference about this on the mentioned PR 🤔

**Comment by ChristophWurst** [comment]
No, we don't backport "features"

**Comment by jotoeri** [comment]
Hm, ok. So as far as i see, the \Types\Types on DBAL have been introduced with v2.10. Can you tell me, which version was used on NC19? (Sorry, didn't find that currently on server)
I just think about, which one to use, if we still support NC19-NC21? We can move to the internal types then as soon, as we set Minversion to 21...

**Comment by ChristophWurst** [comment]
You can explore this via https://github.com/nextcloud/3rdparty/tree/stable19

**Comment by jotoeri** [comment]
🤦‍♂️ And i was wondering why 3rdparty on server is empty.

**Comment by ChristophWurst** [comment]
done with https://github.com/nextcloud/forms/pull/801 I guess

**Comment by ChristophWurst** [comment]
actually no :see_no_evil:
