### ISSUE TITLE
How to set up the development environment on macOS?

### ISSUE THREAD

**Issue by luixxiul** [nextcloud/forms#74]
Hello, I would like to work on the codebase and I am just wondering how to set up the development environment on macOS as easily as possible, from setting up the Nextcloud instance to compiling and debugging the app on real time. This might be rather a general question.

Any suggestions would be appreciated. Thanks in advance.

**Comment by affan98** [comment]
Have you checked the readme? I believe all of those instructions work on MacOS. As far as setting up nextcloud I would look at the instructions on the nextcloud site

**Comment by luixxiul** [comment]
Sorry for the late reply. Thanks for the info!
