### ISSUE TITLE
Server-side validation of Responses

### ISSUE THREAD

**Issue by jandr** [nextcloud/forms#758]
**Describe the bug**
Requirements such as making a specific question mandatory seem to only be enforced client-side (e.g. in the user's browser).  If a user intercepts the HTTP request with their answer and changes the drop-down index to a non-existent one, the form response is accepted by the server and the question is marked as "No Response" (when that should not be possible as the question was marked as mandatory)

**To Reproduce**
1. Create a Form.
2. Add a drop-down question, marked as 'Required'
2. Go to the form link and select one of the answers in the drop-down.
3. Intercept the request to the server (e.g. using a browser extension such as TamperData or an intercepting proxy such as ZAP or Burp)
4. Replace the index of the answer by a non-existent one (e.g. if the answer had 3 options in the drop-down, change the selected index to '5', for example).
5. The response will be accepted.
6. When the responses are viewed by the Form creator, the drop-down answers that were tampered with non-existent indices will appear as "No response".

**Expected behavior**
The server should reject the response informing the user that a non-valid answer to the question was chosen/provided.

**Nextcloud:**
- Nextcloud-Version: 20.0.6
- Forms-Version: 2.1.0

**Comment by Chartman123** [comment]
@jotoeri Am I right that this needs to be handled within the API controller in the insertSubmission method?

**Comment by jotoeri** [comment]
>  API controller in the insertSubmission function

Generally yes, but to not blow that function further, i'd create a function on SubmissionService to validate the submission. And if that fails, the API can throw an Exception. What we finally do on the Validation then, that's discussable. So for empty submissions: I think if having a form, where all questions are not required, then imo it is valid to have empty responses. That might even be used on purpose. But there is also a specific issue for this: #482. That's still to discuss, so as a first step i wouldn't include it here.

Also we could probably shift the actual insertion of the Submission to a specific procedure on the Service. That should make the API a bit more clear.

**Comment by Chartman123** [comment]
Ok, so I'd create a new function `validateSubmission` and call it before `$submission = new Submission();` with the $answers and $questions as we already have them in the code.

I'd propose to create two PRs then: One to close this issue and do a server-side validation. The second to cleanup the ApiController and move the insertion to th Service, too. (And eventually a third one that removes the possibility to submit empty submissions, if it's decided to do so in #482)
