### ISSUE TITLE
Deleting submission results in submission ID increment error

### ISSUE THREAD

**Issue by sircharlo** [nextcloud/forms#764]
**Describe the bug**
When deleting a submission using the form responses view, or when deleting all submissions for a particular form, the submissions are in fact deleted, but the linked answer entries are not. When new submissions are posted, submission IDs do not increment properly, causing ID collision and leading to submissions containing both previous and current answers.

**To Reproduce**

1. Create a form with questions
2. Submit an answer using the form
3. Load the content of the `oc_forms_v2_submissions` table
4. Note the submission's ID
5. Load the content of the `oc_forms_v2_answers` table
6. Confirm that the latest answer entries are linked to the submission ID you noted
7. Delete that submission from the results page
8. Confirm that the submission ID was deleted from the `oc_forms_v2_submissions` table
9.  Confirm that the relevant entries were **not** deleted from the `oc_forms_v2_answers` table
10. Submit a new answer using the form
11. Load the content of the `oc_forms_v2_submissions` table
12. Note the new submission's ID is the same as the previously deleted submission
13. Load the content of the `oc_forms_v2_answers` table
14. Notice that both the previous answer entries, as well as the new ones, are linked to the same submission ID
15. View the submissions using the form. One submission is displayed, but with both previous and current answer entries "merged".

**Expected behavior**
Deleting a submission either:
- should result in deletion of linked answer entries, **or** 
- should not result in restarting the submission ID increment index

**Nextcloud (please complete the following information):**
- Nextcloud-Version: 20.0.7snap1
- Forms-Version: 2.1.0

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: Latest

**Browser log**
```
n/a
```

**Comment by jotoeri** [comment]
Hm, interesting, until now i never saw mysql reusing auto-increment values. But indeed, we erroneously didn't delete answers yet.
I just made a fix - however might take two weeks until the next release.

Thanks for pointing out!

**Comment by sircharlo** [comment]
Thank you for this great piece of software!
