### ISSUE TITLE
Compulsory 'anonymous' or 'connected to Nextcloud account' text problematic

### ISSUE THREAD

**Issue by xadium** [nextcloud/forms#782]
Hi

This functionality has been added and is problematic.  We host a Nextcloud instance which is used by a small number of staff.  We may wish to host a survey which is open to a large number of staff.  I still want to capture employee number of those staff so use a short-text box for the employee number as part of the survey

My options are an anonymous survey which adds 'this survey is anonymous' to the survey which isn't true because I'm asking for identification.  Alternatively the compulsory text 'your responses are connected to your Nextcloud account...' is added which also isn't true because those respondents don't have a Nextcloud account and this is confusing to people who know nothing about Nextcloud.

Thoughts?  Linked to #530, #635 and #685 I guess.

**Comment by jotoeri** [comment]
Yeah, on public forms, we should change that text depending on if the user is logged in or not.
However in this specific case, you would then still see the Anonymous text, which you even don't want.

@jancborchardt Any idea of a good handling?

**Comment by xadium** [comment]
I think perhaps the use of the word ‘anonymous’ is the issue. The suggestion of anonymity is a value-judgement about the content of the survey.  Depending on the questions asked, a survey might not be, and you as developers of the app have no control over the questions asked in a survey. 

Effectively we’re talking about ‘public’ surveys (no Nextcloud account required) versus ‘members-only’ or ‘private’ 

I think injecting uneditable language into the survey description, outside of the control of the user, is a bad idea generally.  I’ve had to hack the JS for this app today to delete these strings to continue to use it for my purposes and not mislead/confuse my users. That’s a breaking change. 

As an aside, depending on their jurisdiction, ‘anonymous’ might have a specific legal meaning which cannot be adequately explained in boilerplate text.

**Comment by internetauftritt** [comment]
> Hallo
> 
> Diese Funktionalität wurde hinzugefügt und ist problematisch. Wir hosten eine Nextcloud-Instanz, die von einer kleinen Anzahl von Mitarbeitern verwendet wird. Möglicherweise möchten wir eine Umfrage durchführen, die einer großen Anzahl von Mitarbeitern offen steht. Ich möchte weiterhin die Mitarbeiternummer dieser Mitarbeiter erfassen. Verwenden Sie daher im Rahmen der Umfrage ein Kurztextfeld für die Mitarbeiternummer
> 
> Meine Optionen sind eine anonyme Umfrage, die der Umfrage "Diese Umfrage ist anonym" hinzufügt. Dies ist nicht der Fall, da ich nach einem Ausweis frage. Alternativ wird der obligatorische Text "Ihre Antworten sind mit Ihrem Nextcloud-Konto verbunden ..." hinzugefügt, was ebenfalls nicht zutrifft, da diese Befragten kein Nextcloud-Konto haben und dies für Personen verwirrend ist, die nichts über Nextcloud wissen.
> 
> Gedanken? Verknüpft mit [# 530](https://github.com/nextcloud/forms/issues/530) , [# 635](https://github.com/nextcloud/forms/pull/635) und [# 685,](https://github.com/nextcloud/forms/issues/685) denke ich.

**Hi from Germany**
the APP is great, but unfortunately not useful.
The sentence: "Answers are linked to your Nextcloud account. An asterisk (*) indicates mandatory questions. Or if you switch to anonymous it means: Answers are anonymous. An asterisk (*) indicates mandatory questions.
I use the APP, i.e. the LINK, to ask applicants 5 questions. But when they read the sentence it is strange and useless. It would also make sense if the applicant then replied and the green tick appears after clicking on send, which would then give the option of inserting a button where the person who answered the questions is redirected to a specific URL via LINK or at least a LINK.
Greetings Holger from Hamburg

**Comment by internetauftritt** [comment]
Hallo,
die APP ist toll, aber leider so nicht zu gebrauchen.
Der Satz: "Antworten sind mit Ihrem Nextcloud-Konto verbunden. Ein Sternchen (*) kennzeichnet Pflichtfragen. oder wenn man auf Anonym umschafltet heißt es: Antworten sind anonym. Ein Sternchen (*) kennzeichnet Pflichtfragen.
Ich verwende die APP, also den LINK um bei Bewerbern 5 Fragen abzufragen. Wenn die aber den Satz lesen ist es merkwürdig und so nicht zu gebrauchen. Außerdem wäre es sinnvoll, wenn der Bewerber dann geantwortet hat und der grüne Haken kommt nacht Klick auf absenden, das dann die Möglichkeit bestehen würden, ein Button einzufügen, wo derjenige, der die Feagen beantwortet hat, wieder mittels LINK auf eine bestimmte URL geleitet wird oder wenigstens einen LINK.
Gruß Holger aus Hamburg
