### ISSUE TITLE
Can't enable Forms on Nextcloud 21

### ISSUE THREAD

**Issue by kevquirk** [nextcloud/forms#798]
**Describe the bug**
I have a new Nextcloud 21 instance and I'm trying to enable Forms. Whenever I try, it downloads, but won't enable. All I see is te following notification:

> An error occured during the request. Unable to proceed.

I've installed other apps, like TOTP, Notes and Talk, all of which installed just fine.

**To Reproduce**
1. Go to apps page
2. Try to install the Forms app by clicking "Download and install"

**Nextcloud (please complete the following information):**
- Nextcloud-Version: 21
- Forms-Version: 2.1.0

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.2
 - Browser Firefox 85.0.1

**Comment by jotoeri** [comment]
Hey @kevquirk,

can you have a look into your server log? Is there any information about this?

Greets,
Jonas

**Comment by kevquirk** [comment]
Thanks for the quick reply. All I'm seeing in the logs is a 500 error:

```
2021-02-23 13:16:09 | Error | [IP REDACTED] | 500 | POST /index.php/settings/apps/enable HTTP/1.0 |   |   | 5.78 K | Apache SSL/TLS access
```

**Comment by jotoeri** [comment]
Ah - Sorry. I meant the Nextcloud-Server log. Can you tell us, what is in there? 🙈

**Comment by kevquirk** [comment]
Doh! Of course you did, sorry!

It spits a number of errors when I try. Here's the exported log - https://pastebin.com/3nttPi44

**Comment by jotoeri** [comment]
Hm, @kevquirk not sure, if you are aware, that your domain of the instance is in there. Shouldn't be too much of a problem, but some people like to not have it public everywhere. So probably you might want to remove that log-file again... ;)

However: @skjnldsv Probably we should get current stuff done and release v2.2.0 these days?! 😉 
> {"Exception":"Error","Message":"Undefined class constant 'INTEGER'", [...] "class":"OCA\\Forms\\Migration\\Version010200Date20200323141300"

@kevquirk If you are motivated, you could change your update-channel to beta an try the forms v2.2.0-beta.1 (and reset update-channel afterwards). As far as i see by now and to the best of my knowledge, that should only produce a duplicated index on db, but nothing that should break your instance. However keep in mind it is a beta-version and please don't kill me if unexpected things happen. 🙈 But that should solve at least the error quoted above...

**Comment by kevquirk** [comment]
Let's do it! :cowboy_hat_face: 

I'll report back and let you know how it goes.

**Comment by kevquirk** [comment]
Whoop! You sir, are a genius. I now have forms working on my instance and nothing seems to be broken. Thanks for the help and the incredibly quick response!

**Comment by kevquirk** [comment]
> Hm, @kevquirk not sure, if you are aware, that your domain of the instance is in there. Shouldn't be too much of a problem, but some people like to not have it public everywhere. So probably you might want to remove that log-file again... ;)

I know, I just wanted to get it to you without having to sanitise it. I've deleted the pastebin now.

**Comment by fuzunspm** [comment]
I can't enable on N21 instance with an error output of:

```
An unhandled exception has been thrown:
Error: Undefined class constant 'INTEGER' in /var/www/html/nextcloud/apps/forms/lib/Migration/Version010200Date20200323141300.php:80
Stack trace:
#0 /var/www/html/nextcloud/lib/private/DB/MigrationService.php(455): OCA\Forms\Migration\Version010200Date20200323141300->changeSchema()
#1 /var/www/html/nextcloud/lib/private/DB/MigrationService.php(418): OC\DB\MigrationService->migrateSchemaOnly()
#2 /var/www/html/nextcloud/lib/private/Installer.php(163): OC\DB\MigrationService->migrate()
#3 /var/www/html/nextcloud/core/Command/App/Enable.php(123): OC\Installer->installApp()
#4 /var/www/html/nextcloud/core/Command/App/Enable.php(93): OC\Core\Command\App\Enable->enableApp()
#5 /var/www/html/nextcloud/apps/mail/vendor/symfony/console/Command/Command.php(255): OC\Core\Command\App\Enable->execute()
#6 /var/www/html/nextcloud/apps/mail/vendor/symfony/console/Application.php(971): Symfony\Component\Console\Command\Command->run()
#7 /var/www/html/nextcloud/apps/mail/vendor/symfony/console/Application.php(290): Symfony\Component\Console\Application->doRunCommand()
#8 /var/www/html/nextcloud/apps/mail/vendor/symfony/console/Application.php(166): Symfony\Component\Console\Application->doRun()
#9 /var/www/html/nextcloud/lib/private/Console/Application.php(215): Symfony\Component\Console\Application->run()
#10 /var/www/html/nextcloud/console.php(100): OC\Console\Application->run()
#11 /var/www/html/nextcloud/occ(11): require_once('/var/www/html/n...')
#12 {main}%                                           
```
