### ISSUE TITLE
Migration not working on NC18 & NC19!

### ISSUE THREAD

**Issue by jotoeri** [nextcloud/forms#799]
Just tested it, with the new Types `Doctrine\DBAL\Types\Types` we get an Error on NC18 & NC19.
> Exception: Class 'Doctrine\DBAL\Types\Types' not found

@skjnldsv For NC18 i would say we just put it out of support for Forms `v2.2.0`?!

@ChristophWurst In general, for apps without stable branches to support all officially supported NC-versions, it would be good to backport the DB-Types! As it is a completely new feature, this should not break anything on backwards compatibility!?

**Comment by ChristophWurst** [comment]
> @ChristophWurst In general, for apps without stable branches to support all officially supported NC-versions, it would be good to backport the DB-Types! As it is a completely new feature, this should not break anything on backwards compatibility!?

Just inline the strings.
