### ISSUE TITLE
How are statistics calculated?

### ISSUE THREAD

**Issue by cloud2018** [nextcloud/forms#8]
**Which Forms version are you running?** (see apps page)
 1.0.3
**Nextcloud or ownCloud?:**
NC
**Nextcloud/ownCloud version:** (see Nextcloud admin page)
NC 16, demo.nextcloud.com

### Steps to reproduce
1. Create a form with 2 questions
1.1. Question 1 with 3 radio buttons
1.2. Question 2 with 2 check boxes
2. Vote one time 
3. See the statistics

### Actual behaviour
Question 1: 50.00% of respondents voted for answer choice: radio b 

### Expected behaviour
since there was only 1 vote, i expect 100% for each statistic.:
Question 1: 100.00% of respondents voted for answer choice: radio b 
Question 2: 100.00% of respondents voted for answer choice: box a

### Screenshots
![Forms   Nextcloud(1)](https://user-images.githubusercontent.com/34692335/58692269-916dd600-838e-11e9-92e3-be4f1504ab49.png)

![Forms   Nextcloud](https://user-images.githubusercontent.com/34692335/58692284-96328a00-838e-11e9-8eca-774cc57cf583.png)

**Comment by affan98** [comment]
Looks like a bug. I'll look into it

**Comment by JimmyKater** [comment]
+1

**Comment by pricard32** [comment]
I would like to see the result not like a poll, but the filled form. And the ability to send the result to a email or notify the admin/group of this form.

**Comment by mlckha** [comment]
Hi,

I have a bug on the statistic. The calculations are done incorrectly and the display on statistics bord is not functional.

I try with 5 box.

Thank you for your help.

**Comment by WNYmathGuy** [comment]
It's only doing "vote" tallies on discrete answers; radio-buttons and drop-downs. That's reasonable given the nature of how to classify "votes" for 3 out of 9 checkboxes checked.

It's a divisor problem. I didn't look at the way the data is represented, but it might be a bad query that makes the divisor. 

I'm on my first form. Four questions with one a drop-down and the other short answer. The calculation for the results on the two entries shows me the formula is something like this:
`(aggregate count of discrete value A)/((aggregate count of responses)*(number of questions in the form))`
With two entries to my form and two distinct choices for the drop-down I have 12.50% for each choice. `2/(2*4) = 0.125`
When repeating a choice for a third entry the 2 count gets 16.67% and the 1 count gets 8.33%.
`2/(3*4) = 0.1666666666666666667`
`1/(3*4) = 0.0833333333333333333`

**Comment by schniepp** [comment]
I also found the stats wrong. I got 28% results on two questions when only 1 person had responded to the form. Instead it should have been 100%. The form had 2 discrete-answer questions out of 7 total questions. The fraction 2/7 is 28%. But that's just totally non-sensible. It's the wrong enumerator **and** the wrong denominator. Both should have been 1 instead of 2 and 7.

**Comment by schniepp** [comment]
This is a clear bug. Instead of **"How are the statistics are calculated"**, this issue should be called: **"Statistics calculation is wrong"**. 

Probably the OP wanted to be polite. In this case, I think the politeness might mask that there is a real problem.

**Comment by skjnldsv** [comment]
We need to improve on the stats page yes.

**Comment by jancborchardt** [comment]
Isn’t this kind of outdated with version 2 as atm we don’t have statistics yet? @skjnldsv @jotoeri – we should of course bring them back, but the issue can be closed as it’s not relevant to v2 anymore.
