### ISSUE TITLE
Enabling app gives error

### ISSUE THREAD

**Issue by mehdibo** [nextcloud/forms#809]
**Describe the bug**

**To Reproduce**
1. Go to 'apps'
2. Try to enable 'forms'

**Expected behavior**
The app to be enabled

**Nextcloud (please complete the following information):**
- Nextcloud-Version:  21.0.0

**Additional context**
Logs:

> Error: Undefined index: comments at /var/www/html/lib/private/AppFramework/Bootstrap/RegistrationContext.php#404
Error: Call to a member function getContainer() on null
Error: Undefined index: dav at /var/www/html/lib/private/AppFramework/Bootstrap/RegistrationContext.php#404
Error: Call to a member function getContainer() on null
Error: Undefined index: files_trashbin at /var/www/html/lib/private/AppFramework/Bootstrap/RegistrationContext.php#404
Error: Call to a member function getContainer() on null
Exception: Undefined class constant 'INTEGER'

**Comment by szaimen** [comment]
https://github.com/nextcloud/server/issues/24711

**Comment by jotoeri** [comment]
> [nextcloud/server#24711](https://github.com/nextcloud/server/issues/24711)

Nah, that solves the first errors, while these don't prevent the app from beeing enabled afaik.

> Exception: Undefined class constant 'INTEGER'

@mehdibo, we're aware, that v2.1 does not work on NC21. Shouldn't take too long until release now, i think. If you really urgently need it, you can install current forms-beta, which will leave you a duplicate index on db, but should not break your instance. If you have a bit of time, just wait a week or two, that will keep your DB a little bit cleaner. :wink: For more information see https://github.com/nextcloud/forms/issues/798#issuecomment-784214965

**Comment by mehdibo** [comment]
Thank you all for the answers.

@jotoeri I can wait two weeks, thanks!
