### ISSUE TITLE
Delete a users Forms, when the user got deleted

### ISSUE THREAD

**Issue by jotoeri** [nextcloud/forms#828]
> interesting side effect, deleting as admin a user with his data from the nextcloud instance does not remove the users information from the polls tables …
Not really GDPR compliant. 

Just saw that comment on the forum. Applies to forms as to polls. I think we should delete a users forms when the user gets deleted.

Maybe one should also think about making corresponding submissions anonymous, if a user gets deleted.

**Comment by skjnldsv** [comment]
There is an event you can listen too iirc.
We can also decide to add a cron task to check and scale in case there are a lot of data.

**Comment by jotoeri** [comment]
Probably some combination...!? I think only using a cron would be quite some overhead to permanently check all forms. Having some listener to the event, that then tells our cron job to delete for that specifc user would be a good combination i think.
We'll see when implementing this... 😉

**Comment by skjnldsv** [comment]
Yes, maybe just check if the user have a lot of forms and send that to the cron Job if too much?
Don't know the proper approach for such scaling... Maybe @rullzer or @ChristophWurst can help?

**Comment by rullzer** [comment]
Don't do to much magic.

Listen to the event => inject job
Cron jobs are run often. So it should pick it up soon to delete it.
