### ISSUE TITLE
Error after upgrading "not a callable action"

### ISSUE THREAD

**Issue by thomasgg23** [nextcloud/forms#831]
**Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!**

**Describe the bug**
After upgrading to 2.2.0 (prior 2.1.0) and trying to access the forms tab we are getting an internal server error.

nextcloud.log content
{"reqId":"7wtnSyvvx7lnlur7RGWo","level":3,"time":"2021-03-09T16:17:55+00:00","remoteAddr":"XXXXXXX","user":"XXXXX","app":"index","method":"GET","url":"/index.php/apps/forms","message":{"Exception":"Exception","Message":"not a callable action","Code":0,"Trace":[{"file":"/var/www/html/lib/base.php","line":1010,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/html/index.php","line":37,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/html/lib/private/Route/Router.php","Line":294,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.72 Safari/537.36 Edg/89.0.774.45","version":"19.0.9.1"}

**Expected behavior**
Open the forms tab

**Nextcloud (please complete the following information):**
- Nextcloud-Version: 19.0.9.1
- Forms-Version: 2.2.0

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Edge
 - Version 89.0.774.45

**Comment by jotoeri** [comment]
Hey Thomas,
did you already try to clear your Browser cache? If that does not help, i'll have a look into tomorrow...
Greets,
Jonas :)
