### ISSUE TITLE
Error after upgrade to 2.2

### ISSUE THREAD

**Issue by enuf2bdangerous** [nextcloud/forms#832]
Running Nextcloud 19.0.9 on my local server running Ubuntu 20.4 and performed Forms upgrade to 2.2.0. using Chrome 89.0.4xx on Windows 10 Pro.  All previous Forms not visible in Nextcloud Files.  Selecting Forms icon produces this error:

Internal Server Error
The server was unable to complete your request.
If this happens again, please send the technical details below to the server administrator.
More details can be found in the server log.
Technical details
Remote Address: 63.224..x.x
Request ID: 2sOPqVQUx9KZSIFDQJpx

User Nextcloud Logging shows:

```json
{
    "reqId": "qZH0bOoT7elfajWmp9JZ",
    "level": 3,
    "time": "2021-03-09T20:55:40+01:00",
    "remoteAddr": "63.224.x.x",
    "user": "XXXXXXXXXXXXX",
    "app": "index",
    "method": "GET",
    "url": "/apps/forms",
    "message": {
        "Exception": "Exception",
        "Message": "not a callable action",
        "Code": 0,
        "Trace": [
            {
                "file": "/var/www/nextcloud/lib/base.php",
                "line": 1010,
                "function": "match",
                "class": "OC\\Route\\Router",
                "type": "->"
            },
            {
                "file": "/var/www/nextcloud/index.php",
                "line": 37,
                "function": "handleRequest",
                "class": "OC",
                "type": "::"
            }
        ],
        "File": "/var/www/nextcloud/lib/private/Route/Router.php",
        "Line": 294,
        "CustomMessage": "--"
    },
    "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.82 Safari/537.36",
    "version": "19.0.9.1",
    "id": "6047d2cbf3ebd"
}
```
FWIW, I performed the upgrade for Deck without incident before the Forms upgrade.  
I did clear Chrome cache and restart Chrome and no change

Thanks.

**Comment by enuf2bdangerous** [comment]
FWIW:  I just ran the Forms upgrade on a testbed-install of 20.0.8 Nextcloud (all system details nearly identical) and there was no problem.  Forms works fine on that system-- including existing Forms.

**Comment by enuf2bdangerous** [comment]
Additional: Performed Ubuntu update/upgrade. Pulled 29 files, 20+ were phpx.xx updates.  Restarted server (no errors down or up) and problem remains.

**Comment by ZS-Man** [comment]
Hi, same problem after upgrade to 2.2.0 on Nextloud 19.0.4, Ubuntu 18.04

 Selecting Forms icon produces Internal Server Error.

On my test server NC21, Ubuntu 20.04, Forms working without problem.

**Comment by skjnldsv** [comment]
cc @jotoeri

**Comment by skjnldsv** [comment]
Can't reproduce the issue though :thinking: tested on nc 20 and 21
