### ISSUE TITLE
Answers don't get aggregated after upgrade v2.2.0

### ISSUE THREAD

**Issue by RedTiger26** [nextcloud/forms#834]
**Describe the bug**
After upgrade to version 2.2.0, answers for questions of type dropdown list will not get aggregated on the summarized answers page. This means, there are no more percentages for these type of answers but all answers are listed individually.

This affects existing questions and newly created ones.

**To Reproduce**
1. Add a question of type dropdown to a new form
2. Answer the from multiple times
3. See the summarized results page

**Expected behavior**
Get the percentages like before

**Screenshots**
View after upgrade:
![grafik](https://user-images.githubusercontent.com/16443625/110596911-32064200-8180-11eb-99a9-26b3efa21361.png)

Before upgrade, there were only two lines with a count of numbers of answers.

**Nextcloud (please complete the following information):**
- Nextcloud-Version: 20.0.8
- Forms-Version: 2.2.0

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 86.0

**Comment by jotoeri** [comment]
Yeah, thank you for reporting! There was a small dumb error on my code-changes. Fixed that, will come as patch these days. 😉
