### ISSUE TITLE
Error while upgrading to Version 2.2.0

### ISSUE THREAD

**Issue by lhsei** [nextcloud/forms#838]
While updating forms to Version 2.2.0 the following error occurs (web and console output):

Updating <forms> ...
Doctrine\DBAL\Schema\SchemaException: There is no column with name 'owner_id' on table 'oc_forms_v2_forms'.
Update failed

1. Go to Apps
2. Click on Updates
3. Update Forms to Version 2.2.0

**Expected behavior**
A clean update to Version 2.2.0

**Nextcloud (please complete the following information):**
- Nextcloud-Version: 20.0.8
- Forms-Version: 2.1.0

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox 86.0

**Additional context**
The same error occurs from the console using the occ-command.

The only "solution" is to deactivate the forms-app.

**Comment by lhsei** [comment]
I use MariaDB10.3 on Ubuntu 18.04.2 LTS.

The log-message appears, when i try to update the app from version 2.1.0 to 2.2.0. 
I tried to make the update on the web and also on the console via occ upgrade. The error persists. 

I had disabled the app to continue using the nextcloud. If I try to enable the app, the same error occurs and the app keeps disabled.

**Comment by lhsei** [comment]
I have found the issue!

The upgrade has destroyed the data in the table oc_forms_v2_forms. I have disabled and deleted the app, recovered the table oc_forms_v2_forms from the last backup and installed the app again. Now it works!

**Comment by jotoeri** [comment]
Hm, very good it works now for you. 👍 However, that should not happen normally 🤔

**Comment by jotoeri** [comment]
Can you tell me, which part was corrupted on the table? Or in which way it was corrupted?

**Comment by lhsei** [comment]
I think, the source of the problem was the usage of german umlauts "äöüß" and special characters "#/?*" in the description and the title field. This lead to an corrupted database-table.
I had tried to repair the table with the mysql-command  REPAIR TABLE oc_forms_v2_forms; but it gives an unrecoverable error. The CHECK TABLE oc_forms_v2_forms; command gives also an error.

**Comment by jotoeri** [comment]
Hm, then just as a hint - mabe check your Database configuration. If it is properly configured, these characters should not produce issues. https://docs.nextcloud.com/server/20/admin_manual/configuration_database/linux_database_configuration.html

Thanks for providing all the informations! 😉
Greets,
Jonas
