### ISSUE TITLE
Change language

### ISSUE THREAD

**Issue by severin10** [nextcloud/forms#84]
**Which Forms version are you running?** (see apps page)
Version 1.0.3

**Nextcloud or ownCloud?:**
Nextcloud

**Nextcloud/ownCloud version:** (see Nextcloud admin page)
Nextcloud 16.0.4.1

### Steps to reproduce
1. Start Forms
2. Search for language setting

### Actual behaviour
Tell us what happens
--> can't change to german (or any other language than english).

### Expected behaviour
I'd like to the Forms app to either assume the nextcloud language setting (which is german) or to be able to change the Forms app language manually.
Where can I do that?

**Comment by manu-p** [comment]
+1 for french, please

**Comment by jotoeri** [comment]
Should be essentially done meanwhile.
