### ISSUE TITLE
Forms App not working. Redirect to NC Dashboard

### ISSUE THREAD

**Issue by YouthGarage** [nextcloud/forms#841]
**Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!**

**Describe the bug**
If you press on the "Forms" Symbol on the menu bar the app won't show up and the Dashboard will be shown

**To Reproduce**
Update to 2.2.1.
open forms

**Expected behavior**

**Screenshots**
![Bildschirmfoto 2021-03-11 um 10 55 09](https://user-images.githubusercontent.com/80455481/110769252-4289eb80-8258-11eb-82a6-aaaa5d8d645d.png)

**Nextcloud (please complete the following information):**
- Nextcloud-Version: 20.0.8
- Forms-Version: 2.2.1

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser Safari 14.0.3 (16610.4.3.1.7) and Firefox 86.0

**Browser log**
```
Open your console, reload your page and/or do the action leading to this issue and copy/paste the log in this thread.
```

<details>
<summary>How to access your browser console (Click to expand)</summary>

# Chrome
- Press either CTRL + SHIFT + J to open the “console” tab of the Developer Tools.
- Alternative method:
    1. Press either CTRL + SHIFT + I or F12 to open the Developer Tools.
    2. Click the “console” tab.

# Safari
- Press CMD + ALT + I to open the Web Inspector.
- See Chrome’s step 2. (Chrome and Safari have pretty much identical dev tools.)

# IE9
1. Press F12 to open the developer tools.
2. Click the “console” tab.

# Firefox
- Press CTRL + SHIFT + K to open the Web console (COMMAND + SHIFT + K on Macs).
- or, if Firebug is installed (recommended):
    1. Press F12 to open Firebug.
    2. Click on the “console” tab.

# Opera
1. Press CTRL + SHIFT + I to open Dragonfly.
2. Click on the “console” tab.
</details>

**Additional context**

**Comment by EBendinelli** [comment]
Tried installing Forms this morning and encountered this exact same issue.

Nextcloud version: 20.0.8
Forms-version: 2.2.1

**Comment by jotoeri** [comment]
Hey @YouthGarage @EBendinelli,

- are you probably on an nginx server? Could you please provide some information on the server-setup?
- Did you both restart your servers and clear all caches? At least it seems to be something like that: #836 
- The app itself seems functional, i have working setups in that server/app combination by hand. Nor do i have a clear error message to look into.

Greets,
Jonas

**Comment by YouthGarage** [comment]
@jotoeri 

I did restart the vm and cleared the cache.
Sry this is my first time reporting. What exactly do you need? Does this Help?

```
Operating system: Linux 5.4.0-66-generic #74-Ubuntu SMP Wed Jan 27 22:54:38 UTC 2021 x86_64

Webserver: nginx/1.19.8 (fpm-fcgi)
Database: mysql 10.5.9
PHP version: 7.4.3
Nextcloud version: 20.0.8 - 20.0.8.1

```
Besides that. I have Nextcloud in http not https running and I have a Gateway Host in front of the Nextcloud handling the https and forward the traffic to the nextcloud vm.

If i klick the form button in the top bar I get 301 followed by 302 and then dashboard again.

Interestingly if I use a link to a shared form then it works.

**Comment by EBendinelli** [comment]
Adding my info as well:
```
OS: Alpine-linux
nginx version: nginx/1.18.0
PHP 7.4.15
```

Restarted Nginx, php and cleared cache with no luck. Can't see anything in the nginx/php/nextcloud logs. I also have a reverse proxy in front of NC (also restarted everything there). I'll keep investigating

**Comment by jotoeri** [comment]
Hm, ok... Really seems to be some nginx-related stuff.

I just created a thread on the forum. Please head over to there, ideally just place a short message, signaling you are affected and still need help. Also best include a short information, what you tried already. (And of course happily show there, if you got a solution 😉)
https://help.nextcloud.com/t/forms-update-redirect-to-dashboard/110567

As i wrote there - i'm no server expert, nor do i have the resources to provide support here. Sorry. 😞 Once we have an error-message or some ansatz that i can trace, just tell me and i'll look for. 🙂
