### ISSUE TITLE
Forms Error "There is no column with name 'owner_id' on table 'oc_forms_v2_forms'"

### ISSUE THREAD

**Issue by Jan747** [nextcloud/forms#843]
**Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!**

**Describe the bug**

"There is no column with name 'owner_id' on table 'oc_forms_v2_forms'" message is shown, when i try to activate the app. 
This error happened after I updated the Nextcloud instance from 20.0.6 to 20.0.8. Before I changed the Database from mysql 5.7 to MariaDB 10.3. So this error might be related to the change of the Database. 

**Expected behavior**
Activate the forms App. 

**Nextcloud (please complete the following information):**
- Nextcloud-Version: 20.0.8
- Forms-Version: 2.2.1

Additional information:
My nextcloud is running on Ubuntu 18.04 with Plesk Obsidian 18.0.34,

**Comment by jotoeri** [comment]
There was something similar already (#838), but i honestly don't know how that should happen. There obviously is a column like this. So somehow your database got currupted, i think. Can you have a look on DB how that table looks and what is in there?

**Comment by Jan747** [comment]
@jotoeri thank you for your comment. It seems like my problem is similar to #838. I did the following steps in my database:
select * from oc_forms_v2_forms;
ERROR 1033 (HY000): Incorrect information in file: './next_cloud/oc_forms_v2_forms.frm'

Also REPAIR TABLE didn't work. 

------------------------------+--------+----------+---------------------------------------------------------------------+
| Table                        | Op     | Msg_type | Msg_text                                                            |
+------------------------------+--------+----------+---------------------------------------------------------------------+
| next_cloud.oc_forms_v2_forms | repair | Error    | Incorrect information in file: './next_cloud/oc_forms_v2_forms.frm' |
| next_cloud.oc_forms_v2_forms | repair | error    | Corrupt                                                             |
+------------------------------+--------+----------+---------------------------------------------------------------------+
2 rows in set (0.001 sec)

I will now try to get the table from my backup file. Thank you for your help.

**Comment by X-Raph-X** [comment]
Hi,
i've the same problem. If someone could post the table content (ideally the SQL query to create the table), it should help, please.
Is it possible to simply delete the forms app, then delete with a SQL query the table oc_forms_v2_forms en at the end, re-install the forms app ?
Thank you very much for your help.

**Comment by jotoeri** [comment]
Hey @X-Raph-X,

generally it should work, if you deactivate the app, delete the forms tables, and delete forms-related entries out of `oc_migrations` and `oc_appconfig`.
However, keep in mind:
- You will loose all your forms-data
- This feels like a quite hacky way.
- **Make a backup** before doing anything on DB!

More interesting part for me: Can you somehow show/provide your forms-tables and the related entries on the migration-table to us? I'd like to see how it looks and get known how this error happens.

Greets, 🙂 
Jonas

**Comment by X-Raph-X** [comment]
Thanks for your answer. I finally succeed in installing Forms. I had to drop the table, and recreate it y hand from and old mysql dump lost somewhere on my disk.
Before I dropped the table, it was impossible to access ti it because the file .frm was corrupted. Unfortunately, the table oc_form_v2_forms is not in the sql dump file of last night and I don't have any copy of the .frm and .ibd files.

**Comment by jotoeri** [comment]
@ChristophWurst @rullzer , do you probably see some error on [this migration](https://github.com/nextcloud/forms/blob/d6b886135be85ec040448b735cd8a3ff3ba5a4a0/lib/Migration/Version020200Date20210120082018.php), that could cause such corrupt tables? Or is that just some setup-error?

**Comment by ChristophWurst** [comment]
I don't see why that happened, https://github.com/nextcloud/forms/blob/6a06a6b916792343ac57e1aae43b25ec5c2b1a7a/lib/Migration/Version010200Date20200323141300.php#L100 adds that column.
