### ISSUE TITLE
Name/Contact field for non-anonymous forms

### ISSUE THREAD

**Issue by kfkloos** [nextcloud/forms#858]
**Nextcloud (please complete the following information):**
- Nextcloud-Version: 20.0.8
- Forms-Version: 2.2.2

**Is your feature request related to a problem? Please describe.**
If I want a non-anonymous from, I will need to know who replied what. This is currently only the case, if the user is logged in. If this is not the case, the answer is listed as anonymous.

**Describe the solution you'd like**
In the case, the form is set to non-anonymous and no user is logged in, please add a mandatory name & email contact field.

**Describe alternatives you've considered**
I could add a question for name & mail-adress; however, then these fields are either optional (and it's not guranteed, that the users fills them) or I set them mandatory and logged-in users must provide their details manually.

**Comment by skjnldsv** [comment]
Hi, you can already do that. Add a name/email input and set it as mandatory.
We decided it would be the easier as it uses already in-place tools :)

I think there was already some similar requests and we closed them with the same reply! Have a great day!
Cheers

**Comment by kfkloos** [comment]
Hi @skjnldsv !
As I have written in the alternative section, I don't think this is a valid option:

1. Anyone *with* an account will need to fill these fields by hand (very inconvenient).
2. The reports will not be correct.
3. I believe at the moment there is no email-adress validator. (It might be cool to add a "REGEX"-validator to the free-text fields at some point ;)).

Anyway – thanks for considering and quick response!
