### ISSUE TITLE
Missing answers to checkbox questions in exported CSVs

### ISSUE THREAD

**Issue by salat0id** [nextcloud/forms#859]
**Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue. Please don't comment if you have no relevant information to add!**

**Describe the bug**
When exporting to CSV, only one answer per checkbox-type question is present in the CSV, no matter how many were picked.
(The answers are displayed just fine in the web interface.)

**To Reproduce**
1. Create a form with a checkbox question with multiple options.
2. Fill out the form, choosing more than one option; submit.
3. Download submissions as CSV.
4. The column in question will only contain one option, even though multiple were selected.

**Expected behavior**
In earlier versions, if multiple options were selected, the corresponding column would contain all of them separated by semicolons (`;`).

**Nextcloud:**
- Nextcloud-Version: 20.0.7
- Forms-Version: 2.2.1

**Desktop (shouldn't matter):**
 - OS: Windows
 - Browser: chrome
 - Version: 89

**Suspected cause**
It's probably the way `$answers` is generated inside `SubmissionService->getSubmissionCsv()`, but I don't know enough PHP to properly fix it myself.

**Comment by jotoeri** [comment]
Hey @salat0id,

thanks for reporting. You're right, that got lost in the new SubmissionCsv-Processing. I just pushed a fix.

For the release: I'd like to wait one or two weeks if you're ok with, so we might catch some more bugs that probably get reported. But in case you need it urgently, just tell us. 😉 

Greets,
Jonas
