### ISSUE TITLE
Request on how to remove the footer

### ISSUE THREAD

**Issue by ridhwn** [nextcloud/forms#861]
Hi sorry ive search inside github and didn't find the same request.

is there any way we can remove the footer appearing at the forms in the page when user want to respond? because if you sent the forms to public user, the footer is coming from nextcloud which have wording doesn't suite and intended for the form.

attached is the screenshot

![image](https://user-images.githubusercontent.com/75796080/112235345-69451a80-8c79-11eb-9f25-8ed6fc4f2a5c.png)

**Comment by skjnldsv** [comment]
Hey, sorry, there is no such option. You can try to target this with the custom_css app to hide it.

**Comment by skjnldsv** [comment]
You can also change the instance name and slogan n your instance theming settings.
