### ISSUE TITLE
Question type "Linear sclae" (Likert scale)

### ISSUE THREAD

**Issue by TheBitFighter** [nextcloud/forms#880]
Which Forms version are you running?
v2.2.4

Nextcloud or ownCloud?:
Nextcloud

# Feature request
This request is very strongly related to [this issue](https://github.com/nextcloud/forms/issues/356). It would involve either a question type or simple variation of the already requested matrix with only one line of radio buttons (with a selectable starting and end number), no line description but instead description of the ends of the scale, very much like the Linear Scale question type in Google forms. This is the main question type we use for our "After Event evaluation forms".

What do I mean by this? This:
![linear scale](https://user-images.githubusercontent.com/22227120/113473715-8e9d0a00-946b-11eb-8318-9510880ee74c.png)
Sorry for the German.
Thoughts?

**Comment by jotoeri** [comment]
Hm, can you please comment on the other issue, with your use-case resp. variation? On the proposed matrix, the single line will most probably be available anyways, if we somehow implement the line-endings separately we'll see then. But i don't think we would have a completely separate question-type for this.
So to keep track of this question-type in a single issue please just state your desired variation there... 😉
