### ISSUE TITLE
Limiting Users to answering a form but not creating new forms

### ISSUE THREAD

**Issue by greavette** [nextcloud/forms#884]
**Nextcloud (please complete the following information):**
- Nextcloud-Version: 20.0.8
- Forms-Version: 2.2.4

Apologies if this has already been asked before (I've searched but not been able to find the enhancement I'm requesting:

Management and Admin would have Forms available to them to create forms.
Employees will need to complete the forms assigned to them.  
Employees would not be able to see any other form management/Admin creates. They only see the forms assigned to them to complete.
Employees will not be able to Create their own Forms.  

I've tried the following scenario:  

- The Admin created a form for an employee who is not an Admin or owner.  Admin assigned the form to the employee: 
- General Settings > Choose users to share with.
- This User did not have Forms app available to them.
- Admin shared the link for this form for the user.  The user tried accessing this link but would only be directed to the Dashboard page.  

I do not want this employee to be able to create their own forms so I don't want the New Form button available to all employees.  But I do want them to be able to complete the forms assigned to them.

I hope this explains what I would like to accomplish.

Thank you.

**Comment by jotoeri** [comment]
Hey @greavette,

huhh, if i read your text right, the enhancement you want is to define users/groups, that are allowed to create forms, no? Such you wouldn't need to block the access to the app, but could just restrict employees to not beeing able to create their own forms.

If this is the case, then i think it's a duplicate to #647 ?

Greets, 😉 
Jonas
