### ISSUE TITLE
Breadcrumbs bar not needed for this app

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/forms#9]
The breadcrumbs bar only makes sense for deep levels of nesting, and the only app where this is really needed is Files.

Other apps like this only need the [AppNavigation component](https://github.com/nextcloud/nextcloud-vue/tree/master/src/components/AppNavigation). :) You simply have all the forms listed in the left navigation, and selecting one opens the detail view.

That way you always have the forms overview, and can also quickly switch between them. And on mobile or narrower sizes, the left navigation bar automatically hides.

**Comment by stefan123t** [comment]
It could be useful if the forms app allows multiple screens after each other, eg by introducing some kind of page separator question type. Then you could add forward backward buttons and the current page title / question as part of the breadcrumb.
Just my two cents.

**Comment by jancborchardt** [comment]
If that ever comes up, we can still see – and then it is a separate issue. The way it is currently used is definitely not something which is needed. :)

**Comment by jancborchardt** [comment]
:tada: nice cleanup @skjnldsv!
