### ISSUE TITLE
Bug occurs when exporting survey results

### ISSUE THREAD

**Issue by aron9015** [nextcloud/forms#903]
A bug occurs when exporting survey results. 
In case of multiple answers ("checkboxes"), only one of the selected answers is exported. 

The other answers of such a checkbox question that allows more than one answer will not be included in the export file.

Nextcloud Forms Version 2.2.4

**Comment by jotoeri** [comment]
Are you sure, you are on version 2.2.4? We fixed that with 2.2.3 and i can't reproduce it currently on 2.2.4.

**Comment by aron9015** [comment]
Thank you for pointing this out. I have checked the time sequence again. The bug was discovered before the update to 2.2.4 - so all is well :)
