### ISSUE TITLE
Scale shape

### ISSUE THREAD

**Issue by coinfastman** [nextcloud/forms#914]
Hello.
The google form and one driver form have one form that allows you to poll on a 10-point scale from lowest to highest. Are you planning to add such a field in the next versions?

**Comment by skjnldsv** [comment]
I think that was already suggested, but can't find the ticket :thinking:

**Comment by coinfastman** [comment]
This is a very useful form, other services have it, I would like to see it for you.

**Comment by jotoeri** [comment]
Duplicate of #356 
Please search for existing issues before opening a new one. 😉
