### ISSUE TITLE
Increase length for description and show proper errors

### ISSUE THREAD

**Issue by Sohalt** [nextcloud/forms#92]
**Which Forms version are you running?**
1.0.3

**Nextcloud or ownCloud?:**
Nextcloud

**Nextcloud/ownCloud version:** (see Nextcloud admin page)
16.0.4

### Steps to reproduce
1. Try to submit a form with a description with more than 1024 characters

### Actual behaviour
Form does not get saved and shows a generic "Error on saving form, see console".
Request gives a 500 Internal Server Error.

### Expected behaviour
Form does get saved (or at least an error message saying that descriptions with more than 1024 characters are not supported).

**Comment by skjnldsv** [comment]
@jotoeri done, right?

**Comment by jotoeri** [comment]
Hm, i set on DB maxlengths to:

'title' => 256,
'description' => 2048,
'questiontext' => 2048,
'optiontext' => 1024,
'answertext' => 2048,

I think the input-fields on the vue-components are not adapted yet. Just a maxlength everywhere should do that, as it is not possible to produce the error on db then...?

**Comment by skjnldsv** [comment]
> should do that, as it is not possible to produce the error on db then...?

It is, but not properly.
We should make this available as initialstate and use them int he app
https://github.com/nextcloud/forms/blob/e2f503e189b0e588668f42e5389fd3ff02724a5f/src/components/Questions/QuestionLong.vue#L38
https://github.com/nextcloud/forms/blob/e2f503e189b0e588668f42e5389fd3ff02724a5f/src/components/Questions/QuestionShort.vue#L38

**Comment by jotoeri** [comment]
Hm, don't know, what you mean with initialstate... :/

**Comment by skjnldsv** [comment]
https://github.com/nextcloud/forms/blob/38f4f1aa03440655fd7a4df02db9953aaeb10572/lib/Controller/PageController.php#L184
https://github.com/nextcloud/forms/blob/38f4f1aa03440655fd7a4df02db9953aaeb10572/src/views/Submit.vue#L69
https://github.com/nextcloud/forms/blob/38f4f1aa03440655fd7a4df02db9953aaeb10572/src/views/Submit.vue#L99

Our api to provide static initial data from php to any js application :)
