### ISSUE TITLE
Allow admins to select which sharing options should be made available

### ISSUE THREAD

**Issue by keda82** [nextcloud/forms#922]
Sharing an instance with organizations and separation is performed by groups rather than dedicated Nextcloud instances makes the option "Show for all users for this instance" an option you do not want enabled

Make it possible for admins to configure which share options should be displayed for end users

**Comment by JB1985** [comment]
I thing this is a bug. In any case, it wasn't like that before.

If I set that sharing is only allowed with the group,  Then "everyone" should only be "everyone" in the group and not in the entire cloud.

@nickvergessen @rullzer @skjnldsv
