### ISSUE TITLE
Allow custom/other answer for 'multiple' questions (radio & checkbox)

### ISSUE THREAD

**Issue by Sohalt** [nextcloud/forms#93]
**Which Forms version are you running?** (see apps page)
1.0.3

**Nextcloud or ownCloud?:**
Nextcloud

It would be cool to be able to enable an "other" option with a free form text input for radio buttons and checkboxes, to give the user the possibility to provide other answers than those that are explicitly given.

**Comment by rami999999999** [comment]
I would like to add that it would also be great that what users type in "other" should then be available as an options to other users

**Comment by ei8fdb** [comment]
:100: agree with this request. The _other_ option would allow for short number of words to be typed as answer.

**Comment by Sohalt** [comment]
This should not be the default though, because it could leak sensitive information.

**Comment by ei8fdb** [comment]
> > I would like to add that it would also be great that what users type in "other" should then be available as an options to other users
> 
> This should not be the default though, because it could leak sensitive information.

To me this ("what users type in "other" should then be available as an options to other users") seems strange behaviour for a form to support. My thinking:

the form is (usually) a request from the creator to others. The..."information flow" is from the person completing the form to the creator, not between towards others completing the form

I agree with @Sohalt that it shouldn't be default behaviour.

**Comment by jdittrich** [comment]
This is also feature I need often and it currently is a bit of a blocker to not have it. 

Use cases:
* For questions like: "What is your favorite activity when using X" and allowing an answer that the survey creator did not think of or where including all possible answers would make the form really really long. 
* For "What is your gender?" although the normal "other" label is not nice here (think of "othering"). It would be cool if one could adjust the label and "other" would be just the default, so one could replace it e.g. with "prefer to self describe"

**Comment by jdittrich** [comment]
If there is a more elaborate (BDD or so) specification and/or mockup needed, I can create it.

**Comment by hanswundersam** [comment]
Is the "other" text field still something on the table for the forms app? It would be incredibly useful indeed for Nextcloud Forms to be a true replacement for external forms providers.

**Comment by jotoeri** [comment]
It is, just not with highest priority currently. Also see the Milestone.
